######################################################################
# Automatically generated by qmake (2.01a) ven. juin 8 21:29:34 2007
######################################################################

TEMPLATE = lib
TARGET = qcodeedit
DESTDIR = ..
#CONFIG += debug

DEPENDPATH += . document language widgets qnfa
INCLUDEPATH += . document language widgets qnfa

CONFIG += qnfa

QT += xml

UI_DIR = 
MOC_DIR = .build
OBJECTS_DIR = .build


# Input
include(lib.pri)
