/***************************************************************************
 *   copyright       : (C) 2003-2007 by Pascal Brachet                     *
 *   http://www.xm1math.net/texmaker/                                      *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#include "metapostlistwidget.h"

MetapostListWidget::MetapostListWidget(QWidget *parent):QListWidget(parent)
{
addItem("beginfig();");
addItem("endfig;");
addItem("extra_beginfig()");
addItem("extra_endfig");
addItem("begingraph()");
addItem("endgraph");
addItem("begingroup");
addItem("endgroup");
addItem("for  upto");
addItem("forever:");
addItem("forsuffixes :");
addItem("endfor");
addItem("if :");
addItem("else :");
addItem("fi");
addItem("----------");
addItem("abs");
addItem("addto also");
addItem("addto contour");
addItem("addto doublepath");
addItem("ahangle");
addItem("ahlength");
addItem("and");
addItem("angle");
addItem("arclength");
addItem("arctime of");
addItem("augment.");
addItem("auto.");
addItem("Autoform");
addItem("autogrid()");
addItem("background");
addItem("bbox");
addItem("bboxmargin");
addItem("beveled");
addItem("black");
addItem("blue");
addItem("bluepart");
addItem("boolean");
addItem("bot");
addItem("boxit");
addItem("boxjoin()");
addItem("bp");
addItem("bpath");
addItem("btex  etex");
addItem("buildcycle()");
addItem("butt");
addItem("ceiling");
addItem("char");
addItem("charcode");
addItem("circleit");
addItem("circmargin");
addItem("clip");
addItem("color");
addItem("controls");
addItem("cosd");
addItem("curl");
addItem("currentpen");
addItem("currentpicture");
addItem("cutafter");
addItem("cutbefore");
addItem("cutdraw");
addItem("cycle");
addItem("dashed");
addItem("dashpattern");
addItem("day");
addItem("dd");
addItem("decimal");
addItem("decr");
addItem("defaultdx:=");
addItem("defaultdy:=");
addItem("defaultfont:=");
addItem("defaultpen:=");
addItem("defaultscale:=");
addItem("def  enddef");
addItem("direction   of");
addItem("directionpoint  of");
addItem("directiontime  of");
addItem("ditto");
addItem("div");
addItem("dotlabel.");
addItem("dotlabels.");
addItem("dotprod");
addItem("down");
addItem("downto");
addItem("draw");
addItem("draw_mark()");
addItem("draw_marked()");
addItem("drawarrow");
addItem("drawblarrow");
addItem("drawboxed()");
addItem("drawboxes()");
addItem("drawoptions()");
addItem("drawshadowed()");
addItem("drawunboxed()");
addItem("epsilon");
addItem("evenly");
addItem("exitif");
addItem("exitunless");
addItem("expr");
addItem("Fe_base");
addItem("Fe_plus");
addItem("fill");
addItem("filldraw");
addItem("fixpos()");
addItem("fixsize()");
addItem("floor");
addItem("fontsize");
addItem("format()");
addItem("frame.");
addItem("fullcircle");
addItem("gdata()");
addItem("gdotlabel.");
addItem("gdraw");
addItem("gdrawarrow");
addItem("gdrawdblarrow");
addItem("getmid");
addItem("gfill");
addItem("glabel.");
addItem("Gmarks");
addItem("Gminlog");
addItem("Gpaths");
addItem("green");
addItem("greenpart");
addItem("grid.");
addItem("halfcircle");
addItem("hex");
addItem("hide()");
addItem("identity");
addItem("image()");
addItem("in");
addItem("incr()");
addItem("infinity");
addItem("infont");
addItem("init_numbers()");
addItem("input");
addItem("interim");
addItem("intersectionpoint");
addItem("intersectiontimes");
addItem("inverse");
addItem("itick.");
addItem("joinup()");
addItem("known");
addItem("label.");
addItem("labeloffset");
addItem("labels.");
addItem("left");
addItem("length");
addItem("let");
addItem("lft");
addItem("linear");
addItem("linecap:=");
addItem("linejoin:=");
addItem("llcorner");
addItem("llft");
addItem("log");
addItem("loggingall");
addItem("lrcorner");
addItem("lrt");
addItem("makepath");
addItem("makepen");
addItem("mark_angle()");
addItem("mark_rt_angle()");
addItem("max");
addItem("mexp");
addItem("mfplain");
addItem("middlepoint()");
addItem("midpoint()");
addItem("min");
addItem("mitered");
addItem("miterlimit:=");
addItem("Mlog");
addItem("mlog");
addItem("mm");
addItem("mod");
addItem("month");
addItem("mp");
addItem("mpxbreak");
addItem("Mreadpath()");
addItem("Mten");
addItem("newinternal");
addItem("normaldeviate");
addItem("not");
addItem("nullpicture");
addItem("numeric");
addItem("oct");
addItem("odd");
addItem("or");
addItem("origin");
addItem("otick.");
addItem("OUT");
addItem("pair");
addItem("path");
addItem("pausing");
addItem("pc");
addItem("pen");
addItem("pencircle");
addItem("penoffset");
addItem("pensquare");
addItem("pic");
addItem("pickup");
addItem("picture");
addItem("plot");
addItem("point  of");
addItem("postcontrol");
addItem("precontrol");
addItem("primarydef  enddef");
addItem("pt");
addItem("quartecircle");
addItem("readfrom");
addItem("red");
addItem("redpart");
addItem("reflectedabout()");
addItem("reverse");
addItem("right");
addItem("rotated");
addItem("rotatedaround()");
addItem("round");
addItem("rounded");
addItem("rt");
addItem("Sabs");
addItem("Sadd");
addItem("sarith");
addItem("save");
addItem("scaled");
addItem("Scvnum");
addItem("Sdiv");
addItem("secondarydef  enddef");
addItem("self");
addItem("setbounds  to");
addItem("setcoords()");
addItem("setrange()");
addItem("shifted");
addItem("shipout");
addItem("show");
addItem("showdependencies");
addItem("showstopping");
addItem("showtoken");
addItem("showvariable");
addItem("sind");
addItem("slanted");
addItem("Sleq");
addItem("Smul");
addItem("Sneq");
addItem("special");
addItem("sqrt");
addItem("squared");
addItem("Ssub");
addItem("step");
addItem("str");
addItem("string");
addItem("stroked");
addItem("subpath");
addItem("substring");
addItem("tertiarydef  enddef");
addItem("text");
addItem("thelabel.");
addItem("time");
addItem("top");
addItem("tracingall");
addItem("tracingcapsules");
addItem("tracingchoices");
addItem("tracingcommands");
addItem("tracingequations");
addItem("tracinglostchars");
addItem("tracingmacros");
addItem("tracingnone");
addItem("tracingonline");
addItem("tracingoutput");
addItem("tracingrestores");
addItem("tracingspecs");
addItem("tracingstats");
addItem("tracingtitles");
addItem("transform");
addItem("transformed");
addItem("true");
addItem("truecorners:=");
addItem("ulcorner");
addItem("ulft");
addItem("undraw");
addItem("unfill");
addItem("unfilldraw");
addItem("uniformdeviate");
addItem("unitsquare");
addItem("unitvector");
addItem("unknown");
addItem("until");
addItem("up");
addItem("urcorner");
addItem("urt");
addItem("vardef  enddef");
addItem("whatever[]");
addItem("white");
addItem("withcolor");
addItem("withdots");
addItem("withpen");
addItem("write  to");
addItem("xpart");
addItem("xscaled");
addItem("xxpart");
addItem("xypart");
addItem("year");
addItem("yscaled");
addItem("yxpart");
addItem("yypart");
addItem("zscaled");
}
MetapostListWidget::~MetapostListWidget()
{
}



