######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 29 15:55:06 2013
######################################################################

TEMPLATE = app
LANGUAGE = C++
TARGET = gesymb-ng
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt
QT += xml

# Input
SOURCES += gesymb-ng.cpp
