# academicons package
# Matthew Bertucci 2025/09/17 for v1.9.6

#include:iftex

\aiicon{icon name%keyvals}

#keyvals:\aiicon#c
academia
academia-square
acclaim
acclaim-square
acm
acm-square
acmdl
acmdl-square
ads
ads-square
africarxiv
africarxiv-square
archive
archive-square
arxiv
arxiv-square
biorxiv
biorxiv-square
ceur
ceursquare
ciencia-vitae
ciencia-vitae-square
clarivate
clarivate-square
conversation
conversation-square
coursera
coursera-square
crossref
crossref-square
cv
cvsquare
datacite
datacite-square
dataverse
dataverse-square
dblp
dblp-square
depsy
depsy-square
doi
doi-square
dryad
dryad-square
elsevier
elsevier-square
ideas-repec
ideas-repec-square
figshare
figshare-square
googlescholar
googlescholar-square
hal
hal-square
hypothesis
hypothesis-square
ieee
ieee-square
impactstory
impactstory-square
inaturalist
inaturalist-square
inpn
inpn-square
inspire
inspire-square
isidore
isidore-square
isni
isni-square
jstor
jstor-square
lattes
lattes-square
mathoverflow
mathoverflow-square
mendeley
mendeley-square
moodle
moodle-square
mtmt
mtmt-square
nakala
nakala-square
closed-access
closed-access-square
obp
obp-square
open-access
open-access-square
open-data
open-data-square
open-materials
open-materials-square
openedition
openedition-square
orcid
orcid-square
osf
osf-square
overleaf
overleaf-square
philpapers
philpapers-square
piazza
piazza-square
preregistered
preregistered-square
protocols
protocols-square
psyarxiv
psyarxiv-square
publons
publons-square
pubmed
pubmed-square
pubpeer
pubpeer-square
researcherid
researcherid-square
researchgate
researchgate-square
ror
ror-square
sci-hub
sci-hub-square
scirate
scirate-square
scopus
scopus-square
semanticscholar
semanticscholar-square
springer
springer-square
ssrn
ssrn-square
stackoverflow
stackoverflow-square
viaf
viaf-square
wiley
wiley-square
zenodo
zenodo-square
zotero
zotero-square
#endkeyvals

\aiAcademia
\aiAcademiaSquare
\aiAcclaim
\aiAcclaimSquare
\aiACM
\aiACMSquare
\aiACMDL
\aiACMDLSquare
\aiADS
\aiADSSquare
\aiAfricArXiv
\aiAfricArXivSquare
\aiArchive
\aiArchiveSquare
\aiarXiv
\aiarXivSquare
\aibioRxiv
\aibioRxivSquare
\aiCEUR
\aiCEURSquare
\aiCIENCIAVITAE
\aiCIENCIAVITAESquare
\aiClarivate
\aiClarivateSquare
\aiConversation
\aiConversationSquare
\aiCoursera
\aiCourseraSquare
\aiCrossref
\aiCrossrefSquare
\aiCV
\aiCVSquare
\aiDataCite
\aiDataCiteSquare
\aiDataverse
\aiDataverseSquare
\aidblp
\aidblpSquare
\aiDepsy
\aiDepsySquare
\aiDoi
\aiDoiSquare
\aiDryad
\aiDryadSquare
\aiElsevier
\aiElsevierSquare
\aiIDEASRePEc
\aiIDEASRePEcSquare
\aiFigshare
\aiFigshareSquare
\aiGoogleScholar
\aiGoogleScholarSquare
\aiHAL
\aiHALSquare
\aiHypothesis
\aiHypothesisSquare
\aiIEEE
\aiIEEESquare
\aiImpactstory
\aiImpactstorySquare
\aiiNaturalist
\aiiNaturalistSquare
\aiINPN
\aiINPNSquare
\aiInspire
\aiInspireSquare
\aiISIDORE
\aiISIDORESquare
\aiIsni
\aiIsniSquare
\aiJSTOR
\aiJSTORSquare
\aiLattes
\aiLattesSquare
\aiMathOverflow
\aiMathOverflowSquare
\aiMendeley
\aiMendeleySquare
\aiMoodle
\aiMoodleSquare
\aiMTMT
\aiMTMTSquare
\aiNAKALA
\aiNAKALASquare
\aiClosedAccess
\aiClosedAccessSquare
\aiOBP
\aiOBPSquare
\aiOpenAccess
\aiOpenAccessSquare
\aiOpenData
\aiOpenDataSquare
\aiOpenMaterials
\aiOpenMaterialsSquare
\aiOpenEdition
\aiOpenEditionSquare
\aiOrcid
\aiOrcidSquare
\aiOSF
\aiOSFSquare
\aiOverleaf
\aiOverleafSquare
\aiPhilPapers
\aiPhilPapersSquare
\aiPiazza
\aiPiazzaSquare
\aiPreregistered
\aiPreregisteredSquare
\aiProtocols
\aiProtocolsSquare
\aiPsyArXiv
\aiPsyArXivSquare
\aiPublons
\aiPublonsSquare
\aiPubMed
\aiPubMedSquare
\aiPubPeer
\aiPubPeerSquare
\aiResearcherID
\aiResearcherIDSquare
\aiResearchGate
\aiResearchGateSquare
\aiROR
\aiRORSquare
\aiSciHub
\aiSciHubSquare
\aiSciRate
\aiSciRateSquare
\aiScopus
\aiScopusSquare
\aiSemanticScholar
\aiSemanticScholarSquare
\aiSpringer
\aiSpringerSquare
\aiSSRN
\aiSSRNSquare
\aiStackOverflow
\aiStackOverflowSquare
\aiViaf
\aiViafSquare
\aiWiley
\aiWileySquare
\aiZenodo
\aiZenodoSquare
\aiZotero
\aiZoteroSquare
