# academicons package
# Matthew Bertucci 11/28/2021 for v1.9.1

\aiicon{icon name%keyvals}

#keyvals:\aiicon#c
academia
academiasquare
acclaim
acclaimsquare
acm
acmsquare
acmdl
acmdlsquare
ads
adssquare
africarxiv
africarxivsquare
arxiv
arxivsquare
biorxiv
biorxivsquare
ceur
ceursquare
cienciavitae
cienciavitaesquare
conversation
conversationsquare
coursera
courserasquare
crossref
crossrefsquare
cv
cvsquare
datacite
datacitesquare
dataverse
dataversesquare
dblp
dblpsquare
depsy
depsysquare
doi
doisquare
dryad
dryadsquare
elsevier
elseviersquare
ideasrepec
ideasrepecsquare
figshare
figsharesquare
googlescholar
googlescholarsquare
hal
halsquare
ieee
ieeesquare
impactstory
impactstorysquare
inaturalist
inaturalistsquare
inpn
inpnsquare
inspire
inspiresquare
isidore
isidoresquare
jstor
jstorsquare
lattes
lattessquare
mathoverflow
mathoverflowsquare
mendeley
mendeleysquare
moodle
moodlesquare
mtmt
mtmtsquare
nakala
nakalasquare
closedaccess
closedaccesssquare
openaccess
openaccesssquare
opendata
opendatasquare
openmaterials
openmaterialssquare
openedition
openeditionsquare
orcid
orcidsquare
osf
osfsquare
overleaf
overleafsquare
philpapers
philpaperssquare
piazza
piazzasquare
preregistered
preregisteredsquare
protocols
protocolssquare
psyarxiv
psyarxivsquare
publons
publonssquare
pubmed
pubmedsquare
pubpeer
pubpeersquare
researcherid
researcheridsquare
researchgate
researchgatesquare
scirate
sciratesquare
semanticscholar
semanticscholarsquare
springer
springersquare
ssrn
ssrnsquare
stackoverflow
stackoverflowsquare
zotero
zoterosquare
#endkeyvals

\aiAcademia
\aiAcademiaSquare
\aiAcclaim
\aiAcclaimSquare
\aiACM
\aiACMSquare
\aiACMDL
\aiACMDLSquare
\aiADS
\aiADSSquare
\aiAfricArXiv
\aiAfricArXivSquare
\aiarXiv
\aiarXivSquare
\aibioRxiv
\aibioRxivSquare
\aiCEUR
\aiCEURSquare
\aiCIENCIAVITAE
\aiCIENCIAVITAESquare
\aiConversation
\aiConversationSquare
\aiCoursera
\aiCourseraSquare
\aiCrossref
\aiCrossrefSquare
\aiCV
\aiCVSquare
\aiDataCite
\aiDataCiteSquare
\aiDataverse
\aiDataverseSquare
\aidblp
\aidblpSquare
\aiDepsy
\aiDepsySquare
\aiDoi
\aiDoiSquare
\aiDryad
\aiDryadSquare
\aiElsevier
\aiElsevierSquare
\aiIDEASRePEc
\aiIDEASRePEcSquare
\aiFigshare
\aiFigshareSquare
\aiGoogleScholar
\aiGoogleScholarSquare
\aiHAL
\aiHALSquare
\aiIEEE
\aiIEEESquare
\aiImpactstory
\aiImpactstorySquare
\aiiNaturalist
\aiiNaturalistSquare
\aiINPN
\aiINPNSquare
\aiInspire
\aiInspireSquare
\aiISIDORE
\aiISIDORESquare
\aiJSTOR
\aiJSTORSquare
\aiLattes
\aiLattesSquare
\aiMathOverflow
\aiMathOverflowSquare
\aiMendeley
\aiMendeleySquare
\aiMoodle
\aiMoodleSquare
\aiMTMT
\aiMTMTSquare
\aiNAKALA
\aiNAKALASquare
\aiClosedAccess
\aiClosedAccessSquare
\aiOpenAccess
\aiOpenAccessSquare
\aiOpenData
\aiOpenDataSquare
\aiOpenMaterials
\aiOpenMaterialsSquare
\aiOpenEdition
\aiOpenEditionSquare
\aiOrcid
\aiOrcidSquare
\aiOSF
\aiOSFSquare
\aiOverleaf
\aiOverleafSquare
\aiPhilPapers
\aiPhilPapersSquare
\aiPiazza
\aiPiazzaSquare
\aiPreregistered
\aiPreregisteredSquare
\aiProtocols
\aiProtocolsSquare
\aiPsyArXiv
\aiPsyArXivSquare
\aiPublons
\aiPublonsSquare
\aiPubMed
\aiPubMedSquare
\aiPubPeer
\aiPubPeerSquare
\aiResearcherID
\aiResearcherIDSquare
\aiResearchGate
\aiResearchGateSquare
\aiSciRate
\aiSciRateSquare
\aiSemanticScholar
\aiSemanticScholarSquare
\aiSpringer
\aiSpringerSquare
\aiSSRN
\aiSSRNSquare
\aiStackOverflow
\aiStackOverflowSquare
\aiZotero
\aiZoteroSquare

\AI#*