# algolrevived package
# Matthew Bertucci 8/22/2021 for v1.052

#include:textcomp
#include:xstring
#include:ifthen
#include:scalefnt
#include:mweights
#include:fontaxes

\textsu{text}#n
\sufigures#n
\textinf{text}#n
\infigures#n
\textlf{text}#n
\lfstyle#n
\texttlf{text}#n
\tlfstyle#n
\textosf{text}#n
\osfstyle#n
\texttosf{text}#n
\tosfstyle#n
\textfrac{upper}{lower}#n
\textfrac[whole part]{upper}{lower}#*n
\textprime#n
\textdprime#n
\textleftrightarrow#n
\textupdownarrow#n
\textLeftarrow#n
\textUparrow#n
\textRightarrow#n
\textDownarrow#n
\textLeftrightarrow#n
\textUpdownarrow#n
\textforall#n
\textcomplement#n
\textpartial#n
\textexists#n
\textnexists#n
\textvarnothing#n
\textincrement#n
\textnabla#n
\textin#n
\textnotin#n
\textsmallin#n
\textni#n
\textnni#n
\textsmallni#n
\textsmallsetminus#n
\textlargebullet#n
\textland#n
\textlor#n
\textcap#n
\textcup#n
\textcoloneq#n
\texteqcolon#n
\textneq#n
\textequiv#n
\textneqiv#n
\textleq#n
\textgeq#n
\textsubset#n
\textsupset#n
\textnsubset#n
\textnsupset#n
\textsubseteq#n
\textsupseteq#n
\textnsubseteq#n
\textnsupseteq#n
\textsqsubset#n
\textsqsupset#n
\textsqsubseteq#n
\textsqcap#n
\textsqcup#n