#include:ifthen

# Autogenerated from .sty and in algorithmicx manual
\Comment{text}#/algorithmic
\Statex#/algorithmic
\algblock[block]{start}{end}
\algblockdefx[block]{start}{end}[startparamcount%args][default value]{start text}[sendparamcount%args][default value]{end text}
\algblockx[block]{start}{end}[startparamcount%args][default value]{start text}[sendparamcount%args][default value]{end text}
\algcblock[new block]{old block}{continue}{end}
\algcblockdefx[new block]{old block}{continue}{end}[continueparamcount%args][default value]{continue text}[endparamcount%args][default value]{end text}
\algcblockx[new block]{old block}{continue}{end}[continueparamcount%args][default value]{continue text}[endparamcount%args][default value]{end text}
\algcloop[new loop]{old block}{continue}
\algcloopdefx[new loop]{old block}{continue}[continueparamcount%args][default value]{continue text}
\algcloopx[new loop]{old block}{continue}[continueparamcount%args][default value]{continue text}
\algdefaulttext[block]{command}
\algdef # Too many optional arguments
\alglanguage{layoutname}
\algloop[loop]{start}
\algloopdefx[loop]{start}[startparamcount%args][default value]{start text}
\algnewcommand
\algnotext[block]{ending command}
\algref{algorithm}{line}#r
\algrenewcommand[block]{command}[paramcount%args][default value]{text}
\algrenewtext{arg1}{arg2}
\algrestore{savename}#/algorithmic
\algrestore*{savename}#/algorithmic
\algsetblock[block]{start}{end}{lifetime}{indent}
\algsetblockdefx{start}{end}{lifetime}{indent}[startparamcount%args][default value]{start text}[endparamcount%args][default value]{end text}
\algsetblockx[block]{start}{end}{lifetime}{indent}[startparamcount%args][default value]{start text}[endparamcount%args][default value]{end text}
\algsetcblock
\algsetcblockdefx
\algsetcblockx
\algstore{savename}#/algorithmic
\algstore*{savename}#/algorithmic
\begin{algorithmic}[lines]#\algorithm
\end{algorithmic}

# Not autogenerated
\State#/algorithmic
\algorithmicindent
\algcsetblock[new block]{old block}{continue}{end}{lifetime}{indent}
\algcsetblockdefx[new block]{old block}{continue}{stop}{lifetime}{indent}[continueparamcount%args][default value]{continue text}[endparamcount%args][default value]{end text}
\algcsetblockx[new block]{old block}{continue}{stop}{lifetime}{indent}[continueparamcount%args][default value]{continue text}[endparamcount%args][default value]{end text}

# Autogenerated from .sty and not in algorithmicx manual
\ALG#S
\BState#S
\algbreak#S
\algdeflanguage{arg1}#S
\algnewlanguage{arg1}#S
\algrenewcomment#S
\algsetlanguage{arg1}#S
\algtext#S
