# mode: amsmath.sty
# dani/2006-02-19
# muzimuzhi/1 Nov 2019

#include:amsbsy
#include:amsopn

\allowdisplaybreaks
\AmS
\AmSfont
\begin{align}#\math,array
\begin{align*}#\math,array
\begin{alignat}[alignment]{ncols}#\math,array
\begin{alignat*}[alignment]{ncols}#\math,array
\begin{alignat}{ncols}#\math,array
\begin{alignat*}{ncols}#\math,array
\begin{aligned}#m\array
\begin{aligned}[alignment]#m\array
\begin{alignedat}{ncols}#m\array
\begin{bmatrix}#m\array
\begin{Bmatrix}#m\array
\begin{cases}#\array
\begin{equation*}#\math
\begin{flalign}#\math,array
\begin{flalign*}#\math,array
\begin{gather}#\math
\begin{gather*}#\math
\begin{gathered}#\math
\begin{gathered}[alignment]#\math
\begin{matrix}#m\array
\begin{multline}#\math
\begin{multline*}#\math
\begin{pmatrix}#m\array
\begin{smallmatrix}#m\array
\begin{split}#\array
\begin{subarray}
\begin{subarray}[align]
\begin{subequations}
\begin{vmatrix}#m\array
\begin{Vmatrix}#m\array
\begin{xalignat}#*
\begin{xalignat*}#*
\begin{xxalignat}#*
\binom{above}{below}#m
\boldsymbol{argument}#m
\boxed{argument}
\cfrac[align]{%<num%:translatable%>}{%<den%:translatable%>}#m
\cfrac{%<num%:translatable%>}{%<den%:translatable%>}#m
\dbinom{above}{below}#m
\ddddot{arg}#m
\dddot{arg}#m
\DeclareMathOperator{command}{definition}#nd
\DeclareMathOperator*{command}{definition}#nd
\dfrac{%<num%:translatable%>}{%<den%:translatable%>}#m
\displaybreak
\displaybreak[value]
\dotsb#m
\dotsc#m
\dotsi#m
\dotsm#m
\dotso#m
\end{align}
\end{align*}
\end{alignat}
\end{alignat*}
\end{aligned}
\end{alignedat}
\end{bmatrix}
\end{Bmatrix}
\end{cases}
\end{equation*}
\end{flalign}
\end{flalign*}
\end{gather}
\end{gather*}
\end{gathered}
\end{matrix}
\end{multline}
\end{multline*}
\end{pmatrix}
\end{smallmatrix}
\end{split}
\end{subarray}
\end{subequations}
\end{vmatrix}
\end{Vmatrix}
\end{xalignat}
\end{xalignat*}
\end{xxalignat}
\eqref{label}#r
\genfrac{left-delim}{right-delim}{thickness%l}{mathstyle}{numerator}{denominator}#m
\hdotsfor{columns}
\hdotsfor[multiplier]{columns}
\idotsint#m
\iiiint#m
\iiint#m
\iint#m
\impliedby#m
\implies#m
\intertext{word or phrase}#m
\leftroot{argument}
\lvert#m
\lVert#m
\mod#m
\mspace{dimen}#m
\multlinegap#*
\nobreakdash
\notag#m
\numberwithin{env}{counter}
\numberwithin[format]{env}{counter}
\operatorname{name}
\operatorname*{name}
\operatornamewithlimits{name}
\overleftrightarrow{argument}#m
\overset{superscript}{argument}#m
\overunderset{superscript}{subscript}{argument}#m
\pod#m
\raisetag{dimen}
\rvert#m
\rVert#m
\shoveright{arg}#m
\shoveleft{arg}#m
\sideset{left}{right}{symbol}#m
\smash{argument}
\smash[valign]{argument}
\substack{argument}#m
\tag{label}#m
\tag*{label}#m
\tbinom{above}{below}#m
\text{text}#m
\tfrac{%<num%:translatable%>}{%<den%:translatable%>}#m
\underleftarrow{argument}#m
\underleftrightarrow{argument}#m
\underrightarrow{argument}#m
\underset{subscript}{argument}#m
\uproot{argument}
\varDelta#m
\varGamma#m
\varLambda#m
\varOmega#m
\varPhi#m
\varPi#m
\varPsi#m
\varSigma#m
\varTheta#m
\varUpsilon#m
\varXi#m
\xleftarrow[subscript]{superscript}#m
\xleftarrow{superscript}#m
\xrightarrow[subscript]{superscript}#m
\xrightarrow{superscript}#m
