# arsenal-math package
# Matthew Bertucci 2025/11/17 for v0.9.2

#include:unicode-math

#keyvals:\usepackage/arsenal-math#c
Scale=%<factor%>
#endkeyvals

# additional symbols available with the font
\barV#m
\bigstar#m
\blacktriangle#m
\blacktriangledown#m
\boxast#m
\boxbar#m
\boxbslash#m
\boxdiag#m
\candra{arg}#m
\Coloneq#m
\diamondcdot#m
\Digamma#m
\doublebarwedge#m
\downdasharrow#m
\dualmap#m
\fint#m
\Finv#m
\Game#m
\geqqslant#m
\harrowextender#*m
\intextender#*m
\Join#m
\lbag#m
\leftdasharrow#m
\leftwavearrow#m
\leqqslant#m
\lgblkcircle#m
\lgblksquare#m
\lgwhtsquare#m
\mdblkcircle#m
\mdblkdiamond#m
\mdblklozenge#m
\mdblksquare#m
\mdlgblkdiamond#m
\mdlgblklozenge#m
\mdlgwhtdiamond#m
\mdsmblkcircle#m
\mdsmblksquare#m
\mdsmwhtcircle#m
\mdsmwhtsquare#m
\mdwhtcircle#m
\mdwhtdiamond#m
\mdwhtlozenge#m
\mdwhtsquare#m
\obslash#m
\ogreaterthan#m
\olessthan#m
\pitchfork#m
\precapprox#m
\preceqq#m
\precnapprox#m
\precneq#m
\precneqq#m
\rbag#m
\rightdasharrow#m
\rightwavearrow#m
\smallblacktriangleleft#m
\smalltriangleleft#m
\smalltriangleright#m
\smblkdiamond#m
\smblklozenge#m
\smwhtlozenge#m
\sqint#m
\subseteqq#m
\subsetneqq#m
\succapprox#m
\succeqq#m
\succnapprox#m
\succneq#m
\succneqq#m
\supseteqq#m
\supsetneqq#m
\triangledown#m
\upand#m
\updasharrow#m
\upDigamma#m
\vartriangle#m
\Vbar#m
\Vvert#m
\vysmblksquare#m
\vysmwhtsquare#m
\wedgebar#m
\Zbar#m