# chemist package
# Matthew Bertucci 2022/05/15 for v5.01

#include:assurechemist

#keyvals:\usepackage/chemist#c
chemtimes
#endkeyvals

\begin{ChemEqnarray}#\math,array
\end{ChemEqnarray}
\begin{ChemEqnarray*}#\math,array
\end{ChemEqnarray*}
\begin{ChemEquation}#\math
\end{ChemEquation}
\begin{XyMcompd}(width,height)(xshift,yshift){refkey%labeldef}{subkey}#l\picture,pictureHighlight
\end{XyMcompd}
\begin{XyMtab}{cols}#\tabular
\end{XyMtab}
\begin{chemeqn}#\math
\end{chemeqn}
\begin{chemeqnarray}#\math,array
\end{chemeqnarray}
\begin{chemeqnarraya}#\math,array
\end{chemeqnarraya}
\begin{chemmath}#\math
\end{chemmath}
\begin{frameboxit}{width}
\end{frameboxit}
\begin{glshfboxit}{width}
\end{glshfboxit}
\begin{grshfboxit}{width}
\end{grshfboxit}
\begin{lshfboxit}{width}
\end{lshfboxit}
\begin{miniscreen}{width}
\end{miniscreen}
\begin{rshfboxit}{width}
\end{rshfboxit}
\begin{screen}
\end{screen}
\begin{tboxminiscreen}{width}
\end{tboxminiscreen}
\begin{tboxscreen}
\end{tboxscreen}

\bury{content%text}
\cdonecell{dimenA}{dimenB}{content}
\cdtwocell{dimenA}{dimenB}{content}{label}#l
\ChemEqFont#*
\ChemForm{formula}
\chemform{formula}
\chemistsw
\ChemStrut
\compd
\compdlabel{label}#l
\cref{label}#r
\dbond
\degC
\degF
\deriv
\deriva
\derivalabel{label}#l
\derivlabel{label}#l
\derivnum
\doublebond#*
\eqlbarrowstretch#*
\Equilibarrow#m
\equilibarrow#m
\Equiliblongarrow#m
\equiliblongarrow#m
\fboxit{width}{text}
\leftshfbox{text}
\leftshframe{width}{text}
\Lllongleftarrow#m
\lllongleftarrow#m
\lllongleftharpoondown#m
\lllongleftharpoonup#m
\Lllongleftrightarrow#m
\lllongleftrightarrow#m
\Lllongrightarrow#m
\lllongrightarrow#m
\lllongrightharpoondown#m
\lllongrightharpoonup#m
\Llongleftarrow#m
\llongleftarrow#m
\llongleftharpoondown#m
\llongleftharpoonup#m
\Llongleftrightarrow#m
\llongleftrightarrow#m
\Llongrightarrow#m
\llongrightarrow#m
\llongrightharpoondown#m
\llongrightharpoonup#m
\newchemenvironment{envname}{old envname}#N
\nocompd
\nocompdlabel{label}#l
\noderiv
\noderiva
\noderivalabel{label}#l
\noderivlabel{label}#l
\reactarrowsep#*
\reactarrowseprate#*
\reactdarrow{shift}{length}{above}{below}
\reactDEqarrow{shift}{length}{above}{below}
\reactdeqarrow{shift}{length}{above}{below}
\reactdlrarrow{shift}{length}{above}{below}
\reactduarrow{shift}{length}{above}{below}
\reactEqarrow{shift}{length}{above}{below}
\reacteqarrow{shift}{length}{above}{below}
\reactlarrow{shift}{length}{above}{below}
\reactLEqarrow{shift}{length}{above}{below}
\reactleqarrow{shift}{length}{above}{below}
\reactlrarrow{shift}{length}{above}{below}
\reactnearrow{shift}{length}{above}{below}
\reactnwarrow{shift}{length}{above}{below}
\reactrarrow{shift}{length}{above}{below}
\reactREqarrow{shift}{length}{above}{below}
\reactreqarrow{shift}{length}{above}{below}
\reactsearrow{shift}{length}{above}{below}
\reactswarrow{shift}{length}{above}{below}
\reactuarrow{shift}{length}{above}{below}
\reactUEqarrow{shift}{length}{above}{below}
\reactueqarrow{shift}{length}{above}{below}
\reactulrarrow{shift}{length}{above}{below}
\reactVEqarrow{shift}{length}{above}{below}
\reactveqarrow{shift}{length}{above}{below}
\rightshfbox{text}
\rightshframe{width}{text}
\schemelarrow{shift}{length}{above}{below}
\schemelrarrow{shift}{length}{above}{below}
\schemerarrow{shift}{length}{above}{below}
\tbond
\tboxtitle#*
\thecompd#*
\triplebond#*

# not documented
\aaa#S
\agx#S
\agxdv#S
\agxlatent#S
\bbb#S
\begin{ffboxit}#S
\begin{XyMderiv}#S
\Bib#S
\BibTeX#S
\calcontrolpoints{arg1}#S
\Cent#S
\changespace{arg1}#S
\chapinitial#S
\ChemAccent{arg1}{arg2}{arg3}#S
\chemcorr#S
\chemGreekletter{arg1}{arg2}#S
\chemtimesfalse#S
\chemtimestrue#S
\chemUpGreekletter{arg1}{arg2}{arg3}#S
\compdfbox{arg1}{arg2}{arg3}#S
\compdmbox{arg1}{arg2}{arg3}#S
\cyandv#S
\cyandye#S
\deHBr#S
\derivfbox{arg1}{arg2}{arg3}#S
\derivlist{arg1}#S
\derivmbox{arg1}{arg2}{arg3}#S
\downwardarrowcalcA#S
\downwardarrowcalcB#S
\end{ffboxit}#S
\end{XyMderiv}#S
\endash#S
\eqproton#S
\ffparbox{arg1}{arg2}#S
\fgcaption#S
\horizon#S
\ifchemtimes#S
\ifupgreekrm#S
\ifverbswitch#S
\jBibTeX#S
\jLaTeX#S
\journalID#S
\jTeX#S
\kanzanchi#S
\kanzanhalf#S
\kkk#S
\La#S
\lbcompdpbox{arg1}{arg2}{arg3}#S
\lbderivpbox{arg1}{arg2}{arg3}#S
\leavechemcorr#S
\Leftarrowfill#S
\Leftrightarrowfill#S
\leftrightarrowfill#S
\lethead{arg1}{arg2}{arg3}#S
\magentadv#S
\magentadye#S
\member#S
\miniscreentoprule#S
\next#S
\nrep#S
\nrepmax#S
\oldalpha#S
\oldbeta#S
\oldcal#S
\oldchi#S
\oldDelta#S
\olddelta#S
\oldepsilon#S
\oldEquilibarrow#S
\oldequilibarrow#S
\oldEquiliblongarrow#S
\oldequiliblongarrow#S
\oldeta#S
\oldGamma#S
\oldgamma#S
\oldiota#S
\oldkappa#S
\oldlambda#S
\oldLamda#S
\oldLllongleftarrow#S
\oldlllongleftarrow#S
\oldlllongleftharpoondown#S
\oldLllongleftrightarrow#S
\oldlllongleftrightarrow#S
\oldLllongrightarrow#S
\oldlllongrightarrow#S
\oldlllongrightharpoonup#S
\oldLlongleftarrow#S
\oldllongleftarrow#S
\oldllongleftharpoondown#S
\oldLlongleftrightarrow#S
\oldllongleftrightarrow#S
\oldLlongrightarrow#S
\oldllongrightarrow#S
\oldllongrightharpoonup#S
\oldmathcal#S
\oldmathnormal#S
\oldmu#S
\oldnu#S
\oldOmega#S
\oldomega#S
\oldPhi#S
\oldphi#S
\oldPi#S
\oldpi#S
\oldPsi#S
\oldpsi#S
\oldreactdarrow#S
\oldreactdeqarrow#S
\oldreactdlrarrow#S
\oldreactduarrow#S
\oldreacteqarrow#S
\oldreactlarrow#S
\oldreactleqarrow#S
\oldreactlrarrow#S
\oldreactnearrow#S
\oldreactnwarrow#S
\oldreactrarrow#S
\oldreactreqarrow#S
\oldreactsearrow#S
\oldreactswarrow#S
\oldreactuarrow#S
\oldreactueqarrow#S
\oldreactulrarrow#S
\oldreactveqarrow#S
\oldrho#S
\oldschemelarrow{arg1}{arg2}{arg3}{arg4}#S
\oldschemelrarrow{arg1}{arg2}{arg3}{arg4}#S
\oldschemerarrow{arg1}{arg2}{arg3}{arg4}#S
\oldSigma#S
\oldsigma#S
\oldstyle#S
\oldtau#S
\oldTheta#S
\oldtheta#S
\oldUpsilon#S
\oldupsilon#S
\oldvarepsilon#S
\oldvarphi#S
\oldvarpi#S
\oldvarrho#S
\oldvarsigma#S
\oldvartheta#S
\oldXi#S
\oldxi#S
\oldzeta#S
\penetrate{arg1}{arg2}#S
\PiC#S
\PiCTeX#S
\Post#S
\PostScript#S
\pTeX#S
\pushtowall#S
\resetfontsize#S
\Rightarrowfill#S
\rshfboxit{arg1}#S
\sboxit{arg1}{arg2}#S
\Script#S
\SetChemSymbol#S
\smcaption#S
\Sub#S
\SubBib#S
\tbaselineshift#S
\tbcaption#S
\tboxscreentoprule#S
\TestCount#S
\thederiv#S
\tmpkern#S
\tpic#S
\upgreekrmfalse#S
\upgreekrmtrue#S
\upwardarrowcalcA#S
\upwardarrowcalcB#S
\verbatimbaselineskip#S
\verbatimleftmargin#S
\verbatimsize#S
\verbswitchfalse#S
\verbswitchtrue#S
\xlethead{arg1}#S
\xymrefa#S
\xymrefb#S
\ybaselineshift#S
\yellowdv#S
\yellowdye#S
\yen#S
\yubin#S
\Yubin{arg1}#S