# autogenerated by txs edited by Stefan Kraus 2013-09-11
# edited 3/18/2022 for v2.0m

#include:amstext
#include:caption
#include:chemscheme
#include:siunitx
#include:varioref
#include:xspace

#keyvals:\usepackage/chemstyle#c,\cstsetup#c
abbrcomma#true,false
abbremph#true,false
journal=#angew,jomc,ic,jacs,jcp,orglett,rsc,tetlett
language=%<language%>
nonotes#true,false
nophrases#true,false
notes#true,false
notesbefore#true,false
phrases#true,false
rademph#true,false
radhyphen#true,false
radprefix#true,false
radsuper#true,false
varioref#true,false
xspace#true,false
#endkeyvals

#ifOption:journal=orglett
#include:xcolor
#endif

\Hz
\Molar
\cmc
\cstsetup{options%keyvals}
\cubiccentimeter
\eg
\etal
\etc
\ie
\invacuo
\latin{text}
\latinemphoff#*
\latinemphon#*
\mmHg
\mol
\molar
\standardstate
\thebibnote#*
\torr#*
