# brief class
# Matthew Bertucci 3/29/2022 for v2.0s

#keyvals:\documentclass/brief#c
a4paper
letterpaper
USletter
10pt
11pt
12pt
twoside
oneside
draft
final
leqno
fleqn
typhulp
geentyphulp
streepjes
geenstreepjes
adreslinks
adresrechts
dutch
english
american
german
french
#endkeyvals

\address{address}
\afsluiting{text}
\antwoordadres{return address}
\begin{brief}{name}
\end{brief}
\betreft{subject%text}
\bijlagen{text}
\cc{text}
\datum{date}
\en
\location{location}
\maakbriefhoofd*{header%text}{address}
\maakbriefhoofd{header%text}{address}
\name{name}
\ondertekening{signature}
\onskenmerk{text}
\opening{text}
\ps{text}
\telephone{phone number}
\uwbriefvan{date}
\uwkenmerk{reference}
\vandaag
\voetitem{label%text}{text}

\adresveld#*
\adresveldbreedte#*
\americanbrief#*
\begin{letter}{name}#*
\end{letter}#*
\betrefttekst
\bijlage{arg1}
\bijlagentekst
\bijlagetekst
\bladnummertekst#*
\briefhoofd#*
\ccname#*
\closing{text}#*
\datumtekst#*
\dutchbrief#*
\encl{text}#*
\englishbrief#*
\footitem{label%text}{text}
\footsep#*
\frenchbrief#*
\fromlocation#*
\fromname#*
\fromsig#*
\geadresseerdetekst#*
\germanbrief#*
\kleinvet#*
\labelcount#*
\makeheader*{header%text}{address}#*
\makeheader{header%text}{address}#*
\mlabel{return address}{to address}#*
\onderwerp{subject%text}#*
\onskenmerktekst#*
\perfstreepje#*
\re{subject%text}#*
\referentieregel#*
\refkopfont#*
\refveldbreedte#*
\replyaddress{return address}#*
\returnaddress#*
\signature{signature}#*
\startbreaks#*
\startlabels#*
\stopbreaks#*
\stopletter#*
\streepje#*
\streepjes{height}#*
\subject{subject%text}#*
\telefoontekst#*
\telephonenum#*
\toaddress#*
\toname#*
\uwbrieftekst#*
\uwkenmerktekst#*
\vensterskip#*
\vervolghoofd#*
\vervolgreferentieregel#*
\voetregel#*
\vouwstreepjes#*
\yourletterof{date}#*
\yourreference{reference}#*