# sapthesis class
# Matthew Bertucci 2022/06/07 for v5.0

#include:xkeyval
#include:class-book
#include:geometry
#include:ifxetex
#include:fontenc
# loads T1 option of fontenc
#include:textcomp
#include:lmodern
#include:caption
#include:graphicx
#include:color
#include:booktabs
#include:amsmath
#include:etoolbox
#include:fancyhdr

#keyvals:\documentclass/sapthesis#c
a4paper
a5paper
b5paper
layout=#a5paper,b5paper
draft
oneside
twoside
binding=##L
noexaminfo
nodefaultfont
romandiff
italian
english
#endkeyvals

\begin{abstract}
\begin{abstract}[title%text]
\end{abstract}
\begin{acknowledgments}
\begin{acknowledgments}[title%text]
\end{acknowledgments}

\subtitle{text}
\alttitle{text}
\IDnumber{number}
\course{course%text}
\cycle{cycle}
\courseorganizer{text}
\AcademicYear{year}
\advisor{name}
\customadvisorlabel{text}
\coadvisor{name}
\customcoadvisorlabel{text}
\director{name}
\customdirectorlabel{text}
\examdate{date}
\examiner{name}
\examiner[role]{name}
\thesistype{type%text}
\ISBN{ISBN}
\copyyear{year}
\copyrightstatement{text}
\versiondate{date}
\website{URL}#U
\authoremail{email%URL}#U
\reviewer{name}
\extrainfo{text}
\dedication{text}
\eu
\iu
\der{function}{var1,var2,...}#m
\pder{function}{var1,var2,...}#m
\rb{sub}
\rp{sup}
\tb{sub}
\tp{sup}
\un{units%formula}
\g
\degree#*
\C
\celsius#*
\A
\angstrom#*
\micro
\ohm
\di#m
\x#m

sapred#B

# from T1 option of fontenc
\DH#n
\dh#n
\dj#n
\DJ#n
\guillemetleft#n
\guillemetright#n
\guillemotleft#*n
\guillemotright#*n
\guilsinglleft#n
\guilsinglright#n
\Hwithstroke#n
\hwithstroke#n
\k{arg}#n
\NG#n
\ng#n
\quotedblbase#n
\quotesinglbase#n
\textogonekcentered{arg}#n
\textquotedbl#n
\th#n
\TH#n