# mode: koma letter class (scrlttr2)
# dani/2006-02-21
\addrchar
\addrentry{last}{first}{address}{tel}{f1}{f2}{f3}{f4}{comment}{short}
\addtolengthplength[factor]{length}{plength}
\addtolengthplength{length}{plength}
\addtoreffields{name}
\adrchar
\adrentry{last}{first}{address}{tel}{f1}{f2}{comment}{short}
\AtBeginLetter{commands}
\bankname
\begin{letter}{name}
\captionsamerican
\captionsaustrian
\captionsbritish
\captionscroatian
\captionsdutch
\captionsenglish
\captionsfinnish
\captionsfrench
\captionsgerman
\captionsitalian
\captionsngerman
\captionsspanish
\captionsUKenglish
\captionsUSenglish
\ccname
\cc{text}
\closing{text}
\customername
\dateamerican
\dateaustrian
\datebritish
\datecroatian
\datedutch
\dateenglish
\datefinnish
\datefrench
\dategerman
\dateitalian
\datename
\datengerman
\datespanish
\dateUKenglish
\dateUSenglish
\defaultreffields
\emailname
\enclname
\encl{text}
\end{letter}
\faxname
\firstfoot{text}
\firsthead{text}
\headfromname
\headtoname
\ifkomavarempty{name}{true}{false}
\ifkomavarempty*{name}{true}{false}
\invoicename
\KOMAoptions{list}
\LetterOptionNeedsPapersize{option}{papersize}
\LoadLetterOption{name}
\myrefname
\newcaptionname{language}{name}{text}
\newkomavar[alias]{name}
\newkomavar*[alias]{name}
\newkomavar{name}
\newkomavar*{name}
\nextfoot{text}
\nexthead{text}
\opening{text}
\phonename
\providecaptionname{language}{name}{text}
\ps{text}
\raggedsignature
\removereffields
\renewcaptionname{language}{name}{text}
\setkomavar{name}[alias]{value}
\setkomavar*{name}[alias]{value}
\setkomavar{name}{value}
\setkomavar*{name}{value}
\setlengthtoplength[factor]{length}{plength}
\setlengthtoplength{length}{plength}
\subjectname
\usekomavar[alias]{name}
\usekomavar*[alias]{name}
\usekomavar{name}
\usekomavar*{name}
\useplength{name}
\wwwname
\yourmailname
\yourrefname
