# jourcl class
# Matthew Bertucci 2022/12/16 for v2022/12/16

#include:graphicx
#include:fancyhdr
#include:parskip
#include:inputenc
#include:babel
# loads english option of babel
#include:framed
#include:lipsum
#include:isodate
#include:fontawesome5
#include:orcidlink

#keyvals:\documentclass/jourcl#c
top
afterToEditor
afterIntroduction
afterAbstract
bottom
#endkeyvals

\abstract{text}
\AuthorOrcid{ORCID}
\bestregards
\CityPostal{city}
\conflictofinterest{text}
\declaration{text}
\Editor{name}
\Email{email%URL}#U
\final{text}
\FirstEmail{email%URL}#U
\FirstInstitution{institution}
\FirstNameSurname{name}
\FirstRecommended{name}
\ImagePath{imagefile}#g
\InstitutionName{institution}
\Introduction{text}
\JournalName{journal%text}
\NameSurname{name}
\pabstract#*
\pAuthorOrcid
\pCityPostal#*
\pconflictofinterest#*
\pdeclaration#*
\pEditor
\pEmail
\PersonAddressing{text}
\pfinal#*
\pFirstEmail
\pFirstInstitution
\pFirstNameSurname
\pFirstRecommended
\Phone{phone number}
\pImagePath#*
\pInstitutionName#*
\pIntroduction#*
\pJournalName
\pNameSurname
\pPersonAddressing#*
\pPhone
\pSecondEmail
\pSecondInstitution
\pSecondNameSurname
\pSecondRecommended
\psignature#*
\pSignaturePath
\pSpecialIssue
\pStreetNo#*
\pThirdEmail
\pThirdInstitution
\pThirdNameSurname
\pThirdRecommended
\pTitle
\ptoEditor#*
\pvalediction#*
\SecondEmail{email%URL}#U
\SecondInstitution{institution}
\SecondNameSurname{name}
\SecondRecommended{name}
\showreviewers
\showSignature{imagefile}#g
\signature{text}
\signaturePath{imagefile}#g
\SpecialIssue{issue}
\StreetNo{streetno}
\ThirdEmail{email%URL}#U
\ThirdInstitution{institution}
\ThirdNameSurname{name}
\ThirdRecommended{name}
\Title{text}
\toEditor{text}
\valediction{text}
\yoursfaithfully
\yourssincerely
\yourstruly

\aboutme{text}#S
\addreviewersPosition#S
\ifempty{arg}#S
\RecommendedPerson{role}{name}{institution}{email%URL}#*U

# from english option of babel
\captionsenglish#*
\dateenglish#*
\extrasenglish#*
\noextrasenglish#*
\englishhyphenmins#*
\britishhyphenmins#*
\americanhyphenmins#*
\prefacename#*
\bibname#*
\chaptername#*
\enclname#*
\ccname#*
\headtoname#*
\pagename#*
\seename#*
\alsoname#*
\proofname#*
\glossaryname#*
