# updated 8/19/2021 for v3.7p
#include:etex
#include:iftex
#include:array
#include:dcolumn
#include:delarray
#include:tabularx
#include:textcase

#keyvals:\documentclass/memoir
9pt
10pt
11pt
12pt
14pt
17pt
20pt
25pt
30pt
36pt
48pt
60pt
*pt
extrafontsizes
a6paper
a5paper
a4paper
a3paper
b6paper
b5paper
b4paper
b3paper
mcrownvopaper
mlargecrownvopaper
mdemyvopaper
msmallroyalvopaper
dbillpaper
statementpaper
executivepaper
letterpaper
oldpaper
legalpaper
ledgerpaper
broadsheetpaper
pottvopaper
foolscapvopaper
crownvopaper
postvopaper
largecrownvopaper
largepostvopaper
smalldemyvopaper
demyvopaper
mediumvopaper
smallroyalvopaper
royalvopaper
superroyalvopaper
imperialvopaper
twoside
oneside
onecolumn
twocolumn
openright
openleft
openany
final
draft
ms
showtrims
rleqno
fleqn
openbib
article
oldfontcommands
#endkeyvals

\abnormalparskip{length}#*
\abovecaptionskip
\aboverulesep#*
\abscolnamefont#*
\abscoltextfont#*
\abslabeldelim{text}#*
\absleftindent#*
\absnamepos#*
\absparindent#*L
\absparsep#*L
\absrightindent#*L
\abstitleskip#*L
\abstractcol#*
\abstractintoc#*
\abstractname#*
\abstractnamefont#*
\abstractnum#*
\abstractrunin#*
\abstracttextfont#*
\addappheadtotoc#*
\added{arg1}#*
\addlinespace#*
\addperiod{arg1}#*
\addtodef#*
\addtoiargdef#*
\addtonotes{arg1}#*
\addtopsmarks{arg1}{arg2}{arg3}#*
\addtostream{arg1}{arg2}#*
\afterbookskip#*
\afterchapskip
\afterchapternum#*
\afterchaptertitle#*
\afterepigraphskip
\afterpartskip#*
\afterPoemTitle#*
\afterPoemTitlenum#*
\afterPoemTitleskip
\afterpoemtitleskip
\aliaspagestyle{arg1}{arg2}#*
\alsoname#*
\amname#*
\and#*
\andnext#*
\anyptfilebase#*
\anyptsize#*
\appendixname#*
\appendixpage#*
\appendixpage*#*
\appendixpagename#*
\appendixrefname#*
\appendixtocname#*
\Aref{key}#
\arraybackslash#*
\arraytostring{arg1}{arg2}#*
\AtBeginClass{arg1}{arg2}#*
\AtBeginFile{arg1}{arg2}#*
\AtBeginPackage{arg1}{arg2}#*
\atcentercr#*
\AtEndClass{arg1}{arg2}#*
\AtEndFile{arg1}{arg2}#*
\AtEndPackage{arg1}{arg2}#*
\atendtheglossaryhook#*
\autocols{preamble}{numOfCols}{arg3}{arg4}{arg5}#
\autorows{preamble}{numOfCols}{arg3}{arg4}{arg5}#
\backmatter#
\baselinestretch#*
\beforebookskip#*
\beforechapskip
\beforeepigraphskip
\beforepartskip#*
\beforePoemTitleskip
\beforepoemtitleskip
\begin{adjustwidth*}{left%l}{right%l}
\begin{adjustwidth}#*
\begin{altverse}#
\begin{appendices}#
\begin{bibitemlist}#
\begin{blockdescription}#
\begin{boxedverbatim*}#V
\begin{boxedverbatim}#V
\begin{comment}
\begin{ctabular}[position]{preamble}#\tabular
\begin{DoubleSpace*}#
\begin{DoubleSpace}#
\begin{epigraphs}#
\begin{fboxverbatim}#V
\begin{flexlabelled}#
\begin{framed}#
\begin{hangparas}#
\begin{KeepFromToc}#*
\begin{labelled}#
\begin{leftbar}#
\begin{marginfigure}#
\begin{margintable}#
\begin{midsloppypar}#
\begin{onecolabstract}#
\begin{OnehalfSpace*}#
\begin{OnehalfSpace}#
\begin{patverse*}
\begin{patverse}#
\begin{qframe}#
\begin{qshade}#
\begin{quotation}#
\begin{quote}#
\begin{shaded}#
\begin{sidecaption}[fortoc]{title%plain}[label%plain]#*
\begin{sidecontcaption}{title%plain}[label%plain]#*
\begin{sidelegend}{title%plain}[label%plain]#*
\begin{sidenamedlegend}{title%plain}[label%plain]#*
\begin{SingleSpace}#
\begin{snugshade}#
\begin{Spacing}{factor}#
\begin{subappendices}#
\begin{subfloat}#
\begin{symbols}#
\begin{theglossary}#
\begin{theindex}#
\begin{titlingpage*}#
\begin{titlingpage}#
\begin{verbatimoutput}{file}#V
\begin{verse}#
\begin{vminipage}#
\begin{vplace}#
\begin{writeverbatim}{stream}#V
\begintheglossaryhook#*
\belowcaptionskip
\belowrulesep#*
\bibintoc#*
\bibitemsep
\biblistextra#*
\bibmark#*
\bibname#*
\bibsection#*
\bicaption{arg1}{arg2}{arg3}{arg4}{arg5}#*
\bicontcaption{arg1}{arg2}{arg3}#*
\binding
\bionenumcaption{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#*
\bitwonumcaption{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#*
\bktabrule{arg1}#*
\blockdescriptionlabel{arg1}#*
\book{title}#L0
\bookblankpage#*
\bookname#*
\booknamefont#*
\booknamenum#*
\booknumberline{arg1}#*
\booknumberlinebox#*
\booknumberlinehook{arg1}#*
\booknumfont#*
\bookpageend#*
\bookpagemark{tile}#*
\bookrefname#*
\booktitlefont#*
\bottomrule#*
\bottomsectionpenalty#*
\bottomsectionskip
\boxedverbatim#*
\boxedverbatiminput#*
\boxverbflag#*
\Bref{key}#
\bs#*
\bvbox#*
\bvboxsep
\bvendofpage{arg1}#*
\bvendrulehook#*
\bvleftsidehook#*
\bvnumbersinside#*
\bvnumbersoutside#*
\bvnumlength
\bvperpagefalse#*
\bvperpagetrue#*
\bvrightsidehook#*
\bvsides#*
\bvtopandtail#*
\bvtopmidhook#*
\bvtopofpage{arg1}#*
\bvtoprulehook#*
\cal#*
\calccentering{arg1}#*
\cancelthanksrule#*
\caption#*
\captiondelim{delim}#*
\captionnamefont{font}#*
\captionsize#*
\captionstyle[shortstyle]{style}#*
\captiontitlefinal{text}#*
\captiontitlefont{font}#*
\captionwidth{arg1}#*
\cardinal{arg1}#*
\centerfloat#*
\centerlastline#*
\cftaddnumtitleline{arg1}{arg2}{arg3}{arg4}{arg5}#*
\cftaddtitleline{arg1}{arg2}{arg3}{arg4}#*
\cftappendixname#*
\cftbeforebookskip
\cftbeforechapterskip
\cftbeforepartskip
\cftbookafterpnum#*
\cftbookaftersnum#*
\cftbookaftersnumb#*
\cftbookbreak#*
\cftbookdotsep#*
\cftbookfillnum{arg1}#*
\cftbookfont#*
\cftbookformatpnum{arg1}#*
\cftbookformatpnumhook{arg1}#*
\cftbookindent#*
\cftbookleader#*
\cftbookname#*
\cftbooknumwidth#*
\cftbookpagefont#*
\cftbookpresnum#*
\cftchapterafterpnum#*
\cftchapteraftersnum#*
\cftchapteraftersnumb#*
\cftchapterbreak#*
\cftchapterdotsep#*
\cftchapterfillnum{arg1}#*
\cftchapterfont#*
\cftchapterformatpnum{arg1}#*
\cftchapterformatpnumhook{arg1}#*
\cftchapterindent
\cftchapterleader#*
\cftchaptername#*
\cftchapternumwidth
\cftchapterpagefont#*
\cftchapterpresnum#*
\cftdot#*
\cftdotfill{arg1}#*
\cftdotsep#*
\cftinsert{arg1}#*
\cftinsertcode{arg1}{arg2}#*
\cftinserthook{arg1}{arg2}#*
\cftlocalchange{arg1}{arg2}{arg3}#*
\cftnodots#*
\cftpagenumbersoff{kind}#*
\cftpagenumberson{kind}#*
\cftparfillskip#*
\cftparskip
\cftpartafterpnum#*
\cftpartaftersnum#*
\cftpartaftersnumb#*
\cftpartbreak#*
\cftpartdotsep#*
\cftpartfillnum{arg1}#*
\cftpartfont#*
\cftpartformatpnum{arg1}#*
\cftpartformatpnumhook{arg1}#*
\cftpartindent
\cftpartleader#*
\cftpartname#*
\cftpartnumwidth
\cftpartpagefont#*
\cftpartpresnum#*
\cftsetindents{arg1}{arg2}{arg3}#*
\cftwhatismyname#*
\changecaptionwidth#*
\changed{arg1}#*
\changeglossactual{arg1}{arg2}#*
\changeglossnum{arg1}{arg2}#*
\changeglossnumformat{arg1}{arg2}#*
\changeglossref{arg1}{arg2}#*
\changemarks#*
\chapindent
\chapnamefont#*
\chapnumfont#*
\chapter*{title}#*
\chapter[toc-title%title][head-title%title]{title}#*
\chapter[toc-title%title]{title}#*
\chapter{title}#L2
\chapterheadstart#*
\chaptermark#*
\chaptermark{arg1}#*
\chaptername#*
\chapternamenum#*
\chapternumberline{arg1}#*
\chapternumberlinebox#*
\chapternumberlinehook{arg1}#*
\chapterprecis{text}#*
\chapterprecishere{text}#*
\chapterprecistoc{text}#*
\chapterrefname#*
\chapterstyle{style%keyvals}#*
#keyvals:\chapterstyle
bianchi
bringhurst
brotherton
chappell
crosshead
culver
dash
demo2
demo3
dowding
ell
ger
komalike
lyhne
madsen
ntglike
pedersen
southall
tandh
thatcher
veelo
verville
wilsondob
%chapterstyle
#endkeyvals
\chaptitlefont#*
\checkandfixthelayout[algoritm%keyvals]#*
#keyvals:\checkandfixthelayout
fixed
classic
lines
nearest
#endkeyvals
\checkarrayindex{arg1}{arg2}#*
\checkifinteger{arg1}#*
\checkoddpage#*
\checkthelayout[algoritm%keyvals]#*
#keyvals:\checkthelayout
fixed
classic
lines
nearest
#endkeyvals
\cite#*
\citeindexfile#*
\cleardoublepage#*
\clearforchapter#*
\clearmark{arg1}#*
\clearplainmark{arg1}#*
\cleartoevenpage{arg1}#*
\cleartooddpage{arg1}#*
\cleartorecto#*
\cleartoverso#*
\closeinputstream{arg1}#*
\closeoutputstream{arg1}#*
\cmd{arg1}#*
\cmdprint{arg1}#*
\cmidrule#*
\cmidrulekern#*
\cmidrulewidth#*
\cmrsideswitch#*
\colorchapnum#*
\colorchaptitle#*
\commentsoff{arg1}#*
\commentson{arg1}#*
\contcaption#*
\contentsname#*
\continuousmarks#*
\continuousnotenums#*
\contsubbottom#*
\contsubcaption#*
\contsubtop#*
\copypagestyle{arg1}{arg2}#*
\counterwithin#*
\counterwithout#*
\cplabel#*
\createmark{arg1}{arg2}{arg3}{arg4}{arg5}#*
\createplainmark{arg1}{arg2}{arg3}#*
\Cref{key}#
\cs{arg}
\ctabsetlines#*
\ctabular{arg1}#*
\currenttitle#*
\dashbox{length}(width,height)[position]{text}
\date#*
\defaultaddspace#*
\defaultlists#*
\defaultsecnum#*
\deleted{arg1}#*
\DeleteShortVerb{arg1}#*
\descriptionlabel{arg1}#*
\DisemulatePackage{arg1}#*
\do#*
\doccoltocetc#*
\DoubleSpacing#*
\DoubleSpacing*#*
\downbracefill#*
\dropchapter{arg1}#*
\droptitle#*
\easypagecheck#*
\eminnershape{shape}#*
\emptythanks#*
\EmulatedPackage#*
\EmulatedPackageWithOptions#*
\end{adjustwidth*}
\end{adjustwidth}#
\end{altverse}#
\end{appendices}#
\end{bibitemlist}#
\end{blockdescription}#
\end{boxedverbatim*}#V
\end{boxedverbatim}#V
\end{comment}
\end{ctabular}
\end{DoubleSpace*}#
\end{DoubleSpace}#
\end{epigraphs}#
\end{fboxverbatim}#V
\end{flexlabelled}#
\end{framed}#
\end{hangparas}#
\end{KeepFromToc}#*
\end{labelled}#
\end{leftbar}#
\end{marginfigure}#
\end{margintable}#
\end{midsloppypar}#
\end{onecolabstract}#
\end{OnehalfSpace*}#
\end{OnehalfSpace}#
\end{patverse*}
\end{patverse}#
\end{qframe}#
\end{qshade}#
\end{quotation}#
\end{quote}#
\end{shaded}#
\end{sidecaption}#*
\end{sidecontcaption}#*
\end{sidelegend}#*
\end{sidenamedlegend}#*
\end{SingleSpace}#
\end{snugshade}#
\end{Spacing}#
\end{subappendices}#
\end{subfloat}#
\end{symbols}#
\end{theglossary}#
\end{theindex}#
\end{titlingpage*}#
\end{titlingpage}#
\end{verbatimoutput}#V
\end{verse}#
\end{vminipage}#
\end{vplace}#
\end{writeverbatim}#V
\endarray#*
\endboxedverbatim#*
\endctabular#*
\endfboxverbatim#*
\enditemize#*
\endMakeFramed#*
\endminipage#*
\endnoteentry#*
\endnoteentryend#*
\endsidecaption#*
\endsidecontcaption#*
\endsidelegend#*
\endsidenamedlegend#*
\endtabular#*
\endtabularx#*
\endverbatim#*
\endverbatimoutput#*
\endwriteverbatim#*
\ensureonecol#*
\enumerate#*
\epigraph{arg1}{arg2}#*
\epigraphflush#*
\epigraphfontsize{fontsize}#*
\epigraphforheader{arg1}{arg2}#*
\epigraphhead{arg1}{arg2}#*
\epigraphpicture#*
\epigraphposition{flush}#*
\epigraphrule
\epigraphsize#*
\epigraphsourceposition{flush}#*
\epigraphtextposition{flush}#*
\epigraphwidth
\extrafeetendmini#*
\extrafeetendminihook#*
\extrafeetins#*
\extrafeetinshook#*
\extrafeetminihook#*
\extrafeetreinshook#*
\extratabsurround
\fancybreak#*
\fboxverbatim#*
\fcardinal{arg1}#*
\feetabovefloat#*
\feetbelowfloat#*
\figurename#*
\figurerefname#*
\firmlist#*
\firmlists#*
\FirstFrameCommand#*
\firsthline#*
\fixdvipslayout#*
\fixheaderwidths#*
\fixpdflayout#*
\fixthelayout#*
\flagverse{arg1}#*
\flegfigure#*
\flegtable#*
\FloatBlock#*
\FloatBlockAllowAbove#*
\FloatBlockAllowBelow#*
\flushleftright#*
\fnumbersep#*
\footfootmark#*
\footfudgefiddle#*
\footinsdim
\footmarksep
\footmarkstyle{style}#*
\footmarkwidth
\footnote#*
\footnotemark#*
\footnoterule#*
\footnotesatfoot#*
\footnotesinmargin#*
\footnotesize#*
\footparindent
\footref{arg1}#*
\footruleheight#*
\footruleskip#*
\footscript#*
\foottextfont#*
\foottopagenote#*
\fordinal{arg1}#*
\foremargin
\FrameCommand#*
\framed#*
\FrameHeightAdjust#*
\framepichead#*
\framepichook#*
\framepictextfoot#*
\FrameRestore#*
\FrameRule#*
\FrameSep#*
\fref{key}#
\frenchspacing#*
\frontmatter#*
\frontmatter*#*
\Ftrimpicbl#*
\futurenonspacelet{arg1}#*
\getarrayelement{arg1}{arg2}{arg3}#*
\getthelinenumber{arg1}{arg2}#*
\glossary#*
\glossarycolsep#*
\glossaryintoc#*
\glossarymark#*
\glossaryname#*
\glossaryrule#*
\glossaryspace#*
\glossitem{arg1}{arg2}{arg3}{arg4}#*
\gobm{arg1}#*
\hangcaption#*
\hangfrom{arg1}#*
\hangpara{arg1}{arg2}#*
\hangsecnum#*
\hangsubcaption#*
\hbadness#*
\headdrop
\headnameref#*
\headstyles{arg1}#*
\headwidth
\heavyrulewidth#*
\hfuzz#*
\hideindexmarks#*
\hline#*
\hmpunct#*
\huge#*
\hyperlink{arg1}{arg2}#*
\hyperpage{arg1}#*
\hyperspindexpage#*
\i#*
\idtextinnotes{arg1}#*
\ifbounderror#*
\ifdraftdoc#*
\ifinteger#*
\ifoddpage#*
\ifonlyfloats{arg1}{arg2}#*
\ifsamename#*
\ifsidecapleft#*
\IfStreamOpen{arg1}{arg2}{arg3}#*
\ignorenoidxfile#*
\iiirdstring#*
\iindstring#*
\indentafterchapter#*
\indentcaption{arg1}#*
\indentpattern{arg1}#*
\indexcolsep
\indexintoc#*
\indexmark#*
\indexmarkstyle#*
\indexname#*
\indexrule
\indexspace#*
\insertchapterspace#*
\iscntrmod{arg1}{arg2}#*
\isopage{spine%l}#*
\iststring#*
\itemsepi
\itemsepii
\itemsepiii
\justlastraggedleft#*
\KeepFromToc#*
\keepthetitle#*
\killtitle#*
\LARGE#*
\Large#*
\LastFrameCommand#*
\lasthline#*
\lastlineparrule#*
\lastlinerulefill#*
\lcminusname#*
\leadpagetoclevel#*
\leavespergathering{arg1}#*
\leftbar#*
\leftcenterright#*
\leftspringright{arg1}{arg2}{arg3}{arg4}#*
\legend{arg1}#*
\letcountercounter{arg1}{arg2}#*
\lightrulewidth#*
\linemodnum#*
\linenottooshort{arg1}#*
\linenumberfont{font}#*
\linenumberfrequency{arg1}#*
\linespercol#*
\listfigurename#*
\listtablename#*
\lofmark#*
\loosesubcaptions#*
\lotmark#*
\lowermargin
\Ltrimpicbl#*
\Ltrimpicbr#*
\Ltrimpictl#*
\Ltrimpictr#*
\lxvchars
\m#*
\mainmatter#*
\mainmatter*#*
\makechapterstyle{name}{style}#*s#%chapterstyle
\makeevenfoot{arg1}{arg2}{arg3}{arg4}#*
\makeevenhead{arg1}{arg2}{arg3}{arg4}#*
\makefootmark{arg1}#*
\makefootmarkhook#*
\makefootrule{arg1}{arg2}{arg3}{arg4}#*
\MakeFramed{arg1}#*
\makeglossary#*
\makeheadfootruleprefix{arg1}{arg2}{arg3}#*
\makeheadfootstrut{arg1}{arg2}{arg3}#*
\makeheadfootvposition{arg1}{arg2}{arg3}#*
\makeheadposition{arg1}{arg2}{arg3}{arg4}{arg5}#*
\makeheadrule{arg1}{arg2}{arg3}#*
\makeheadstyles{arg1}{arg2}#*
\makeindex#*
\makelabel#*
\makememglossaryhook#*
\makememindexhook#*
\makeoddfoot{arg1}{arg2}{arg3}{arg4}#*
\makeoddhead{arg1}{arg2}{arg3}{arg4}#*
\makepagenote#*
\makepagestyle{arg1}#*
\makepsmarks{arg1}{arg2}#*
\makerunningfootwidth{arg1}{arg2}#*
\makerunningheadwidth{arg1}{arg2}#*
\makerunningwidth{arg1}#*
\MakeShortVerb{arg1}#*
\makesidefootmark{arg1}#*
\makesidefootmarkhook#*
\MakeTextLowercase{text}#*
\MakeTextUppercase{text}#*
\makethanksmark#*
\makethanksmarkhook#*
\maketitle#
\maketitlehooka#*
\maketitlehookb#*
\maketitlehookc#*
\maketitlehookd#*
\marg{arg}
\marginfloatmarginmacro#*
\marginparmargin{arg1}#*
\markboth#*
\markright#*
\maxsecnumdepth{secname%keyvals}#*
#keyvals:\maxsecnumdepth
book
part
chapter
section
subsection
subsubsection
paragraph
subparagraph
#endkeyvals
\maxtocdepth{arg1}#*
\medievalpage{spine%l}#*
\medspace#*
\mem#*
\memappchapinfo{arg1}{arg2}{arg3}{arg4}#*
\memappchapstarinfo{arg1}{arg2}#*
\memapppageinfo{arg1}#*
\memapppagestarinfo{arg1}#*
\membicaptioninfo{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#*
\membionenumcaptioninfo{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}{arg7}#*
\membitwonumcaptioninfo{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}{arg7}#*
\membookinfo{arg1}{arg2}{arg3}#*
\membookstarinfo{arg1}#*
\memcaptioninfo#*
\memcaptioninfo{arg1}{arg2}{arg3}{arg4}#*
\memchapinfo{arg1}{arg2}{arg3}{arg4}#*
\memchapstarinfo{arg1}{arg2}#*
\memcline{arg1}{arg2}#*
\memdskips#*
\memdskipstretch#*
\memendofchapterhook#*
\memfblineboxa{arg1}#*
\memfblineboxtwo{arg1}#*
\memfblistfixparams#*
\memfontenc#*
\memfontfamily#*
\memfontpack#*
\memglodesc{arg1}#*
\memglofile#*
\memglonum{arg1}#*
\memgloref{arg1}#*
\memgloterm{arg1}#*
\memgobble{arg1}#*
\memhline{arg1}#*
\memifmacroused{arg1}#*
\memjustarg{arg1}#*
\memleadpageinfo{arg1}{arg2}{arg3}#*
\memleadpagestarinfo{arg1}{arg2}{arg3}#*
\memlegendinfo{arg1}#*
\memlettxttxt{arg1}#*
\memlistsubcaptions#*
\memnamedlegendinfo{arg1}{arg2}{arg3}#*
\memoirpostopthook#*
\memorigdbs#*
\memorigpar#*
\mempartinfo{arg1}{arg2}{arg3}#*
\mempartstarinfo{arg1}#*
\mempnofilewarn#*
\mempoeminfo{arg1}#*
\mempoemstarinfo{arg1}#*
\memPoemTitleinfo{arg1}{arg2}{arg3}{arg4}#*
\memPoemTitlestarinfo{arg1}{arg2}#*
\mempostaddapppagetotochook#*
\mempostaddbooktotochook#*
\mempostaddchaptertotochook#*
\mempostaddparttotochook#*
\mempreaddapppagetotochook#*
\mempreaddbooktotochook#*
\mempreaddchaptertotochook#*
\mempreaddparttotochook#*
\memRTLleftskip#*
\memRTLmainraggedleft#*
\memRTLmainraggedright#*
\memRTLraggedleft#*
\memRTLraggedright#*
\memRTLrightskip#*
\memRTLvleftskip#*
\memRTLvrightskip#*
\memsavefootnote#*
\memsavepagenote#*
\memsecinfo{arg1}{arg2}{arg3}{arg4}{arg5}#*
\memsecstarinfo{arg1}{arg2}#*
\memsetcounter{arg1}{arg2}#*
\memsetlengthmax{arg1}{arg2}{arg3}#*
\memsetlengthmin{arg1}{arg2}{arg3}#*
\memsetmacrounused{arg1}#*
\memsetmacroused{arg1}#*
\memUChead#*
\memversion#*
\memwritetoglo#*
\memwritetoglo{arg1}{arg2}{arg3}{arg4}{arg5}#*
\mergepagefloatstyle{arg1}{arg2}{arg3}#*
\meta{arg}
\midbicaption{text}
\midbookskip#*
\midchapskip
\MidFrameCommand#*
\midpartskip#*
\midPoemTitleskip
\midrule#*
\midsloppy#*
\miniscule#*
\minusname#*
\mit#*
\morecmidrules#*
\movetoevenpage{arg1}#*
\movetooddpage{arg1}#*
\mpjustification#*
\msdoublespacing#*
\mssinglespacing#*
\multfootsep#*
\multicolumn{arg1}#*
\multiplefootnotemarker#*
\multiput(x,y)(dx,dy){num}{object}#/picture
\namedlegend#*
\namedsubappendices#*
\namenumberand#*
\namenumbercomma#*
\namerefoff#*
\namerefon#*
\nametest{arg1}{arg2}#*
\Needspace#*
\needspace{arg1}#*
\newarray{arg1}{arg2}{arg3}#*
\newblock#*
\newcolumntype{arg1}#*
\newcomment{arg1}#*
\newfixedcaption{arg1}{arg2}{arg3}#*
\newfloat#*
\newfloat{arg1}{arg2}{arg3}{arg4}#*
\newfootnoteseries{arg1}#*
\newinputstream{arg1}#*
\newleadpage*{pagestyle}{cmd}{title}#*
\newleadpage{pagestyle}{cmd}{title}#*
\newlistentry{arg1}{arg2}{arg3}{arg4}#*
\newlistof{arg1}{arg2}{arg3}#*
\newloglike#*
\newoutputstream{arg1}#*
\newpmemlabel{arg1}{arg2}#*
\newsubfloat{arg1}#*
\nexttoken#*
\nNamec#*
\nNamei#*
\nNameii#*
\nNameiii#*
\nNameiv#*
\nNameix#*
\nNamel#*
\nNamelx#*
\nNamelxx#*
\nNamelxxx#*
\nNamem#*
\nNamemm#*
\nNamemmm#*
\nNameo#*
\nNamev#*
\nNamevi#*
\nNamevii#*
\nNameviii#*
\nNamex#*
\nNamexc#*
\nNamexi#*
\nNamexii#*
\nNamexiii#*
\nNamexiv#*
\nNamexix#*
\nNamexl#*
\nNamexv#*
\nNamexvi#*
\nNamexvii#*
\nNamexviii#*
\nNamexx#*
\nNamexxx#*
\nobibintoc#*
\nobookblankpage#*
\nobvbox#*
\NoCaseChange{text}#*
\nochangemarks#*
\noDisplayskipStretch#*
\noglossaryintoc#*
\noindentafterchapter#*
\noindexintoc#*
\nonzeroparskip#*
\nopartblankpage#*
\noprelistbreak#*
\normalbottomsection#*
\normalcaption#*
\normalcaptionwidth#*
\normalrulethickness
\normalsubcaption#*
\notedivision#*
\noteidinnotes{arg1}{arg2}#*
\noteinnotes{arg1}#*
\notenuminnotes{arg1}#*
\notenumintext{arg1}#*
\notepageref#*
\notesname#*
\nouppercaseheads#*
\nthNamei#*
\nthNameii#*
\nthNameiii#*
\nthNameiv#*
\nthNameix#*
\nthNamel#*
\nthNamelx#*
\nthNamelxx#*
\nthNamelxxx#*
\nthNameo#*
\nthNamev#*
\nthNamevi#*
\nthNamevii#*
\nthNameviii#*
\nthNamexc#*
\nthNamexii#*
\nthNamexl#*
\nthNamexx#*
\nthNamexxx#*
\nthstring#*
\numberline#*
\numberlinebox#*
\numberlinehook{arg1}#*
\NumberPoemTitle#*
\numdigits{arg1}#*
\NumtoName{number}#*
\numtoName{number}#*
\numtoname{number}#*
\oarg{arg}
\onecolglossary#*
\onecolindex#*
\onecoltocetc#*
\OnehalfSpacing#*
\OnehalfSpacing*#*
\onelineskip
\openany#*
\openinputfile{arg1}{arg2}#*
\openleft#*
\openoutputfile{arg1}{arg2}#*
\openright#*
\ordinal{arg1}#*
\OrdinaltoName{number}#*
\ordinaltoName{number}#*
\ordinaltoname{number}#*
\ordscript{arg1}#*
\ordstring#*
\oval(width,height)[portion]#/picture
\overridescapmargin{arg1}#*
\pageai#*
\pageaii#*
\pageaiii#*
\pageaiv#*
\pageao#*
\pageav#*
\pageavi#*
\pagebi#*
\pagebii#*
\pagebiii#*
\pagebiv#*
\pagebo#*
\pagebroadsheet#*
\pagebv#*
\pagebvi#*
\pagecrownvo#*
\pagedbill#*
\pagedemyvo#*
\pageexecutive#*
\pagefoolscapvo#*
\pageimperialvo#*
\pageinnotes{arg1}#*
\pagelargecrownvo#*
\pagelargepostvo#*
\pageledger#*
\pagelegal#*
\pageletter#*
\pagemcrownvo#*
\pagemdemyvo#*
\pagemediumvo#*
\pagemlargecrownvo#*
\pagemsmallroyalvo#*
\pagename#*
\pagenote#*
\pagenoteanchor#*
\pagenotehyperanchor{arg1}#*
\pagenotesubhead{arg1}{arg2}{arg3}#*
\pagenotesubheadstarred#*
\pageold#*
\pagepostvo#*
\pagepottvo#*
\pagerefname#*
\pageroyalvo#*
\pagesmalldemyvo#*
\pagesmallroyalvo#*
\pagestatement#*
\pagesuperroyalvo#*
\pagetofootnote#*
\paragraph*{title}#*
\paragraph[toc-title%title][head-title%title]{title}#*
\paragraph[toc-title%title]{title}#*
\paragraph{title}#L6
\paragraphfootnotes#*
\paragraphfootstyle{style}#*
\paraheadstyle#*
\parahook#*
\paraindent#*L
\parg{arg}
\parnopar#*
\parsepi
\parsepii
\part{title}#L1
\partblankpage#*
\partmark{tile}#*
\partname#*
\partnamefont#*
\partnamenum#*
\partnumberline{arg1}#*
\partnumberlinebox#*
\partnumberlinehook{arg1}#*
\partnumfont#*
\partopsepii
\partopsepiii
\partpageend#*
\partrefname#*
\parttitlefont#*
\patchcmdError{arg1}#*
\patchcommand{arg1}#*
\pfbreak#*
\pfbreakdisplay#*
\pfbreakOutput#*
\pfbreakskip
\phantomsection#*
\plainbreak#*
\plainfancybreak#*
\plainfootnotes#*
\plainfootstyle{arg1}#*
\PlainPoemTitle#*
\pmemlabel{arg1}#*
\pmemlabelref{arg1}#*
\pmname#*
\pnchap#*
\pnschap#*
\PoemTitle#*
\poemtitle#*
\PoemTitlefont#*
\poemtitlefont#*
\PoemTitleheadstart#*
\poemtitlemark{arg1}#*
\PoemTitlenumfont#*
\poemtitlepstyle#*
\poemtitlestarmark{arg1}#*
\poemtitlestarpstyle#*
\poemtoc#*
\postauthor{text}#*
\postautotab#*
\postbibhook#*
\postcaption{text}
\postchapterprecis#*
\postdate{text}#*
\postitle{text}
\postnoteinnotes#*
\postnotetext#*
\posttitle{text}#*
\preauthor{text}#*
\preautotab#*
\prebibhook#*
\precaption{text}
\prechapterprecis#*
\prechapterprecisshift#*
\precisfont#*
\precistocfont#*
\precistocformat#*
\precistoctext{text}#*
\predate{text}#*
\pref{arg1}#*
\Pref{key}#
\preglossaryhook#*
\preindexhook#*
\prenoteinnotes#*
\prenotetext#*
\pretitle{text}#*
\printbookname#*
\printbooknum#*
\printbooktitle{title}#*
\printchaptername#*
\printchapternonum#*
\printchapternum#*
\printchaptertitle{title}#*
\printglossary{arg1}#*
\printindex{arg1}#*
\printpageinnotes{text}#*
\printpageinnoteshyperref{arg1}#*
\printpagenotes#*
\printpartname#*
\printpartnum#*
\printparttitle{title}#*
\printPoemTitlenonum#*
\printPoemTitlenum#*
\printPoemTitletitle#*
\printtime#*
\protect#*
\providecounter{arg1}#*
\provideenvironment#*
\providefixedcaption{arg1}{arg2}{arg3}#*
\providelength{arg1}#*
\provideloglike#*
\put(x,y){object}#/picture
\qbezier[num](Xs,Ys)(Xm,Ym)(Xe,Ye)#/picture
\qbeziermax#*
\qitem{arg1}{arg2}#*
\qitemlabel{arg1}#*
\quarkmarks#*
\raggedbottomsection#*
\raggedrightthenleft#*
\raggedwrap#*
\raggedyright{arg1}#*
\ragrparindent#*
\readaline{arg1}#*
\readboxedverbatim#*
\readstream{arg1}#*
\readverbatim#*
\refixpagelayout#*
\registrationColour{arg1}#*
\renewfixedcaption{arg1}{arg2}{arg3}#*
\renewleadpage*{pagestyle}{cmd}{title}#*
\renewleadpage{pagestyle}{cmd}{title}#*
\reparticle#*
\reportnoidxfile#*
\RequireAtEndClass{arg1}{arg2}#*
\RequireAtEndPackage{arg1}{arg2}#*
\RequireXeTeX#*
\resetbvlinenumber#*
\restoreapp#*
\restorefromonecol#*
\restorepagenumber#*
\restoretrivseps#*
\russianpar#*
\savepagenumber#*
\savetrivseps#*
\saythanks#*
\sc#*
\scriptsize#*
\secheadstyle#*
\sechook#*
\secindent#*L
\section*{title}#*
\section[toc-title%title][head-title%title]{title}#*
\section[toc-title%title]{title}#*
\section{title}#L3
\sectionmark#*
\sectionname#*
\sectionrefname#*
\see{arg1}{arg2}#*
\seealso{arg1}{arg2}#*
\seename#*
\semiisopage{spine%l}#*
\setafterparaskip{arg1}#*
\setaftersecskip{arg1}#*
\setaftersubparaskip{arg1}#*
\setaftersubsecskip{arg1}#*
\setaftersubsubsecskip{arg1}#*
\setarrayelement{arg1}{arg2}{arg3}#*
\setbeforeparaskip{arg1}#*
\setbeforesecskip{arg1}#*
\setbeforesubparaskip{arg1}#*
\setbeforesubsecskip{arg1}#*
\setbeforesubsubsecskip{arg1}#*
\setbiblabel{arg1}#*
\setbinding{arg1}#*
\setbvlinenums{arg1}{arg2}#*
\setcolsepandrule{arg1}{arg2}#*
\setDisplayskipStretch{fraction}#*
\setfillsize{arg1}{arg2}{arg3}{arg4}{arg5}#*
\setfloatadjustment{arg1}{arg2}#*
\setFloatBlockFor{arg1}#*
\setFloatBLockFor{sectional name}#*
\setfloatlocations{arg1}{arg2}#*
\setFloatSpacing{factor}#*
\setfootins{length normal}{length minipage}#*
\setfootnoterule{arg1}{arg2}{arg3}{arg4}#*
\sethangfrom{arg1}#*
\setheaderspaces{headdrop%l}{headsep%l}{ratio}#*
\setheadfoot{headheight%l}{footskip%l}#*
\setlrmargins{spine%l}{edge%l}{ratio}#*
\setlrmarginsandblock{spine%l}{edge%l}{ratio}#*
\setlxvchars{arg1}#*
\setmarginfloatcaptionadjustment{arg1}{arg2}#*
\setmarginnotes{separation%l}{width}{psuh%l}#*
\setmpbools#*
\setmpjustification{arg1}{arg2}#*
\setnzplist#*
\setpagebl{height}{width}{ratio}#*
\setpagebm{height}{width}{ratio}#*
\setpagebr{height}{width}{ratio}#*
\setpagecc{height}{width}{ratio}#*
\setpageml{height}{width}{ratio}#*
\setpagemr{height}{width}{ratio}#*
\setPagenoteSpacing{factor}#*
\setpagetl{height}{width}{ratio}#*
\setpagetm{height}{width}{ratio}#*
\setpagetr{height}{width}{ratio}#*
\setparaheadstyle{arg1}#*
\setparahook{arg1}#*
\setparaindent{arg1}#*
\setpnumwidth{arg1}#*
\setrectanglesize{arg1}{arg2}{arg3}#*
\setrmarg{arg1}#*
\setsecheadstyle{arg1}#*
\setsechook{arg1}#*
\setsecindent{arg1}#*
\setsecnumdepth{secname%keyvals}#*
#keyvals:\setsecnumdepth
book
part
chapter
section
subsection
subsubsection
paragraph
subparagraph
#endkeyvals
\setsecnumformat{arg1}#*
\setsidebarheight{arg1}#*
\setsidebars{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#*
\setsidecappos{arg1}#*
\setsidecaps{arg1}{arg2}#*
\setsidefeet{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#*
\setsidefootheight{height}#
\setSingleSpace{factor}#*
\setSpacing{arg1}#*
\setspbools#*
\setspcode#*
\setstocksize{height}{width}#*
\setsubparaheadstyle{arg1}#*
\setsubparahook{arg1}#*
\setsubparaindent{arg1}#*
\setsubsecheadstyle{arg1}#*
\setsubsechook{arg1}#*
\setsubsecindent{arg1}#*
\setsubsubsecheadstyle{arg1}#*
\setsubsubsechook{arg1}#*
\setsubsubsecindent{arg1}#*
\setthesection#*
\settocdepth{arg1}#*
\settocpreprocessor{arg1}{arg2}#*
\settrimmedsize{height}{width}{ratio}#*
\settrims{top}{foredge}#*
\settypeblocksize{height}{width}{ratio}#*
\settypeoutlayoutunit{unit}#*
\setulmargins{upper%l}{lower%l}{ratio}#*
\setulmarginsandblock{upper%l}{lower%l}{ratio}#*
\setupcomment#*
\setverbatimbreak#*
\setverbatimfont{font}#*
\setverselinenums{arg1}{arg2}#*
\setxlvchars{arg1}#*
\shaded#*
\shortsubcaption#*
\showcols#*
\showheadfootlocoff#*
\showheadfootlocon#*
\showindexmarks#*
\showtextblocklocoff#*
\showtextblocklocon#*
\showtextblockoff#*
\showtrimsoff#*
\showtrimson#*
\sidcapwidth#*
\sidebar{arg1}#*
\sidebarfont#*
\sidebarform#*
\sidebarhsep
\sidebarmargin{arg1}#*
\sidebartopsep
\sidebarvsep
\sidebarwidth
\sidecapfloatwidth#*
\sidecapmargin{arg1}#*
\sidecapraise#*
\sidecapsep#*
\sidecapsep#*
\sidecapstyle#*
\sidecaption#*
\sidecapwidth#*
\sidecontcaption#*
\sidecontents#*
\sidefootadjust
\sidefootcontents#*
\sidefootfootmark#*
\sidefootform#*
\sidefootheight
\sidefoothsep
\sidefootmargin{arg1}#*
\sidefootmarksep
\sidefootmarkwidth
\sidefootnote#*
\sidefootnotemark#*
\sidefootnotetext#*
\sidefootparindent
\sidefootscript#*
\sidefoottextfont#*
\sidefootvsep
\sidefootwidth
\sidelegend#*
\sidenamedlegend#*
\sidepar#*
\sideparfont#*
\sideparform#*
\sideparmargin{arg1}#*
\sideparvshift
\SingleSpacing#*
\slashfrac{top}{bottom}
\slashfracstyle{fraction}#*
\sloppybottom#*
\snugshade#*
\sourceatright{arg1}{arg2}#*
\sourceflush#*
\specialindex#*
\specialindex{arg1}{arg2}{arg3}#*
\specialrule{arg1}#*
\spinemargin
\Sref{key}#
\stanzaskip
\startnoteentry#*
\startnoteentrystart{arg1}{arg2}{arg3}{arg4}#*
\stockai#*
\stockaii#*
\stockaiii#*
\stockaiv#*
\stockao#*
\stockav#*
\stockavi#*
\stockbi#*
\stockbii#*
\stockbiii#*
\stockbiv#*
\stockbo#*
\stockbroadsheet#*
\stockbv#*
\stockbvi#*
\stockcrownvo#*
\stockdbill#*
\stockdemyvo#*
\stockexecutive#*
\stockfoolscapvo#*
\stockheight#*
\stockimperialvo#*
\stocklargecrownvo#*
\stocklargepostvo#*
\stockledger#*
\stocklegal#*
\stockletter#*
\stockmcrownvo#*
\stockmdemyvo#*
\stockmediumvo#*
\stockmlargecrownvo#*
\stockmsmallroyalvo#*
\stockold#*
\stockpostvo#*
\stockpottvo#*
\stockroyalvo#*
\stocksmalldemyvo#*
\stocksmallroyalvo#*
\stockstatement#*
\stocksuperroyalvo#*
\stockwidth
\strictpagecheck#*
\stringtoarray{arg1}{arg2}#*
\subbottom#*
\subcaption#*
\subcaptionfont{font}#*
\subcaptionlabelfont{font}#*
\subcaptionref{label}#*r
\subcaptionsize{size}#*
\subcaptionstyle{style}#*
\subconcluded#*
\subitem#*
\subparagraph*{title}#*
\subparagraph[toc-title%title][head-title%title]{title}#*
\subparagraph[toc-title%title]{title}#*
\subparagraph{title}#L7
\subparaheadstyle#*
\subparahook#*
\subparaindent
\subsecheadstyle#*
\subsechook#*
\subsecindent#*L
\subsection*{title}#*
\subsection[toc-title%title][head-title%title]{title}#*
\subsection[toc-title%title]{title}#*
\subsection{title}#L4
\subsubitem#*
\subsubsecheadstyle#*
\subsubsechook#*
\subsubsecindent
\subsubsection*{title}#*
\subsubsection[toc-title%title][head-title%title]{title}#*
\subsubsection[toc-title%title]{title}#*
\subsubsection{title}#L5
\subtop#*
\symboldef{arg1}{arg2}#*
\symbollabel{arg1}#*
\symbolthanksmark#*
\tablename#*
\tablerefname#*
\tabsoff#*
\tabson{arg1}#*
\tabularnewline#*
\tabularxcolumn{arg1}#*
\tamark#*
\teennumbername{arg1}#*
\teenordinalname{arg1}#*
\teenstring#*
\tensnumbername{arg1}{arg2}#*
\tensordinalname{arg1}{arg2}#*
\tensunitsep#*
\textflush#*
\thanks#*
\thanksfootextra#*
\thanksfootmark#*
\thanksgap#*
\thanksgap{arg1}#*
\thanksheadextra{pre}{post}#*
\thanksmark{n}#*
\thanksmarksep#*L
\thanksmarkseries{format}#*
\thanksmarkstyle{defn}#*
\thanksmarkwidth#*L
\thanksrule#*
\thanksscript{text}#*
\theauthor#*
\thebook
\thebvlinectr
\thechapter
\thechrsinstr
\thedate#*
\theHbook#*
\theHpoem#*
\theHpoemline#*
\thelastpage
\thelastsheet
\themaxsecnumdepth
\thememfbvline
\thememfvsline
\thepagenote
\thepagenoteshadow
\theparagraph
\thepart
\thepoem
\thepoemline
\thesection
\thesheetsequence
\thesidefootnote
\thesidempfn#*
\thestoredpagenumber
\thesubparagraph
\thesubsection
\thesubsubsection
\thetitle#*
\theTitleReference{arg1}{arg2}#*
\theverse
\thevslineno
\thicklines#/picture
\thinlines#/picture
\threecolumnfootnotes#*
\threecolumnfootstyle{arg1}#*
\tiethstring#*
\tightlist#*
\tightlists#*
\tightsubcaptions#*
\titleref{label}#r
\titlingpageend#*
\tmarkbl#*
\tmarkbm#*
\tmarkbr#*
\tmarkml#*
\tmarkmr#*
\tmarktl#*
\tmarktm#*
\tmarktr#*
\tocbaseline
\tocentryskip
\tocmark#*
\tocnameref#*
\tocskip{arg1}#*
\today#*
\toprule#*
\topsepi
\topsepii
\topsepiii
\tracingtabularx#*
\traditionalparskip#*
\tref{arg1}#*
\trimedge
\trimFrame#*
\trimLmarks#*
\trimmark#*
\trimmarks#*
\trimmarkscolor#*
\trimNone#*
\trimtop
\trimXmarks#*
\tt#*
\twocolglossary#*
\twocolindex#*
\twocoltocetc#*
\twocolumnfootnotes#*
\twocolumnfootstyle{arg1}#*
\typeoutlayout#*
\typeoutstandardlayout#*
\ucminusname#*
\undodrop#*
\unitnumbername{arg1}#*
\unitordinalname{arg1}#*
\unletcounter{arg1}#*
\unnamedsubappendices#*
\uppercaseheads#*
\uppermargin
\usethanksrule#*
\vector(i,j){distance%l}#/picture
\verb#*
\verbatimbreakchar#*
\verbatimindent
\verbatiminput#*
\verbatimoutput{arg1}#*
\verbfootnote#*
\verselinebreak{arg1}#*
\verselinenumbersleft#*
\verselinenumbersright#*
\versewidth
\vgap
\vin#*
\vindent
\vinphantom{arg1}#*
\vleftmargin#*
\vleftofline{arg1}#*
\vleftskip
\vlvnumfont#*
\vrightskip
\width#*
\wrappingoff#*
\wrappingon#*
\wrapright#*
\writeverbatim{arg1}#*
\x#*
\xindyindex#*
\xlvchars
\zerotrivseps#*
