# xepersian-magazine class
# Matthew Bertucci 2022/05/05 for v0.2

#include:ifthen
#include:ifxetex
#include:multido
#include:datetime
#include:multicol
#include:fancyhdr
#include:fancybox
#include:geometry
#include:textpos
#include:hyphenat
#include:lastpage
#include:setspace
#include:ragged2e

#keyvals:\documentclass/xepersian-magazine#c
10pt
11pt
12pt
9pt
hyphenatedtitles
columnlines
showgrid
a3paper
#endkeyvals

\begin{frontpage}
\end{frontpage}
\firstimage{imagefile}{description%text}#g
\firstarticle{title%text}{opening%text}{time}
\secondarticle{title%text}{subtitle%text}{opening%text}{pagesof}{time}
\thirdarticle{title%text}{subtitle%text}{opening%text}{pagesof}{time}
\begin{indexblock}{title%text}
\end{indexblock}
\begin{authorblock}
\end{authorblock}
\begin{weatherblock}{title%text}
\end{weatherblock}
\indexitem{title%text}{label}#r
\weatheritem{imagefile}{day}{max}{min}{description%text}#g
\begin{article}{num of columns}{title%text}{subtitle%text}{pagesof}{label}#l
\end{article}
\authorandplace{author}{place%text}
\timestamp{time}
\image{imagefile}{description%text}#g
\columntitle{type%keyvals}{text}
\expandedtitle{type%keyvals}{text}
#keyvals:\columntitle,\expandedtitle
shadowbox
doublebox
ovalbox
Ovalbox
lines
#endkeyvals
\begin{editorial}{num of columns}{title%text}{author}{label}#l
\end{editorial}
\begin{shortarticle}{num of columns}{title%text}{subtitle%text}{label}#l
\end{shortarticle}
\shortarticleitem{title%text}{text}
\articlesep
\newsection{name%text}
\customlogo{text}
\customminilogo{text}
\custommagazinename{text}
\edition{edition}
\editionFormat#*
\indexFormat#*
\indexEntryFormat#*
\indexEntryPageTxt#*
\indexEntryPageFormat#*
\indexEntrySeparator#*
\weatherFormat#*
\weatherTempFormat#*
\weatherUnits#*
\firstTitleFormat#*
\firstTextFormat#*
\secondTitleFormat#*
\secondSubtitleFormat#*
\secondTextFormat#*
\thirdTitleFormat#*
\thirdSubtitleFormat#*
\thirdTextFormat#*
\pictureCaptionFormat#*
\pagesFormat#*
\innerTitleFormat#*
\innerSubtitleFormat#*
\innerAuthorFormat#*
\innerPlaceFormat#*
\timestampTxt#*
\timestampSeparator#*
\timestampFormat#*
\innerTextFinalMark#*
\minraggedcols#*
\raggedFormat#*
\heading{left%text}{center%text}{right%text}
\foot{left%text}{center%text}{right%text}
\columnlines#*
\customwwwTxt{text}#*
\editorialAuthorFormat#*
\editorialTitleFormat#*
\grid{cols}{rows}#*
\grid[show]{%<cols%>}{%<rows%>}#*
\headDateTimeFormat#*
\logo#*
\minilogo#*
\mylogo{text}#*
\shortarticleItemTitleFormat#*
\shortarticleSubtitleFormat#*
\shortarticleTitleFormat#*
\xepersianInit#*
