# newlfm class
# Matthew Bertucci 4/28/2022 for v9.4

#include:keyval
#include:ifthen
#include:ifpdf
#include:setdim
#include:fancyhdr
#include:eso-pic
#include:setspace
#include:lastpage
#include:calc
#include:graphicx
#include:rotating
#include:class-letter
#include:addrset
#include:afterpage
#include:envlab

#keyvals:\usepackage/newlfm#c
a3paper
a4paper
addrfromemail
addrfromfax
addrfromleft
addrfromno
addrfromphone
addrfromright
addrtoemail
addrtofax
addrtoleft
addrtono
addrtophone
addrtoright
american
Avery5160
Avery5161
Avery5162
Avery5163
Avery5164
Avery5261
Avery5264
biggap
Blankall
blankall
blankfooter
Blankfooter
blankheader
Blankheader
blankleftmargin
Blankleftmargin
blanklmargin
blankrightmargin
Blankrightmargin
blankrmargin
BlankTotal
busletter
busletternofrom
cellowindow
datecenter
dateleft
dateno
dateright
dateyes
dspace
english
faxbla
faxblb
faxblocka
faxblockb
faxhba
faxhbb
faxheaderpage
faxhp
french
fullmemo
german
greetno
labcolfrto
labrowfrto
labto
legalpaper
letterpaper
margflush
memoaddrfrom
memoaddrto
memodate
memoemailfrom
memoemailto
memofaxfrom
memofaxto
memonofrom
memonore
memonoto
memopagerfrom
memopagerto
memophonefrom
memophoneto
noaddrfr
noaddrfrom
noaddrto
orderdatefromto
orderfromdateto
orderfromtodate
othlang
piglatin
pressrelease
printallfrom
printallto
setuplabel
sidebyside
sigcenter
sigleft
signaturecenter
signatureleft
signatureno
signatureright
sigright
sspace
stdletter
stdletternofrom
stdmemo
stdpressrelease
useenvlab
# options passed to letter class
a5paper
b5paper
executivepaper
landscape
10pt
11pt
12pt
twoside
oneside
draft
final
leqno
fleqn
#endkeyvals

\newlfmP{options%keyvals}

#keyvals:\newlfmP
a3paper#true,false
a4paper#true,false
addrf=%<id%>
addrfromemail=%<email%>
addrfromfax#true,false
addrfromleft#true,false
addrfromphone#true,false
addrfromright#true,false
addrfromskipafter=##L
addrfromskipbefore=##L
addrt=%<id%>
addrtoemail#true,false
addrtoleft#true,false
addrtophone#true,false
addrtoright#true,false
addrtoskipafter=##L
addrtoskipbefore=##L
american#true,false
Avery5160#true,false
Avery5161#true,false
Avery5162#true,false
Avery5163#true,false
Avery5164#true,false
Avery5261#true,false
Avery5264#true,false
Background=
background=
Blankall#true,false
blankall#true,false
blankfooter#true,false
Blankfooter#true,false
blankheader#true,false
Blankheader#true,false
blankleftmargin#true,false
Blankleftmargin#true,false
blankrightmargin#true,false
Blankrightmargin#true,false
BlankTotal#true,false
bottommarginskip=##L
bottommarginskipbelow=##L
busletter#true,false
busletternofrom#true,false
cellodown=##L
celloheight=##L
celloleft=##L
cellowidth=##L
cellowindow#true,false
closeskipafter=##L
closeskipbefore=##L
datecenter#true,false
dateleft#true,false
dateno#true,false
dateright#true,false
dateskipafter=##L
dateskipbefore=##L
dspace#true,false
english#true,false
faxblocka#true,false
faxblockb#true,false
faxhba#true,false
faxheaderpage#true,false
footermarginsize=##L
Footlinewd=##L
footlinewd=##L
french#true,false
fullmemo#true,false
german#true,false
greettoskipafter=##L
headermarginsize=##L
headermarginskip=##L
Headlinewd=##L
headlinewd=##L
InfoFileName=%<file name%>
labcolfrto#true,false
labrowfrto#true,false
labsize=%<size cmd%>
labto#true,false
leftmarginsize=##L
leftmarginskipleft=##L
leftmarginskipright=##L
leftmargintopdist=##L
legalpaper#true,false
letrh=%<id%>
letterpaper#true,false
margflush#true,false
memoaddrfrom#true,false
memoaddrto#true,false
memodate#true,false
memoemailfrom#true,false
memoemailto#true,false
memofaxfrom#true,false
memofaxto#true,false
memonofrom#true,false
memonore#true,false
memonoto#true,false
memopagerfrom#true,false
memopagerto#true,false
memophonefrom#true,false
memophoneto#true,false
memoskipafter=##L
memoskipbefore=##L
MinFoot=##L
minfoot=##L
MinHead=##L
minhead=##L
MinLeft=##L
minleft=##L
MinRight=##L
minright=##L
noaddrfrom#true,false
noaddrto#true,false
nofootline#true,false
noFootline#true,false
nogreet#true,false
noheadline#true,false
noHeadline#true,false
nolines#true,false
noLines#true,false
orderdatefromto#true,false
orderfromdateto#true,false
orderfromtodate#true,false
othlang#true,false
piglatin#true,false
postsigskipafter=##L
postsigskipbefore=##L
pressrelease#true,false
printallfrom#true,false
printallto#true,false
rightmarginsize=##L
rightmarginskipleft=##L
rightmarginskipright=##L
rightmargintopdist=##L
setuplabel#true,false
sidebyside#true,false
sigcenter#true,false
sigleft#true,false
signaturecenter#true,false
signatureleft#true,false
signatureno#true,false
signatureright#true,false
sigright#true,false
sigsize=##L
sigskipafter=##L
sigskipbefore=##L
sigskipcolumn=##L
sigskiprow=##L
sigtr=%<id%>
sspace#true,false
stdletter#true,false
stdletternofrom#true,false
stdmemo#true,false
stdpressrelease#true,false
textheightsize=##L
textwidthsize=##L
topmarginsize=##L
topmarginskip=##L
unprbottom=##L
unprleft=##L
unprright=##L
unprtop=##L
useenvlab#true,false
waterpage=%<imagefile%>
#endkeyvals

\begin{newlfm}
\end{newlfm}
\addrf{id}
\addrfromskipafter{skip%l}
\addrfromskipbefore{skip%l}
\addrt{id}
\addrtoskipafter{skip%l}
\addrtoskipbefore{skip%l}
\adr#S
\Alaba#*
\Alabb#*
\Alabc#*
\Alabd#*
\Alabe#*
\background{code}
\Background{code}
\bottommarginskip{skip%l}
\bottommarginskipbelow{skip%l}
\boxht{height}#*
\boxwd{width}#*
\btwlb{length}#*
\cellodown{length}#*
\celloheight{height}#*
\celloleft{length}#*
\cellowidth{width}#*
\Cfooter{text}
\cfooter{text}
\Cheader{text}
\cheader{text}
\clearall#*
\closeskipafter{skip%l}
\closeskipbefore{skip%l}
\closlfm#*
\COfooter{text}#*
\CUheader{text}
\datecenter{true|false}#*
\dateleft{true|false}#*
\dateno{true|false}#*
\DatePhrase{text}#*
\dateright{true|false}#*
\dateskipafter{skip%l}
\dateskipbefore{skip%l}
\datestamp#*
\Dimens#S
\DimensP{arg}#S
\doletter{commands}
\doltr{commands}#*
\faxblocka#*
\faxblockb#*
\FAXP{arg}#S
\faxpage
\FAZParam#S
\fixcs{definition}#*
\fixem{definition}#*
\fixfs{definition}#*
\fixhh{definition}#*
\fixhs{definition}#*
\fixom{definition}#*
\fixphr{arg1}{arg2}#*
\fixth{definition}#*
\fixtm{definition}#*
\fixtw{definition}#*
\footermarginsize{size%l}
\Footlinewd{width}#*
\footlinewd{width}#*
\greettoskipafter{skip%l}
\headermarginsize{size%l}
\headermarginskip{skip%l}
\Headlinewd{width}#*
\headlinewd{width}#*
\ifempty{arg}{true}{false}#*
\iffixf{true}{false}#*
\iffixq{true}{false}#*
\iffixt{true}{false}#*
\ifpempty{arg}{true}{false}#*
\labpl{length}#*
\labsize{size%l}#*
\Language#S
\LanguageP{arg}#S
\leftmarginsize{size%l}
\leftmarginskipleft{skip%l}
\leftmarginskipright{skip%l}
\leftmargintopdist{dist%l}
\letrh{id}
\letterbody{text}
\LetterP{arg}#S
\LetterParam#S
\Lfooter{text}
\lfooter{text}
\lftwd{width}#*
\lheader{text}
\Lheader{text}
\Lmargin{text}
\lmargin{text}
\LOfooter{text}#*
\lth#S
\ltrbody{text}#*
\LUheader{text}
\makeenvfn#*
\makeenvst#*
\MemoP{arg}#S
\MemoParam#S
\memosec
\memoskipafter{skip%l}
\memoskipbefore{skip%l}
\MinFoot{length}#*
\minfoot{length}#*
\MinHead{length}#*
\minhead{length}#*
\MinLeft{length}#*
\minleft{length}#*
\MinRight{length}#*
\minright{length}#*
\monthname#*
\multletter{id1,id2,...}
\newlfmParam#S
\noFootline#*
\nofootline#*
\noheadline#*
\noHeadline#*
\nolines#*
\noLines#*
\npind#*
\oneletter{id}
\openlfm#*
\pgrph{text}#*
\PhrCc{text}
\PhrContact{text}
\PhrDocument{text}
\PhrEmail{text}
\PhrEncl{text}
\PhrFax{text}
\PhrFAXcovp{text}
\PhrFAXpgcnt{text}
\PhrFrom{text}
\PhrMessage{text}
\PhrMore{text}
\PhrPager{text}
\PhrPhone{text}
\PhrPpps{text}
\PhrPps{text}
\PhrPRend{text}
\PhrPs{text}
\PhrRe{text}
\PhrRegard{regarding%text}
\PhrRelease{text}
\PhrSubre{text}
\PhrTo{text}
\postsigskipafter{skip%l}
\postsigskipbefore{skip%l}
\pressbegin#*
\restletter{text}
\restlettera{text}
\restletterb{text}
\restletterc{text}
\restletterd{text}
\restlettere{text}
\Rfooter{text}
\rfooter{text}
\rheader{text}
\Rheader{text}
\rightmarginsize{size%l}
\rightmarginskipleft{skip%l}
\rightmarginskipright{skip%l}
\rightmargintopdist{dist%l}
\Rmargin{text}
\rmargin{text}
\ROfooter{text}#*
\RUheader{text}
\setsigc#*
\setsigl#*
\setsigr#*
\showdim{text}
\sig#S
\sigcenter{true|false}#*
\sigleft{true|false}#*
\signaturecenter{true|false}#*
\signatureleft{true|false}#*
\signatureno{true|false}#*
\signatureright{true|false}#*
\sigright{true|false}#*
\sigsize{true|false}#*
\sigskipafter{skip%l}
\sigskipbefore{skip%l}
\sigskipcolumn{skip%l}
\sigskiprow{skip%l}
\sigtr{id}
\textheightsize{size%l}#*
\textwidthsize{size%l}#*
\timestamp#*
\timestring#*
\topht{height}#*
\topmarginsize{size%l}
\topmarginskip{skip%l}
\txb{text}#*
\unprbottom{length}
\unprleft{length}
\unprright{length}
\unprtop{length}
\waterpage{imagefile}#g