# created by sungmin817
#include:amsmath
#include:ifthen
\abs{arg1}#m
\abs[size]{arg1}#m
\appref{arg1}#r
\assref{arg1}#r
\cbr{arg1}#m
\cbr[size]{arg1}#m
\colref{arg1}#r
\defnref{arg1}#r
\del{arg1}#m
\del[size]{arg1}#m
\dif#m
\Dif#m
\dmd{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#m
\dod{arg1}{arg2}#m
\dod[order]{arg1}{arg2}#m
\dpd{arg1}{arg2}#m
\dpd[order]{arg1}{arg2}#m
\enVert{arg1}#m
\enVert[size]{arg1}#m
\envert{arg1}#m
\envert[size]{arg1}#m
\eval{arg1}#m
\eval[size]{arg1}#m
\exref{arg1}#r
\figref{arg1}#r
\fullfunction{arg1}{arg2}{arg3}{arg4}{arg5}#m
\intcc{arg1}#m
\intcc[size]{arg1}#m
\intco{arg1}#m
\intco[size]{arg1}#m
\intoc{arg1}#m
\intoc[size]{arg1}#m
\intoo{arg1}#m
\intoo[size]{arg1}#m
\lemref{arg1}#r
\md{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#m
\od{arg1}{arg2}#m
\od[order]{arg1}{arg2}#m
\pd{arg1}{arg2}#m
\pd[order]{arg1}{arg2}#m
\propref{arg1}#r
\remref{arg1}#r
\sVert{arg1}#m
\sVert[size]{arg1}#m
\sbr{arg1}#m
\sbr[size]{arg1}#m
\secref{arg1}#r
\set{arg1}#m
\set[size]{arg1}#m
\thmref{arg1}#r
\tmd{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#m
\tod{arg1}{arg2}#m
\tod[order]{arg1}{arg2}#m
\tpd{arg1}{arg2}#m
\tpd[order]{arg1}{arg2}#m
