# contracard package
# Matthew Bertucci 2022/06/17 for v2.0.0

#include:calc
#include:intcalc
#include:ifthen
#include:tocloft
#include:textcomp

#keyvals:\usepackage/contracard#c
showcountafter
showcountbefore
enableidx
#endkeyvals

#ifOption:enableidx
#include:imakeidx
#endif

\defaultcontraenv#*
\dancetitleenv#*
\dancetitleformat#*
\danceauthorformat#*
\danceformformat#*
\movedelimiter#*
\partdelimiter#*
\midpartdelimiter#*
\phrasevspace#*
\phraseseparator#*
\showcountbefore
\showcountafter
\hidecountbefore
\hidecountafter
\countleftbracket{bracket}
\countrightbracket{bracket}
\setdefaultnotesenv{envname}
\prenotevspace#*
\thedancecount#*
\thepartcount#*
\thephrasecount#*
\thedancepart#*
\thedancephrase#*
\thedancepartlength#*
\thedancephraselength#*
\resetdancepartlength
\resetdancephraselength
\resetdancephrase
\resetdancephrase*
\resetdancepart
\resetdancepart*
\newdancephrase
\newdancepart
\thephrasemovenum#*
\thepartmovenum#*
\thehalfpartmovenum#*
\thedancemovenum#*
\begin{contra}{title}{author}{form}
\begin{contra}[envname]{title}{author}{form}
\end{contra}
\move{move%text}
\move[beats]{move%text}
\move*{move%text}
\move*[beats]{move%text}
\themovecount#*
\allemande{beats}{direction%text}
\allemande[person]{beats}{direction%text}
\allemande*{beats}{direction%text}
\allemande*[person]{beats}{direction%text}
\balance
\balance[post-text%text]
\balance*
\balance*[pre-text%text]
\balanceand
\balanceand[post-text%text]
\balanceand*
\balanceand*[pre-text%text]
\butterflywhirl{beats}
\butterflywhirl[post-text%text]{beats}
\butterflywhirl*{beats}
\butterflywhirl*[pre-text%text]{beats}
\circleleft{beats}
\circleleft[post-text%text]{beats}
\circleleft*{beats}
\circleleft*[pre-text%text]{beats}
\circleright{beats}
\circleright[post-text%text]{beats}
\circleright*{beats}
\circleright*[pre-text%text]{beats}
\courtesyturn{beats}
\courtesyturn[person]{beats}
\courtesyturn*{beats}
\courtesyturn*[person]{beats}
\dosido{beats}
\dosido[person]{beats}
\dosido*{beats}
\dosido*[person]{beats}
\seesaw{beats}
\seesaw[person]{beats}
\seesaw*{beats}
\seesaw*[person]{beats}
\walkaround{beats}
\walkaround[person]{beats}
\walkaround*{beats}
\walkaround*[person]{beats}
\walkaroundleft{beats}
\walkaroundleft[person]{beats}
\walkaroundleft*{beats}
\walkaroundleft*[person]{beats}
\walkaroundright{beats}
\walkaroundright[person]{beats}
\walkaroundright*{beats}
\walkaroundright*[person]{beats}
\heyforfour
\heyforfour[post-text%text]
\heyforfour*
\heyforfour*[pre-text%text]
\halfhey
\halfhey[post-text%text]
\halfhey*
\halfhey*[pre-text%text]
\halfheyricochet
\halfheyricochet[post-text%text]
\halfheyricochet*
\halfheyricochet*[pre-text%text]
\fullhey
\fullhey[post-text%text]
\fullhey*
\fullhey*[pre-text%text]
\fullheyricochet
\fullheyricochet[post-text%text]
\fullheyricochet*
\fullheyricochet*[pre-text%text]
\ladieschain
\ladieschain[post-text%text]
\ladieschain*
\ladieschain*[pre-text%text]
\menchain
\menchain[post-text%text]
\menchain*
\menchain*[pre-text%text]
\halfladieschain
\halfladieschain[post-text%text]
\halfladieschain*
\halfladieschain*[pre-text%text]
\halfmenchain
\halfmenchain[post-text%text]
\halfmenchain*
\halfmenchain*[pre-text%text]
\fullladieschain
\fullladieschain[post-text%text]
\fullladieschain*
\fullladieschain*[pre-text%text]
\fullmenchain
\fullmenchain[post-text%text]
\fullmenchain*
\fullmenchain*[pre-text%text]
\lines
\lines[type%text]
\lines*
\lines*[type%text]
\longlines
\longlines[type%text]
\longlines*
\longlines*[type%text]
\madrobin
\madrobin[post-text%text]
\madrobin*
\madrobin*[pre-text%text]
\petronella
\petronella[post-text%text]
\petronella*
\petronella*[pre-text%text]
\petronellanella
\petronellanella[post-text%text]
\petronellanella*
\petronellanella*[pre-text%text]
\promenade{beats}
\promenade[person]{beats}
\promenade*{beats}
\promenade*[person]{beats}
\halfpromenade
\halfpromenade[person]
\halfpromenade*
\halfpromenade*[person]
\rightandleftthrough
\rightandleftthrough[post-text%text]
\rightandleftthrough*
\rightandleftthrough*[pre-text%text]
\rightsandlefts
\rightsandlefts[post-text%text]
\rightsandlefts*
\rightsandlefts*[pre-text%text]
\rollaway
\rollaway[post-text%text]
\rollaway*{post-text%text}
\rollaway*[pre-text%text]{post-text%text}
\rollawaysashay
\rollawaysashay[post-text%text]
\rollawaysashay*{post-text%text}
\rollawaysashay*[pre-text%text]{post-text%text}
\starleft{beats}
\starleft*{beats}
\starright{beats}
\starright*{beats}
\sashay{beats}
\sashay[post-text%text]{beats}
\sashay*{beats}{pre-text%text}
\sashay*[post-text%text]{beats}{pre-text%text}
\swing
\swing[post-text%text]
\swing*
\swing*[pre-text%text]
\turnalone
\turnalone[post-text%text]
\turnalone*{beats}
\turnalone*[post-text%text]{beats}
\turncouple
\turncouple[post-text%text]
\turncouple*{beats}
\turncouple*[post-text%text]{beats}
\turntogether
\turntogether[post-text%text]
\turntogether*{beats}
\turntogether*[post-text%text]{beats}
\twirltoswap
\californiatwirl
\starthrough
\starthru
\boxthegnat
\swattheflea
\jerseytwirl
\arizonatwirl
\downthehall{beats}
\downthehall[post-text%text]{beats}
\downthehall*{beats}
\downthehall*[pre-text%text]{beats}
\upthehall{beats}
\upthehall[post-text%text]{beats}
\upthehall*{beats}
\upthehall*[pre-text%text]{beats}
\dancetitle
\danceauthor
\danceform
\listofdance#S
\listofdances
\thedance#*
\lodtitle#*
\enableidx
\pauseindexing
\resumeindexing
\dbtname#*
\dbaname#*
\mvpname#*
\mvdname#*
\moveindex{entry%text}
\moveindex*{entry%text}
\moveindexNoStar{entry%text}#S
\moveindexStar{entry%text}#S
\timesaround{beats-around}{total-beats}
\thetimesaround#*
\thequartertimesaround#*
\notes{text}
\spelldosido#*
\spellDosido#*
\setdosidospelling{spelling}