# crefthe package
# Matthew Bertucci 2022/08/30 for release 2022/08/28

#include:cleveref
#include:regexpatch

#keyvals:\usepackage/crefthe#c
overwrite#true,false
# options passed to cleveref
poorman
sort
compress
sort&compress
nosort
capitalise
capitalize
nameinlink
noabbrev
english
german
ngerman
dutch
french
spanish
italian
russian
ukrainian
norsk
danish
esperanto
swedish
brazilian
catalan
#endkeyvals

\crefthe{labellist}#r
\crefthe[prep]{labellist}#r
\crefthe*{labellist}#r
\crefthe*[prep]{labellist}#r
\crefthe-{labellist}#*r
\crefthe-[prep]{labellist}#*r
\crefthe+{labellist}#*r
\crefthe+[prep]{labellist}#*r
\Crefthe{labellist}#r
\Crefthe[prep]{labellist}#r
\Crefthe*{labellist}#r
\Crefthe*[prep]{labellist}#r
\Crefthe-{labellist}#*r
\Crefthe-[prep]{labellist}#*r
\Crefthe+{labellist}#*r
\Crefthe+[prep]{labellist}#*r

\namecrefthe{labellist}#r
\namecrefthe[prep]{labellist}#r
\namecrefthe-{labellist}#*r
\namecrefthe-[prep]{labellist}#*r
\namecrefthe+{labellist}#*r
\namecrefthe+[prep]{labellist}#*r
\nameCrefthe{labellist}#r
\nameCrefthe[prep]{labellist}#r
\nameCrefthe-{labellist}#*r
\nameCrefthe-[prep]{labellist}#*r
\nameCrefthe+{labellist}#*r
\nameCrefthe+[prep]{labellist}#*r
\namecrefsthe{labellist}#r
\namecrefsthe[prep]{labellist}#r
\namecrefsthe-{labellist}#*r
\namecrefsthe-[prep]{labellist}#*r
\namecrefsthe+{labellist}#*r
\namecrefsthe+[prep]{labellist}#*r
\nameCrefsthe{labellist}#r
\nameCrefsthe[prep]{labellist}#r
\nameCrefsthe-{labellist}#*r
\nameCrefsthe-[prep]{labellist}#*r
\nameCrefsthe+{labellist}#*r
\nameCrefsthe+[prep]{labellist}#*r

\crefthemark{text}
\crefthename{type}{singular}{plural}
\crefthename{type}[prep1]{singular}[prep2]{plural}
\Crefthename{type}{singular}{plural}
\Crefthename{type}[prep1]{singular}[prep2]{plural}
\crefthepatchname{counters}

#ifOption:overwrite
\cref[prep]{labellist}#r
\cref*[prep]{labellist}#r
\cref-{labellist}#*r
\cref-[prep]{labellist}#*r
\cref+{labellist}#*r
\cref+[prep]{labellist}#*r
\Cref[prep]{labellist}#r
\Cref*[prep]{labellist}#r
\Cref-{labellist}#*r
\Cref-[prep]{labellist}#*r
\Cref+{labellist}#*r
\Cref+[prep]{labellist}#*r
\crefname{type}[prep1]{singular}[prep2]{plural}
\Crefname{type}[prep1]{singular}[prep2]{plural}
#endif
#ifOption:overwrite=true
\cref[prep]{labellist}#r
\cref*[prep]{labellist}#r
\cref-{labellist}#*r
\cref-[prep]{labellist}#*r
\cref+{labellist}#*r
\cref+[prep]{labellist}#*r
\Cref[prep]{labellist}#r
\Cref*[prep]{labellist}#r
\Cref-{labellist}#*r
\Cref-[prep]{labellist}#*r
\Cref+{labellist}#*r
\Cref+[prep]{labellist}#*r
\crefname{type}[prep1]{singular}[prep2]{plural}
\Crefname{type}[prep1]{singular}[prep2]{plural}
#endif
