# dejavu-otf package
# Matthew Bertucci 9/30/2021 for v0.04

#include:ifxetex
#include:ifluatex
#include:unicode-math
#include:textcomp

\DejaVuSerifCondensed
\DejaVuSansCondensed
\DejaVuSansLight

\acwopencirclearrow#m
\adots#m
\Angstrom#m
\approxident#m
\arceq#m
\assert#m
\asteraccent{arg}#m
\awint#m
\backcong#m
\backdprime#m
\backtrprime#m
\barvee#m
\Bbbeight#m
\Bbbfive#m
\Bbbfour#m
\Bbbgamma#m
\BbbGamma#m
\Bbbnine#m
\Bbbone#m
\Bbbpi#m
\BbbPi#m
\Bbbseven#m
\Bbbsix#m
\Bbbsum#m
\Bbbthree#m
\Bbbtwo#m
\Bbbzero#m
\bigblacktriangledown#m
\bigblacktriangleup#m
\bigbot#m
\bigcupdot#m
\bigsqcap#m
\bigtimes#m
\bigtop#m
\blackpointerleft#m
\blackpointerright#m
\blanksymbol#m
\blockfull#m
\blockhalfshaded#m
\blockqtrshaded#m
\blockthreeqtrshaded#m
\carriagereturn#m
\circledequal#m
\Colon#m
\coloneq#m
\concavediamond#m
\concavediamondtickleft#m
\concavediamondtickright#m
\cupdot#m
\cupleftarrow#m
\cwopencirclearrow#m
\dashcolon#m
\DashVDash#m
\dashVdash#m
\diameter#m
\divslash#m
\Doteq#m
\dotminus#m
\dotsminusdots#m
\dottedsquare#m
\downuparrows#m
\downwhitearrow#m
\dprime#m
\eighthnote#m
\enclosecircle#m
\enclosediamond#m
\enclosesquare#m
\enclosetriangle#m
\eqcolon#m
\eqdef#m
\eqgtr#m
\eqless#m
\equal#m
\equalparallel#m
\Equiv#m
\Eulerconst#m
\euro#m
\fracslash#m
\greater#m
\hermitmatrix#m
\horizbar#m
\hrectangle#m
\hrectangleblack#m
\imageof#m
\increment#m
\intbottom#m
\intclockwise#m
\intextender#m
\inttop#m
\invlazys#m
\invnot#m
\kernelcontraction#m
\lAngle#m
\lbracelend#m
\lbracemid#m
\lbraceuend#m
\lBrack#m
\lbrackextender#m
\lbracklend#m
\lbrackuend#m
\Ldsh#m
\leftharpoonaccent{arg}#m
\leftsquigarrow#m
\leftthreearrows#m
\leftwhitearrow#m
\less#m
\lgwhtcircle#m
\linefeed#m
\longdashv#m
\longleftsquigarrow#m
\longmapsfrom#m
\Longmapsfrom#m
\Longmapsto#m
\longrightsquigarrow#m
\lozengeminus#m
\lparen#m
\lparenextender#m
\lparenlend#m
\lparenuend#m
\mapsdown#m
\mapsfrom#m
\Mapsfrom#m
\Mapsto#m
\mapsup#m
\mathampersand#m
\mathatsign#m
\mathcolon#m
\mathcomma#m
\matheth#m
\mathexclam#m
\mathhyphen#m
\mathoctothorpe#m
\mathpercent#m
\mathperiod#m
\mathplus#m
\mathquestion#m
\mathratio#m
\mathsemicolon#m
\mathslash#m
\mathvisiblespace#m
\mathyen#m
\mbffrakA#m
\mbffraka#m
\mbffrakB#m
\mbffrakb#m
\mbffrakC#m
\mbffrakc#m
\mbffrakD#m
\mbffrakd#m
\mbffrakE#m
\mbffrake#m
\mbffrakF#m
\mbffrakf#m
\mbffrakG#m
\mbffrakg#m
\mbffrakH#m
\mbffrakh#m
\mbffrakI#m
\mbffraki#m
\mbffrakJ#m
\mbffrakj#m
\mbffrakK#m
\mbffrakk#m
\mbffrakL#m
\mbffrakl#m
\mbffrakM#m
\mbffrakm#m
\mbffrakN#m
\mbffrakn#m
\mbffrakO#m
\mbffrako#m
\mbffrakP#m
\mbffrakp#m
\mbffrakQ#m
\mbffrakq#m
\mbffrakR#m
\mbffrakr#m
\mbffrakS#m
\mbffraks#m
\mbffrakT#m
\mbffrakt#m
\mbffrakU#m
\mbffraku#m
\mbffrakV#m
\mbffrakv#m
\mbffrakW#m
\mbffrakw#m
\mbffrakX#m
\mbffrakx#m
\mbffrakY#m
\mbffraky#m
\mbffrakZ#m
\mbffrakz#m
\mbfitsansA#m
\mbfitsansa#m
\mbfitsansAlpha#m
\mbfitsansalpha#m
\mbfitsansB#m
\mbfitsansb#m
\mbfitsansBeta#m
\mbfitsansbeta#m
\mbfitsansC#m
\mbfitsansc#m
\mbfitsansChi#m
\mbfitsanschi#m
\mbfitsansD#m
\mbfitsansd#m
\mbfitsansDelta#m
\mbfitsansdelta#m
\mbfitsansE#m
\mbfitsanse#m
\mbfitsansEpsilon#m
\mbfitsansepsilon#m
\mbfitsansEta#m
\mbfitsanseta#m
\mbfitsansF#m
\mbfitsansf#m
\mbfitsansG#m
\mbfitsansg#m
\mbfitsansGamma#m
\mbfitsansgamma#m
\mbfitsansH#m
\mbfitsansh#m
\mbfitsansI#m
\mbfitsansi#m
\mbfitsansIota#m
\mbfitsansiota#m
\mbfitsansJ#m
\mbfitsansj#m
\mbfitsansK#m
\mbfitsansk#m
\mbfitsansKappa#m
\mbfitsanskappa#m
\mbfitsansL#m
\mbfitsansl#m
\mbfitsansLambda#m
\mbfitsanslambda#m
\mbfitsansM#m
\mbfitsansm#m
\mbfitsansMu#m
\mbfitsansmu#m
\mbfitsansN#m
\mbfitsansn#m
\mbfitsansnabla#m
\mbfitsansNu#m
\mbfitsansnu#m
\mbfitsansO#m
\mbfitsanso#m
\mbfitsansOmega#m
\mbfitsansomega#m
\mbfitsansOmicron#m
\mbfitsansomicron#m
\mbfitsansP#m
\mbfitsansp#m
\mbfitsanspartial#m
\mbfitsansPhi#m
\mbfitsansphi#m
\mbfitsansPi#m
\mbfitsanspi#m
\mbfitsansPsi#m
\mbfitsanspsi#m
\mbfitsansQ#m
\mbfitsansq#m
\mbfitsansR#m
\mbfitsansr#m
\mbfitsansRho#m
\mbfitsansrho#m
\mbfitsansS#m
\mbfitsanss#m
\mbfitsansSigma#m
\mbfitsanssigma#m
\mbfitsansT#m
\mbfitsanst#m
\mbfitsansTau#m
\mbfitsanstau#m
\mbfitsansTheta#m
\mbfitsanstheta#m
\mbfitsansU#m
\mbfitsansu#m
\mbfitsansUpsilon#m
\mbfitsansupsilon#m
\mbfitsansV#m
\mbfitsansv#m
\mbfitsansvarepsilon#m
\mbfitsansvarkappa#m
\mbfitsansvarphi#m
\mbfitsansvarpi#m
\mbfitsansvarrho#m
\mbfitsansvarsigma#m
\mbfitsansvarTheta#m
\mbfitsansvartheta#m
\mbfitsansW#m
\mbfitsansw#m
\mbfitsansX#m
\mbfitsansx#m
\mbfitsansXi#m
\mbfitsansxi#m
\mbfitsansY#m
\mbfitsansy#m
\mbfitsansZ#m
\mbfitsansz#m
\mbfitsansZeta#m
\mbfitsanszeta#m
\mbfsansA#m
\mbfsansa#m
\mbfsansAlpha#m
\mbfsansalpha#m
\mbfsansB#m
\mbfsansb#m
\mbfsansBeta#m
\mbfsansbeta#m
\mbfsansC#m
\mbfsansc#m
\mbfsansChi#m
\mbfsanschi#m
\mbfsansD#m
\mbfsansd#m
\mbfsansDelta#m
\mbfsansdelta#m
\mbfsansE#m
\mbfsanse#m
\mbfsanseight#m
\mbfsansEpsilon#m
\mbfsansepsilon#m
\mbfsansEta#m
\mbfsanseta#m
\mbfsansF#m
\mbfsansf#m
\mbfsansfive#m
\mbfsansfour#m
\mbfsansG#m
\mbfsansg#m
\mbfsansGamma#m
\mbfsansgamma#m
\mbfsansH#m
\mbfsansh#m
\mbfsansI#m
\mbfsansi#m
\mbfsansIota#m
\mbfsansiota#m
\mbfsansJ#m
\mbfsansj#m
\mbfsansK#m
\mbfsansk#m
\mbfsansKappa#m
\mbfsanskappa#m
\mbfsansL#m
\mbfsansl#m
\mbfsansLambda#m
\mbfsanslambda#m
\mbfsansM#m
\mbfsansm#m
\mbfsansMu#m
\mbfsansmu#m
\mbfsansN#m
\mbfsansn#m
\mbfsansnabla#m
\mbfsansnine#m
\mbfsansNu#m
\mbfsansnu#m
\mbfsansO#m
\mbfsanso#m
\mbfsansOmega#m
\mbfsansomega#m
\mbfsansOmicron#m
\mbfsansomicron#m
\mbfsansone#m
\mbfsansP#m
\mbfsansp#m
\mbfsanspartial#m
\mbfsansPhi#m
\mbfsansphi#m
\mbfsansPi#m
\mbfsanspi#m
\mbfsansPsi#m
\mbfsanspsi#m
\mbfsansQ#m
\mbfsansq#m
\mbfsansR#m
\mbfsansr#m
\mbfsansRho#m
\mbfsansrho#m
\mbfsansS#m
\mbfsanss#m
\mbfsansseven#m
\mbfsansSigma#m
\mbfsanssigma#m
\mbfsanssix#m
\mbfsansT#m
\mbfsanst#m
\mbfsansTau#m
\mbfsanstau#m
\mbfsansTheta#m
\mbfsanstheta#m
\mbfsansthree#m
\mbfsanstwo#m
\mbfsansU#m
\mbfsansu#m
\mbfsansUpsilon#m
\mbfsansupsilon#m
\mbfsansV#m
\mbfsansv#m
\mbfsansvarepsilon#m
\mbfsansvarkappa#m
\mbfsansvarphi#m
\mbfsansvarpi#m
\mbfsansvarrho#m
\mbfsansvarsigma#m
\mbfsansvarTheta#m
\mbfsansvartheta#m
\mbfsansW#m
\mbfsansw#m
\mbfsansX#m
\mbfsansx#m
\mbfsansXi#m
\mbfsansxi#m
\mbfsansY#m
\mbfsansy#m
\mbfsansZ#m
\mbfsansz#m
\mbfsanszero#m
\mbfsansZeta#m
\mbfsanszeta#m
\mbfscrA#m
\mbfscra#m
\mbfscrB#m
\mbfscrb#m
\mbfscrC#m
\mbfscrc#m
\mbfscrD#m
\mbfscrd#m
\mbfscrE#m
\mbfscre#m
\mbfscrF#m
\mbfscrf#m
\mbfscrG#m
\mbfscrg#m
\mbfscrH#m
\mbfscrh#m
\mbfscrI#m
\mbfscri#m
\mbfscrJ#m
\mbfscrj#m
\mbfscrK#m
\mbfscrk#m
\mbfscrL#m
\mbfscrl#m
\mbfscrM#m
\mbfscrm#m
\mbfscrN#m
\mbfscrn#m
\mbfscrO#m
\mbfscro#m
\mbfscrP#m
\mbfscrp#m
\mbfscrQ#m
\mbfscrq#m
\mbfscrR#m
\mbfscrr#m
\mbfscrS#m
\mbfscrs#m
\mbfscrT#m
\mbfscrt#m
\mbfscrU#m
\mbfscru#m
\mbfscrV#m
\mbfscrv#m
\mbfscrW#m
\mbfscrw#m
\mbfscrX#m
\mbfscrx#m
\mbfscrY#m
\mbfscry#m
\mbfscrZ#m
\mbfscrz#m
\mdlgblkcircle#m
\mdlgblksquare#m
\mdlgwhtcircle#m
\mdlgwhtlozenge#m
\mdlgwhtsquare#m
\measeq#m
\measuredrightangle#m
\mfrakA#m
\mfraka#m
\mfrakB#m
\mfrakb#m
\mfrakc#m
\mfrakC#m
\mfrakD#m
\mfrakd#m
\mfrakE#m
\mfrake#m
\mfrakF#m
\mfrakf#m
\mfrakG#m
\mfrakg#m
\mfrakh#m
\mfrakH#m
\mfraki#m
\mfrakJ#m
\mfrakj#m
\mfrakK#m
\mfrakk#m
\mfrakL#m
\mfrakl#m
\mfrakM#m
\mfrakm#m
\mfrakN#m
\mfrakn#m
\mfrakO#m
\mfrako#m
\mfrakP#m
\mfrakp#m
\mfrakQ#m
\mfrakq#m
\mfrakr#m
\mfrakS#m
\mfraks#m
\mfrakT#m
\mfrakt#m
\mfrakU#m
\mfraku#m
\mfrakV#m
\mfrakv#m
\mfrakW#m
\mfrakw#m
\mfrakX#m
\mfrakx#m
\mfrakY#m
\mfraky#m
\mfrakz#m
\mfrakZ#m
\minus#m
\mitBbbD#m
\mitBbbd#m
\mitBbbe#m
\mitBbbi#m
\mitBbbj#m
\mitsansA#m
\mitsansa#m
\mitsansB#m
\mitsansb#m
\mitsansC#m
\mitsansc#m
\mitsansD#m
\mitsansd#m
\mitsansE#m
\mitsanse#m
\mitsansF#m
\mitsansf#m
\mitsansG#m
\mitsansg#m
\mitsansH#m
\mitsansh#m
\mitsansI#m
\mitsansi#m
\mitsansJ#m
\mitsansj#m
\mitsansK#m
\mitsansk#m
\mitsansL#m
\mitsansl#m
\mitsansM#m
\mitsansm#m
\mitsansN#m
\mitsansn#m
\mitsansO#m
\mitsanso#m
\mitsansP#m
\mitsansp#m
\mitsansQ#m
\mitsansq#m
\mitsansR#m
\mitsansr#m
\mitsansS#m
\mitsanss#m
\mitsansT#m
\mitsanst#m
\mitsansU#m
\mitsansu#m
\mitsansV#m
\mitsansv#m
\mitsansW#m
\mitsansw#m
\mitsansX#m
\mitsansx#m
\mitsansY#m
\mitsansy#m
\mitsansZ#m
\mitsansz#m
\msansA#m
\msansa#m
\msansB#m
\msansb#m
\msansC#m
\msansc#m
\msansD#m
\msansd#m
\msansE#m
\msanse#m
\msanseight#m
\msansF#m
\msansf#m
\msansfive#m
\msansfour#m
\msansG#m
\msansg#m
\msansH#m
\msansh#m
\msansI#m
\msansi#m
\msansJ#m
\msansj#m
\msansK#m
\msansk#m
\msansL#m
\msansl#m
\msansM#m
\msansm#m
\msansN#m
\msansn#m
\msansnine#m
\msansO#m
\msanso#m
\msansone#m
\msansP#m
\msansp#m
\msansQ#m
\msansq#m
\msansR#m
\msansr#m
\msansS#m
\msanss#m
\msansseven#m
\msanssix#m
\msansT#m
\msanst#m
\msansthree#m
\msanstwo#m
\msansU#m
\msansu#m
\msansV#m
\msansv#m
\msansW#m
\msansw#m
\msansX#m
\msansx#m
\msansY#m
\msansy#m
\msansZ#m
\msansz#m
\msanszero#m
\mscrA#m
\mscra#m
\mscrb#m
\mscrB#m
\mscrC#m
\mscrc#m
\mscrD#m
\mscrd#m
\mscre#m
\mscrE#m
\mscrf#m
\mscrF#m
\mscrG#m
\mscrg#m
\mscrh#m
\mscrH#m
\mscri#m
\mscrI#m
\mscrJ#m
\mscrj#m
\mscrK#m
\mscrk#m
\mscrl#m
\mscrL#m
\mscrm#m
\mscrM#m
\mscrN#m
\mscrn#m
\mscrO#m
\mscro#m
\mscrP#m
\mscrp#m
\mscrQ#m
\mscrq#m
\mscrr#m
\mscrR#m
\mscrS#m
\mscrs#m
\mscrT#m
\mscrt#m
\mscrU#m
\mscru#m
\mscrV#m
\mscrv#m
\mscrW#m
\mscrw#m
\mscrX#m
\mscrx#m
\mscrY#m
\mscry#m
\mscrZ#m
\mscrz#m
\mtteight#m
\mttfive#m
\mttfour#m
\mttnine#m
\mttone#m
\mttseven#m
\mttsix#m
\mttthree#m
\mtttwo#m
\mttzero#m
\multimapinv#m
\napprox#m
\nasymp#m
\Nearrow#m
\nequiv#m
\ngtrless#m
\ngtrsim#m
\nlessgtr#m
\nlesssim#m
\nni#m
\npreccurlyeq#m
\nsime#m
\nsimeq#m
\nsqsubseteq#m
\nsqsupseteq#m
\nsubset#m
\nsucccurlyeq#m
\nsupset#m
\nvartriangleleft#m
\nvartriangleright#m
\Nwarrow#m
\obrbrak#m
\ocirc{arg}#m
\oiiint#m
\oiint#m
\ointctrclockwise#m
\origof#m
\overbar{arg}#m
\overbracket{arg}#m
\overparen{arg}#m
\ovhook{arg}#m
\Planckconst#m
\QED#m
\qprime#m
\questeq#m
\rAngle#m
\rbracelend#m
\rbracemid#m
\rbraceuend#m
\rBrack#m
\rbrackextender#m
\rbracklend#m
\rbrackuend#m
\Rdsh#m
\rightangle#m
\rightarrowonoplus#m
\rightharpoonaccent{arg}#m
\rightthreearrows#m
\rightwhitearrow#m
\rparen#m
\rparenextender#m
\rparenlend#m
\rparenuend#m
\Searrow#m
\sime#m
\simneqq#m
\sinewave#m
\smallin#m
\smallni#m
\smblkcircle#m
\smblksquare#m
\smwhtcircle#m
\smwhtdiamond#m
\smwhtsquare#m
\sqrtbottom#m
\sqsubsetneq#m
\sqsupsetneq#m
\stareq#m
\sumbottom#m
\sumtop#m
\Swarrow#m
\trprime#m
\turnednot#m
\twoheaddownarrow#m
\twoheaduparrow#m
\twolowline#m
\ubrbrak#m
\underbracket{arg}#m
\underparen{arg}#m
\unicodecdots#m
\unicodeellipsis#m
\updownarrows#m
\upwhitearrow#m
\varbarwedge#m
\varclubsuit#m
\vardiamondsuit#m
\vardoublebarwedge#m
\varheartsuit#m
\varlrtriangle#m
\varointclockwise#m
\varspadesuit#m
\vbraceextender#m
\VDash#m
\vectimes#m
\veeeq#m
\vertoverlay{arg}#m
\vlongdash#m
\vysmblkcircle#m
\vysmwhtcircle#m
\wedgeq#m
\widebridgeabove{arg}#m
