# autogenerated by txs
#include:soul
#include:todonotes
#include:xcolor
\addColor#*
\add{text}#
\alertColor#*
\alert{text}#
\comment{text}{comment}#
\highlight{text}#
\removeColor#*
\remove{text}#
\replace{text}{replacement%text}#
\setreviewsoff#
\setreviewson#
\substitute{text}{replacement%text}#*
ifistoreview#S
istoreviewfalse#S
istoreviewtrue#S

