# autogenerated by txs

#include:soul
#include:todonotes
#include:xcolor

\addColor#*
\add{text}
\alertColor#*
\alert{text}
\comment{text}{comment%text}#
\highlight{text}
\removeColor#*
\remove{text}
\replace{text}{replacement%text}
\setreviewsoff
\setreviewson
\substitute{text}{replacement%text}#*
\ifistoreview#*
\istoreviewfalse#*
\istoreviewtrue#*
