# eqnlines package
# Matthew Bertucci 2026/01/31 for v0.14.1

#include:keyval

\begin{align}#\math,array
\end{align}
\begin{align*}#\math,array
\end{align*}
\begin{alignat}{ncols}#\math,array
\begin{alignat}[alignment]{ncols}#\math,array
\end{alignat}
\begin{alignat*}{ncols}#\math,array
\begin{alignat*}[alignment]{ncols}#\math,array
\end{alignat*}
\begin{aligned}#m\array
\end{aligned}#m
\begin{alignedat}{ncols}#m\array
\end{alignedat}#m
\begin{Bmatrix}#m\array
\end{Bmatrix}#m
\begin{bmatrix}#m\array
\end{bmatrix}#m
\begin{cases}#m\array
\begin{cases}[options%keyvals]#m\array
\end{cases}#m
\begin{equation*}#\math
\end{equation*}
\begin{equations}#\math,array
\begin{equations}[options%keyvals]#\math,array
\end{equations}
\begin{equationsbox}#\math,array
\begin{equationsbox}[options%keyvals]#\math,array
\end{equationsbox}
\begin{flalign}#\math,array
\end{flalign}
\begin{flalign*}#\math,array
\end{flalign*}
\begin{gather}#\math
\end{gather}
\begin{gather*}#\math
\end{gather*}
\begin{gathered}#m
\end{gathered}#m
\begin{intertext}
\begin{intertext}[options%keyvals]
\end{intertext}
\begin{matrix}#m\array
\end{matrix}#m
\begin{multline}#\math
\end{multline}
\begin{multline*}#\math
\end{multline*}
\begin{multlined}#m
\end{multlined}#m
\begin{pmatrix}#m\array
\end{pmatrix}#m
\begin{subequations}
\begin{subequations}[options%keyvals]
\end{subequations}
\begin{Vmatrix}#m\array
\end{Vmatrix}#m
\begin{vmatrix}#m\array
\end{vmatrix}#m
\begin{xalignat}#*\math,array
\end{xalignat}#*
\begin{xalignat*}#*\math,array
\end{xalignat*}#*
\begin{xxalignat}#*\math,array
\end{xxalignat}#*
\<
\>

\displaybreak
\displaybreak[value]
\donumber
\eqnaddopt{options%keyvals}
\eqnalt{text}
\eqnalt[line|cell]{text}
\eqnbreak
\eqnbreak[skip]
\eqnbreak*
\eqnbreak*[skip]
\eqncontrol{options%keyvals}
\eqnjoin{conjunction}
\eqnjoin[skip]{conjunction}
\eqnjoin*{conjunction}
\eqnjoin*[skip]{conjunction}
\eqnlinesprovide{features%keyvals}
\eqnlinesset{options%keyvals}
\eqnpunct{punct}
\eqnpunctapply
\eqref{label}#r
\eqnsep
\eqnsep[skip]
\eqnsep*
\eqnsep*[skip]
\framecell
\framecell[cmd]
\intertext[options%keyvals]{text}
\intertext{text}
\numberhere
\numbernext
\raisetag{dimen}
\shoveby{dimen}
\shoveby*{dimen}
\shovecenter
\shoveleft!
\shoveleft*
\shoveleft[dimen]
\shoveleft
\shoveright
\tag*{label%text}#m
\tag{label%text}#m
\tagform#*
\tagbox#*
\tagboxed#*
\theHparentequation#*
\theparentequation#*

#keyvals:\usepackage/eqnlines#c,\eqnlinesset,\begin{equation},\eqnaddopt,\begin{equationsbox}
spread=##L
spread*
spread*=##L
style=#text,display
strut#true,false
punctsep=%<sep%>
punct=%<punct%>
punctline=%<punct%>
punctcol=%<punct%>
punct*=%<punct%>
punctline*=%<punct%>
punctcol*=%<punct%>
punctall=
shape=%<mode%>
padding=##L
pad=##L
padleft=##L
padright=##L
padmax#true,false
indent=##L
classout=%<class%>
classin=%<class%>
classin*=%<class%>
classlead=%<class%>
ampeq
eqamp
class=#ampeq,eqamp
margin=##L
marginleft=##L
marginright=##L
scanpar#true,false
verbose#true,false
displayheight=##L
displaydepth=##L
#endkeyvals

#keyvals:\usepackage/eqnlines#c,\eqnlinesset,\begin{equation},\eqnaddopt
allowbreaks=#0,1,2,3,4
allowdisplaybreaks=#0,1,2,3,4
tagmargin=##L
tagmargin*=##L
tagmarginratio=%<factor%>
tagmarginthreshold=%<threshold%>
mintagsep=##L
mintagwidth=##L
mintagwidth*=##L
tagsnap=
layout=#left,center
center
left
leftmargin=##L
leftmargin*=%<text%>
minleftmargin=##L
maxleftmargin=##L
marginbadness=%<integer%>
maxbadness=%<integer%>
fulllength=#on,off
linesep=##L
linesep*=##L
mincolsep=##L
maxcolsep=##L
margins#true,false
alignshrink=
tagshrink=
alignbadness=%<integer%>
tagbadness=%<integer%>
transpose=#plain,cont
#endkeyvals

#keyvals:\usepackage/eqnlines#c,\eqnlinesset,\begin{equationsbox},\begin{cases}
top
t
center
c
bottom
b
colsep=##L
frame
frame=%<cmd%>
wrap={{%<cmd-l%>}{%<cmd-r%>}}
#endkeyvals

#keyvals:\begin{equationsbox},\begin{cases}
cases
matrix
matrix=%<type%>
intro=%<text%>
introtext=%<text%>
textcond#true,false
condsep=##L
delim=%<type%>
braces=%<type%>
#endkeyvals

#keyvals:\usepackage/eqnlines#c,\eqnlinesset
native#true,false
scanequation#true,false
scanbox#true,false
sqropt={%<options%>}
angopt={%<options%>}
boxangopt={%<options%>}
noskip
noskip=#above,below,both
skip=##L
longskip=##L
aboveskip=##L
belowskip=##L
abovelongskip=##L
belowlongskip=##L
aboveshortskip=##L
belowshortskip=##L
tagskip=##L
abovetagskip=##L
belowtagskip=##L
medskip=##L
abovemedskip=##L
abovetopskip=##L
aboveparskip=##L
abovecontskip=##L
abovecontskip*
belowmedskip=##L
belowtopskip=##L
belowparskip=##L
belowcontskip=##L
shortmode=#off,above,belowone,belowall
abovecontmode=#long,short,cont
aboveparmode=#long,short,cont,par
abovetopmode=#long,short,cont,par,top
belowcontmode=#long,short,cont
belowparmode=#long,short,cont,par
belowtopmode=#long,short,cont,par,top
tagbox=%<code%>
tagbox*=%<code%>
tagform=%<code%>
tagform*=%<code%>
subeqtemplate=%<code%>
autolabel#true,false
autotag#true,false
defaults=#classic,eqnlines
ampproof#true,false
equationcr#true,false
strutdepth=##L
modifierwarning#true,false
marksymbol=%<symbol%>
qedsymbol=%<symbol%>
markpos=#below,baseline,bottom
#endkeyvals

#keyvals:\usepackage/eqnlines#c
env=#none,equation,amsmath
amsmathends#true,false
backup#true,false
ang#true,false
eqref#true,false
matrix#true,false
#endkeyvals

#keyvals:\begin{equations},\begin{subequations}
label=##l
tag=%<text%>
tag*=%<text%>
labelname=%<name%>
alt=%<text%>
#endkeyvals

#keyvals:\usepackage/eqnlines#c,\eqnlinesset,\begin{equations},\eqnaddopt
numberline=%<mode%>
nonumber
*
donumber
!
tagsleft
leqno
tagsright
reqno
tags
eqno
evadetag#true,false
tagbetween#true,false
linesfallback=#true,false,reuse
#endkeyvals

#keyvals:\begin{equations},\eqnaddopt
equation
eq
single
1
gather
ga
lines
ln
align
al
columns
col
native#true,false
displaybreak=#0,1,2,3,4
short
short=#above,below,both
long
long=#above,below,both
noskip
noskip=#above,below,both
medskip
medskip=#above,below,both
par=#cont,par,top
skip=##L
aboveskip=##L
belowskip=##L
abovespace=##L
belowspace=##L
prebreak=#0,1,2,3,4
postbreak=#0,1,2,3,4
prepenalty=
postpenalty=
interpenalty=
linewidth=##L
colsep=##L
colsep*=##L
#endkeyvals

#keyvals:\eqncontrol
vspace=
vspace*=
vspace!=
break=
penalty=
label=
labelname=
tag=
tag*=
taglabel=
shifttag=##L
smashtag=##L
pushtag
framecell
framecell=%<command%>
frametag
frametag=%<command%>
inject=%<command%>
inject*=%<command%>
markline={%<symbol=<symbol>,<options>%>}
markline*={%<symbol=<symbol>,<options>%>}
qed
qed={%<options%>}
nonumber
*
donumber
!
numberhere
numbernext
align=
shift=
shift*=
punctsep=
punct=
punct*
punctapply
#endkeyvals

#keyvals:\begin{intertext},\intertext
skip=##L
aboveskip=##L
belowskip=##L
noskip
noskip=#above,below,both
short
short=#above,below,both
long
long=#above,below,both
medskip
medskip=#above,below,both
#endkeyvals

#keyvals:\eqnlinesprovide
equation
equation*
displaymath
gather
gather*
multline
multline*
align
align*
flalign
flalign*
alignat
alignat*
xalignat
xalignat*
xxalignat
gathered
multlined
aligned
alignedat
cases
matrix
pmatrix
bmatrix
Bmatrix
vmatrix
Vmatrix
subequations
sqr
ang
eqref
tagform
maketag
#endkeyvals
