# euler-math package
# Matthew Bertucci 2026/02/21 for v0.75

#include:iftex
#include:unicode-math

#keyvals:\usepackage/euler-math#c
CharacterVariant={%<glyph num list%>}
StylisticSet=#5,6
Style=#smaller,subsetneq
Scale=#%<factor%>,MatchUppercase
Numbers=#Uppercase,UppercaseOff,Lowercase,LowercaseOff,Lining,LiningOff,OldStyle,OldStyleOff,Proportional,ProportionalOff,Monospaced,MonospacedOff,SlashedZero,SlashedZeroOff,Arabic,ArabicOff,ResetAll
#endkeyvals

# non-default unicode-math symbols supported
\backepsilon#m
\bigstar#m
\blacktriangle#m
\blacktriangledown#m
\cuberootsign{arg}#*m
\cuberoot{arg}#m
\doublebarwedge#m
\downdasharrow#m
\eqqslantgtr#m
\eqqslantless#m
\Finv#m
\fourthrootsign{arg}#*m
\fourthroot{arg}#m
\Game#m
\geqqslant#m
\harrowextender#*m
\intextender#*m
\Join#m
\leftcurvedarrow#m
\leftdasharrow#m
\leqqslant#m
\lgblkcircle#m
\lgblksquare#m
\lgwhtsquare#m
\mbfvarPhi#*m
\mdblkcircle#m
\mdblkdiamond#m
\mdblklozenge#m
\mdblksquare#m
\mdlgblkdiamond#m
\mdlgblklozenge#m
\mdlgwhtdiamond#m
\mdsmblkcircle#m
\mdsmblksquare#m
\mdsmwhtcircle#m
\mdsmwhtsquare#m
\mdwhtcircle#m
\mdwhtdiamond#m
\mdwhtlozenge#m
\mdwhtsquare#m
\mupvarPhi#*m
\pitchfork#m
\precapprox#m
\preceqq#m
\precnapprox#m
\precneq#m
\precneqq#m
\rightcurvedarrow#m
\rightdasharrow#m
\smallblacktriangleleft#m
\smallblacktriangleright#m
\smalltriangleleft#m
\smalltriangleright#m
\smblkdiamond#m
\smblklozenge#m
\smwhtlozenge#m
\subseteqq#m
\subsetneqq#m
\succapprox#m
\succeqq#m
\succnapprox#m
\succneq#m
\succneqq#m
\supseteqq#m
\supsetneqq#m
\triangledown#m
\upand#m
\upbackepsilon#*m
\updasharrow#m
\updigamma#*m
\varPhi#m
\vartriangle#m
\Vvert#m
\vysmblksquare#m
\vysmwhtsquare#m
\wedgebar#m
\Zbar#m

# symbols added by package
\varemptyset#m
\mbfwp#m
\mbfdotlessi#m
\mbfdotlessj#m
\mbfhbar#m
\lesseqslantgtr#*m
\gtreqslantless#*m
\lesseqqslantgtr#*m
\gtreqqslantless#*m
\nleqqslant#*m
\ngeqqslant#*m
\widearc{arg}#m
\overrightarc{arg}#m
\circledR#m
\circledS#m
\diagup#m
\diagdown#m
\shortmid#m
\shortparallel#m
\nshortmid#m
\nshortparallel#m
\lvertneqq#m
\gvertneqq#m
\nleqslant#m
\ngeqslant#m
\nleqq#m
\ngeqq#m
\varsubsetneq#m
\varsupsetneq#m
\nsubseteqq#m
\nsupseteqq#m
\varsubsetneqq#m
\varsupsetneqq#m
\npreceq#m
\nsucceq#m
\centerdot#m
\restriction#m
\doteqdot#m
\doublecup#m
\doublecap#m
\llless#*m
\gggtr#*m
\circlearrowleft#m
\circlearrowright#m
\lozenge#m
\blacklozenge#m
\square#m
\blacksquare#m
\dashleftarrow#m
\dashrightarrow#m
\ntriangleleft#m
\ntriangleright#m
\varpropto#*m
\thicksim#*m
\thickapprox#*m
\smallsmile#*m
\smallfrown#*m
\lhd#m
\rhd#m
\unlhd#m
\unrhd#m
\leadsto#m
\Box#m
\Diamond#m

# sans greek
\msansAlpha#*m
\msansBeta#*m
\msansGamma#*m
\msansDelta#*m
\msansEpsilon#*m
\msansZeta#*m
\msansEta#*m
\msansTheta#*m
\msansIota#*m
\msansKappa#*m
\msansLambda#*m
\msansMu#*m
\msansNu#*m
\msansXi#*m
\msansOmicron#*m
\msansPi#*m
\msansRho#*m
\msansvarTheta#*m
\msansSigma#*m
\msansTau#*m
\msansUpsilon#*m
\msansPhi#*m
\msansChi#*m
\msansPsi#*m
\msansOmega#*m
\msansnabla#*m
\msansalpha#*m
\msansbeta #*m
\msansgamma#*m
\msansdelta#*m
\msansvarepsilon#*m
\msanszeta#*m
\msanseta#*m
\msanstheta#*m
\msansiota#*m
\msanskappa#*m
\msanslambda#*m
\msansmu#*m
\msansnu#*m
\msansxi#*m
\msansomicron#*m
\msanspi#*m
\msansrho#*m
\msansvarsigma#*m
\msanssigma#*m
\msanstau#*m
\msansupsilon#*m
\msansphi#*m
\msanschi#*m
\msanspsi#*m
\msansomega#*m
\msanspartial#*m
\msansepsilon#*m
\msansvartheta#*m
\msansvarkappa#*m
\msansvarphi#*m
\msansvarrho#*m
\msansvarpi#*m

# not documented
\NEUtoks#S