# expex package
# Matthew Bertucci 2022/04/30 for v5.1b

#include:xkeyval

\lingset{options%keyvals}

\ex
\ex<tag>
\ex[options%keyvals]
\ex[options%keyvals]<tag>
\xe

\excnt#*
\lingnumoffset#*
\lingtextoffset#*
\lingaboveexskip#*
\lingbelowexskip#*

\pex
\pex<tag>
\pex[options%keyvals]
\pex[options%keyvals]<tag>

\pexcnt#*
\linglabeloffset#*
\linglabelwidth#*
\lingpreambleoffset#*
\linginterpartskip#*
\lingbelowgpreambleskip#*

\a
\a<label>
\a[options%keyvals]
\a[options%keyvals]<label>

#keyvals:\a
label=%<text%>
tag=%<tag%>
#endkeyvals

\definelabeltype{name}{options%keyvals}
\actualexno
\keepexcntlocal
\definelingstyle{name}{options%keyvals}
\lingeveryex#*
\lingEveryex#*

\judge{string}
\judge*
\ljudge{string}
\ljudge*

\begingl
\begingl[options%keyvals]
\glpreamble
\glpreamble[options%keyvals]
\gla
\gla[options%keyvals]
\glb
\glb[options%keyvals]
\glc
\glc[options%keyvals]
\glft
\glft[options%keyvals]
\endgl

\lingaboveglbskip#*
\lingaboveglcskip#*
\lingbelowglpreambleskip#*
\lingaboveglftskip#*
\lingextraglskip#*
\lingglspace#*

\nogloss{code}
\endpreamble
\trailingcitation{text}
\rightcomment{text}
\defineglwlevels{name1,name2,...}
\beginglpanel
\beginglpanel[options%keyvals]
\endpanel
\gluf#*
\lastx
\nextx
\blastx
\anextx
\bblastx

\deftag{reference%text}{name}
\deftagex{name}
\deftaglabel{name}
\deftagpage{name}
\getref{tag}
\getref{%<tag%>.%<label%>}
\getfullref{tag}
\getfullref{%<tag%>.%<label%>}

\refproofing
\gathertags
\tagfilesuffix{suffix}
\lastlabel
\hwit{text}
\labels
\labels[options%keyvals]
\tl
\nl
\tspace
\tspace[key%plain]
\crs
\exdisplay
\exdisplay[options%keyvals]
\noexno
\exnoprint
\crnb
\Lingset{options%keyvals}
\exbreak
\exbreak[dimen%l]

#keyvals:\lingset,\ex,\pex,\definelabeltype,\definelingstyle,\begingl,\glpreamble,\gla,\glb,\glc,\glft,\beginglpanel,\labels,\exdisplay,\Lingset#c
numoffset=##L
textoffset=##L
aboveexskip=##L
belowexskip=##L
exskip=##L
exno=%<text%>
exnoformat=%<format%>
exnotype=#arabic
labeltype=#alpha,caps,numeric,roman
labeloffset=##L
labelwidth=##L
preambleoffset=##L
interpartskip=##L
belowgpreambleskip=##L
samplelabel=%<text%>
nopreamble#true,false
labelanchor=#numright,numleft,margin
preambleanchor=#numright,labelleft,text
textanchor=#numleft,normal
everylabel=%<code%>
labelformat=%<format%>
labelalign=#left,center,right
labelgen=#char,number,romannumber,list
pexcnt=%<integer%>
labellist={%<labels%>}
sampleexno=%<text%>
avoidnumlabelclash#true,false
appendtopexarg={%<tokens%>}
everyex=%<code%>
Everyex=%<code%>
lingstyle=%<style name%>
*=%<string%>
everygl=%<code%>
everyglpreamble=%<code%>
everyglilg=%<code%>
everygla=%<code%>
everyglb=%<code%>
everyglc=%<code%>
everyglft=%<code%>
aboveglbskip=##L
aboveglcskip=##L
belowglpreambleskip=##L
aboveglftskip=##L
extraglskip=##L
glspace=##L
glrightskip=##L
glhangindent=##L
glhangstyle=#none,normal,cascade
glstyle=#wrap,nlevel
everyglword=%<code%>
glneveryline={%<tokens1,tokens2,...%>}
glnabovelineskip={%<dimen1,dimen2,...%>}
glwidth=##L
mincitesep=##L
everytrailingcitation=%<code%>
glrightskip=##L
glftpos=#below,right
sssep=##L
ssratio=%<ratio%>
ssrightskip=##L
everypanel=%<code%>
glufcloseup=##L
everygluf=%<code%>
glwordalign=#left,center
tag=%<tag%>
fullrefformat=%<format%>
exbreakfil=##L
exbreakpenalty=%<integer%>
splitpartspenalty=%<integer%>
#endkeyvals

# not documented
\ExPexMessage#S
\XKVforn{arg}#S
\aboveskiplist#S
\alist#S
\blist#S
\cascadeshape#S
\clist#S
\colorlist#S
\everylist#S
\foop#S
\glhangcarry#S
\glstrut#S
\glwordalign#S
\itemtypelist#S
\itlist#S
\lingaboveglaskip#S
\mainlist#S
\next#S
\pageno#S
\printlbrack#S
\printrbrack#S
\pstglcolors#S
\resetatcatcode#S
\resumepexcnt#S
\rightcite#S
\stepexcnt#S
\strutlist#S
\tspacea#S
\tspaceb#S
\tspacec#S
\worklist#S