# autogenerated by txs
\begin{fullwidth}#
\begin{innertitlepage}#
\end{fullwidth}#
\end{innertitlepage}#
\fulltextwidth
\setauthor{arg1}#
\setinstitute{arg1}#
\setpartnerlogo{arg1}#
\setpartner{arg1}#
\setsubtitle{text}#
\settitle{text}#

