#include:ifthen
#include:verbatim
#include:xkeyval
#
#Basics 
\fxsetup{setup}#*
\listoffixmes#*
\fxnote{FIX%todo}#D
\fxwarning{FIX%todo}#D
\fxerror{FIX%todo}#D
\fxfatal{FIX%todo}#D
#
#Starred
\fxsetup*{setup}#*
\fxnote*{FIX%todo}#D
\fxwarning*{FIX%todo}#D
\fxerror*{FIX%todo}#D
\fxfatal*{FIX%todo}#D
#
# Environments
\begin{anfxerror*}{summary}#
\begin{anfxerror}{summary}#
\begin{anfxfatal*}{summary}#
\begin{anfxfatal}{summary}#
\begin{anfxnote*}{summary}#
\begin{anfxnote}{summary}#
\begin{anfxwarning*}{summary}#
\begin{anfxwarning}{summary}#

