# fnspe package
# Matthew Bertucci 2022/07/02 for v1.2a

#include:xstring
#include:bm
#include:amsmath
#include:amsfonts
#include:mathrsfs
#include:amsthm
#include:amssymb
#include:xcolor
#include:listings
#include:physics
#include:tikz
#include:substr
#include:mathtools

#keyvals:\usepackage/fnspe#c
isointerval
isoointerval
fnspeinterval
isotensor
undertensor
arrowtensor
oldcomplex
isocomplex
deftext
defcolon
#endkeyvals

\xvec{arg}
\mat{letter%formula}
\tder{}{}
\tder[]{}{}
\oi{left%formula}{right%formula}
\ci{left%formula}{right%formula}
\rci{left%formula}{right%formula}
\lci{left%formula}{right%formula}
\dif{arg}#m
\hlf#m
\degree
\hem
\hem[width]
\htwoem#*
\htem#*
\oover{arg%formula}
\realn
\compn
\inte
\ratin
\natun
\nnzero
\impem#m
\rot#m
\lapl#m
\varun{var%formula}{unit%formula}
\unit{unit}#m
\expv{arg}#m
\ceil{arg}#m
\floor{arg}#m
\df
\allset{n}
\allsetzero{n}
\cclass#m
\ccof{superscript}#m
\ccinf#m