# fontscale package
# Matthew Bertucci 2026/03/04 for v5.0.0

\fontscalesetup{keyvals}
\fontscalesetup*{keyvals}

#keyvals:\fontscalesetup,\fontscalesetup*
typographic-scale=#classic,musical
classic
musical
classic/base=#10,11,12
classic/point=#pt,bp,dd,nd
musical/base=##L
musical/ratio=%<number%>
musical/notes=%<integer%>
baselineskip-size-ratio=%<factor%>
tiny/size-normalsize-ratio=%<number%>
tiny/size=%<size%>
tiny/baselineskip-size-ratio=%<factor%>
tiny/baselineskip=##L
tiny=%<size%>
scriptsize/size-normalsize-ratio=%<number%>
scriptsize/size=%<size%>
scriptsize/baselineskip-size-ratio=%<factor%>
scriptsize/baselineskip=##L
scriptsize=%<size%>
scriptsize=%<size%>
footnotesize/size-normalsize-ratio=%<number%>
footnotesize/size=%<size%>
footnotesize/baselineskip-size-ratio=%<factor%>
footnotesize/baselineskip=##L
footnotesize=%<size%>
small/size-normalsize-ratio=%<number%>
small/size=%<size%>
small/baselineskip-size-ratio=%<factor%>
small/baselineskip=##L
small=%<size%>
normalsize/size=%<size%>
normalsize/baselineskip-size-ratio=%<factor%>
normalsize/baselineskip=##L
normalsize=%<size%>
large/size-normalsize-ratio=%<number%>
large/size=%<size%>
large/baselineskip-size-ratio=%<factor%>
large/baselineskip=##L
large=%<size%>
Large/size-normalsize-ratio=%<number%>
Large/size=%<size%>
Large/baselineskip-size-ratio=%<factor%>
Large/baselineskip=##L
Large=%<size%>
LARGE/size-normalsize-ratio=%<number%>
LARGE/size=%<size%>
LARGE/baselineskip-size-ratio=%<factor%>
LARGE/baselineskip=##L
LARGE=%<size%>
huge/size-normalsize-ratio=%<number%>
huge/size=%<size%>
huge/baselineskip-size-ratio=%<factor%>
huge/baselineskip=##L
huge=%<size%>
Huge/size-normalsize-ratio=%<number%>
Huge/size=%<size%>
Huge/baselineskip-size-ratio=%<factor%>
Huge/baselineskip=##L
Huge=%<size%>
#endkeyvals

\currentnormalsize
\currentfontsize
\currentfontbaselineskip
\setfontsize{dimen}
\setfontsize[skip]{dimen}
\stepfontsize{integer}
\setfontbaselineskip{skip%l}
\printsampletext{text}
\printsampletext*{text}
\printfontsizecommand
