# fontscale package
# Matthew Bertucci 2025/03/04 for v4.0.0

\fontscalesetup{keyvals}
\fontscalesetup*{keyvals}

#keyvals:\fontscalesetup,\fontscalesetup*
baselineskip-size-ratio=%<number%>
typographic-scale=#classic-10pt,classic-11pt,classic-12pt,musical
classic-10pt
classic-11pt
classic-12pt
musical
musical/base=##L
musical/ratio=%<number%>
musical/notes=%<integer%>
tiny/scale=%<number%>
tiny/size=%<size%>
tiny/baselineskip=##L
tiny=%<size%>
tiny=%<size%>/%<baselineskip%>
scriptsize/scale=%<number%>
scriptsize/size=%<size%>
scriptsize/baselineskip=##L
scriptsize=%<size%>
scriptsize=%<size%>/%<baselineskip%>
footnotesize/scale=%<number%>
footnotesize/size=%<size%>
footnotesize/baselineskip=##L
footnotesize=%<size%>
footnotesize=%<size%>/%<baselineskip%>
small/scale=%<number%>
small/size=%<size%>
small/baselineskip=##L
small=%<size%>
small=%<size%>/%<baselineskip%>
normalsize/scale=%<number%>
normalsize/size=%<size%>
normalsize/baselineskip=##L
normalsize=%<size%>
normalsize=%<size%>/%<baselineskip%>
large/scale=%<number%>
large/size=%<size%>
large/baselineskip=##L
large=%<size%>
large=%<size%>/%<baselineskip%>
Large/scale=%<number%>
Large/size=%<size%>
Large/baselineskip=##L
Large=%<size%>
Large=%<size%>/%<baselineskip%>
LARGE/scale=%<number%>
LARGE/size=%<size%>
LARGE/baselineskip=##L
LARGE=%<size%>
LARGE=%<size%>/%<baselineskip%>
huge/scale=%<number%>
huge/size=%<size%>
huge/baselineskip=##L
huge=%<size%>
huge=%<size%>/%<baselineskip%>
Huge/scale=%<number%>
Huge/size=%<size%>
Huge/baselineskip=##L
Huge=%<size%>
Huge=%<size%>/%<baselineskip%>
#endkeyvals

\currentfontstep
\currentfontscale
\currentfontsize
\currentfontbaselineskip
\setfontstep{number}
\setfontstep*{number}
\setfontscale{number}
\setfontscale*{number}
\setfontsize{dimen}
\setfontsize*{dimen}
\scalefont{number}
\setfontsizebaselineskip{dimen}{skip%l}
\setfontbaselineskip{skip%l}
\setfontbaselineskip*{skip%l}
\printfontsizeparameters
\printallfontsizeparameters
\printsampletext{text}
\printsampletext*{text}
\printfontsizecommand
