# fontscale package
# Matthew Bertucci 2025/04/07 for v4.1.0

\fontscalesetup{keyvals}
\fontscalesetup*{keyvals}

#keyvals:\fontscalesetup,\fontscalesetup*
baselineskip-size-ratio=%<number%>
typographic-scale=#classic-10pt,classic-11pt,classic-12pt,classic-10bp,classic-11bp,classic-12bp,classic-10dd,classic-11dd,classic-12dd,classic-10nd,classic-11nd,classic-12nd,musical
classic-10pt
classic-11pt
classic-12pt
classic-10bp
classic-11bp
classic-12bp
classic-10dd
classic-11dd
classic-12dd
classic-10nd
classic-11nd
classic-12nd
musical
musical/base=##L
musical/ratio=%<number%>
musical/notes=%<integer%>
baselineskip-size-ratio=%<factor%>
tiny/scale=%<number%>
tiny/size=%<size%>
tiny/baselineskip-size-ratio=%<factor%>
tiny/baselineskip=##L
tiny=%<size%>
scriptsize/scale=%<number%>
scriptsize/size=%<size%>
scriptsize/baselineskip-size-ratio=%<factor%>
scriptsize/baselineskip=##L
scriptsize=%<size%>
scriptsize=%<size%>
footnotesize/scale=%<number%>
footnotesize/size=%<size%>
footnotesize/baselineskip-size-ratio=%<factor%>
footnotesize/baselineskip=##L
footnotesize=%<size%>
small/scale=%<number%>
small/size=%<size%>
small/baselineskip-size-ratio=%<factor%>
small/baselineskip=##L
small=%<size%>
normalsize/size=%<size%>
normalsize/baselineskip-size-ratio=%<factor%>
normalsize/baselineskip=##L
normalsize=%<size%>
large/scale=%<number%>
large/size=%<size%>
large/baselineskip-size-ratio=%<factor%>
large/baselineskip=##L
large=%<size%>
Large/scale=%<number%>
Large/size=%<size%>
Large/baselineskip-size-ratio=%<factor%>
Large/baselineskip=##L
Large=%<size%>
LARGE/scale=%<number%>
LARGE/size=%<size%>
LARGE/baselineskip-size-ratio=%<factor%>
LARGE/baselineskip=##L
LARGE=%<size%>
huge/scale=%<number%>
huge/size=%<size%>
huge/baselineskip-size-ratio=%<factor%>
huge/baselineskip=##L
huge=%<size%>
Huge/scale=%<number%>
Huge/size=%<size%>
Huge/baselineskip-size-ratio=%<factor%>
Huge/baselineskip=##L
Huge=%<size%>
#endkeyvals

\currentnormalsize
\currentfontstep
\currentfontscale
\currentfontsize
\currentfontbaselineskip
\setfontstep{number}
\setfontstep*{number}
\setfontscale{number}
\setfontscale*{number}
\setfontsize{dimen}
\setfontsize*{dimen}
\scalefont{number}
\setfontsizebaselineskip{dimen}{skip%l}
\setfontbaselineskip{skip%l}
\setfontbaselineskip*{skip%l}
\printfontsizeparameters
\printallfontsizeparameters
\printsampletext{text}
\printsampletext*{text}
\printfontsizecommand
