# glossary-longextra package
# Matthew Bertucci 2022/11/09 for v1.50

#include:glossary-longbooktabs

\GlsLongExtraUseTabulartrue#*
\GlsLongExtraUseTabularfalse#*
\ifGlsLongExtraUseTabular#*
\glslongextraTabularVAlign#*
\glslongextraHeaderFmt{text}#*
\glslongextraNameFmt{label}#*
\glslongextraSubNameFmt{level}{label}#*
\glslongextraNameAlign#*
\glslongextraDescFmt{label}#*
\glslongextraSubDescFmt{level}{label}#*
\glslongextraDescAlign#*
\glslongextraSetWidest{widest-name}#*
\glslongextraUpdateWidest{name}#*
\glslongextraUpdateWidestChild{level}{name}#*
\glslongextraLocationFmt{label}{location-list}#*
\glslongextraSubLocationFmt{level}{label}{location-list}#*
\glslongextraLocationAlign#*
\glslongextraSymbolFmt{label}#*
\glslongextraSubSymbolFmt{level}{label}#*
\glslongextraSymbolAlign#*
\glslongextraGroupHeading{num-cols}{group-label}#*
\glslongextraSubGroupHeading{num-cols}{prev-group-level}{group-level}{parent-label}{group-label}#*
\glslongextraSetDescWidth#*
\glslongextraNameDescTabularHeader#*
\glslongextraNameDescTabularFooter#*
\glslongextraNameDescHeader#*
\glslongextraDescNameTabularHeader#*
\glslongextraDescNameTabularFooter#*
\glslongextraDescNameHeader#*
\glslongextraSymSetDescWidth#*
\glslongextraNameDescSymTabularHeader#*
\glslongextraNameDescSymTabularFooter#*
\glslongextraNameDescSymHeader#*
\glslongextraNameSymDescTabularHeader#*
\glslongextraNameSymDescTabularFooter#*
\glslongextraNameSymDescHeader#*
\glslongextraSymDescNameTabularHeader#*
\glslongextraSymDescNameTabularFooter#*
\glslongextraSymDescNameHeader#*
\glslongextraDescSymNameTabularHeader#*
\glslongextraDescSymNameTabularFooter#*
\glslongextraDescSymNameHeader#*
\glslongextraLocSetDescWidth#*
\glslongextraNameDescLocationTabularHeader#*
\glslongextraNameDescLocationTabularFooter#*
\glslongextraNameDescLocationHeader#*
\glslongextraLocationDescNameTabularHeader#*
\glslongextraLocationDescNameTabularFooter#*
\glslongextraLocationDescNameHeader#*
\glslongextraSymLocSetDescWidth#*
\glslongextraNameDescSymLocationTabularHeader#*
\glslongextraNameDescSymLocationTabularFooter#*
\glslongextraNameDescSymLocationHeader#*
\glslongextraNameSymDescLocationTabularHeader#*
\glslongextraNameSymDescLocationTabularFooter#*
\glslongextraNameSymDescLocationHeader#*
\glslongextraLocationSymDescNameTabularHeader#*
\glslongextraLocationSymDescNameTabularFooter#*
\glslongextraLocationSymDescNameHeader#*
\glslongextraLocationDescSymNameTabularHeader#*
\glslongextraLocationDescSymNameTabularFooter#*
\glslongextraLocationDescSymNameHeader#*
\glslongextraSymbolNameAlign#*
\glslongextraSymbolTargetFmt{label}#*
\glslongextraSubSymbolTargetFmt{level}{label}#*
\glslongextraSymbolOrName{label}#*
\glslongextraSubSymbolOrName{level}{label}#*
\glslongextraSymNoNameSetDescWidth#*
\glslongextraSymDescTabularHeader#*
\glslongextraSymDescTabularFooter#*
\glslongextraSymDescHeader#*
\glslongextraDescSymTabularHeader#*
\glslongextraDescSymTabularFooter#*
\glslongextraDescSymHeader#*
\glslongextraShortHeader#*
\glslongextraLongHeader#*
\glslongextraShortTargetFmt{label}#*
\glslongextraLongFmt{label}#*
\glslongextraSubShortTargetFmt{level}{label}#*
\glslongextraSubLongFmt{level}{label}#*
\glslongextraShortNoNameSetDescWidth#*
\glslongextraShortLongTabularHeader#*
\glslongextraShortLongTabularFooter#*
\glslongextraShortLongHeader#*
\glslongextraLongShortTabularHeader#*
\glslongextraLongShortTabularFooter#*
\glslongextraLongShortHeader#*
\glslongextraCustomIField#*
\glslongextraCustomIIField#*
\glslongextraCustomIIIField#*
\glslongextraCustomIHeader#*
\glslongextraCustomIIHeader#*
\glslongextraCustomIIIHeader#*
\glslongextraCustomIFmt{label}#*
\glslongextraSubCustomIFmt{level}{label}#*
\glslongextraCustomIIFmt{label}#*
\glslongextraSubCustomIIFmt{level}{label}#*
\glslongextraCustomIIIFmt{label}#*
\glslongextraSubCustomIIIFmt{level}{label}#*
\glslongextraCustomIAlign#*
\glslongextraCustomIIAlign#*
\glslongextraCustomIIIAlign#*
\glslongextraCustomTabularFooter#*
\glslongextraNameCustomITabularHeader#*
\glslongextraNameCustomIHeader#*
\glslongextraCustomINameTabularHeader#*
\glslongextraCustomINameHeader#*
\glslongextraNameCustomIITabularHeader#*
\glslongextraNameCustomIIHeader#*
\glslongextraCustomIINameTabularHeader#*
\glslongextraCustomIINameHeader#*
\glslongextraNameCustomIIITabularHeader#*
\glslongextraNameCustomIIIHeader#*
\glslongextraCustomIIINameTabularHeader#*
\glslongextraCustomIIINameHeader#*
\glslongextraCustomISetDescWidth#*
\glslongextraCustomIISetDescWidth#*
\glslongextraCustomIIISetDescWidth#*
\glslongextraNameCustomIDescTabularHeader#*
\glslongextraNameCustomIDescHeader#*
\glslongextraDescCustomINameTabularHeader#*
\glslongextraDescCustomINameHeader#*
\glslongextraNameCustomIIDescTabularHeader#*
\glslongextraNameCustomIIDescHeader#*
\glslongextraDescCustomIINameTabularHeader#*
\glslongextraDescCustomIINameHeader#*
\glslongextraNameCustomIIIDescTabularHeader#*
\glslongextraNameCustomIIIDescHeader#*
\glslongextraDescCustomIIINameTabularHeader#*
\glslongextraDescCustomIIINameHeader#*
