# glossary-longextra package
# Matthew Bertucci 2022/10/19 for v1.49

#include:glossary-longbooktabs

\ifGlsLongExtraUseTabular#*
\GlsLongExtraUseTabulartrue#*
\GlsLongExtraUseTabularfalse#*
\glslongextraTabularVAlign#*
\glslongextraHeaderFmt{text}#*
\glslongextraNameAlign#*
\glslongextraSymbolAlign#*
\glslongextraSymbolNameAlign#*
\glslongextraLocationAlign#*
\glslongextraDescAlign#*
\glslongextraSetDescWidth#*
\glslongextraSetWidest{widest name}#*
\glslongextraUpdateWidest{text}#*
\glslongextraUpdateWidestChild{level}{text}#*
\glslongextraSymSetDescWidth#*
\glslongextraSymNoNameSetDescWidth#*
\glslongextraLocSetDescWidth#*
\glslongextraSymLocSetDescWidth#*
\glslongextraShortNoNameSetDescWidth#*
\glslongextraNameFmt{label}#*
\glslongextraDescFmt{label}#*
\glslongextraSymbolFmt{label}#*
\glslongextraSymbolTargetFmt{label}#*
\glslongextraSymbolOrName{label}#*
\glslongextraLocationFmt{label}{locations}#*
\glslongextraShortTargetFmt{label}#*
\glslongextraLongFmt{label}#*
\glslongextraSubNameFmt{level}{label}#*
\glslongextraSubDescFmt{level}{label}#*
\glslongextraSubSymbolFmt{level}{label}#*
\glslongextraSubSymbolTargetFmt{level}{label}#*
\glslongextraSubSymbolOrName{level}{label}#*
\glslongextraSubShortTargetFmt{level}{label}#*
\glslongextraSubLongFmt{level}{label}#*
\glslongextraSubLocationFmt{level}{label}{locations}#*
\glslongextraGroupHeading{n}{label}#*
\glslongextraSubGroupHeading{n}{prev-group-level}{group-level}{parent-label}{group-label}#*
\glslongextraNameDescHeader#*
\glslongextraNameDescTabularHeader#*
\glslongextraNameDescTabularFooter#*
\glslongextraNameDescLocationHeader#*
\glslongextraNameDescLocationTabularHeader#*
\glslongextraNameDescLocationTabularFooter#*
\glslongextraDescNameHeader#*
\glslongextraDescNameTabularHeader#*
\glslongextraDescNameTabularFooter#*
\glslongextraLocationDescNameHeader#*
\glslongextraLocationDescNameTabularHeader#*
\glslongextraLocationDescNameTabularFooter#*
\glslongextraNameDescSymHeader#*
\glslongextraNameDescSymTabularHeader#*
\glslongextraNameDescSymTabularFooter#*
\glslongextraNameDescSymLocationHeader#*
\glslongextraNameDescSymLocationTabularHeader#*
\glslongextraNameDescSymLocationTabularFooter#*
\glslongextraNameSymDescHeader#*
\glslongextraNameSymDescTabularHeader#*
\glslongextraNameSymDescTabularFooter#*
\glslongextraNameSymDescLocationHeader#*
\glslongextraNameSymDescLocationTabularHeader#*
\glslongextraNameSymDescLocationTabularFooter#*
\glslongextraSymDescHeader#*
\glslongextraSymDescTabularHeader#*
\glslongextraSymDescTabularFooter#*
\glslongextraDescSymHeader#*
\glslongextraDescSymTabularHeader#*
\glslongextraDescSymTabularFooter#*
\glslongextraShortLongHeader#*
\glslongextraShortHeader#*
\glslongextraLongHeader#*
\glslongextraShortLongTabularHeader#*
\glslongextraShortLongTabularFooter#*
\glslongextraLongShortHeader#*
\glslongextraLongShortTabularHeader#*
\glslongextraLongShortTabularFooter#*
\glslongextraSymDescNameHeader#*
\glslongextraSymDescNameTabularHeader#*
\glslongextraSymDescNameTabularFooter#*
\glslongextraLocationSymDescNameHeader#*
\glslongextraLocationSymDescNameTabularHeader#*
\glslongextraLocationSymDescNameTabularFooter#*
\glslongextraDescSymNameHeader#*
\glslongextraDescSymNameTabularHeader#*
\glslongextraDescSymNameTabularFooter#*
\glslongextraLocationDescSymNameHeader#*
\glslongextraLocationDescSymNameTabularHeader#*
\glslongextraLocationDescSymNameTabularFooter#*
