# autogenerated by txs edited by Stefan Kraus 2013-09-09, completed by Denis Bitouz\'e 13-10-2014
# edited Matthew Bertucci 11/7/2021 for v4.49

#include:ifthen
#include:xkeyval
#include:mfirstuc
#include:textcase
#include:xfor
#include:datatool-base
#include:amsgen
#include:etoolbox
#include:glossary-hypernav
#include:glossary-list
#include:glossary-long
#include:glossary-super
#include:glossary-tree
#include:glossaries-compatible-307

\GlsSetQuote{character}#*
\glstextup{text}#*

\acronymname#*
\andname#*
\descriptionname#*
\entryname#*
\glossaryname#*
\glsnumbersgroupname#*
\glssymbolsgroupname#*
\pagelistname#*
\seename#*
\symbolname#*
	
### 2 Package Options ###
## 2.1 General Options ##
#keyvals:\usepackage/glossaries#c
nowarn
nolangwarn
noredefwarn
debug=#false,true,showtargets,showaccsupp
savewrites#true,false
translate=#true,false,babel
notranslate
hyperfirst#true,false
writeglslabels
writeglslabelnames
toc#true,false
numberline#true,false
section=%<section unit%>
ucmark#true,false
numberedsection=#false,nolabel,autolabel
savenumberlist#true,false
entrycounter#true,false
counterwithin=%<counter%>
subentrycounter#true,false
style=
nolong
nosuper
nolist
notree
nostyles
nonumberlist
seeautonumberlist
counter=%<counter%>
nopostdot#true,false
nogroupskip#true,false
seenoindex=#error,warn,ignore
esclocations#true,false
indexonlyfirst#true,false
sanitizesort#true,false
sort=#standard,def,use,none
order=#word,letter
makeindex
xindy
xindygloss
xindynoglsnumbers
automake=#false,true,immediate
disablemakegloss
restoremakegloss
nohypertypes={%<list%>}
nomain
symbols
numbers
index
noglossaryindex
acronym#true,false
acronyms
acronymlists={%<value%>}
shortcuts
compatible-2.07#true,false
compatible-3.07#true,false
kernelglossredefs={%<value%>}
#endkeyvals

#ifOption:debug=showtargets
\glsshowtarget{target name}
\glsshowtargetouter{label}
\glsshowtargetfont#*
#endif

#ifOption:debug=showaccsupp
\glsshowaccsupp{options}{tag}{replacement text}
#endif

#ifOption:translate=babel
#include:glossaries-babel
#endif

\glslinkcheckfirsthyperhook#*

## 2.2 Sectioning, Headings and TOC Options ##
\glstoctrue#*
\glstocfalse#*
\setglossarysection{name}
\glsglossarymark{glossary title}
\glsclearpage#*
\ifglsucmark#*
\glsautoprefix#*
\acronymtype#*
\glsdefaulttype#*

## 2.3 Glossary Appearance Options ##
\theglossaryentry#*
\theglossarysubentry#*
\glsrefentry{label}#*
\GlsEntryCounterLabelPrefix#*
\glsresetentrycounter#*

## 2.4 Indexing Options ##
\glswriteentry{label}{wr-code}#*
\glssortnumberfmt{number}#*
\glsprestandardsort{sort cs}{type}{label}#*
\glsdosanitizesort#*

## 2.6 Glossary Type Options ##
\GlsDeclareNoHyperList{list}#*
#ifOption:symbols
\printsymbols
\printsymbols[options%keyvals]
#endif
#ifOption:numbers
\printnumbers
\printnumbers[options%keyvals]
#endif
#ifOption:index
\newterm{term}
\newterm[options%keyvals]{term}
\printindex
\printindex[options%keyvals]
#endif
#ifOption:acronym
\printacronyms
\printacronyms[options%keyvals]
#endif
#ifOption:acronym=true
\printacronyms
\printacronyms[options%keyvals]
#endif
#ifOption:acronyms
\printacronyms
\printacronyms[options%keyvals]
#endif
\DeclareAcronymList{list}#*
\SetAcronymLists{list}#*
\glsIfListOfAcronyms{label}{true}{false}#*
\DefineAcronymSynonyms#*
#ifOption:compatible-2.07
#include:glossaries-compatible-207
#endif
#ifOption:compatible-2.07=true
#include:glossaries-compatible-207
#endif

## 2.10 Setting Options After the Package is Loaded ##
\setupglossaries{options%keyvals}
#keyvals:\setupglossaries
debug=#false,true,showtargets,showaccsupp
savewrites#true,false
hyperfirst#true,false
writeglslabels
writeglslabelnames
toc#true,false
numberline#true,false
section=%<section unit%>
ucmark#true,false
numberedsection=#false,nolabel,autolabel
savenumberlist#true,false
entrycounter#true,false
counterwithin=%<counter%>
subentrycounter#true,false
style=
nonumberlist
seeautonumberlist
counter=%<counter%>
nopostdot#true,false
nogroupskip#true,false
seenoindex=#error,warn,ignore
esclocations#true,false
indexonlyfirst#true,false
sanitizesort#true,false
sort=#standard,def,use,none
order=#word,letter
automake=#false,true,immediate
disablemakegloss
restoremakegloss
nohypertypes={%<list%>}
symbols
numbers
index
noglossaryindex
acronymlists={%<value%>}
shortcuts
kernelglossredefs={%<value%>}
#endkeyvals
  
### 3 Setting Up ###
\makenoidxglossaries#n
\makeglossaries#n
\noist#n
\setStyleFile{name}#*
\glsSetCompositor{symbol}#*
\glsSetAlphaCompositor{symbol}#*

### 4 Defining Glossary Entries ###
\newglossaryentry{label}{keyvals}#l
\longnewglossaryentry{label}{keyvals}{long description}#l
\provideglossaryentry{label}{keyvals}#l
\longprovideglossaryentry{label}{keyvals}{long description}#l

#keyvals:\newglossaryentry#c,\longnewglossaryentry#c,\provideglossaryentry#c,\longprovideglossaryentry#c,\newacronym#c,\newterm#c
name=
description=
parent=
descriptionplural=
text=
first=
plural=
firstplural=
symbol=
symbolplural=
sort=
type=
user1=
user2=
user3=
user4=
user5=
user6=
nonumberlist#true,false
see=
#endkeyvals

\nopostdesc
\glspar#*

## 4.1 Plurals ##
\glspluralsuffix#*

## 4.3 Additional Keys ##
\glsaddkey{key%plain}{default}{nolink cs}{nolink ucfirst cs}{link cs}{link ucfirst cs}{link allcaps cs}#*
\glsaddstoragekey{key%plain}{default}{nolink cs}#*

## 4.4 Expansion ##
\glssetexpandfield{field}#*
\glssetnoexpandfield{field}#*
\glsexpandfields#*
\glsnoexpandfields#*

## 4.6 Loading Entries From a File ##
\loadglsentries{file}#i
\loadglsentries[type]{file}#i

## 4.7 Moving Entries to Another Glossary ##
\glsmoveentry{label}{target glossary label%ref}#r

### 5 Referencing Entries in the Document ###
## 5.1 Links to Glossary Entries ##
\glstextformat{text}#*
\glspatchtabularx#*

\gls{label}#r
\gls[options%keyvals]{label}#r
\gls{label}[insert]#*r
\gls[options%keyvals]{label}[insert]#*r
\Gls{label}#r
\Gls[options%keyvals]{label}#r
\Gls{label}[insert]#*r
\Gls[options%keyvals]{label}[insert]#*r
\GLS{label}#r
\GLS[options%keyvals]{label}#r
\GLS{label}[insert]#*r
\GLS[options%keyvals]{label}[insert]#*r
\gls*{label}#Sr
\gls*[options]{label}#Sr
\gls*{label}[insert]#Sr
\gls*[options]{label}[insert]#Sr
\Gls*{label}#Sr
\Gls*[options]{label}#Sr
\Gls*{label}[insert]#Sr
\Gls*[options]{label}[insert]#Sr
\GLS*{label}#Sr
\GLS*[options]{label}#Sr
\GLS*{label}[insert]#Sr
\GLS*[options]{label}[insert]#Sr
\gls+{label}#Sr
\gls+[options]{label}#Sr
\gls+{label}[insert]#Sr
\gls+[options]{label}[insert]#Sr
\Gls+{label}#Sr
\Gls+[options]{label}#Sr
\Gls+{label}[insert]#Sr
\Gls+[options]{label}[insert]#Sr
\GLS+{label}#Sr
\GLS+[options]{label}#Sr
\GLS+{label}[insert]#Sr
\GLS+[options]{label}[insert]#Sr

\glspl{label}#r
\glspl[options%keyvals]{label}#r
\glspl{label}[insert]#*r
\glspl[options%keyvals]{label}[insert]#*r
\Glspl{label}#r
\Glspl[options%keyvals]{label}#r
\Glspl{label}[insert]#*r
\Glspl[options%keyvals]{label}[insert]#*r
\GLSpl{label}#r
\GLSpl[options%keyvals]{label}#r
\GLSpl{label}[insert]#*r
\GLSpl[options%keyvals]{label}[insert]#*r
\glspl*{label}#Sr
\glspl*[options]{label}#Sr
\glspl*{label}[insert]#Sr
\glspl*[options]{label}[insert]#Sr
\Glspl*{label}#Sr
\Glspl*[options]{label}#Sr
\Glspl*{label}[insert]#Sr
\Glspl*[options]{label}[insert]#Sr
\GLSpl*{label}#Sr
\GLSpl*[options]{label}#Sr
\GLSpl*{label}[insert]#Sr
\GLSpl*[options]{label}[insert]#Sr
\glspl+{label}#Sr
\glspl+[options]{label}#Sr
\glspl+{label}[insert]#Sr
\glspl+[options]{label}[insert]#Sr
\Glspl+{label}#Sr
\Glspl+[options]{label}#Sr
\Glspl+{label}[insert]#Sr
\Glspl+[options]{label}[insert]#Sr
\GLSpl+{label}#Sr
\GLSpl+[options]{label}#Sr
\GLSpl+{label}[insert]#Sr
\GLSpl+[options]{label}[insert]#Sr

\glsdisp{label}{link text}#r
\glsdisp[options%keyvals]{label}{link text}#r
\glsdisp*{label}{link text}#Sr
\glsdisp*[options]{label}{link text}#Sr
\glsdisp+{label}{link text}#Sr
\glsdisp+[options]{label}{link text}#Sr

\glslink{label}{link text}#r
\glslink[options%keyvals]{label}{link text}#r
\glslink*{label}{link text}#Sr
\glslink*[options]{label}{link text}#Sr
\glslink+{label}{link text}#Sr
\glslink+[options]{label}{link text}#Sr

\glstext{label}#*r
\glstext[options%keyvals]{label}#*r
\glstext{label}[insert]#*r
\glstext[options%keyvals]{label}[insert]#*r
\Glstext{label}#*r
\Glstext[options%keyvals]{label}#*r
\Glstext{label}[insert]#*r
\Glstext[options%keyvals]{label}[insert]#*r
\GLStext{label}#*r
\GLStext[options%keyvals]{label}#*r
\GLStext{label}[insert]#*r
\GLStext[options%keyvals]{label}[insert]#*r
\glstext*{label}#Sr
\glstext*[options]{label}#Sr
\glstext*{label}[insert]#Sr
\glstext*[options]{label}[insert]#Sr
\Glstext*{label}#Sr
\Glstext*[options]{label}#Sr
\Glstext*{label}[insert]#Sr
\Glstext*[options]{label}[insert]#Sr
\GLStext*{label}#Sr
\GLStext*[options]{label}#Sr
\GLStext*{label}[insert]#Sr
\GLStext*[options]{label}[insert]#Sr
\glstext+{label}#Sr
\glstext+[options]{label}#Sr
\glstext+{label}[insert]#Sr
\glstext+[options]{label}[insert]#Sr
\Glstext+{label}#Sr
\Glstext+[options]{label}#Sr
\Glstext+{label}[insert]#Sr
\Glstext+[options]{label}[insert]#Sr
\GLStext+{label}#Sr
\GLStext+[options]{label}#Sr
\GLStext+{label}[insert]#Sr
\GLStext+[options]{label}[insert]#Sr

\glsfirst{label}#*r
\glsfirst[options%keyvals]{label}#*r
\glsfirst{label}[insert]#*r
\glsfirst[options%keyvals]{label}[insert]#*r
\Glsfirst{label}#*r
\Glsfirst[options%keyvals]{label}#*r
\Glsfirst{label}[insert]#*r
\Glsfirst[options%keyvals]{label}[insert]#*r
\GLSfirst{label}#*r
\GLSfirst[options%keyvals]{label}#*r
\GLSfirst{label}[insert]#*r
\GLSfirst[options%keyvals]{label}[insert]#*r
\glsfirst*{label}#Sr
\glsfirst*[options]{label}#Sr
\glsfirst*{label}[insert]#Sr
\glsfirst*[options]{label}[insert]#Sr
\Glsfirst*{label}#Sr
\Glsfirst*[options]{label}#Sr
\Glsfirst*{label}[insert]#Sr
\Glsfirst*[options]{label}[insert]#Sr
\GLSfirst*{label}#Sr
\GLSfirst*[options]{label}#Sr
\GLSfirst*{label}[insert]#Sr
\GLSfirst*[options]{label}[insert]#Sr
\glsfirst+{label}#Sr
\glsfirst+[options]{label}#Sr
\glsfirst+{label}[insert]#Sr
\glsfirst+[options]{label}[insert]#Sr
\Glsfirst+{label}#Sr
\Glsfirst+[options]{label}#Sr
\Glsfirst+{label}[insert]#Sr
\Glsfirst+[options]{label}[insert]#Sr
\GLSfirst+{label}#Sr
\GLSfirst+[options]{label}#Sr
\GLSfirst+{label}[insert]#Sr
\GLSfirst+[options]{label}[insert]#Sr

\glsplural{label}#*r
\glsplural[options%keyvals]{label}#*r
\glsplural{label}[insert]#*r
\glsplural[options%keyvals]{label}[insert]#*r
\Glsplural{label}#*r
\Glsplural[options%keyvals]{label}#*r
\Glsplural{label}[insert]#*r
\Glsplural[options%keyvals]{label}[insert]#*r
\GLSplural{label}#*r
\GLSplural[options%keyvals]{label}#*r
\GLSplural{label}[insert]#*r
\GLSplural[options%keyvals]{label}[insert]#*r
\glsplural*{label}#Sr
\glsplural*[options]{label}#Sr
\glsplural*{label}[insert]#Sr
\glsplural*[options]{label}[insert]#Sr
\Glsplural*{label}#Sr
\Glsplural*[options]{label}#Sr
\Glsplural*{label}[insert]#Sr
\Glsplural*[options]{label}[insert]#Sr
\GLSplural*{label}#Sr
\GLSplural*[options]{label}#Sr
\GLSplural*{label}[insert]#Sr
\GLSplural*[options]{label}[insert]#Sr
\glsplural+{label}#Sr
\glsplural+[options]{label}#Sr
\glsplural+{label}[insert]#Sr
\glsplural+[options]{label}[insert]#Sr
\Glsplural+{label}#Sr
\Glsplural+[options]{label}#Sr
\Glsplural+{label}[insert]#Sr
\Glsplural+[options]{label}[insert]#Sr
\GLSplural+{label}#Sr
\GLSplural+[options]{label}#Sr
\GLSplural+{label}[insert]#Sr
\GLSplural+[options]{label}[insert]#Sr

\glsfirstplural{label}#*r
\glsfirstplural[options%keyvals]{label}#*r
\glsfirstplural{label}[insert]#*r
\glsfirstplural[options%keyvals]{label}[insert]#*r
\Glsfirstplural{label}#*r
\Glsfirstplural[options%keyvals]{label}#*r
\Glsfirstplural{label}[insert]#*r
\Glsfirstplural[options%keyvals]{label}[insert]#*r
\GLSfirstplural{label}#*r
\GLSfirstplural[options%keyvals]{label}#*r
\GLSfirstplural{label}[insert]#*r
\GLSfirstplural[options%keyvals]{label}[insert]#*r
\glsfirstplural*{label}#Sr
\glsfirstplural*[options]{label}#Sr
\glsfirstplural*{label}[insert]#Sr
\glsfirstplural*[options]{label}[insert]#Sr
\Glsfirstplural*{label}#Sr
\Glsfirstplural*[options]{label}#Sr
\Glsfirstplural*{label}[insert]#Sr
\Glsfirstplural*[options]{label}[insert]#Sr
\GLSfirstplural*{label}#Sr
\GLSfirstplural*[options]{label}#Sr
\GLSfirstplural*{label}[insert]#Sr
\GLSfirstplural*[options]{label}[insert]#Sr
\glsfirstplural+{label}#Sr
\glsfirstplural+[options]{label}#Sr
\glsfirstplural+{label}[insert]#Sr
\glsfirstplural+[options]{label}[insert]#Sr
\Glsfirstplural+{label}#Sr
\Glsfirstplural+[options]{label}#Sr
\Glsfirstplural+{label}[insert]#Sr
\Glsfirstplural+[options]{label}[insert]#Sr
\GLSfirstplural+{label}#Sr
\GLSfirstplural+[options]{label}#Sr
\GLSfirstplural+{label}[insert]#Sr
\GLSfirstplural+[options]{label}[insert]#Sr

\glsname{label}#*r
\glsname[options%keyvals]{label}#*r
\glsname{label}[insert]#*r
\glsname[options%keyvals]{label}[insert]#*r
\Glsname{label}#*r
\Glsname[options%keyvals]{label}#*r
\Glsname{label}[insert]#*r
\Glsname[options%keyvals]{label}[insert]#*r
\GLSname{label}#*r
\GLSname[options%keyvals]{label}#*r
\GLSname{label}[insert]#*r
\GLSname[options%keyvals]{label}[insert]#*r
\glsname*{label}#Sr
\glsname*[options]{label}#Sr
\glsname*{label}[insert]#Sr
\glsname*[options]{label}[insert]#Sr
\Glsname*{label}#Sr
\Glsname*[options]{label}#Sr
\Glsname*{label}[insert]#Sr
\Glsname*[options]{label}[insert]#Sr
\GLSname*{label}#Sr
\GLSname*[options]{label}#Sr
\GLSname*{label}[insert]#Sr
\GLSname*[options]{label}[insert]#Sr
\glsname+{label}#Sr
\glsname+[options]{label}#Sr
\glsname+{label}[insert]#Sr
\glsname+[options]{label}[insert]#Sr
\Glsname+{label}#Sr
\Glsname+[options]{label}#Sr
\Glsname+{label}[insert]#Sr
\Glsname+[options]{label}[insert]#Sr
\GLSname+{label}#Sr
\GLSname+[options]{label}#Sr
\GLSname+{label}[insert]#Sr
\GLSname+[options]{label}[insert]#Sr

\glssymbol{label}#*r
\glssymbol[options%keyvals]{label}#*r
\glssymbol{label}[insert]#*r
\glssymbol[options%keyvals]{label}[insert]#*r
\Glssymbol{label}#*r
\Glssymbol[options%keyvals]{label}#*r
\Glssymbol{label}[insert]#*r
\Glssymbol[options%keyvals]{label}[insert]#*r
\GLSsymbol{label}#*r
\GLSsymbol[options%keyvals]{label}#*r
\GLSsymbol{label}[insert]#*r
\GLSsymbol[options%keyvals]{label}[insert]#*r
\glssymbol*{label}#Sr
\glssymbol*[options]{label}#Sr
\glssymbol*{label}[insert]#Sr
\glssymbol*[options]{label}[insert]#Sr
\Glssymbol*{label}#Sr
\Glssymbol*[options]{label}#Sr
\Glssymbol*{label}[insert]#Sr
\Glssymbol*[options]{label}[insert]#Sr
\GLSsymbol*{label}#Sr
\GLSsymbol*[options]{label}#Sr
\GLSsymbol*{label}[insert]#Sr
\GLSsymbol*[options]{label}[insert]#Sr
\glssymbol+{label}#Sr
\glssymbol+[options]{label}#Sr
\glssymbol+{label}[insert]#Sr
\glssymbol+[options]{label}[insert]#Sr
\Glssymbol+{label}#Sr
\Glssymbol+[options]{label}#Sr
\Glssymbol+{label}[insert]#Sr
\Glssymbol+[options]{label}[insert]#Sr
\GLSsymbol+{label}#Sr
\GLSsymbol+[options]{label}#Sr
\GLSsymbol+{label}[insert]#Sr
\GLSsymbol+[options]{label}[insert]#Sr

\glssymbolplural{label}#*r
\glssymbolplural[options%keyvals]{label}#*r
\glssymbolplural{label}[insert]#*r
\glssymbolplural[options%keyvals]{label}[insert]#*r
\Glssymbolplural{label}#*r
\Glssymbolplural[options%keyvals]{label}#*r
\Glssymbolplural{label}[insert]#*r
\Glssymbolplural[options%keyvals]{label}[insert]#*r
\GLSsymbolplural{label}#*r
\GLSsymbolplural[options%keyvals]{label}#*r
\GLSsymbolplural{label}[insert]#*r
\GLSsymbolplural[options%keyvals]{label}[insert]#*r
\glssymbolplural*{label}#Sr
\glssymbolplural*[options]{label}#Sr
\glssymbolplural*{label}[insert]#Sr
\glssymbolplural*[options]{label}[insert]#Sr
\Glssymbolplural*{label}#Sr
\Glssymbolplural*[options]{label}#Sr
\Glssymbolplural*{label}[insert]#Sr
\Glssymbolplural*[options]{label}[insert]#Sr
\GLSsymbolplural*{label}#Sr
\GLSsymbolplural*[options]{label}#Sr
\GLSsymbolplural*{label}[insert]#Sr
\GLSsymbolplural*[options]{label}[insert]#Sr
\glssymbolplural+{label}#Sr
\glssymbolplural+[options]{label}#Sr
\glssymbolplural+{label}[insert]#Sr
\glssymbolplural+[options]{label}[insert]#Sr
\Glssymbolplural+{label}#Sr
\Glssymbolplural+[options]{label}#Sr
\Glssymbolplural+{label}[insert]#Sr
\Glssymbolplural+[options]{label}[insert]#Sr
\GLSsymbolplural+{label}#Sr
\GLSsymbolplural+[options]{label}#Sr
\GLSsymbolplural+{label}[insert]#Sr
\GLSsymbolplural+[options]{label}[insert]#Sr

\glsdesc{label}#*r
\glsdesc[options%keyvals]{label}#*r
\glsdesc{label}[insert]#*r
\glsdesc[options%keyvals]{label}[insert]#*r
\Glsdesc{label}#*r
\Glsdesc[options%keyvals]{label}#*r
\Glsdesc{label}[insert]#*r
\Glsdesc[options%keyvals]{label}[insert]#*r
\GLSdesc{label}#*r
\GLSdesc[options%keyvals]{label}#*r
\GLSdesc{label}[insert]#*r
\GLSdesc[options%keyvals]{label}[insert]#*r
\glsdesc*{label}#Sr
\glsdesc*[options]{label}#Sr
\glsdesc*{label}[insert]#Sr
\glsdesc*[options]{label}[insert]#Sr
\Glsdesc*{label}#Sr
\Glsdesc*[options]{label}#Sr
\Glsdesc*{label}[insert]#Sr
\Glsdesc*[options]{label}[insert]#Sr
\GLSdesc*{label}#Sr
\GLSdesc*[options]{label}#Sr
\GLSdesc*{label}[insert]#Sr
\GLSdesc*[options]{label}[insert]#Sr
\glsdesc+{label}#Sr
\glsdesc+[options]{label}#Sr
\glsdesc+{label}[insert]#Sr
\glsdesc+[options]{label}[insert]#Sr
\Glsdesc+{label}#Sr
\Glsdesc+[options]{label}#Sr
\Glsdesc+{label}[insert]#Sr
\Glsdesc+[options]{label}[insert]#Sr
\GLSdesc+{label}#Sr
\GLSdesc+[options]{label}#Sr
\GLSdesc+{label}[insert]#Sr
\GLSdesc+[options]{label}[insert]#Sr

\glsdescplural{label}#*r
\glsdescplural[options%keyvals]{label}#*r
\glsdescplural{label}[insert]#*r
\glsdescplural[options%keyvals]{label}[insert]#*r
\Glsdescplural{label}#*r
\Glsdescplural[options%keyvals]{label}#*r
\Glsdescplural{label}[insert]#*r
\Glsdescplural[options%keyvals]{label}[insert]#*r
\GLSdescplural{label}#*r
\GLSdescplural[options%keyvals]{label}#*r
\GLSdescplural{label}[insert]#*r
\GLSdescplural[options%keyvals]{label}[insert]#*r
\glsdescplural*{label}#Sr
\glsdescplural*[options]{label}#Sr
\glsdescplural*{label}[insert]#Sr
\glsdescplural*[options]{label}[insert]#Sr
\Glsdescplural*{label}#Sr
\Glsdescplural*[options]{label}#Sr
\Glsdescplural*{label}[insert]#Sr
\Glsdescplural*[options]{label}[insert]#Sr
\GLSdescplural*{label}#Sr
\GLSdescplural*[options]{label}#Sr
\GLSdescplural*{label}[insert]#Sr
\GLSdescplural*[options]{label}[insert]#Sr
\glsdescplural+{label}#Sr
\glsdescplural+[options]{label}#Sr
\glsdescplural+{label}[insert]#Sr
\glsdescplural+[options]{label}[insert]#Sr
\Glsdescplural+{label}#Sr
\Glsdescplural+[options]{label}#Sr
\Glsdescplural+{label}[insert]#Sr
\Glsdescplural+[options]{label}[insert]#Sr
\GLSdescplural+{label}#Sr
\GLSdescplural+[options]{label}#Sr
\GLSdescplural+{label}[insert]#Sr
\GLSdescplural+[options]{label}[insert]#Sr

\glsuseri{label}#r
\glsuseri[options%keyvals]{label}#r
\glsuseri{label}[insert]#*r
\glsuseri[options%keyvals]{label}[insert]#*r
\Glsuseri{label}#r
\Glsuseri[options%keyvals]{label}#r
\Glsuseri{label}[insert]#*r
\Glsuseri[options%keyvals]{label}[insert]#*r
\GLSuseri{label}#r
\GLSuseri[options%keyvals]{label}#r
\GLSuseri{label}[insert]#*r
\GLSuseri[options%keyvals]{label}[insert]#*r
\glsuseri*{label}#Sr
\glsuseri*[options]{label}#Sr
\glsuseri*{label}[insert]#Sr
\glsuseri*[options]{label}[insert]#Sr
\Glsuseri*{label}#Sr
\Glsuseri*[options]{label}#Sr
\Glsuseri*{label}[insert]#Sr
\Glsuseri*[options]{label}[insert]#Sr
\GLSuseri*{label}#Sr
\GLSuseri*[options]{label}#Sr
\GLSuseri*{label}[insert]#Sr
\GLSuseri*[options]{label}[insert]#Sr
\glsuseri+{label}#Sr
\glsuseri+[options]{label}#Sr
\glsuseri+{label}[insert]#Sr
\glsuseri+[options]{label}[insert]#Sr
\Glsuseri+{label}#Sr
\Glsuseri+[options]{label}#Sr
\Glsuseri+{label}[insert]#Sr
\Glsuseri+[options]{label}[insert]#Sr
\GLSuseri+{label}#Sr
\GLSuseri+[options]{label}#Sr
\GLSuseri+{label}[insert]#Sr
\GLSuseri+[options]{label}[insert]#Sr

\glsuserii{label}#*r
\glsuserii[options%keyvals]{label}#*r
\glsuserii{label}[insert]#*r
\glsuserii[options%keyvals]{label}[insert]#*r
\Glsuserii{label}#*r
\Glsuserii[options%keyvals]{label}#*r
\Glsuserii{label}[insert]#*r
\Glsuserii[options%keyvals]{label}[insert]#*r
\GLSuserii{label}#*r
\GLSuserii[options%keyvals]{label}#*r
\GLSuserii{label}[insert]#*r
\GLSuserii[options%keyvals]{label}[insert]#*r
\glsuserii*{label}#Sr
\glsuserii*[options]{label}#Sr
\glsuserii*{label}[insert]#Sr
\glsuserii*[options]{label}[insert]#Sr
\Glsuserii*{label}#Sr
\Glsuserii*[options]{label}#Sr
\Glsuserii*{label}[insert]#Sr
\Glsuserii*[options]{label}[insert]#Sr
\GLSuserii*{label}#Sr
\GLSuserii*[options]{label}#Sr
\GLSuserii*{label}[insert]#Sr
\GLSuserii*[options]{label}[insert]#Sr
\glsuserii+{label}#Sr
\glsuserii+[options]{label}#Sr
\glsuserii+{label}[insert]#Sr
\glsuserii+[options]{label}[insert]#Sr
\Glsuserii+{label}#Sr
\Glsuserii+[options]{label}#Sr
\Glsuserii+{label}[insert]#Sr
\Glsuserii+[options]{label}[insert]#Sr
\GLSuserii+{label}#Sr
\GLSuserii+[options]{label}#Sr
\GLSuserii+{label}[insert]#Sr
\GLSuserii+[options]{label}[insert]#Sr

\glsuseriii{label}#*r
\glsuseriii[options%keyvals]{label}#*r
\glsuseriii{label}[insert]#*r
\glsuseriii[options%keyvals]{label}[insert]#*r
\Glsuseriii{label}#*r
\Glsuseriii[options%keyvals]{label}#*r
\Glsuseriii{label}[insert]#*r
\Glsuseriii[options%keyvals]{label}[insert]#*r
\GLSuseriii{label}#*r
\GLSuseriii[options%keyvals]{label}#*r
\GLSuseriii{label}[insert]#*r
\GLSuseriii[options%keyvals]{label}[insert]#*r
\glsuseriii*{label}#Sr
\glsuseriii*[options]{label}#Sr
\glsuseriii*{label}[insert]#Sr
\glsuseriii*[options]{label}[insert]#Sr
\Glsuseriii*{label}#Sr
\Glsuseriii*[options]{label}#Sr
\Glsuseriii*{label}[insert]#Sr
\Glsuseriii*[options]{label}[insert]#Sr
\GLSuseriii*{label}#Sr
\GLSuseriii*[options]{label}#Sr
\GLSuseriii*{label}[insert]#Sr
\GLSuseriii*[options]{label}[insert]#Sr
\glsuseriii+{label}#Sr
\glsuseriii+[options]{label}#Sr
\glsuseriii+{label}[insert]#Sr
\glsuseriii+[options]{label}[insert]#Sr
\Glsuseriii+{label}#Sr
\Glsuseriii+[options]{label}#Sr
\Glsuseriii+{label}[insert]#Sr
\Glsuseriii+[options]{label}[insert]#Sr
\GLSuseriii+{label}#Sr
\GLSuseriii+[options]{label}#Sr
\GLSuseriii+{label}[insert]#Sr
\GLSuseriii+[options]{label}[insert]#Sr

\glsuseriv{label}#*r
\glsuseriv[options%keyvals]{label}#*r
\glsuseriv{label}[insert]#*r
\glsuseriv[options%keyvals]{label}[insert]#*r
\Glsuseriv{label}#*r
\Glsuseriv[options%keyvals]{label}#*r
\Glsuseriv{label}[insert]#*r
\Glsuseriv[options%keyvals]{label}[insert]#*r
\GLSuseriv{label}#*r
\GLSuseriv[options%keyvals]{label}#*r
\GLSuseriv{label}[insert]#*r
\GLSuseriv[options%keyvals]{label}[insert]#*r
\glsuseriv*{label}#Sr
\glsuseriv*[options]{label}#Sr
\glsuseriv*{label}[insert]#Sr
\glsuseriv*[options]{label}[insert]#Sr
\Glsuseriv*{label}#Sr
\Glsuseriv*[options]{label}#Sr
\Glsuseriv*{label}[insert]#Sr
\Glsuseriv*[options]{label}[insert]#Sr
\GLSuseriv*{label}#Sr
\GLSuseriv*[options]{label}#Sr
\GLSuseriv*{label}[insert]#Sr
\GLSuseriv*[options]{label}[insert]#Sr
\glsuseriv+{label}#Sr
\glsuseriv+[options]{label}#Sr
\glsuseriv+{label}[insert]#Sr
\glsuseriv+[options]{label}[insert]#Sr
\Glsuseriv+{label}#Sr
\Glsuseriv+[options]{label}#Sr
\Glsuseriv+{label}[insert]#Sr
\Glsuseriv+[options]{label}[insert]#Sr
\GLSuseriv+{label}#Sr
\GLSuseriv+[options]{label}#Sr
\GLSuseriv+{label}[insert]#Sr
\GLSuseriv+[options]{label}[insert]#Sr

\glsuserv{label}#*r
\glsuserv[options%keyvals]{label}#*r
\glsuserv{label}[insert]#*r
\glsuserv[options%keyvals]{label}[insert]#*r
\Glsuserv{label}#*r
\Glsuserv[options%keyvals]{label}#*r
\Glsuserv{label}[insert]#*r
\Glsuserv[options%keyvals]{label}[insert]#*r
\GLSuserv{label}#*r
\GLSuserv[options%keyvals]{label}#*r
\GLSuserv{label}[insert]#*r
\GLSuserv[options%keyvals]{label}[insert]#*r
\glsuserv*{label}#Sr
\glsuserv*[options]{label}#Sr
\glsuserv*{label}[insert]#Sr
\glsuserv*[options]{label}[insert]#Sr
\Glsuserv*{label}#Sr
\Glsuserv*[options]{label}#Sr
\Glsuserv*{label}[insert]#Sr
\Glsuserv*[options]{label}[insert]#Sr
\GLSuserv*{label}#Sr
\GLSuserv*[options]{label}#Sr
\GLSuserv*{label}[insert]#Sr
\GLSuserv*[options]{label}[insert]#Sr
\glsuserv+{label}#Sr
\glsuserv+[options]{label}#Sr
\glsuserv+{label}[insert]#Sr
\glsuserv+[options]{label}[insert]#Sr
\Glsuserv+{label}#Sr
\Glsuserv+[options]{label}#Sr
\Glsuserv+{label}[insert]#Sr
\Glsuserv+[options]{label}[insert]#Sr
\GLSuserv+{label}#Sr
\GLSuserv+[options]{label}#Sr
\GLSuserv+{label}[insert]#Sr
\GLSuserv+[options]{label}[insert]#Sr

\glsuservi{label}#*r
\glsuservi[options%keyvals]{label}#*r
\glsuservi{label}[insert]#*r
\glsuservi[options%keyvals]{label}[insert]#*r
\Glsuservi{label}#*r
\Glsuservi[options%keyvals]{label}#*r
\Glsuservi{label}[insert]#*r
\Glsuservi[options%keyvals]{label}[insert]#*r
\GLSuservi{label}#*r
\GLSuservi[options%keyvals]{label}#*r
\GLSuservi{label}[insert]#*r
\GLSuservi[options%keyvals]{label}[insert]#*r
\glsuservi*{label}#Sr
\glsuservi*[options]{label}#Sr
\glsuservi*{label}[insert]#Sr
\glsuservi*[options]{label}[insert]#Sr
\Glsuservi*{label}#Sr
\Glsuservi*[options]{label}#Sr
\Glsuservi*{label}[insert]#Sr
\Glsuservi*[options]{label}[insert]#Sr
\GLSuservi*{label}#Sr
\GLSuservi*[options]{label}#Sr
\GLSuservi*{label}[insert]#Sr
\GLSuservi*[options]{label}[insert]#Sr
\glsuservi+{label}#Sr
\glsuservi+[options]{label}#Sr
\glsuservi+{label}[insert]#Sr
\glsuservi+[options]{label}[insert]#Sr
\Glsuservi+{label}#Sr
\Glsuservi+[options]{label}#Sr
\Glsuservi+{label}[insert]#Sr
\Glsuservi+[options]{label}[insert]#Sr
\GLSuservi+{label}#Sr
\GLSuservi+[options]{label}#Sr
\GLSuservi+{label}[insert]#Sr
\GLSuservi+[options]{label}[insert]#Sr

#keyvals:\gls#c,\Gls#c,\GLS#c,\glspl#c,\Glspl#c,\GLSpl#c,\glsdisp#c,\glslink#c,\glstext#c,\Glstext#c,\GLStext#c,\glsfirst#c,\Glsfirst#c,\GLSfirst#c,\glsplural#c,\Glsplural#c,\GLSplural#c,\glsfirstplural#c,\Glsfirstplural#c,\GLSfirstplural#c,\glsname#c,\Glsname#c,\GLSname#c,\glssymbol#c,\Glssymbol#c,\GLSsymbol#c,\glssymbolplural#c,\Glssymbolplural#c,\GLSsymbolplural#c,\glsdesc#c,\Glsdesc#c,\GLSdesc#c,\glsdescplural#c,\Glsdescplural#c,\GLSdescplural#c,\glsuseri#c,\Glsuseri#c,\GLSuseri#c,\glsuserii#c,\Glsuserii#c,\GLSuserii#c,\glsuseriii#c,\Glsuseriii#c,\GLSuseriii#c,\glsuseriv#c,\Glsuseriv#c,\GLSuseriv#c,\glsuserv#c,\Glsuserv#c,\GLSuserv#c,\glsuservi#c,\Glsuservi#c,\GLSuservi#c,\cgls#c,\cGls#c,\cglspl#c,\cGlspl#c
hyper#true,false
format=%<csname%>
counter=%<counter%>
local#true,false
#endkeyvals

\hyperrm{arg}#*
\hypersf{arg}#*
\hypertt{arg}#*
\hyperbf{arg}#*
\hypermd{arg}#*
\hyperit{arg}#*
\hypersl{arg}#*
\hyperup{arg}#*
\hypersc{arg}#*
\hyperemph{arg}#*

\glsentryfmt#*
\defglsentryfmt{definition}#*
\defglsentryfmt[type]{definition}#*
\glslabel#*
\glstype#*
\glscustomtext#*
\glsinsert#*
\glsifplural{true}{false}#*
\glscapscase{no case}{first uc}{all caps}#*
\glsifhyperon{hyper true}{hyper false}#*
\glslinkvar{unmodified}{star}{plus}#*
\glsgenentryfmt#*
\glsgenacfmt#*
\genacrfullformat{label}{insert}#*
\genplacrfullformat{label}{insert}#*
\Genacrfullformat{label}{insert}#*
\Genplacrfullformat{label}{insert}#*
\glslinkpostsetkeys#*
\glspostlinkhook#*
\glsdisablehyper#*
\glsenablehyper#*

## 5.2 Using Glossary Terms Without Links ##
\glsentrytitlecase{label}{field}#r
\glscapitalisewords{text}#*
\glsentryname{label}#r
\Glsentryname{label}#r
\glossentryname{label}#*r
\Glossentryname{label}#*r
\glsentrytext{label}#*r
\Glsentrytext{label}#*r
\glsentryplural{label}#*r
\Glsentryplural{label}#*r
\glsentryfirst{label}#*r
\Glsentryfirst{label}#*r
\glsentryfirstplural{label}#*r
\Glsentryfirstplural{label}#*r
\glsentrydesc{label}#*r
\Glsentrydesc{label}#*r
\glossentrydesc{label}#*r
\Glossentrydesc{label}#*r
\glsentrydescplural{label}#*r
\Glsentrydescplural{label}#*r
\glsentrysymbol{label}#*r
\Glsentrysymbol{label}#*r
\glsletentryfield{cmd}{label}{field}#*d
\glossentrysymbol{label}#*r
\Glossentrysymbol{label}#*r
\glsentrysymbolplural{label}#*r
\Glsentrysymbolplural{label}#*r
\glsentryuseri{label}#*r
\Glsentryuseri{label}#*r
\glsentryuserii{label}#*r
\Glsentryuserii{label}#*r
\glsentryuseriii{label}#*r
\Glsentryuseriii{label}#*r
\glsentryuseriv{label}#*r
\Glsentryuseriv{label}#*r
\glsentryuserv{label}#*r
\Glsentryuserv{label}#*r
\glsentryuservi{label}#*r
\Glsentryuservi{label}#*r

\glshyperlink{label}#r
\glshyperlink[link text]{label}#r

\glsentrynumberlist{label}#*r
\glsdisplaynumberlist{label}#*r
\glsnumlistsep#*
\glsnumlistlastsep#*

### 6 Acronyms and Other Abbreviations ###
\newacronym{label}{abbrv}{long}#l
\newacronym[options%keyvals]{label}{abbrv}{long}#l

#keyvals:\newacronym#c
long=
longplural=
short=
shortplural=
#endkeyvals

\glsacrpluralsuffix#*
\acrpluralsuffix#*

\acrshort{label}#r
\acrshort[options%keyvals]{label}#r
\acrshort{label}[insert]#*r
\acrshort[options%keyvals]{label}[insert]#*r
\acrshort*{label}#Sr
\acrshort*[options]{label}#Sr
\acrshort*{label}[insert]#Sr
\acrshort*[options]{label}[insert]#Sr
\acrshort+{label}#Sr
\acrshort+[options]{label}#Sr
\acrshort+{label}[insert]#Sr
\acrshort+[options]{label}[insert]#Sr

\Acrshort{label}#r
\Acrshort[options%keyvals]{label}#r
\Acrshort{label}[insert]#*r
\Acrshort[options%keyvals]{label}[insert]#*r
\Acrshort*{label}#Sr
\Acrshort*[options]{label}#Sr
\Acrshort*{label}[insert]#Sr
\Acrshort*[options]{label}[insert]#Sr
\Acrshort+{label}#Sr
\Acrshort+[options]{label}#Sr
\Acrshort+{label}[insert]#Sr
\Acrshort+[options]{label}[insert]#Sr

\ACRshort{label}#r
\ACRshort[options%keyvals]{label}#r
\ACRshort{label}[insert]#*r
\ACRshort[options%keyvals]{label}[insert]#*r
\ACRshort*{label}#Sr
\ACRshort*[options]{label}#Sr
\ACRshort*{label}[insert]#Sr
\ACRshort*[options]{label}[insert]#Sr
\ACRshort+{label}#Sr
\ACRshort+[options]{label}#Sr
\ACRshort+{label}[insert]#Sr
\ACRshort+[options]{label}[insert]#Sr

\acrshortpl{label}#*r
\acrshortpl[options%keyvals]{label}#*r
\acrshortpl{label}[insert]#*r
\acrshortpl[options%keyvals]{label}[insert]#*r
\acrshortpl*{label}#Sr
\acrshortpl*[options]{label}#Sr
\acrshortpl*{label}[insert]#Sr
\acrshortpl*[options]{label}[insert]#Sr
\acrshortpl+{label}#Sr
\acrshortpl+[options]{label}#Sr
\acrshortpl+{label}[insert]#Sr
\acrshortpl+[options]{label}[insert]#Sr

\Acrshortpl{label}#*r
\Acrshortpl[options%keyvals]{label}#*r
\Acrshortpl{label}[insert]#*r
\Acrshortpl[options%keyvals]{label}[insert]#*r
\Acrshortpl*{label}#Sr
\Acrshortpl*[options]{label}#Sr
\Acrshortpl*{label}[insert]#Sr
\Acrshortpl*[options]{label}[insert]#Sr
\Acrshortpl+{label}#Sr
\Acrshortpl+[options]{label}#Sr
\Acrshortpl+{label}[insert]#Sr
\Acrshortpl+[options]{label}[insert]#Sr

\ACRshortpl{label}#*r
\ACRshortpl[options%keyvals]{label}#*r
\ACRshortpl{label}[insert]#*r
\ACRshortpl[options%keyvals]{label}[insert]#*r
\ACRshortpl*{label}#Sr
\ACRshortpl*[options]{label}#Sr
\ACRshortpl*{label}[insert]#Sr
\ACRshortpl*[options]{label}[insert]#Sr
\ACRshortpl+{label}#Sr
\ACRshortpl+[options]{label}#Sr
\ACRshortpl+{label}[insert]#Sr
\ACRshortpl+[options]{label}[insert]#Sr

\acrlong{label}#r
\acrlong[options%keyvals]{label}#r
\acrlong{label}[insert]#*r
\acrlong[options%keyvals]{label}[insert]#*r
\acrlong*{label}#Sr
\acrlong*[options]{label}#Sr
\acrlong*{label}[insert]#Sr
\acrlong*[options]{label}[insert]#Sr
\acrlong+{label}#Sr
\acrlong+[options]{label}#Sr
\acrlong+{label}[insert]#Sr
\acrlong+[options]{label}[insert]#Sr

\Acrlong{label}#r
\Acrlong[options%keyvals]{label}#r
\Acrlong{label}[insert]#*r
\Acrlong[options%keyvals]{label}[insert]#*r
\Acrlong*{label}#Sr
\Acrlong*[options]{label}#Sr
\Acrlong*{label}[insert]#Sr
\Acrlong*[options]{label}[insert]#Sr
\Acrlong+{label}#Sr
\Acrlong+[options]{label}#Sr
\Acrlong+{label}[insert]#Sr
\Acrlong+[options]{label}[insert]#Sr

\ACRlong{label}#r
\ACRlong[options%keyvals]{label}#r
\ACRlong{label}[insert]#*r
\ACRlong[options%keyvals]{label}[insert]#*r
\ACRlong*{label}#Sr
\ACRlong*[options]{label}#Sr
\ACRlong*{label}[insert]#Sr
\ACRlong*[options]{label}[insert]#Sr
\ACRlong+{label}#Sr
\ACRlong+[options]{label}#Sr
\ACRlong+{label}[insert]#Sr
\ACRlong+[options]{label}[insert]#Sr

\acrlongpl{label}#*r
\acrlongpl[options%keyvals]{label}#*r
\acrlongpl{label}[insert]#*r
\acrlongpl[options%keyvals]{label}[insert]#*r
\acrlongpl*{label}#Sr
\acrlongpl*[options]{label}#Sr
\acrlongpl*{label}[insert]#Sr
\acrlongpl*[options]{label}[insert]#Sr
\acrlongpl+{label}#Sr
\acrlongpl+[options]{label}#Sr
\acrlongpl+{label}[insert]#Sr
\acrlongpl+[options]{label}[insert]#Sr

\Acrlongpl{label}#*r
\Acrlongpl[options%keyvals]{label}#*r
\Acrlongpl{label}[insert]#*r
\Acrlongpl[options%keyvals]{label}[insert]#*r
\Acrlongpl*{label}#Sr
\Acrlongpl*[options]{label}#Sr
\Acrlongpl*{label}[insert]#Sr
\Acrlongpl*[options]{label}[insert]#Sr
\Acrlongpl+{label}#Sr
\Acrlongpl+[options]{label}#Sr
\Acrlongpl+{label}[insert]#Sr
\Acrlongpl+[options]{label}[insert]#Sr

\ACRlongpl{label}#*r
\ACRlongpl[options%keyvals]{label}#*r
\ACRlongpl{label}[insert]#*r
\ACRlongpl[options%keyvals]{label}[insert]#*r
\ACRlongpl*{label}#Sr
\ACRlongpl*[options]{label}#Sr
\ACRlongpl*{label}[insert]#Sr
\ACRlongpl*[options]{label}[insert]#Sr
\ACRlongpl+{label}#Sr
\ACRlongpl+[options]{label}#Sr
\ACRlongpl+{label}[insert]#Sr
\ACRlongpl+[options]{label}[insert]#Sr

\acrfull{label}#r
\acrfull[options%keyvals]{label}#r
\acrfull{label}[insert]#*r
\acrfull[options%keyvals]{label}[insert]#*r
\acrfull*{label}#Sr
\acrfull*[options]{label}#Sr
\acrfull*{label}[insert]#Sr
\acrfull*[options]{label}[insert]#Sr
\acrfull+{label}#Sr
\acrfull+[options]{label}#Sr
\acrfull+{label}[insert]#Sr
\acrfull+[options]{label}[insert]#Sr

\Acrfull{label}#r
\Acrfull[options%keyvals]{label}#r
\Acrfull{label}[insert]#*r
\Acrfull[options%keyvals]{label}[insert]#*r
\Acrfull*{label}#Sr
\Acrfull*[options]{label}#Sr
\Acrfull*{label}[insert]#Sr
\Acrfull*[options]{label}[insert]#Sr
\Acrfull+{label}#Sr
\Acrfull+[options]{label}#Sr
\Acrfull+{label}[insert]#Sr
\Acrfull+[options]{label}[insert]#Sr

\ACRfull{label}#r
\ACRfull[options%keyvals]{label}#r
\ACRfull{label}[insert]#*r
\ACRfull[options%keyvals]{label}[insert]#*r
\ACRfull*{label}#Sr
\ACRfull*[options]{label}#Sr
\ACRfull*{label}[insert]#Sr
\ACRfull*[options]{label}[insert]#Sr
\ACRfull+{label}#Sr
\ACRfull+[options]{label}#Sr
\ACRfull+{label}[insert]#Sr
\ACRfull+[options]{label}[insert]#Sr

\acrfullpl{label}#*r
\acrfullpl[options%keyvals]{label}#*r
\acrfullpl{label}[insert]#*r
\acrfullpl[options%keyvals]{label}[insert]#*r
\acrfullpl*{label}#Sr
\acrfullpl*[options]{label}#Sr
\acrfullpl*{label}[insert]#Sr
\acrfullpl*[options]{label}[insert]#Sr
\acrfullpl+{label}#Sr
\acrfullpl+[options]{label}#Sr
\acrfullpl+{label}[insert]#Sr
\acrfullpl+[options]{label}[insert]#Sr

\Acrfullpl{label}#*r
\Acrfullpl[options%keyvals]{label}#*r
\Acrfullpl{label}[insert]#*r
\Acrfullpl[options%keyvals]{label}[insert]#*r
\Acrfullpl*{label}#Sr
\Acrfullpl*[options]{label}#Sr
\Acrfullpl*{label}[insert]#Sr
\Acrfullpl*[options]{label}[insert]#Sr
\Acrfullpl+{label}#Sr
\Acrfullpl+[options]{label}#Sr
\Acrfullpl+{label}[insert]#Sr
\Acrfullpl+[options]{label}[insert]#Sr

\ACRfullpl{label}#*r
\ACRfullpl[options%keyvals]{label}#*r
\ACRfullpl{label}[insert]#*r
\ACRfullpl[options%keyvals]{label}[insert]#*r
\ACRfullpl*{label}#Sr
\ACRfullpl*[options]{label}#Sr
\ACRfullpl*{label}[insert]#Sr
\ACRfullpl*[options]{label}[insert]#Sr
\ACRfullpl+{label}#Sr
\ACRfullpl+[options]{label}#Sr
\ACRfullpl+{label}[insert]#Sr
\ACRfullpl+[options]{label}[insert]#Sr

\acrfullfmt{options%keyvals}{label}{insert}#*r
\ACRfullfmt{options%keyvals}{label}{insert}#*r
\Acrfullfmt{options%keyvals}{label}{insert}#*r
\ACRfullplfmt{options%keyvals}{label}{insert}#*r
\Acrfullplfmt{options%keyvals}{label}{insert}#*r
\acrfullplfmt{options%keyvals}{label}{insert}#*r

#keyvals:\acrshort#c,\Acrshort#c,\acrshortpl#c,\Acrshortpl#c, \acrlong#c,\Acrlong#c,\acrlongpl#c,\Acrlongpl#c,\acrfull#c,\Acrfull#c,\acrfullpl#c,\Acrfullpl#c,\acs#c,\Acs#c,\acsp#c,\Acsp#c,\acl#c,\Acl#c,\aclp#c,\Aclp#c,\acf#c,\Acf#c,\acfp#c,\Acfp#c,\ac#c,\Ac#c,\acp#c,\Acp#c,\acrfullfmt#c,\ACRfullfmt#c,\Acrfullfmt#c,\ACRfullplfmt#c,\Acrfullplfmt#c,\acrfullplfmt#c
hyper#true,false
format=%<csname%>
counter=%<counter%>
local#true,false
#endkeyvals

#ifOption:shortcuts
\acs{label}#r
\acs[options%keyvals]{label}#r
\acs{label}[insert]#*r
\acs[options%keyvals]{label}[insert]#*r
\acs*{label}#Sr
\acs*[options]{label}#Sr
\acs*{label}[insert]#Sr
\acs*[options]{label}[insert]#Sr
\acs+{label}#Sr
\acs+[options]{label}#Sr
\acs+{label}[insert]#Sr
\acs+[options]{label}[insert]#Sr

\Acs{label}#r
\Acs[options%keyvals]{label}#r
\Acs{label}[insert]#*r
\Acs[options%keyvals]{label}[insert]#*r
\Acs*{label}#Sr
\Acs*[options]{label}#Sr
\Acs*{label}[insert]#Sr
\Acs*[options]{label}[insert]#Sr
\Acs+{label}#Sr
\Acs+[options]{label}#Sr
\Acs+{label}[insert]#Sr
\Acs+[options]{label}[insert]#Sr

\acsp{label}#*r
\acsp[options%keyvals]{label}#*r
\acsp{label}[insert]#*r
\acsp[options%keyvals]{label}[insert]#*r
\acsp*{label}#Sr
\acsp*[options]{label}#Sr
\acsp*{label}[insert]#Sr
\acsp*[options]{label}[insert]#Sr
\acsp+{label}#Sr
\acsp+[options]{label}#Sr
\acsp+{label}[insert]#Sr
\acsp+[options]{label}[insert]#Sr

\Acsp{label}#*r
\Acsp[options%keyvals]{label}#*r
\Acsp{label}[insert]#*r
\Acsp[options%keyvals]{label}[insert]#*r
\Acsp*{label}#Sr
\Acsp*[options]{label}#Sr
\Acsp*{label}[insert]#Sr
\Acsp*[options]{label}[insert]#Sr
\Acsp+{label}#Sr
\Acsp+[options]{label}#Sr
\Acsp+{label}[insert]#Sr
\Acsp+[options]{label}[insert]#Sr

\acl{label}#r
\acl[options%keyvals]{label}#r
\acl{label}[insert]#*r
\acl[options%keyvals]{label}[insert]#*r
\acl*{label}#Sr
\acl*[options]{label}#Sr
\acl*{label}[insert]#Sr
\acl*[options]{label}[insert]#Sr
\acl+{label}#Sr
\acl+[options]{label}#Sr
\acl+{label}[insert]#Sr
\acl+[options]{label}[insert]#Sr

\Acl{label}#r
\Acl[options%keyvals]{label}#r
\Acl{label}[insert]#*r
\Acl[options%keyvals]{label}[insert]#*r
\Acl*{label}#Sr
\Acl*[options]{label}#Sr
\Acl*{label}[insert]#Sr
\Acl*[options]{label}[insert]#Sr
\Acl+{label}#Sr
\Acl+[options]{label}#Sr
\Acl+{label}[insert]#Sr
\Acl+[options]{label}[insert]#Sr

\aclp{label}#*r
\aclp[options%keyvals]{label}#*r
\aclp{label}[insert]#*r
\aclp[options%keyvals]{label}[insert]#*r
\aclp*{label}#Sr
\aclp*[options]{label}#Sr
\aclp*{label}[insert]#Sr
\aclp*[options]{label}[insert]#Sr
\aclp+{label}#Sr
\aclp+[options]{label}#Sr
\aclp+{label}[insert]#Sr
\aclp+[options]{label}[insert]#Sr

\Aclp{label}#*r
\Aclp[options%keyvals]{label}#*r
\Aclp{label}[insert]#*r
\Aclp[options%keyvals]{label}[insert]#*r
\Aclp*{label}#Sr
\Aclp*[options]{label}#Sr
\Aclp*{label}[insert]#Sr
\Aclp*[options]{label}[insert]#Sr
\Aclp+{label}#Sr
\Aclp+[options]{label}#Sr
\Aclp+{label}[insert]#Sr
\Aclp+[options]{label}[insert]#Sr

\acf{label}#r
\acf[options%keyvals]{label}#r
\acf{label}[insert]#*r
\acf[options%keyvals]{label}[insert]#*r
\acf*{label}#Sr
\acf*[options]{label}#Sr
\acf*{label}[insert]#Sr
\acf*[options]{label}[insert]#Sr
\acf+{label}#Sr
\acf+[options]{label}#Sr
\acf+{label}[insert]#Sr
\acf+[options]{label}[insert]#Sr

\Acf{label}#r
\Acf[options%keyvals]{label}#r
\Acf{label}[insert]#*r
\Acf[options%keyvals]{label}[insert]#*r
\Acf*{label}#Sr
\Acf*[options]{label}#Sr
\Acf*{label}[insert]#Sr
\Acf*[options]{label}[insert]#Sr
\Acf+{label}#Sr
\Acf+[options]{label}#Sr
\Acf+{label}[insert]#Sr
\Acf+[options]{label}[insert]#Sr

\acfp{label}#*r
\acfp[options%keyvals]{label}#*r
\acfp{label}[insert]#*r
\acfp[options%keyvals]{label}[insert]#*r
\acfp*{label}#Sr
\acfp*[options]{label}#Sr
\acfp*{label}[insert]#Sr
\acfp*[options]{label}[insert]#Sr
\acfp+{label}#Sr
\acfp+[options]{label}#Sr
\acfp+{label}[insert]#Sr
\acfp+[options]{label}[insert]#Sr

\Acfp{label}#*r
\Acfp[options%keyvals]{label}#*r
\Acfp{label}[insert]#*r
\Acfp[options%keyvals]{label}[insert]#*r
\Acfp*{label}#Sr
\Acfp*[options]{label}#Sr
\Acfp*{label}[insert]#Sr
\Acfp*[options]{label}[insert]#Sr
\Acfp+{label}#Sr
\Acfp+[options]{label}#Sr
\Acfp+{label}[insert]#Sr
\Acfp+[options]{label}[insert]#Sr

\ac{label}#r
\ac[options%keyvals]{label}#r
\ac{label}[insert]#*r
\ac[options%keyvals]{label}[insert]#*r
\Ac{label}#r
\Ac[options%keyvals]{label}#r
\Ac{label}[insert]#*r
\Ac[options%keyvals]{label}[insert]#*r
\ac*{label}#Sr
\ac*[options]{label}#Sr
\ac*{label}[insert]#Sr
\ac*[options]{label}[insert]#Sr
\Ac*{label}#Sr
\Ac*[options]{label}#Sr
\Ac*{label}[insert]#Sr
\Ac*[options]{label}[insert]#Sr
\ac+{label}#Sr
\ac+[options]{label}#Sr
\ac+{label}[insert]#Sr
\ac+[options]{label}[insert]#Sr
\Ac+{label}#Sr
\Ac+[options]{label}#Sr
\Ac+{label}[insert]#Sr
\Ac+[options]{label}[insert]#Sr

\acp{label}#r
\acp[options%keyvals]{label}#r
\acp{label}[insert]#*r
\acp[options%keyvals]{label}[insert]#*r
\Acp{label}#r
\Acp[options%keyvals]{label}#r
\Acp{label}[insert]#*r
\Acp[options%keyvals]{label}[insert]#*r
\acp*{label}#Sr
\acp*[options]{label}#Sr
\acp*{label}[insert]#Sr
\acp*[options]{label}[insert]#Sr
\Acp*{label}#Sr
\Acp*[options]{label}#Sr
\Acp*{label}[insert]#Sr
\Acp*[options]{label}[insert]#Sr
\acp+{label}#Sr
\acp+[options]{label}#Sr
\acp+{label}[insert]#Sr
\acp+[options]{label}[insert]#Sr
\Acp+{label}#Sr
\Acp+[options]{label}#Sr
\Acp+{label}[insert]#Sr
\Acp+[options]{label}[insert]#Sr
#endif

\glsentrylong{label}#*r
\Glsentrylong{label}#*r
\glsentrylongpl{label}#*r
\Glsentrylongpl{label}#*r
\glsentryshort{label}#*r
\Glsentryshort{label}#*r
\glsentryshortpl{label}#*r
\Glsentryshortpl{label}#*r
\glsentryfull{label}#*r
\Glsentryfull{label}#*r
\glsentryfullpl{label}#*r
\Glsentryfullpl{label}#*r

## 6.2 Changing the Acronym Style ##
\setacronymstyle{style name%keyvals}
#keyvals:\setacronymstyle#c
long-short
long-sc-short
long-sm-short
long-sp-short
short-long
sc-short-long
sm-short-long
long-short-desc
long-sc-short-desc
long-sm-short-desc
long-sp-short-desc
short-long-desc
sc-short-long-desc
sm-short-long-desc
dua
dua-desc
footnote
footnote-sc
footnote-sm
footnote-desc
footnote-sc-desc
footnote-sm-desc
#endkeyvals
\acronymentry{label}#*r
\acronymsort{short}{long}#*
\acrnameformat{short}{long}#*
\firstacronymfont{text}#*
\acronymfont{text}#*
\textsmaller{text}#*
\glsacspace{label}#*
\newacronymstyle{style name}{display}{definitions}#*
\renewacronymstyle{style name}{display}{definitions}#*
\GenericAcronymFields#*
\GlsUseAcrEntryDispStyle{style name}#*
\GlsUseAcrStyleDefs{style name}#*
\glslabeltok#*
\glslongtok#*
\glsshorttok#*

## 6.4 Upgrading From the glossary Package ##
\oldacronym{abbrv}{long}{keyvals}#*
\oldacronym[label]{abbrv}{long}{keyvals}#*

### 7 Unsetting and Resetting Entry Flags ###
\glsreset{label}#*r
\glslocalreset{label}#*r
\glsunset{label}#*r
\glslocalunset{label}#*r
\glsresetall#*
\glsresetall[glossary list]#*
\glslocalresetall#*
\glslocalresetall[glossary list]#*
\glsunsetall#*
\glsunsetall[glossary list]#*
\glslocalunsetall#*
\glslocalunsetall[glossary list]#*
\ifglsused{label}{true}{false}#*

## 7.1 Counting the Number of Times an Entry has been Used (First Use Flag Unset) ##
\glsenableentrycount#*
\glsentrycurrcount{label}#*r
\glsentryprevcount{label}#*r

\cgls{label}#*r
\cgls[options%keyvals]{label}#*r
\cgls{label}[insert]#*r
\cgls[options%keyvals]{label}[insert]#*r
\cGls{label}#*r
\cGls[options%keyvals]{label}#*r
\cGls{label}[insert]#*r
\cGls[options%keyvals]{label}[insert]#*r
\cgls*{label}#Sr
\cgls*[options]{label}#Sr
\cgls*{label}[insert]#Sr
\cgls*[options]{label}[insert]#Sr
\cGls*{label}#Sr
\cGls*[options]{label}#Sr
\cGls*{label}[insert]#Sr
\cGls*[options]{label}[insert]#Sr
\cgls+{label}#Sr
\cgls+[options]{label}#Sr
\cgls+{label}[insert]#Sr
\cgls+[options]{label}[insert]#Sr
\cGls+{label}#Sr
\cGls+[options]{label}#Sr
\cGls+{label}[insert]#Sr
\cGls+[options]{label}[insert]#Sr

\cglspl{label}#*r
\cglspl[options%keyvals]{label}#*r
\cglspl{label}[insert]#*r
\cglspl[options%keyvals]{label}[insert]#*r
\cGlspl{label}#*r
\cGlspl[options%keyvals]{label}#*r
\cGlspl{label}[insert]#*r
\cGlspl[options%keyvals]{label}[insert]#*r
\cglspl*{label}#Sr
\cglspl*[options]{label}#Sr
\cglspl*{label}[insert]#Sr
\cglspl*[options]{label}[insert]#Sr
\cGlspl*{label}#Sr
\cGlspl*[options]{label}#Sr
\cGlspl*{label}[insert]#Sr
\cGlspl*[options]{label}[insert]#Sr
\cglspl+{label}#Sr
\cglspl+[options]{label}#Sr
\cglspl+{label}[insert]#Sr
\cglspl+[options]{label}[insert]#Sr
\cGlspl+{label}#Sr
\cGlspl+[options]{label}#Sr
\cGlspl+{label}[insert]#Sr
\cGlspl+[options]{label}[insert]#Sr

\cglsformat{label}{insert}#*r
\cglsplformat{label}{insert}#*r
\cGlsformat{label}{insert}#*r
\cGlsplformat{label}{insert}#*r

### 8 Displaying a Glossary ###
\printnoidxglossaries
\printglossaries

\printnoidxglossary
\printnoidxglossary[options%keyvals]
\printglossary
\printglossary[options%keyvals]

#keyvals:\printnoidxglossary#c,\printglossary#c,\printsymbols#c,\printnumbers#c,\printindex#c,\printacronyms#c
type=
title=
toctitle=
style=
numberedsection=#false,nolabel,autolabel
nonumberlist#true,false
nogroupskip#true,false
nopostdot#true,false
entrycounter#true,false
subentrycounter#true,false
sort=#word,letter,standard,use,def,nocase,case
#endkeyvals

\glsglossarymark{title%plain}#*
\glossarypreamble#*
\setglossarypreamble{preamble text}#*
\setglossarypreamble[type]{preamble text}#*
\glossarypostamble#*
\glsnamefont{name}#*
\glossarysection{text}#*
\glscurrententrylabel#*

## 9 Defining New Glossaries ##
\newglossary{name}{in-ext}{out-ext}{title%plain}
\newglossary[log-ext]{name}{in-ext}{out-ext}{title%plain}
\newglossary[log-ext]{name}{in-ext}{out-ext}{title%plain}[counter]#*
\newglossary*{name}{title%plain}#*
\newglossary*{name}{title%plain}[counter]#*
\altnewglossary{name}{tag}{title%plain}#*
\altnewglossary*{name}{tag}{title%plain}[counter]#*
\newignoredglossary{name}#*
\ifignoredglossary{name}{true}{false}#*

## 10 Adding an Entry to the Glossary Without Generating Text ##
\glsadd{label}#r
\glsadd[options%keyvals]{label}#r
\glsaddall
\glsaddall[options%keyvals]
#keyvals:\glsadd#c,\glsaddall#c
format=%<csname%>
counter=%<counter%>
local#true,false
#endkeyvals
#keyvals:\glsaddall#c
types=
#endkeyvals
\glsaddallunused
\glsaddallunused[list]

## 11 Cross-Referencing Entries ##
\glssee{label}{xr label list}#r
\glssee[tag]{label}{xr label list}#r
\glsseeformat{label list}{location}#*
\glsseeformat[tag]{label list}{location}#*
\glsseesep#*
\glsseelastsep#*
\glsseeitemformat{label}#*r
\glsseelist{list}#*

## 12 Number Lists ##
\glsnumberformat{text}#*
\glshypernumber{text}#*
\glsignore{text}#*
\glsaddprotectedpagefmt{internal cs name}#*
\glswrallowprimitivemodsfalse#*
\glsSetSuffixF{suffix}#*
\glsSetSuffixFF{suffix}#*
\glsnumberlistloop{label}{handler cs}{xr handler cs}#*
\glsnoidxdisplayloc{prefix}{counter}{format}{location}#*
\GlsSetWriteIstHook{code}#*
\glswrite{style information}#*

## 13 Glossary Styles ##
\setglossarystyle{style name%keyvals}
#keyvals:\setglossarystyle#c
list
listgroup
altlist
altlistgroup
altlisthypergroup
listdotted
sublistdotted
index
indexgroup
indexhypergroup
tree
treegroup
treehypergroup
treenoname
treenonamegroup
treenonamehypergroup
alttree
alttreegroup
alttreehypergroup
mcolindex
mcolindexgroup
mcolindexhypergroup
mcolindexspannav
mcoltree
mcoltreegroup
mcoltreehypergroup
mcoltreespannav
mcoltreenoname
mcoltreenonamegroup
mcoltreenonamehypergroup
mcoltreenonamespannav
mcolalttree
mcolalttreegroup
mcolalttreehypergroup
mcolalttreespannav
long
longborder
longheader
longheaderborder
long3col
long3colborder
long3colheader
long3colheaderborder
long4col
long4colborder
long4colheader
long4colheaderborder
altlong4col
altlong4colborder
altlong4colheader
altlong4colheaderborder
longragged
longraggedborder
longraggedheader
longraggedheaderborder
longragged3col
longragged3colborder
longragged3colheader
longragged3colheaderborder
altlongragged4col
altlongragged4colborder
altlongragged4colheader
altlongragged4colheaderborder
long-booktabs
long3col-booktabs
long4col-booktabs
altlong4col-booktabs
longragged-booktabs
longragged3col-booktabs
altlongragged4col-booktabs
super
superborder
superheader
superheaderborder
super3col
super3colborder
super3colheader
super3colheaderborder
super4col
super4colborder
super4colheader
super4colheaderborder
altsuper4col
altsuper4colborder
altsuper4colheader
altsuper4colheaderborder
superragged
superraggedborder
superraggedheader
superraggedheaderborder
superragged3col
superragged3colborder
superragged3colheader
superragged3colheaderborder
altsuperragged4col
altsuperragged4colborder
altsuperragged4colheader
altsuperragged4colheaderborder
inline
#endkeyvals

\newglossarystyle{name}{definitions}#*
\renewglossarystyle{name}{definitions}#*
\begin{theglossary}#*
\end{theglossary}#*
\glossaryheader#*
\glsgroupheading{label}#*
\glsgetgrouptitle{label}#*
\glsgetgrouplabel{title%plain}
\glsgroupskip#*
\glossentry{label}{number list}#*r
\glsentryitem{label}#*r
\glsentrycounterlabel#*
\glstarget{label}{text}#*r
\glolinkprefix#*
\glossaryentrynumbers{code}#*
\delimN#*
\delimR#*
\setentrycounter{counter}{format cmd}{numbers}#*
\setentrycounter[Hprefix]{counter}{format cmd}{numbers}#*
\subglossentry{level}{label}{number list}#*r
\glssubentryitem{label}#*r
\glssubentrycounterlabel#*
\currentglossary#*

## 14 Xindy ##
\glsopenbrace#*
\glsclosebrace#*
\glspercentchar#*
\glstildechar#*
\glsbackslash#*
\glsquote{text}#*

#ifOption:xindy
\GlsSetXdyLanguage{language}
\GlsSetXdyLanguage[glossary type]{language}
\GlsSetXdyCodePage{code}
\GlsAddXdyCounters{counter list}
\GlsAddXdyAttribute{name}
\GlsAddXdyLocation{name}{definition}
\GlsAddXdyLocation[prefix-location]{name}{definition}
\GlsSetXdyLocationClassOrder{location names}
\GlsSetXdyMinRangeLength{integer}
\GlsSetXdyFirstLetterAfterDigits{letter}
\GlsSetXdyNumberGroupOrder{relative location}
\GlsAddLetterGroup{arg1}{arg2}
\GlsAddSortRule{arg1}{arg2}
\GlsAddXdyAlphabet{name}{definition}
\GlsAddXdyStyle{xindy style}
\GlsSetXdyStyles{xindy styles}
#endif

## 15 Utilities ##
\forallglossaries{cmd}{body}#*
\forallglossaries[glossary list]{cmd}{body}#*
\forallacronyms{cmd}{body}#*
\forglsentries{cmd}{body}#*
\forglsentries[glossary label]{cmd}{body}#*
\forallglsentries{cmd}{body}#*
\forallglsentries[glossary list]{cmd}{body}#*

\ifglossaryexists{label}{true}{false}#*
\ifglsentryexists{label}{true}{false}#*
\glsdoifexists{label}{code}#*
\glsdoifnoexists{label}{code}#*
\glsdoifexistsorwarn{label}{code}#*
\glsdoifexistsordo{label}{code}#*
\glsdoifnoexistsordo{label}{code}#*
\doifglossarynoexistsordo{label}{true}{false}#*
\ifglshaschildren{label}{true}{false}#*r
\ifglshasparent{label}{true}{false}#*r
\ifglshassymbol{label}{true}{false}#*r
\ifglshaslong{label}{true}{false}#*r
\ifglshasshort{label}{true}{false}#*r
\ifglshasdesc{label}{true}{false}#*r
\ifglsdescsuppressed{label}{true}{false}#*r
\ifglshasfield{field}{label}{true}{false}#*r
\glscurrentfieldvalue#*
\ifglsfieldeq{label}{field}{string}{true}{false}#*r
\ifglsfielddefeq{label}{field}{cmd}{true}{false}#*r
\ifglsfieldcseq{label}{field}{csname}{true}{false}#*r

\glsentrytype{label}#*r
\glsentryparent{label}#*r
\glsentrysort{label}#*r
\glsfieldfetch{label}{field}{cmd}#*d
\glsunexpandedfieldvalue{label}{field}#*r
\glsfielddef{label}{field}{definition}#*r
\glsfieldedef{label}{field}{definition}#*r
\glsfieldgdef{label}{field}{definition}#*r
\glsfieldxdef{label}{field}{definition}#*r

## not in main documentation ##
\acrfootnote{options}{label}{link text}#*r
\acrlinkfootnote{options}{label}{link text}#*r
\acrnolinkfootnote{options}{label}{link text}#*
\addglossarytocaptions{arg}#*
\compatibleglossentry{label}{page list}#*r
\compatiblesubglossentry{level}{label}{page list}#*r
\currentglssubentry#*
\CustomAcronymFields#*
\CustomNewAcronymDef#*
\DefaultNewAcronymDef#*
\DescriptionDUANewAcronymDef#*
\DescriptionFootnoteNewAcronymDef#*
\DescriptionNewAcronymDef#*
\DUANewAcronymDef#*
\findrootlanguage#*
\FootnoteNewAcronymDef#*
\glosortentrieswarning
\GlossariesWarning{warning}#*
\GlossariesWarningNoLine{warning}#*
\glossarytitle#*
\glossarytoctitle#*
\glsacronymtrue#*
\glsacrshortcutsfalse#*
\glsacrshortcutstrue#*
\glsautomakefalse#*
\glsautomaketrue#*
\glscompositor#*
\glscounter#*
\glsdefmain#*
\glsdetoklabel{arg}#*
\glsdohyperlink{target}{link text}#*
\glsdohypertarget{target}{anchor text}#*
\glsdonohyperlink{target}{link text}#*
\glsdoparenifnotempty{arg}{cmd}#*
\glsentrycounter#*
\glsentrycounterfalse#*
\glsentrycountertrue#*
\glsesclocationsfalse#*
\glsesclocationstrue#*
\glshyperfirstfalse#*
\glshyperfirsttrue#*
\glsifusedtranslatordict{dict}{true}{false}#*
\glsindexonlyfirstfalse#*
\glskeylisttok#*
\glslongkey#*
\glslongpluralkey#*
\glsnextpages#*
\glsnogroupskipfalse#*
\glsnoidxdisplayloclisthandler{arg}#*
\glsnoidxloclist{list cmd}#*
\glsnoidxloclisthandler{arg}#*
\glsnoidxnumberlistloophandler{arg}#*
\glsnoidxstripaccents#*
\glsnomakeindexwarning{cmd}#*
\glsnonextpages#*
\ifglsnopostdotfalse#*
\glsnopostdotfalse#*
\glsnopostdottrue#*
\ifglsnonumberlist#*
\glsnonumberlisttrue#*
\glsnonumberlistfalse#*
\glsnoxindywarning{cmd}#*
\glsnumlistparser#*
\glsorder#*
\glspostdescription#*
\glsresetentrylist#*
\glsresetsubentrycounter#*
\glssanitizesortfalse#*
\glssanitizesorttrue#*
\glssavenumberlistfalse#*
\glssavewritesfalse#*
\glsseeitem{label}#*r
\glssettoctitle{title%plain}#*
\glsshortkey#*
\glsshortpluralkey#*
\glsshowtargetsymbol#*
\glsspace#*
\glsstepentry{label}#*r
\glsstepsubentry{label}#*r
\glssubentrycounterfalse#*
\glstranslatefalse#*
\glstranslatetrue#*
\glsucmarkfalse#*
\glsucmarktrue#*
\glsupacrpluralsuffix#*
\glswrallowprimitivemodstrue#*
\glswritedefhook#*
\glswritefiles#*
\glsxindyfalse#*
\glsxindytrue#*
\IeC#*
\ifglsacrdescription#*
\ifglsacrdua#*
\ifglsacrfootnote#*
\ifglsacronym#*
\ifglsacrshortcuts#*
\ifglsacrsmallcaps#*
\ifglsacrsmaller#*
\ifglsautomake#*
\ifglsentrycounter#*
\ifglsesclocations#*
\ifglshyperfirst#*
\ifglsindexonlyfirst#*
\ifglsnogroupskip#*
\ifglsnonumberlist#*
\ifglsnopostdot#*
\ifglsnumberline#*
\ifglssanitizesort#*
\ifglssavenumberlist#*
\ifglssavewrites#*
\ifglssubentrycounter#*
\ifglstoc#*
\ifglstranslate#*
\ifglswrallowprimitivemods#*
\ifglsxindy#*
\istfilename#*
\languagename#*
\newacronymhook#*
\ProvidesGlossariesLang{language}#*
\RequireGlossariesLang{language}#*
\SetAcronymStyle#*
\SetCustomDisplayStyle#*
\SetCustomStyle#*
\SetDefaultAcronymDisplayStyle#*
\SetDefaultAcronymStyle#*
\SetDescriptionAcronymDisplayStyle#*
\SetDescriptionAcronymStyle#*
\SetDescriptionDUAAcronymDisplayStyle#*
\SetDescriptionDUAAcronymStyle#*
\SetDescriptionFootnoteAcronymDisplayStyle#*
\SetDescriptionFootnoteAcronymStyle#*
\SetDUADisplayStyle#*
\SetDUAStyle#*
\SetFootnoteAcronymDisplayStyle#*
\SetFootnoteAcronymStyle#*
\SetGenericNewAcronym#*
\setglossentrycompatibility#*
\SetSmallAcronymDisplayStyle#*
\SetSmallAcronymStyle#*
\showacronymlists#*
\showglocounter{label}#*r
\showglodesc{label}#*r
\showglodescplural{label}#*r
\showglofield{label}{field}#*r
\showglofirst{label}#*r
\showglofirstpl{label}#*r
\showgloflag{label}#*r
\showgloindex{label}#*r
\showglolevel{label}#*r
\showgloloclist{label}#*r
\showglolong{label}#*r
\showgloname{label}#*r
\showgloparent{label}#*r
\showgloplural{label}#*r
\showgloshort{label}#*r
\showglosort{label}#*r
\showglossaries#*
\showglossarycounter{glossary label}#*
\showglossaryentries{glossary label}#*
\showglossaryin{glossary label}#*
\showglossaryout{glossary label}#*
\showglossarytitle{glossary label}#*
\showglosymbol{label}#*r
\showglosymbolplural{label}#*r
\showglotext{label}#*r
\showglotype{label}#*r
\showglouseri{label}#*r
\showglouserii{label}#*r
\showglouseriii{label}#*r
\showglouseriv{label}#*r
\showglouserv{label}#*r
\showglouservi{label}#*r
\SmallNewAcronymDef#*
\theglossary#*
\theglsentrycounter#*
\theH#*
\theHglossaryentry#*
\theHglossarysubentry#*
\theHglsentrycounter#*
\writeist#*

## deprecated ##
\acrfullformat#S
\acrlinkfullformat#S
\defglsdisplay#S
\defglsdisplayfirst#S
\glossaryentryfield#S
\glossarymark#S
\glossarystyle{style}#S
\glossarysubentryfield#S
\glsdisplay#S
\glsdisplayfirst#S
\glsifhyper#S
\istfile#S
