# glossaries-extra-bib2gls package
# Matthew Bertucci 11/27/2021 for v1.48

\glsxtrmultientryadjustedname{sublist1}{name}{sublist2}{label}#*r
\Glsxtrmultientryadjustedname{sublist1}{name}{sublist2}{label}#*r
\GlsXtrmultientryadjustedname{sublist1}{name}{sublist2}{label}#*r
\GLSxtrmultientryadjustedname{sublist1}{name}{sublist2}{label}#*r
\glsxtrmultientryadjustednamesep{pre label}{post label}#*
\glsxtrmultientryadjustednamepresep{pre label}{post label}#*
\glsxtrmultientryadjustednamepostsep{pre label}{post label}#*
\glsxtrmultientryadjustednamefmt{text}#*
\Glsxtrmultientryadjustednamefmt{text}#*
\GlsXtrmultientryadjustednamefmt{text}#*
\GLSxtrmultientryadjustednamefmt{text}#*
\glsxtrmultientryadjustednameother{label}#*r
\Glsxtrmultientryadjustednameother{label}#*r
\GlsXtrmultientryadjustednameother{label}#*r
\GLSxtrmultientryadjustednameother{label}#*r
\glsxtrprovidecommand{cmd}{definition}#*d
\glsxtrprovidecommand{cmd}[args]{definition}#*d
\glsxtrprovidecommand{cmd}[args][default]{definition}#*d
\glsrenewcommand{cmd}{definition}#*d
\glsrenewcommand{cmd}[args]{definition}#*d
\glsrenewcommand{cmd}[args][default]{definition}#*d
\GlsXtrIndexCounterLink{text}{label}#*
\GlsXtrDualField#*
\glsxtrSetWidest{type}{level}{text}#*
\glsxtrSetWidestFallback{max depth}{list}#*
\glsxtrdisplaysupploc{prefix}{counter}{format}{src}{location}#*
\glsxtrmultisupplocation{location}{src}{format}#*
\glsxtrdisplaylocnameref{prefix}{counter}{format}{location}{title%text}{href}{hcounter}{file}#*
\glsxtrnamereflink{format}{title%text}{target}{file}#*
\glsxtrfmtinternalnameref{target}{format}{title%text}#*
\glsxtrfmtexternalnameref{target}{format}{title%text}{file}#*
\glsxtrnameloclink{prefix}{counter}{format}{location}{title%text}{file}#*
\glshex#*
\glscapturedgroup#*
\GlsXtrIfHasNonZeroChildCount{label}{true}{false}#*r
\GlsXtrBibTeXEntryAliases#*
\GlsXtrProvideBibTeXFields#*
\glsxtrcontrolrules#*
\glsxtrspacerules#*
\glsxtrnonprintablerules#*
\glsxtrcombiningdiacriticrules#*
\glsxtrcombiningdiacriticIrules#*
\glsxtrcombiningdiacriticIIrules#*
\glsxtrcombiningdiacriticIIIrules#*
\glsxtrcombiningdiacriticIVrules#*
\glsxtrhyphenrules#*
\glsxtrgeneralpuncrules#*
\glsxtrgeneralpuncIrules#*
\glsxtrcurrencyrules#*
\glsxtrgeneralpuncIIrules#*
\glsxtrdigitrules#*
\glsxtrBasicDigitrules#*
\glsxtrSubScriptDigitrules#*
\glsxtrSuperScriptDigitrules#*
\glsxtrfractionrules#*
\glsxtrGeneralLatinIrules#*
\glsxtrGeneralLatinIIrules#*
\glsxtrGeneralLatinIIIrules#*
\glsxtrGeneralLatinIVrules#*
\glsxtrGeneralLatinVrules#*
\glsxtrGeneralLatinVIrules#*
\glsxtrGeneralLatinVIIrules#*
\glsxtrGeneralLatinVIIIrules#*
\glsxtrLatinA#*
\glsxtrLatinE#*
\glsxtrLatinH#*
\glsxtrLatinK#*
\glsxtrLatinI#*
\glsxtrLatinL#*
\glsxtrLatinM#*
\glsxtrLatinN#*
\glsxtrLatinO#*
\glsxtrLatinP#*
\glsxtrLatinS#*
\glsxtrLatinT#*
\glsxtrLatinX#*
\glsxtrLatinEszettSs#*
\glsxtrLatinEszettSz#*
\glsxtrLatinEth#*
\glsxtrLatinThorn#*
\glsxtrLatinAELigature#*
\glsxtrLatinOELigature#*
\glsxtrLatinOslash#*
\glsxtrLatinLslash#*
\glsxtrLatinWynn#*
\glsxtrLatinInsularG#*
\glsxtrLatinSchwa#*
\glsxtrLatinAA#*
\glsxtrMathGreekIrules#*
\glsxtrMathGreekIIrules#*
\glsxtrMathUpGreekIrules#*
\glsxtrMathUpGreekIIrules#*
\glsxtrMathItalicGreekIrules#*
\glsxtrMathItalicGreekIIrules#*
\glsxtrMathItalicUpperGreekIrules#*
\glsxtrMathItalicUpperGreekIIrules#*
\glsxtrMathItalicLowerGreekIrules#*
\glsxtrMathItalicLowerGreekIIrules#*
\glsxtrMathItalicPartial#*
\glsxtrMathItalicNabla#*
\Alpha#*
\Beta#*
\Epsilon#*
\Zeta#*
\Eta#*
\Iota#*
\Kappa#*
\Mu#*
\Nu#*
\Omicron#*
\Rho#*
\Tau#*
\Chi#*
\Digamma#*
\omicron#*
\CurrentTrackedScript#*
\glsxtrMathItalicAlpha#*
\glsxtrMathItalicBeta#*
\glsxtrMathItalicChi#*
\glsxtrMathItalicDelta#*
\glsxtrMathItalicEpsilon#*
\glsxtrMathItalicEta#*
\glsxtrMathItalicGamma#*
\glsxtrMathItalicIota#*
\glsxtrMathItalicKappa#*
\glsxtrMathItalicLambda#*
\glsxtrMathItalicMu#*
\glsxtrMathItalicNu#*
\glsxtrMathItalicOmega#*
\glsxtrMathItalicOmicron#*
\glsxtrMathItalicPhi#*
\glsxtrMathItalicPi#*
\glsxtrMathItalicPsi#*
\glsxtrMathItalicRho#*
\glsxtrMathItalicSigma#*
\glsxtrMathItalicTau#*
\glsxtrMathItalicTheta#*
\glsxtrMathItalicUpsilon#*
\glsxtrMathItalicXi#*
\glsxtrMathItalicZeta#*
\glsxtrUpAlpha#*
\glsxtrUpBeta#*
\glsxtrUpChi#*
\glsxtrUpDelta#*
\glsxtrUpDigamma#*
\glsxtrUpEpsilon#*
\glsxtrUpEta#*
\glsxtrUpGamma#*
\glsxtrUpIota#*
\glsxtrUpKappa#*
\glsxtrUpLambda#*
\glsxtrUpMu#*
\glsxtrUpNu#*
\glsxtrUpOmega#*
\glsxtrUpOmicron#*
\glsxtrUpPhi#*
\glsxtrUpPi#*
\glsxtrUpPsi#*
\glsxtrUpRho#*
\glsxtrUpSigma#*
\glsxtrUpTau#*
\glsxtrUpTheta#*
\glsxtrUpUpsilon#*
\glsxtrUpXi#*
\glsxtrUpZeta#*