# halloweenmath package
# Matthew Bertucci 8/22/2021 for v0.11

\mathleftghost#m
\mathghost#m
\mathrightghost#m
\mathleftbat#m
\mathbat#m
\mathrightbat#m
\pumpkin#m
\skull#m
\mathwitch#m
\reversemathwitch#m
\mathwitch*#m
\reversemathwitch*#m
\bigpumpkin#m
\bigskull#m
\greatpumpkin#m
\mathcloud#m
\reversemathcloud#m
\leftbroom#m
\rightbroom#m
\hmleftpitchfork#m
\hmrightpitchfork#m

\xleftwitchonbroom[below]{above}#m
\xrightwitchonbroom[below]{above}#m
\xleftwitchonbroom*[below]{above}#m
\xrightwitchonbroom*[below]{above}#m
\xleftwitchonpitchfork[below]{above}#m
\xrightwitchonpitchfork[below]{above}#m
\xleftwitchonpitchfork*[below]{above}#m
\xrightwitchonpitchfork*[below]{above}#m
\xleftbroom[below]{above}#m
\xrightbroom[below]{above}#m
\xleftpitchfork[below]{above}#m
\xrightpitchfork[below]{above}#m
\xleftswishingghost[below]{above}#m
\xrightswishingghost[below]{above}#m
\xleftflutteringbat[below]{above}#m
\xrightflutteringbat[below]{above}#m

\overleftwitchonbroom{arg}#m
\overrightwitchonbroom{arg}#m
\overleftwitchonbroom*{arg}#m
\overrightwitchonbroom*{arg}#m
\overleftwitchonpitchfork{arg}#m
\overrightwitchonpitchfork{arg}#m
\overleftwitchonpitchfork*{arg}#m
\overrightwitchonpitchfork*{arg}#m
\overleftbroom{arg}#m
\overrightbroom{arg}#m
\overscriptleftbroom{arg}#m
\overscriptrightbroom{arg}#m
\overleftpitchfork{arg}#m
\overrightpitchfork{arg}#m
\overscriptleftpitchfork{arg}#m
\overscriptrightpitchfork{arg}#m
\overleftswishingghost{arg}#m
\overrightswishingghost{arg}#m
\overleftflutteringbat{arg}#m
\overrightflutteringbat{arg}#m
\underleftwitchonbroom{arg}#m
\underrightwitchonbroom{arg}#m
\underleftwitchonbroom*{arg}#m
\underrightwitchonbroom*{arg}#m
\underleftwitchonpitchfork{arg}#m
\underrightwitchonpitchfork{arg}#m
\underleftwitchonpitchfork*{arg}#m
\underrightwitchonpitchfork*{arg}#m
\underleftbroom{arg}#m
\underrightbroom{arg}#m
\underscriptleftbroom{arg}#m
\underscriptrightbroom{arg}#m
\underleftpitchfork{arg}#m
\underrightpitchfork{arg}#m
\underscriptleftpitchfork{arg}#m
\underscriptrightpitchfork{arg}#m
\underleftswishingghost{arg}#m
\underrightswishingghost{arg}#m
\underleftflutteringbat{arg}#m
\underrightflutteringbat{arg}#m
\overbat{xyz}#m
\underbat{xyz}#m
\overscriptleftarrow{arg}#m
\underscriptleftarrow{arg}#m
\overscriptrightarrow{arg}#m
\underscriptrightarrow{arg}#m
\overscriptleftrightarrow{arg}#m
\underscriptleftrightarrow{arg}#m