# hicite package
# Matthew Bertucci 2026/09/10 for v1.1.0

#include:etoolbox
#include:iftex
#include:histrings
#include:hisort
#include:keyval
#include:hiabbrev

#keyvals:\usepackage/hicite#c
review
journal
journalfonts
memofonts
memo
brief
italcase
noauthwarn
endnote
endnotes
somenotename
nonotename
overrideurl
nooverrideurl
fullurl
toaurl
linkurl
useopturl
toastar
noterefs
pagerefs
xrefsupra
legacy
#endkeyvals

\defcitegroup{command}{init text%text}{suffix1,suffix2,...}
\defcitegroup[prefix]{command}{init text%text}{suffix1,suffix2,...}
\defcase{name}{parameters%text}
\defstatcode{name}{parameters%text}
\defregcode{name}{parameters%text}
\defadmincase{name}{parameters%text}
\defcasedoc{name}{parameters%text}
\defcourtdoc{name}{parameters%text}
\defconst{name}{parameters%text}
\defconstamend{name}{parameters%text}
\deffounding{name}{parameters%text}
\deffederalist{name}{parameters%text}
\defstatsess{name}{parameters%text}
\defstattitle{name}{parameters%text}
\defrule{name}{parameters%text}
\defmodelcode{name}{parameters%text}
\defbill{name}{parameters%text}
\defcongdoc{name}{parameters%text}
\defcongprint{name}{parameters%text}
\defcongrec{name}{parameters%text}
\defhearing{name}{parameters%text}
\defprespaper{name}{parameters%text}
\defdcpd{name}{parameters%text}
\defpatent{name}{parameters%text}
\defgovdoc{name}{parameters%text}
\deftestimony{name}{parameters%text}
\defcomments{name}{parameters%text}
\defsecfiling{name}{parameters%text}
\defbook{name}{parameters%text}
\defcitecontainer{name}{parameters%text}
\defjrnart{name}{parameters%text}
\defprocart{name}{parameters%text}
\defmagart{name}{parameters%text}
\defwebsite{name}{parameters%text}
\defmanuscript{name}{parameters%text}
\defworkingpaper{name}{parameters%text}
\defengdebate{name}{parameters%text}
\defengstat{name}{parameters%text}
\defengcommand{name}{parameters%text}
\defforeignconst{name}{parameters%text}
\deftreaty{name}{parameters%text}
\defeucase{name}{parameters%text}
\defunresolution{name}{parameters%text}
\defintdoc{name}{parameters%text}
\deffrcase{name}{parameters%text}
\deffrstat{name}{parameters%text}
\defcjs{name}{parameters%text}
\defrfc{name}{parameters%text}
\defletter{name}{parameters%text}
\defpressrelease{name}{parameters%text}
\defspeech{name}{parameters%text}
\deffilm{name}{parameters%text}
\deftvshow{name}{parameters%text}
\defopinion{name}{parameters%text}
\defcustom{name}{parameters%text}
\defabbrev{name}{parameters%text}
\defalias{name}{parameters%text}
\defselfcite{name}{parameters%text}
\AD
\BC
\BCE
\ACE
\hilabel{label}
\hilabel[text]{label}
\hiendlabel{label}
\hitanlabel{label}
\hitanlabel[text]{label}
\hiendtanlabel{label}
\hiflabel{label}
\hiflabel[text]{label}
\hinotelabel{label}
\hinotelabel[text]{label}
\hisectlabel{label}
\hisectlabel[text]{label}
\hiendsectlabel{label}
\HiUrl{URL}#U
\HiLinkText#*
\HiLinkTrailer#*
\HiUrlDriver{driver}#*
\sentence{text}
\clause{text}
\inline{ref}
\Inline{ref}
\adjective{ref}
\Adjective{ref}
\note{text}
\optclause
\HiSic!
\HiParsePin{number}
\HiAbbrev{scheme}{text}
\HiExplPhrase{phrase%text}
\HiFontPack{name}{specs}
\HiUseFontPack{name}
\HiFont{context}{text}
\HiShowState{ref}
\HiNoId
\HiFullCite{ref}
\HiNoFullCite{ref}
\HiFullTitle{ref}
\HiResetState
\HiDisableTOA
\HiEnableTOA
\HiNewTOACat{name}{supercat}{text}{Y|N}
\HiDefaultTOACat{type}{name}#*
\HiSetTOACat{reference}{category}
\HiAddToToa{ref}
\HiTOATag{tag}
\HiStarCount{number}
\HiStarText#*
\HiStarMark#*
\tableofauthorities
\HiTOAHeading{text}#*
\HiTOATable{list-name}
\HiTOATable[heading text%text]{list-name}
\HiTOALeader#*
\HiTOACite{cite-string}
\HiTOASkip#*
\HiTOAPassimNum#*
\HiTOAPassim#*
\HiTOADitto#*
\HiTOAIndent#*
\tableofabbreviations{callback}
\HiEndNote{text}
\HiENDelay{text}
\HiENSection
\HiENFont#*
\theendnotes

# not documented
\urlbreakskip#S
\TableOfUrls#S
\AddSignal{arg1}{arg2}#S
\TestJoinDivisions{arg1}{arg2}#S
\NotMainParty{arg}#S