# langsci-gb4e package
# Matthew Bertucci 2023/02/12 for v2022-10-21

#include:etoolbox

#keyvals:\usepackage/langsci-gb4e#c
nocgloss
nojambox
lowerpenalty
#endkeyvals

\ea %<<example>%>
\ea[judgment]{example%text}
\z
\ex %<<example>%>
\ex[judgment]{example%text}
\begin{exe}
\begin{exe}[string]
\end{exe}
\begin{xlist}
\begin{xlist}[string]
\end{xlist}
\exi{%<identifier%>} %<<example>%>
\exi{identifier}[judgment]{example%text}
\exr{label}#r
\exr{label}[judgment]{example%text}#r
\exp{label}#r
\exp{label}[judgment]{example%text}#r
\xref{label}#r
\xxref{label1%ref}{label2%ref}#r
\sn %<<example>%>
\sn[judgment]{example%text}
\exewidth{labeltext}
\eanoraggedright
\ealnoraggedright#*
\gll
\glt
\glll
\gllll
\glllll
\gllllll
\glllllll
\gllllllll
\exfont#*
\glossfont#*
\transfont#*
\exnrfont#*
\fnexfont#*
\fnglossfont#*
\fntransfont#*
\fnexnrfont#*
\nogltOffset
\resetgltOffset
\jambox{text}
\jambox[width]{text}
\jambox*{text}
\jamwidth#L

\atcenter{content}
\attop{content}
\begin{qlist}#*
\begin{xlistA}#*
\begin{xlista}#*
\begin{xlistabr}#*
\begin{xlistI}#*
\begin{xlisti}#*
\begin{xlistn}#*
\donewords#*
\eachwordeight#*
\eachwordfive#*
\eachwordfour#*
\eachwordone#*
\eachwordseven#*
\eachwordsix#*
\eachwordthree#*
\eachwordtwo#*
\eafirst#*
\eal#*
\eas#*
\eightsent#S
\end{qlist}#*
\end{xlistA}#*
\end{xlista}#*
\end{xlistabr}#*
\end{xlistI}#*
\end{xlisti}#*
\end{xlistn}#*
\examplesitalics#*
\examplesroman#*
\fivesent#S
\footexindent#*
\fourdigitexamples#*
\foursent#S
\gblabelsep{length}
\getwords#*
\gline#S
\glossglue#S
\gltoffset#*
\ifnotdone#S
\judgewidth{judgment}
\lastword{each}{line box}{word box}#*
\lineeight#S
\linefive#S
\linefour#S
\lineone#S
\lineseven#S
\linesix#S
\linethree#S
\linetwo#S
\more#*
\nobreakbox{text}#*
\nosinglegloss#*
\notdonefalse#S
\notdonetrue#S
\oldFootnotetext#S
\sevensent#S
\singlegloss#*
\sixsent#S
\subexsep{length}
\testdone#S
\thexnumi#*
\thexnumii#*
\thexnumiii#*
\thexnumiv#*
\threedigitexamples#*
\threesent#S
\trans
\twodigitexamples#*
\twosent#S
\wordeight#S
\wordfive#S
\wordfour#S
\wordone#S
\wordseven#S
\wordsix#S
\wordthree#S
\wordtwo#S
\xbox{width}{text}
\zl#*
\zlast#*
\zllast#*
\zs#*
