# denisbitouze, 27.10.2012
\BlettrineOline#n
\BlettrineO{arg1}#n
\BlettrineSline#n
\BlettrineS{arg1}#n
\DeclareListNumberGlyph{arg1}{arg2}{arg3}#n
\DeclareTextGlyphX{arg1}{arg2}{arg3}{arg4}{arg5}#n
\Lcnum{arg1}{arg2}#n
\LlettrineDline#n
\LlettrineD{arg1}#n
\LlettrineM{arg1}{arg2}#n
\LlettrineS{arg1}{arg2}#n
\Lnnum{arg1}{arg2}#n
\Lonum{arg1}{arg2}#n
\Lpnum{arg1}{arg2}#n
\Lpznum{arg1}{arg2}#n
\Ltonum{arg1}{arg2}#n
\Lznum{arg1}{arg2}#n
\ProcessOptionsWithKV{arg1}#n
\Qoppa#n
\Sampi#n
\Stigma#n
\Varqoppa#n
\antisigma#n
\biolinum#n
\biolinumkey#n
\biolinumoutline{arg1}{arg2}#n
\biolinumshadow{arg1}{arg2}#n
\dantisigma#n
\dsigma#n
\libertine#n
\libertineDefText#n
\libertineInitial#n
\libertineLoadUcs{arg1}#n
\libertineVersion#n
\libertineVersionDate#n
\libertineenumerate{arg1}#n
\libertinegrk{arg1}#n
\makelabel#n
\qoppa#n
\sampi#n
\stigma#n
\textbullet#n
\textic{arg1}#n
\textoxiaiota#n
\textsb{arg1}#n
\texttheta#n
\useListNumberGlyph{arg1}{arg2}#n
\varbeta#n
\varepsilon#n
\varkappa#n
\varphi#n
\varpi#n
\varqoppa#n
\varrho#n
\vartheta#n
\?\texteuro#n
\BInitialO#n
\BInitialS#n
\BlettrineO#n
\BlettrineS#n
\LInitialD#n
\LInitialM#n
\LInitialS#n
\LKey#n
\LKeyAlt#n
\LKeyAltF#n
\LKeyAltGr#n
\LKeyAltGrX#n
\LKeyAltX#n
\LKeyAt#n
\LKeyBack#n
\LKeyCapsLock#n
\LKeyCommand#n
\LKeyCtrl#n
\LKeyDel#n
\LKeyDown#n
\LKeyEinf#n
\LKeyEnd#n
\LKeyEnde#n
\LKeyEnter#n
\LKeyEntf#n
\LKeyEsc#n
\LKeyF#n
\LKeyFn#n
\LKeyGNU#n
\LKeyHome#n
\LKeyIns#n
\LKeyLeer#n
\LKeyLeft#n
\LKeyMenu#n
\LKeyOptionKey#n
\LKeyPad#n
\LKeyPageDown#n
\LKeyPageUp#n
\LKeyPgDown#n
\LKeyPgUp#n
\LKeyPos#n
\LKeyReset#n
\LKeyRight#n
\LKeyShift#n
\LKeyShiftAltGrX#n
\LKeyShiftAltX#n
\LKeyShiftStrgX#n
\LKeyShiftX#n
\LKeySpace#n
\LKeyStrg#n
\LKeyStrgAltEnt#n
\LKeyStrgAltF#n
\LKeyStrgAltX#n
\LKeyStrgX#n
\LKeyTab#n
\LKeyTux#n
\LKeyUp#n
\LKeyWin#n
\LMouseEmpty#n
\LMouseIIEmpty#n
\LMouseIIL#n
\LMouseIILR#n
\LMouseIIN#n
\LMouseIIR#n
\LMouseL#n
\LMouseLR#n
\LMouseM#n
\LMouseN#n
\LMouseR#n
\LlettrineD#n
\begin{libertineenumerate}
\biolinumGlyph#n
\biolinumKeyGlyph#n
\end{libertineenumerate}
\libertineGlyph#n
\libertineInitialGlyph#n
