# mode: listings.sty
# dani/2006-02-18
\begin{lstlisting}#V
\begin{lstlisting}[keyvals]
\end{lstlisting}
\lstlisting[keyvals]
#keyvals:\begin{lstlisting}
caption=
title=
label=##l
float=
floatplacement=
aboveskip=##L
belowskip=##L
linesskip=##L
boxpos#b,c,t
print#true,false
firstline=
lastline=
linerange=
showlines#true,false
emptylines=
gobble=
style=
language=
alsolanguage=
defaultdialect=
printpod#true,false
usekeywordsintag#true,false
tagstyle=
markfirstintag=
makemacrouse#true,false
basicstyle=
identifierstyle=
commentstyle=
stringstyle=
keywordstyle=
ndkeywordstyle=
classoffset=
texcsstyle=
directivestyle=
emph=
moreemph=
deleteemph=
emphstyle=
delim=
moredelim=
deletedelim=
extendedchars#true,false
inputencoding=
upquote#true,false
tabsize=
showtabs#true,false
tab=
showspaces#true,false
showstringspaces#true,false
formfeed=
numbers#none,left,right
stepnumber=
numberfirstline#true,false
numberstyle=
numbersep##L
numberblanklines#true,false
firstnumber=
name=
nolol#true,false
numberbychapter#true,false
#endkeyvals
\lstalias{alias}{language}#*
\lstdefinelanguage{language name}{kv-list}#*
\lstdefinestyle{style name}{kv-list}#*
\lstinline|%<code%>|
\lstinline[kv-list]|%<code%>|
\lstinputlisting{filename}
\lstinputlisting[kv-list]{filename}
\lstlistingname
\lstlistlistingname
\lstlistoflistings
\lstname
\lstnewenvironment{envname}[params][default]{starting code}{ending code}#*N
\lstnewenvironment{envname}[params]{starting code}{ending code}#*N
\lstnewenvironment{envname}{starting code}{ending code}#*N
\lstset{kv-list}#*
\thelstlisting
