\luatexversion#*
\directlua{%|}#
\luatexdirectlua{%|}#*
\latelua{%|}#
\luatexlatelua{%|}#*
\luaescapestring#*
\luatexluaescapestring#*
\clearmarks#*
\luatexclearmarks#*
\noligs#*
\luatexnoligs#*
\nokerns#*
\luatexnokerns#*
\formatname#*
\luatexformatname#*
\scantextokens#*
\luatexscantextokens#*
\alignmark#*
\luatexalignmark#*
\aligntab#*
\luatexaligntab#*
\catcodetable#*
\luatexcatcodetable#*
\initcatcodetable#*
\luatexinitcatcodetable#*
\savecatcodetable#*
\luatexsavecatcodetable#*
\suppressfontnotfounderror#*
\luatexsuppressfontnotfounderror#*
\suppresslongerror#*
\luatexsuppresslongerror#*
\suppressifcsnameerror#*
\luatexsuppressifcsnameerror#*
\suppressoutererror#*
\luatexsuppressoutererror#*
\outputbox#*
\luatexoutputbox#*
\pdfrefximage#*
\luatexpdfrefximage#*
\pdfrefxform#*
\luatexpdfrefxform#*
\pdflastximage#*
\luatexpdflastximage#*
\pdflastxform#*
\luatexpdflastxform#*
\gleaders#*
\luatexgleaders#*
