# luatexja-core package
# Matthew Bertucci 4/9/2022 for v20220311.0

#include:luatexbase
#include:luaotfload
#include:ltxcmds
#include:pdftexcmds
#include:xkeyval
#include:etoolbox
#include:everyhook
#include:ltj-base
#include:ltj-latex

\luatexjacoreLoaded#S
\LuaTeXjaAvailable#S
\ltjlineendcomment#*
\jfam#*
\RequireLuaTeXjaSubmodule{name}#*
\RequireLuaTeXjaSubmodule{name}[date]#*
\asluastring{string}#*
\jfont%<\cs%>=%<specification%>
\jfont{cmd}#Sd
\globaljfont%<\cs%>=%<specification%>#*
\globaljfont{cmd}#Sd
\tfont%<\cs%>=%<specification%>
\tfont{cmd}#Sd
\globaltfont%<\cs%>=%<specification%>#*
\globaltfont{cmd}#Sd
\zw
\zh
\disinhibitglue
\inhibitglue
\<#*
\ltjfakeparbegin
\ltjfakeboxbdd
\insertxkanjiskip
\insertkanjiskip
\ltjdefcharrange{name}{ranges}
\ltjsetkanjiskip
\ltjsetxkanjiskip
\ltjsetparameter{parameters%keyvals}
\ltjglobalsetparameter{parameters%keyvals}
#keyvals:\ltjsetparameter,\ltjglobalsetparameter
kcatcode={%<charcode,natural number%>}
prebreakpenalty={%<charcode,penalty%>}
postbreakpenalty={%<charcode,penalty%>}
jatextfont={%<jfam,jfont cs%>}
jascriptfont={%<jfam,jfont cs%>}
jascriptscriptfont={%<jfam,jfont cs%>}
yalbaselineshift=##L
yjabaselineshift=##L
talbaselineshift=##L
tjabaselineshift=##L
jaxspmode={%<charcode,mode%>}
alxspmode={%<charcode,penalty%>}
autospacing#true,false
autoxspacing#true,false
kanjiskip=##L
xkanjiskip=##L
jcharwidowpenalty=%<penalty%>
differentjfm=#average,both,large,small,pleft,pright,paverage
jacharrange=%<ranges%>
kansujichar={%<digit,charcode%>}
direction=%<dir%>
#endkeyvals
\ltjgetparameter{parameter%keyvals}
#keyvals:\ltjgetparameter
differentjfm
autospacing
autoxspacing
kanjiskip
xkanjiskip
prebreakpenalty
postbreakpenalty
jaxspmode
alxspmode
jacharrange
kansujichar
adjustdir
boxdir
chartorange
yalbaselineshift
yjabaselineshift
talbaselineshift
tjabaselineshift
direction
kcatcode
#endkeyvals
\ltjjachar#*
\ltjalchar#*
\ltjsetmathletter%<<number>%>#*
\ltjunsetmathletter%<<number>%>#*
\ltjdeclarealtfont%<\basefontcs\altfontcs%>{%<range%>}
\ltjclearaltfont%<\fontcs%>
\tate
\yoko
\dtou
\utod
\ltjgetwd%<<number>%>
\ltjgetht%<<number>%>
\ltjgetdp%<<number>%>
\ltjsetwd%<<number>%>=%<<dimen>%>
\ltjsetht%<<number>%>=%<<dimen>%>
\ltjsetdp%<<number>%>=%<<dimen>%>
