# lyluatex package
# Matthew Bertucci 2022/11/07 for v1.1.1

#include:graphicx
#include:minibox
#include:environ
#include:currfile
#include:pdfpages
#include:varwidth
#include:luaoptions
#include:metalogo

\lyluatex#*
\IfNextToken%<<match>%>{%<if%>}{%<else%>}#*
\cm#S
\in#S
\mm#S
\pt#S
\lyFilename{filename}#*
\lyIntertext{text}#*
\lyVersion{version}#*
\rmfamilyid#S
\sffamilyid#S
\ttfamilyid#S
\includely{file}#*
\includely[options%keyvals]{file}#*
\musicxmlfile{file}
\musicxmlfile[options%keyvals]{file}
\lyscorebegin#*
\lyscoreend#*
\lysetverbenv{begindef}{enddef}
\begin{lysavefrag}{filename%file}
\end{lysavefrag}
\filename#S
\lyenv{envname}#*
\lynewenvironment{envname}{begindef}{enddef}#N
\lynewenvironment{envname}[args]{begindef}{enddef}#N
\lynewenvironment{envname}[args][default]{begindef}{enddef}#N
\begin{ly}#*
\begin{ly}[options%keyvals]#*
\end{ly}#*
\options#S
\lily{score}#*
\lily[options%keyvals]{score}#*
\lyscore{option%keyvals}
\lilypondfile{file}
\lilypondfile[options%keyvals]{file}
\begin{lilypond}
\begin{lilypond}[options%keyvals]
\end{lilypond}
\lilypond{score}
\lilypond[options%keyvals]{score}

#keyvals:\usepackage/lyluatex#c,\includely#c,\musicxmlfile#c,\begin{ly}#c,\lily#c,\lilypondfile#c,\begin{lilypond}#c,\lilypond#c
insert=#systems,fullpage,inline,bare-inline
fullpagestyle=%<pagestyle%>
print-page-number#true,false
first-page-number#true,false
inline-staffsize=%<pts%>
valign=#center,top,bottom
voffset=##L
hpadding=##L
print-only#true,false
print-only={%<number range(s)%>}
line-width=##L
staffsize=%<pts%>
ragged-right#true,false
noragged-right
indent=##L
noindent
system-count=%<integer%>
quote#true,false
gutter=##L
leftgutter=##L
rightgutter=##L
exampleindent=##L
papersize=%<paper size%>
paperwidth=##L
paperheight=##L
twoside#true,false
max-protrusion=##L
max-left-protrusion=##L
max-right-protrusion=##L
autoindent#true,false
fullpagealign=#crop,staffline
extra-bottom-margin=%<pts%>
extra-top-margin=%<pts%>
fragment#true,false
pass-fonts#true,false
current-font-as-main#true,false
rmfamily=%<font family%>
sffamily=%<font family%>
ttfamily=%<font family%>
noclef#true,false
notimesig#true,false
nostaffsymbol#true,false
notiming#true,false
notime#true,false
nostaff#true,false
relative=%<integer%>
language=%<language%>
label=##l
labelprefix=%<prefix%>
printfilename#true,false
verbatim#true,false
addversion#true,false
intertext=%<text%>
includepaths={%<path1,path2,...%>}
program=%<program%>
ly-version=%<version%>
tmpdir=%<directory%>
cleantmp#true,false
write-headers#true,false
optimize-pdf#true,false
debug#true,false
showfailed#true,false
force-compilation#true,false
fix_badly_cropped_staffgroup_brackets#true,false
xml2ly=%<program%>
absolute#true,false
lxml#true,false
verbose#true,false
no-articulation-directions#true,false
no-beaming#true,false
no-page-layout#true,false
no-rest-positions#true,false
raw-pdf#true,false
#endkeyvals

#keyvals:\setluaoption#c,\lyscore#c
insert
fullpagestyle
print-page-number
first-page-number
inline-staffsize
valign
voffset
hpadding
print-only
line-width
staffsize
ragged-right
noragged-right
indent
system-count
quote
gutter
leftgutter
rightgutter
exampleindent
papersize
paperwidth
paperheight
twoside
max-protrusion
max-left-protrusion
max-right-protrusion
autoindent
fullpagealign
extra-bottom-margin
extra-top-margin
fragment
pass-fonts
current-font-as-main
rmfamily
sffamily
ttfamily
noclef
notimesig
nostaffsymbol
notiming
notime
nostaff
relative
language
label
labelprefix
printfilename
verbatim
addversion
intertext
includepaths
program
ly-version
tmpdir
cleantmp
write-headers
optimize-pdf
debug
showfailed
force-compilation
fix_badly_cropped_staffgroup_brackets
xml2ly
language
absolute
lxml
verbose
no-articulation-directions
no-beaming
no-page-layout
no-rest-positions
raw-pdf
#endkeyvals

#keyvals:\lyscore#c
%<number%>
nsystems
hoffset
#endkeyvals
