# mathabx package
# Matthew Bertucci 8/9/2021

\Aries#m
\asterisk#m
\Asterisk#m
\barin#m
\barleftharpoon#m
\barrightharpoon#m
\barwedge#m
\because#m
\between#m
\bigast#m
\bigboxasterisk#m
\bigboxbackslash#m
\bigboxbot#m
\bigboxcirc#m
\bigboxcoasterisk#m
\bigboxdiv#m
\bigboxdot#m
\bigboxleft#m
\bigboxminus#m
\bigboxperp#m
\bigboxplus#m
\bigboxright#m
\bigboxslash#m
\bigboxtimes#m
\bigboxtop#m
\bigboxtriangleup#m
\bigboxvoid#m
\bigcoast#m
\bigcomplement#m
\bigcurlyvee#m
\bigcurlywedge#m
\bigoasterisk#m
\bigobackslash#m
\bigobot#m
\bigocirc#m
\bigocoasterisk#m
\bigodiv#m
\bigoleft#m
\bigominus#m
\bigoperp#m
\bigoright#m
\bigoslash#m
\bigotop#m
\bigotriangleup#m
\bigovoid#m
\bigplus#m
\bigsqcap#m
\bigsquplus#m
\bigstar#m
\bigtimes#m
\bigvarstar#m
\blackdiamond#m
\blacktriangledown#m
\blacktriangleleft#m
\blacktriangleright#m
\blacktriangleup#m
\botdoteq#m
\boxdiv#m
\boxeddash#m
\boxminus#m
\boxplus#m
\boxtimes#m
\boy#m
\braceld#m
\bracelu#m
\bracemd#m
\bracemu#m
\bracerd#m
\braceru#m
\bracexd#m
\bracexu#m
\bumpedeq#m
\Bumpedeq#m
\Cap#m
\centerdot#m
\circeq#m
\circlearrowleft#m
\circlearrowright#m
\circledast#m
\circledcirc#m
\circleddash#m
\circplus#m
\coasterisk#m
\coAsterisk#m
\coloneq#m
\complement#m
\convolution#m
\corresponds#m
\Cup#m
\curlyeqprec#m
\curlyeqsucc#m
\curlyvee#m
\curlywedge#m
\curvearrowbotleft#m
\curvearrowbotleftright#m
\curvearrowbotright#m
\curvearrowleft#m
\curvearrowleftright#m
\curvearrowright#m
\curvearrowtopleft#m
\curvearrowtopleftright#m
\curvearrowtopright#m
\Dashv#m
\dashV#m
\DashV#m
\dashVv#m
\ddddot{arg}#m
\dddot{arg}#m
\degree#m
\diagdown#m
\diagup#m
\diameter#m
\divdot#m
\divideontimes#m
\divides#m
\dlsh#m
\dotdiv#m
\Doteq#m
\doteqdot#m
\dotplus#m
\dotseq#m
\dottimes#m
\doublebarwedge#m
\doublecap#m
\doublecup#m
\downdownarrows#m
\downdownharpoons#m
\downharpoonleft#m
\downharpoonright#m
\downtouparrow#m
\downuparrows#m
\downupharpoons#m
\drsh#m
\Earth#m
\eqbumped#m
\eqcirc#m
\eqcolon#m
\fallingdotseq#m
\Finv#m
\fourth#m
\fullmoon#m
\Game#m
\Gemini#m
\geqq#m
\geqslant#m
\ggcurly#m
\ggg#m
\girl#m
\gnapprox#m
\gneq#m
\gneqq#m
\gtrapprox#m
\gtrdot#m
\hash#m
\iiint#m
\iiintop#m
\iint#m
\iintop#m
\intop#m
\Join#m
\Jupiter#m
\lcorners#m
\ldbrack#m
\leftbarharpoon#m
\leftleftarrows#m
\leftleftharpoons#m
\leftmoon#m
\leftrightarrows#m
\leftrightharpoon#m
\leftrightharpoons#m
\leftrightsquigarrow#m
\leftsquigarrow#m
\leftthreetimes#m
\lefttorightarrow#m
\Leo#m
\leqq#m
\leqslant#m
\lessdot#m
\lfilet#m
\lhook#m
\Libra#m
\llcorner#m
\llcurly#m
\lll#m
\lnapprox#m
\lneq#m
\lneqq#m
\looparrowdownleft#m
\looparrowdownright#m
\looparrowleft#m
\looparrowright#m
\looparrowupleft#m
\looparrowupright#m
\lrcorner#m
\lsemantic#m
\Lsh#m
\ltimes#m
\mapsfromchar#m
\Mapsfromchar#m
\mapstochar#m
\Mapstochar#m
\Mars#m
\measuredangle#m
\Mercury#m
\Moon#m
\napprox#m
\ncong#m
\ncurlyeqprec#m
\ncurlyeqsucc#m
\ndashv#m
\nDashv#m
\ndashV#m
\nDashV#m
\ndashVv#m
\ndivides#m
\Neptune#m
\nequiv#m
\newmoon#m
\nexists#m
\ngeq#m
\ngeqq#m
\ngeqslant#m
\ngtr#m
\ngtrapprox#m
\nibar#m
\nleftarrow#m
\nLeftarrow#m
\nleftrightarrow#m
\nLeftrightarrow#m
\nleq#m
\nleqq#m
\nleqslant#m
\nless#m
\nlessapprox#m
\notasymp#m
\notbot#m
\notdivides#m
\notequiv#m
\notni#m
\notowner#m
\notowns#m
\notperp#m
\notsign#m
\nottop#m
\nprec#m
\nprecapprox#m
\npreccurlyeq#m
\npreceq#m
\nprecsim#m
\nrightarrow#m
\nRightarrow#m
\nsim#m
\nsimeq#m
\nsqsubset#m
\nsqSubset#m
\nsqsubseteq#m
\nsqsubseteqq#m
\nsqsupset#m
\nsqSupset#m
\nsqsupseteq#m
\nsqsupseteqq#m
\nsubset#m
\nSubset#m
\nsubseteq#m
\nsubseteqq#m
\nsucc#m
\nsuccapprox#m
\nsucccurlyeq#m
\nsucceq#m
\nsuccsim#m
\nsupset#m
\nSupset#m
\nsupseteq#m
\nsupseteqq#m
\ntriangleleft#m
\ntrianglelefteq#m
\ntriangleright#m
\ntrianglerighteq#m
\nvargeq#m
\nvarleq#m
\nvdash#m
\nvDash#m
\nVdash#m
\nVDash#m
\nVvash#m
\oasterisk#m
\obackslash#m
\obot#m
\ocirc#m
\ocoasterisk#m
\odiv#m
\oiint#m
\oiintop#m
\ointop#m
\oleft#m
\operp#m
\oright#m
\otop#m
\otriangleup#m
\ovoid#m
\ownsbar#m
\partialslash#m
\pitchfork#m
\pluscirc#m
\Pluto#m
\precapprox#m
\preccurlyeq#m
\precdot#m
\precnapprox#m
\precneq#m
\precnsim#m
\precsim#m
\rcorners#m
\rdbrack#m
\restriction#m
\rfilet#m
\rhook#m
\rightbarharpoon#m
\rightleftarrows#m
\rightleftharpoon#m
\rightmoon#m
\rightrightarrows#m
\rightrightharpoons#m
\rightsquigarrow#m
\rightthreetimes#m
\righttoleftarrow#m
\ring{arg}#m
\rip#m
\risingdotseq#m
\rsemantic#m
\Rsh#m
\rtimes#m
\Saturn#m
\scoprod#m
\Scorpio#m
\second#m
\smalltriangledown#m
\smalltriangleleft#m
\smalltriangleright#m
\smalltriangleup#m
\sphericalangle#m
\sprod#m
\sqbullet#m
\sqCap#m
\sqCup#m
\sqdoublecap#m
\sqdoublecup#m
\sqsubset#m
\sqSubset#m
\sqsubseteqq#m
\sqsubsetneq#m
\sqsubsetneqq#m
\sqsupset#m
\sqSupset#m
\sqsupseteqq#m
\sqsupsetneq#m
\sqsupsetneqq#m
\square#m
\squplus#m
\ssum#m
\Subset#m
\subseteqq#m
\subsetneq#m
\subsetneqq#m
\succapprox#m
\succcurlyeq#m
\succdot#m
\succnapprox#m
\succneq#m
\succnsim#m
\succsim#m
\Sun#m
\Supset#m
\supseteqq#m
\supsetneq#m
\supsetneqq#m
\Taurus#m
\therefore#m
\thickvert#m
\third#m
\topdoteq#m
\trianglelefteq#m
\triangleq#m
\trianglerighteq#m
\udot#m
\ulcorner#m
\ulsh#m
\updownarrows#m
\updownharpoons#m
\upharpoonleft#m
\upharpoonright#m
\uptodownarrow#m
\upuparrows#m
\upupharpoons#m
\Uranus#m
\urcorner#m
\ursh#m
\varEarth#m
\vargeq#m
\varhash#m
\varleq#m
\varnotin#m
\varnotowner#m
\varnotsign#m
\varsqsubsetneq#m
\varsqsubsetneqq#m
\varsqsupsetneq#m
\varsqsupsetneqq#m
\varstar#m
\varsubsetneq#m
\varsubsetneqq#m
\varsupsetneq#m
\varsupsetneqq#m
\vartriangleleft#m
\vartriangleright#m
\vDash#m
\Vdash#m
\VDash#m
\veebar#m
\veedoublebar#m
\Venus#m
\Vvdash#m
\vvvert#m
\widearrow{arg}#m
\widebar{arg}#m
\widecheck{arg}#m
\wideparen{arg}#m
\overgroup{arg}#m
\undergroup{arg}#m
\overleftrightarrow{arg}#m
\underrightarrow{arg}#m
\underleftarrow{arg}#m
\underleftrightarrow{arg}#m
\overRightarrow{arg}#m
\overLeftarrow{arg}#m
\overLeftRightarrow{arg}#m
\underRightarrow{arg}#m
\underLeftarrow{arg}#m
\underLeftRightarrow{arg}#m
\widering{arg}#m
\widedot{arg}#m
\wideddot{arg}#m
\widedddot{arg}#m
\wideddddot{arg}#m
\varnot#m

\mayadelimiters
\maya{number}
\mayadigit{digit}
\changenotsign#*