# mathalpha package
# Matthew Bertucci 11/2/2021 for v1.142

#include:xkeyval

#keyvals:\usepackage/mathalpha
cal=#cm,euler,rsfs,rsfso,lucida,mathpi,mma,pxtx,mt,mtc,zapfc,esstix,boondox,boondoxo,dutchcal,bickham,bickhams,stix,txupr,boondoxupr,kp,stixplain,stixfancy,stixtwoplain,stixtwofancy
calscaled=
bfcal
calsymbols
scr=#cm,euler,rsfs,rsfso,lucida,mathpi,mma,pxtx,mt,mtc,zapfc,esstix,boondox,boondoxo,dutchcal,bickham,bickhams,stix,txupr,boondoxupr,kp,stixplain,stixfancy,stixtwoplain,stixtwofancys
scrscaled=
bfscr
scrsymbols
frak=#euler,lucida,mathpi,mma,mt,esstix,boondox,pxtx,stixtwo
frakscaled=
bffrak
fraksymbols
bb=#ams,lucida,mathpi,mma,mt,mth,pazo,fourier,esstix,boondox,px,tx,txof,libus,dsserif,bboldx,bboldx-light,dsfontserif,dsfontsans,stixtwo,stix
bbscaled=
bfbb
bbsymbols
oldbold
scaled=
showoptions
#endkeyvals

#ifOption:oldbold
\mathbbb{text}#m
\mathbcal{text}#m
\mathbscr{text}#m
\mathbfrak{text}#m
#endif
#ifOption:scr=bickham
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=bickhams
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=boondox
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=boondoxo
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=boondoxupr
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=cm
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=dutchcal
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=esstix
\mathscr{text}#m
#endif
#ifOption:scr=euler
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=kp
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=lucida
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=mathpi
\mathscr{text}#m
#endif
#ifOption:scr=mma
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=mt
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=mtc
\mathscr{text}#m
#endif
#ifOption:scr=pxtx
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=rsfs
\mathscr{text}#m
#endif
#ifOption:scr=rsfso
\mathscr{text}#m
#endif
#ifOption:scr=stix
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=stixfancy
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=stixplain
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=stixtwofancys
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=stixtwoplain
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=txupr
\mathscr{text}#m
\mathbfscr{text}#m
#endif
#ifOption:scr=zapfc
\mathscr{text}#m
#endif
#ifOption:cal=bickham
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=bickhams
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=boondox
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=boondoxo
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=boondoxupr
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=cm
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=dutchcal
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=esstix
\mathcal{text}#m
#endif
#ifOption:cal=euler
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=kp
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=lucida
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=mathpi
\mathcal{text}#m
#endif
#ifOption:cal=mma
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=mt
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=mtc
\mathcal{text}#m
#endif
#ifOption:cal=pxtx
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=rsfs
\mathcal{text}#m
#endif
#ifOption:cal=rsfso
\mathcal{text}#m
#endif
#ifOption:cal=stix
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=stixfancy
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=stixplain
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=stixtwofancy
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=stixtwoplain
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=txupr
\mathcal{text}#m
\mathbfcal{text}#m
#endif
#ifOption:cal=zapfc
\mathcal{text}#m
#endif
#ifOption:frak=euler
\mathfrak{text}#m
\mathbffrak{text}#m
#endif
#ifOption:frak=lucida
\mathfrak{text}#m
#endif
#ifOption:frak=mathpi
\mathfrak{text}#m
#endif
#ifOption:frak=mma
\mathfrak{text}#m
\mathbffrak{text}#m
#endif
#ifOption:frak=mt
\mathfrak{text}#m
\mathbffrak{text}#m
#endif
#ifOption:frak=esstix
\mathfrak{text}#m
#endif
#ifOption:frak=boondox
\mathfrak{text}#m
\mathbffrak{text}#m
#endif
#ifOption:frak=pxtx
\mathfrak{text}#m
\mathbffrak{text}#m
#endif
#ifOption:frak=stixtwo
\mathfrak{text}#m
\mathbffrak{text}#m
#endif
#ifOption:bb=ams
\mathbb{text}#m
#endif
#ifOption:bb=lucida
\mathbb{text}#m
\mathbfbb{text}#m
#endif
#ifOption:bb=mathpi
\mathbb{text}#m
#endif
#ifOption:bb=mma
\mathbb{text}#m
\mathbfbb{text}#m
#endif
#ifOption:bb=mt
\mathbb{text}#m
\mathbfbb{text}#m
#endif
#ifOption:bb=mth
\mathbb{text}#m
\mathbfbb{text}#m
#endif
#ifOption:bb=pazo
\mathbb{text}#m
#endif
#ifOption:bb=fourier
\mathbb{text}#m
#endif
#ifOption:bb=esstix
\mathbb{text}#m
#endif
#ifOption:bb=boondox
\mathbb{text}#m
\mathbfbb{text}#m
#endif
#ifOption:bb=px
\mathbb{text}#m
\mathbbb{text}#m
#endif
#ifOption:bb=tx
\mathbb{text}#m
\mathbfbb{text}#m
#endif
#ifOption:bb=txof
\mathbb{text}#m
\mathbfbb{text}#m
#endif
#ifOption:bb=libus
\mathbb{text}#m
#endif
#ifOption:bb=dsserif
#include:dsserif
#endif
#ifOption:bb=bboldx
#include:bboldx
#endif
#ifOption:bb=bboldx-light
#include:bboldx
#endif
#ifOption:bb=dsfontserif
\mathbb{text}#m
#endif
#ifOption:bb=dsfontsans
\mathbb{text}#m
#endif
#ifOption:bb=stixtwo
\mathbb{text}#m
\txtbbGamma#*
\txtbbgamma#*
\txtbbPi#*
\txtbbpi#*
\txtbbdotlessi#*
\txtbbdotlessj#*
\txtbbzero#*
\txtbbone#*
\txtbbtwo#*
\txtbbthree#*
\txtbbfour#*
\txtbbfive#*
\txtbbsix#*
\txtbbseven#*
\txtbbeight#*
\txtbbnine#*
#endif
#ifOption:bb=stix
\mathbb{text}#m
\mathbbi{text}#m
\mathbfbb{text}#m
\mathbfbbi{text}#m
\txtbbGamma#*
\txtbbgamma#*
\txtbbPi#*
\txtbbpi#*
\txtbbdotlessi#*
\txtbbdotlessj#*
\txtbbzero#*
\txtbbone#*
\txtbbtwo#*
\txtbbthree#*
\txtbbfour#*
\txtbbfive#*
\txtbbsix#*
\txtbbseven#*
\txtbbeight#*
\txtbbnine#*
#endif
#ifOption:bbsymbols
\imathbb#m
\jmathbb#m
\bbdotlessi#m
\bbdotlessj#m
\bbGamma#m
\bbDelta#m
\bbTheta#m
\bbLambda#m
\bbXi#m
\bbPi#m
\bbSigma#m
\bbUpsilon#m
\bbPhi#m
\bbPsi#m
\bbOmega#m
\bbalpha#m
\bbbeta#m
\bbgamma#m
\bbdelta#m
\bbepsilon#m
\bbzeta#m
\bbeta#m
\bbtheta#m
\bbiota#m
\bbkappa#m
\bblambda#m
\bbmu#m
\bbnu#m
\bbxi#m
\bbpi#m
\bbrho#m
\bbsigma#m
\bbtau#m
\bbupsilon#m
\bbphi#m
\bbchi#m
\bbpsi#m
\bbomega#m
\bbLbrack#m
\bbRbrack#m
\bbLangle#m
\bbRangle#m
\bbLparen#m
\bbRparen#m
#endif
