# autogenerated by txs
\bookautorefname#S
\booknumberline#S
\chapternumberline#S
\endsidecaption#S
\endsidecontcaption#S
\endsubappendices#S
\nameref#S
\numberline#S
\pagenoteanchor#S
\partnumberline#S
\printpageinnotes#S
\theHchapter#S
\theHmemhycontfloat#S
\theHpagenote
\theHsection#S
\thememhycontfloat
