# autogenerated by txs, edited by Stefan Kraus 2013-08-12
#include:amsmath
#include:calc
#include:graphics
#include:ifthen
#include:keyval
#include:pgf
#include:tikz
#include:twoopt
\bond{-=#}
#argument of bond here suggests the three most common types of bonds
\cee{equation}
\ce{formula}
\cf{arg1}{arg2}#S
\cmath{arg1}
#cmath was removed from mhchem: "2006-12-17 v3.05, mhchem fixed: changed: $...$ replaces \cmath{...}", kept for backward compatibility. /Stefan Kraus 2013-08-12
\hyphen
\mhchem#S
\mhchemoptions{option=abc}
\sbond
\dbond
\tbond