# autogenerated by txs
# modified by Tim Hoffmann 2014-03-24
#include:calc
#include:fancyvrb
#include:float
#include:ifplatform
#include:ifthen
#include:keyval
#include:xcolor
\DeleteFile{arg1}#S
\TestAppExists{arg1}#S
\begin{minted}{language}#\verbatim
\begin{minted}[options]{language}#\verbatim
\csname#S
\end{minted}#S
\expandafter#S
\inputminted[options]{language}{file}#i
\listingscaption#S
\listoflistings#S
\listoflistingscaption#S
\minted#
\mint{arg1}{arg2}{arg3}#S
\newmintedfile{arg1}{arg2}{arg3}#S
\newminted{arg1}{arg2}{arg3}#S
\newmint{arg1}{arg2}{arg3}#S
\usemintedstyle{arg1}#S
