# autogenerated by txs
# modified by Tim Hoffmann 2014-03-24
# modified by Elias Kirchgässner 2016-07-27
#include:calc
#include:fancyvrb
#include:float
#include:ifplatform
#include:ifthen
#include:keyval
#include:xcolor
\DeleteFile{arg1}#*
\TestAppExists{arg1}#*
\begin{minted}{language}#V
\begin{minted}[options]{language}#V
\begin{listing}#
\end{listing}
\end{minted}#
\inputminted[options]{language}{file}#
\listingscaption#*
\listoflistings#*
\listoflistingscaption#*
\mint[options]{language}{code}#*
\mint{language}{code}#
\mintinline{language}{code}#
\newmintedfile{arg1}{arg2}{arg3}#S
\newminted{language}{definition}#*
\newmint{cmd}{definition}#*
\usemintedstyle{stylename}#*
