# mnsymbol package
# updated 7/22/2021

#include:amsmath
#include:textcomp

\approxeq#m
\backapprox#m
\backapproxeq#m
\backcong#m
\backeqsim#m
\backneg#m
\backprime#m
\backsim#m
\backsimeq#m
\backslash#m
\backslashdiv#m
\backtriplesim#m
\barwedge#m
\because#m
\beth#m
\between#m
\bigcapdot#m
\bigcapplus#m
\bigcircle#m
\bigcupdot#m
\bigcupplus#m
\bigcurlyvee#m
\bigcurlyveedot#m
\bigcurlywedge#m
\bigcurlywedgedot#m
\bigdoublecurlyvee#m
\bigdoublecurlywedge#m
\bigdoublevee#m
\bigdoublewedge#m
\Biggm#m
\bigoast#m
\bigobackslash#m
\bigocirc#m
\bigominus#m
\bigoslash#m
\bigostar#m
\bigotriangle#m
\bigovert#m
\bigplus#m
\bigsqcap#m
\bigsqcapdot#m
\bigsqcapplus#m
\bigsqcupdot#m
\bigsqcupplus#m
\bigstar#m
\bigtimes#m
\bigveedot#m
\bigwedgedot#m
\blacklozenge#m
\blacksquare#m
\blacktriangle#m
\blacktriangledown#m
\blacktriangleleft#m
\blacktriangleright#m
\Box#m
\boxbackslash#m
\boxbox#m
\boxdot#m
\boxminus#m
\boxplus#m
\boxslash#m
\boxtimes#m
\boxvert#m
\braceld#m
\bracelu#m
\bracemd#m
\bracemid#m
\bracemu#m
\bracerd#m
\braceru#m
\Bumpeq#m
\bumpeq#m
\Cap#m
\capdot#m
\capplus#m
\centerdot#m
\checkmark#m
\circeq#m
\circlearrowleft#m
\circlearrowright#m
\circledast#m
\circledcirc#m
\circleddash#m
\closedcurlyvee#m
\closedcurlywedge#m
\closedequal#m
\closedprec#m
\closedsucc#m
\coloneq#m
\complement#m
\Cup#m
\cupdot#m
\cupplus#m
\curlyeqprec#m
\curlyeqsucc#m
\curlyvee#m
\curlyveedot#m
\curlywedge#m
\curlywedgedot#m
\curvearrowdownup#m
\curvearrowleft#m
\curvearrowleftright#m
\curvearrownesw#m
\curvearrownwse#m
\curvearrowright#m
\curvearrowrightleft#m
\curvearrowsenw#m
\curvearrowswne#m
\curvearrowupdown#m
\daleth#m
\dasharrow#m
\dasheddownarrow#m
\dashedleftarrow#m
\dashednearrow#m
\dashednwarrow#m
\dashedrightarrow#m
\dashedsearrow#m
\dashedswarrow#m
\dasheduparrow#m
\dashleftarrow#m
\dashrightarrow#m
\dbigcap#m
\dbigcapdot#m
\dbigcapplus#m
\dbigcircle#m
\dbigcup#m
\dbigcupdot#m
\dbigcupplus#m
\dbigcurlyvee#m
\dbigcurlyveedot#m
\dbigcurlywedge#m
\dbigcurlywedgedot#m
\dbigdoublecurlyvee#m
\dbigdoublecurlywedge#m
\dbigdoublevee#m
\dbigdoublewedge#m
\dbigoast#m
\dbigobackslash#m
\dbigocirc#m
\dbigodot#m
\dbigominus#m
\dbigoplus#m
\dbigoslash#m
\dbigostar#m
\dbigotimes#m
\dbigotriangle#m
\dbigovert#m
\dbigplus#m
\dbigsqcap#m
\dbigsqcapdot#m
\dbigsqcapplus#m
\dbigsqcup#m
\dbigsqcupdot#m
\dbigsqcupplus#m
\dbigtimes#m
\dbigvee#m
\dbigveedot#m
\dbigwedge#m
\dbigwedgedot#m
\dcomplement#m
\dcoprod#m
\ddotdot#m
\diagdown#m
\diagup#m
\diameter#m
\Diamond#m
\diamondbackslash#m
\diamonddiamond#m
\diamonddot#m
\diamonddots#m
\diamondminus#m
\diamondplus#m
\diamondslash#m
\diamondsuit#m
\diamondtimes#m
\diamondvert#m
\didotsint#m
\diiiint#m
\diiint#m
\diint#m
\dint#m
\divideontimes#m
\divides#m
\dlanddownint#m
\dlandupint#m
\dlcircleleftint#m
\dlcirclerightint#m
\doiint#m
\doint#m
\Doteq#m
\doteqdot#m
\dotmedvert#m
\dotminus#m
\dotplus#m
\doublebarwedge#m
\doublecap#m
\doublecup#m
\doublecurlyvee#m
\doublecurlywedge#m
\doublefrown#m
\doublefrowneq#m
\doublesmile#m
\doublesmileeq#m
\doublesqcap#m
\doublesqcup#m
\doublevee#m
\doublewedge#m
\downarrowtail#m
\downbrace#m
\downbraceg#*m
\downbracegg#*m
\downbraceggg#*m
\downbracegggg#*m
\downdownarrows#m
\downfilledspoon#m
\downfootline#m
\downfree#m
\downharpoonccw#m
\downharpooncw#m
\downharpoonleft#m
\downharpoonright#m
\downlsquigarrow#m
\downmapsto#m
\downModels#m
\downmodels#m
\downpitchfork#m
\downpropto#m
\downrsquigarrow#m
\downslice#m
\downspoon#m
\downtherefore#m
\downuparrows#m
\downupharpoons#m
\downVdash#m
\downvdash#m
\downY#m
\dprod#m
\drcircleleftint#m
\drcirclerightint#m
\dstrokedint#m
\dsum#m
\dsumint#m
\dtimes#m
\emptyfilledspoon#m
\eqbump#m
\eqcirc#m
\eqdot#m
\eqfrown#m
\eqsim#m
\eqslantgtr#m
\eqslantless#m
\eqsmile#m
\equal#m
\equalclosed#m
\equivclosed#m
\fallingdotseq#m
\filleddiamond#m
\filledemptyspoon#m
\filledlargestar#m
\filledlozenge#m
\filledmedlozenge#m
\filledmedsquare#m
\filledmedtriangledown#m
\filledmedtriangleleft#m
\filledmedtriangleright#m
\filledmedtriangleup#m
\filledsquare#m
\filledstar#m
\filledtriangledown#m
\filledtriangleleft#m
\filledtriangleright#m
\filledtriangleup#m
\fivedots#m
\frowneq#m
\frowneqsmile#m
\frownsmile#m
\frownsmileeq#m
\geqclosed#m
\geqdot#m
\geqq#m
\geqslant#m
\geqslantdot#m
\ggg#m
\gggtr#m
\gimel#m
\gnapprox#m
\gneqq#m
\gnsim#m
\gtr#m
\gtrapprox#m
\gtrclosed#m
\gtrdot#m
\gtreqless#m
\gtreqlessslant#m
\gtreqqless#m
\gtrless#m
\gtrneqqless#m
\gtrsim#m
\gvertneqq#m
\hateq#m
\hbipropto#m
\hcrossing#m
\hdotdot#m
\hdots#m
\hookdownminus#m
\hookupminus#m
\hslash#m
\intercal#m
\intop#m
\invbackneg#m
\invneg#m
\Join#m
\landdownint#m
\landupint#m
\langlebar#m
\largecircle#m
\largediamond#m
\largeemptyfilledspoon#m
\largefilledemptyspoon#m
\largelozenge#m
\largepentagram#m
\largesquare#m
\largestar#m
\largestarofdavid#m
\largetriangledown#m
\largetriangleleft#m
\largetriangleright#m
\largetriangleup#m
\lcirclearrowdown#m
\lcirclearrowleft#m
\lcirclearrowright#m
\lcirclearrowup#m
\lcircleleftint#m
\lcirclerightint#m
\lcurvearrowdown#m
\lcurvearrowleft#m
\lcurvearrowne#m
\lcurvearrownw#m
\lcurvearrowright#m
\lcurvearrowse#m
\lcurvearrowsw#m
\lcurvearrowup#m
\leadsto#m
\leftarrowtail#m
\leftfilledspoon#m
\leftfootline#m
\leftfree#m
\lefthalfcap#m
\lefthalfcup#m
\leftharpoonccw#m
\leftharpooncw#m
\leftleftarrows#m
\leftlsquigarrow#m
\leftmapsto#m
\leftModels#m
\leftmodels#m
\leftpitchfork#m
\leftpropto#m
\leftrightarrows#m
\leftrightharpoondownup#m
\leftrightharpoons#m
\leftrightharpoonupdown#m
\Leftrightline#m
\leftrightline#m
\leftrightsquigarrow#m
\leftrsquigarrow#m
\leftslice#m
\leftspoon#m
\lefttherefore#m
\leftthreetimes#m
\leftVdash#m
\leftY#m
\leqclosed#m
\leqdot#m
\leqq#m
\leqslant#m
\leqslantdot#m
\less#m
\lessapprox#m
\lessclosed#m
\lessdot#m
\lesseqgtr#m
\lesseqgtrslant#m
\lesseqqgtr#m
\lessgtr#m
\lessneqqgtr#m
\lesssim#m
\lhd#m
\lhookdownarrow#m
\lhookleftarrow#m
\lhooknearrow#m
\lhooknwarrow#m
\lhookrightarrow#m
\lhooksearrow#m
\lhookswarrow#m
\lhookuparrow#m
\lightning#m
\llangle#m
\llcorner#m
\Lleftarrow#m
\lll#m
\llless#m
\lnapprox#m
\lneqq#m
\lnsim#m
\looparrowleft#m
\looparrowright#m
\lozenge#m
\lrcorner#m
\lsem#m
\Lsh#m
\ltimes#m
\lvertneqq#m
\lWavy#m
\lwavy#m
\maltese#m
\mathcal{letter}#m
\mathdollar#m
\mathfrak{letter}#m
\mathparagraph#m
\mathsection#m
\mathsterling#m
\measuredangle#m
\medbackslash#m
\medcircle#m
\meddiamond#m
\medlozenge#m
\medslash#m
\medsquare#m
\medstar#m
\medstarofdavid#m
\medtriangledown#m
\medtriangleleft#m
\medtriangleright#m
\medtriangleup#m
\medvert#m
\medvertdot#m
\middlebar{arg}#m
\middleslash{arg}#m
\minus#m
\minusdot#m
\minushookdown#m
\minushookup#m
\multimap#m
\mVert#m
\mvert#m
\napprox#m
\napproxeq#m
\nasymp#m
\nbackapprox#m
\nbackapproxeq#m
\nbackcong#m
\nbackeqsim#m
\nbacksim#m
\nbacksimeq#m
\nbacktriplesim#m
\nBumpeq#m
\nbumpeq#m
\ncirceq#m
\ncirclearrowleft#m
\ncirclearrowright#m
\nclosedequal#m
\ncong#m
\ncurlyeqprec#m
\ncurlyeqsucc#m
\ncurvearrowdownup#m
\ncurvearrowleft#m
\ncurvearrowleftright#m
\ncurvearrownesw#m
\ncurvearrownwse#m
\ncurvearrowright#m
\ncurvearrowrightleft#m
\ncurvearrowsenw#m
\ncurvearrowswne#m
\ncurvearrowupdown#m
\ndasharrow#m
\ndasheddownarrow#m
\ndashedleftarrow#m
\ndashednearrow#m
\ndashednwarrow#m
\ndashedrightarrow#m
\ndashedsearrow#m
\ndashedswarrow#m
\ndasheduparrow#m
\ndashleftarrow#m
\ndashrightarrow#m
\ndashv#m
\ndiagdown#m
\ndiagup#m
\ndivides#m
\nDoteq#m
\ndoteq#m
\ndoublefrown#m
\ndoublefrowneq#m
\ndoublesmile#m
\ndoublesmileeq#m
\nDownarrow#m
\ndownarrow#m
\ndownarrowtail#m
\ndowndownarrows#m
\ndownfilledspoon#m
\ndownfootline#m
\ndownfree#m
\ndownharpoonccw#m
\ndownharpooncw#m
\ndownharpoonleft#m
\ndownharpoonright#m
\ndownlsquigarrow#m
\ndownmapsto#m
\ndownModels#m
\ndownmodels#m
\ndownpitchfork#m
\ndownrsquigarrow#m
\ndownspoon#m
\ndownuparrows#m
\ndownupharpoons#m
\ndownVdash#m
\ndownvdash#m
\Nearrow#m
\nearrowtail#m
\nefilledspoon#m
\nefootline#m
\nefree#m
\neharpoonccw#m
\neharpooncw#m
\nelsquigarrow#m
\nemapsto#m
\neModels#m
\nemodels#m
\nenearrows#m
\nepitchfork#m
\neqbump#m
\neqcirc#m
\neqdot#m
\neqfrown#m
\neqsim#m
\neqslantgtr#m
\neqslantless#m
\neqsmile#m
\nequal#m
\nequalclosed#m
\nequiv#m
\nequivclosed#m
\nersquigarrow#m
\nespoon#m
\Neswarrow#m
\neswarrow#m
\neswarrows#m
\neswbipropto#m
\neswcrossing#m
\neswharpoonnwse#m
\neswharpoons#m
\neswharpoonsenw#m
\Neswline#m
\neswline#m
\neVdash#m
\nevdash#m
\nexists#m
\nfallingdotseq#m
\nfrown#m
\nfrowneq#m
\nfrowneqsmile#m
\nfrownsmile#m
\nfrownsmileeq#m
\ngeq#m
\ngeqclosed#m
\ngeqdot#m
\ngeqq#m
\ngeqslant#m
\ngeqslantdot#m
\ngets#m
\ngg#m
\nggg#m
\ngtr#m
\ngtrclosed#m
\ngtrdot#m
\ngtreqless#m
\ngtreqlessslant#m
\ngtreqqless#m
\ngtrless#m
\nhateq#m
\nhookleftarrow#m
\nhookrightarrow#m
\nin#m
\nlcirclearrowdown#m
\nlcirclearrowleft#m
\nlcirclearrowright#m
\nlcirclearrowup#m
\nlcurvearrowdown#m
\nlcurvearrowleft#m
\nlcurvearrowne#m
\nlcurvearrownw#m
\nlcurvearrowright#m
\nlcurvearrowse#m
\nlcurvearrowsw#m
\nlcurvearrowup#m
\nleadsto#m
\nLeftarrow#m
\nleftarrow#m
\nleftarrowtail#m
\nleftfilledspoon#m
\nleftfootline#m
\nleftfree#m
\nleftharpoonccw#m
\nleftharpooncw#m
\nleftharpoondown#m
\nleftharpoonup#m
\nleftleftarrows#m
\nleftlsquigarrow#m
\nleftmapsto#m
\nleftModels#m
\nleftmodels#m
\nleftpitchfork#m
\nLeftrightarrow#m
\nleftrightarrow#m
\nleftrightarrows#m
\nleftrightharpoondownup#m
\nleftrightharpoons#m
\nleftrightharpoonupdown#m
\nLeftrightline#m
\nleftrightline#m
\nleftrightsquigarrow#m
\nleftrsquigarrow#m
\nleftspoon#m
\nleftVdash#m
\nleftvdash#m
\nleq#m
\nleqclosed#m
\nleqdot#m
\nleqq#m
\nleqslant#m
\nleqslantdot#m
\nless#m
\nlessclosed#m
\nlessdot#m
\nlesseqgtr#m
\nlesseqgtrslant#m
\nlesseqqgtr#m
\nlessgtr#m
\nlhookdownarrow#m
\nlhookleftarrow#m
\nlhooknearrow#m
\nlhooknwarrow#m
\nlhookrightarrow#m
\nlhooksearrow#m
\nlhookswarrow#m
\nlhookuparrow#m
\nll#m
\nLleftarrow#m
\nlll#m
\nmapsto#m
\nmid#m
\nmodels#m
\nmultimap#m
\nNearrow#m
\nnearrow#m
\nnearrowtail#m
\nnefilledspoon#m
\nnefootline#m
\nnefree#m
\nneharpoonccw#m
\nneharpooncw#m
\nnelsquigarrow#m
\nnemapsto#m
\nneModels#m
\nnemodels#m
\nnenearrows#m
\nnepitchfork#m
\nnersquigarrow#m
\nnespoon#m
\nNeswarrow#m
\nneswarrow#m
\nneswarrows#m
\nneswharpoonnwse#m
\nneswharpoons#m
\nneswharpoonsenw#m
\nNeswline#m
\nneswline#m
\nneVdash#m
\nnevdash#m
\nNwarrow#m
\nnwarrow#m
\nnwarrowtail#m
\nnwfilledspoon#m
\nnwfootline#m
\nnwfree#m
\nnwharpoonccw#m
\nnwharpooncw#m
\nnwlsquigarrow#m
\nnwmapsto#m
\nnwModels#m
\nnwmodels#m
\nnwnwarrows#m
\nnwpitchfork#m
\nnwrsquigarrow#m
\nNwsearrow#m
\nnwsearrow#m
\nnwsearrows#m
\nnwseharpoonnesw#m
\nnwseharpoons#m
\nnwseharpoonswne#m
\nNwseline#m
\nnwseline#m
\nnwspoon#m
\nnwVdash#m
\nnwvdash#m
\not{arg}#m
\nowns#m
\nparallel#m
\nperp#m
\npitchfork#m
\nprec#m
\nprecapprox#m
\npreccurlyeq#m
\npreceq#m
\nprecsim#m
\nrcirclearrowdown#m
\nrcirclearrowleft#m
\nrcirclearrowright#m
\nrcirclearrowup#m
\nrcurvearrowdown#m
\nrcurvearrowleft#m
\nrcurvearrowne#m
\nrcurvearrownw#m
\nrcurvearrowright#m
\nrcurvearrowse#m
\nrcurvearrowsw#m
\nrcurvearrowup#m
\nRelbar#m
\nrelbar#m
\nrestriction#m
\nrhookdownarrow#m
\nrhookleftarrow#m
\nrhooknearrow#m
\nrhooknwarrow#m
\nrhookrightarrow#m
\nrhooksearrow#m
\nrhookswarrow#m
\nrhookuparrow#m
\nRightarrow#m
\nrightarrow#m
\nrightarrowtail#m
\nrightfilledspoon#m
\nrightfootline#m
\nrightfree#m
\nrightharpoonccw#m
\nrightharpooncw#m
\nrightharpoondown#m
\nrightharpoonup#m
\nrightleftarrows#m
\nrightleftharpoons#m
\nrightlsquigarrow#m
\nrightmapsto#m
\nrightModels#m
\nrightmodels#m
\nrightpitchfork#m
\nrightrightarrows#m
\nrightrsquigarrow#m
\nrightspoon#m
\nrightsquigarrow#m
\nrightVdash#m
\nrightvdash#m
\nrisingdotseq#m
\nRrightarrow#m
\nSearrow#m
\nsearrow#m
\nsearrowtail#m
\nsefilledspoon#m
\nsefootline#m
\nsefree#m
\nseharpoonccw#m
\nseharpooncw#m
\nselsquigarrow#m
\nsemapsto#m
\nseModels#m
\nsemodels#m
\nsenwarrows#m
\nsenwharpoons#m
\nsepitchfork#m
\nsersquigarrow#m
\nsesearrows#m
\nsespoon#m
\nseVdash#m
\nsevdash#m
\nshortmid#m
\nshortparallel#m
\nsim#m
\nsimeq#m
\nsmile#m
\nsmileeq#m
\nsmileeqfrown#m
\nsmilefrown#m
\nsmilefrowneq#m
\nsqdoublefrown#m
\nsqdoublefrowneq#m
\nsqdoublesmile#m
\nsqdoublesmileeq#m
\nsqeqfrown#m
\nsqeqsmile#m
\nsqfrown#m
\nsqfrowneq#m
\nsqfrowneqsmile#m
\nsqfrownsmile#m
\nsqsmile#m
\nsqsmileeq#m
\nsqsmileeqfrown#m
\nsqsmilefrown#m
\nSqsubset#m
\nsqsubset#m
\nsqsubseteq#m
\nsqsubseteqq#m
\nSqsupset#m
\nsqsupset#m
\nsqsupseteq#m
\nsqsupseteqq#m
\nsqtriplefrown#m
\nsqtriplesmile#m
\nsquigarrowdownup#m
\nsquigarrowleftright#m
\nsquigarrownesw#m
\nsquigarrownwse#m
\nsquigarrowrightleft#m
\nsquigarrowsenw#m
\nsquigarrowswne#m
\nsquigarrowupdown#m
\nSubset#m
\nsubset#m
\nsubseteq#m
\nsubseteqq#m
\nsucc#m
\nsuccapprox#m
\nsucccurlyeq#m
\nsucceq#m
\nsuccsim#m
\nSupset#m
\nsupset#m
\nsupseteq#m
\nsupseteqq#m
\nSwarrow#m
\nswarrow#m
\nswarrowtail#m
\nswfilledspoon#m
\nswfootline#m
\nswfree#m
\nswharpoonccw#m
\nswharpooncw#m
\nswlsquigarrow#m
\nswmapsto#m
\nswModels#m
\nswmodels#m
\nswnearrows#m
\nswneharpoons#m
\nswpitchfork#m
\nswrsquigarrow#m
\nswspoon#m
\nswswarrows#m
\nswVdash#m
\nswvdash#m
\nto#m
\ntriangleeq#m
\ntriangleleft#m
\ntrianglelefteq#m
\ntriangleright#m
\ntrianglerighteq#m
\ntriplefrown#m
\ntriplesim#m
\ntriplesmile#m
\ntwoheaddownarrow#m
\ntwoheadleftarrow#m
\ntwoheadnearrow#m
\ntwoheadnwarrow#m
\ntwoheadrightarrow#m
\ntwoheadsearrow#m
\ntwoheadswarrow#m
\ntwoheaduparrow#m
\nUparrow#m
\nuparrow#m
\nuparrowtail#m
\nUpdownarrow#m
\nupdownarrow#m
\nupdownarrows#m
\nupdownharpoonleftright#m
\nupdownharpoonrightleft#m
\nupdownharpoons#m
\nUpdownline#m
\nupdownline#m
\nupfilledspoon#m
\nupfootline#m
\nupfree#m
\nupharpoonccw#m
\nupharpooncw#m
\nupharpoonleft#m
\nupharpoonright#m
\nuplsquigarrow#m
\nupmapsto#m
\nupModels#m
\nupmodels#m
\nuppitchfork#m
\nuprsquigarrow#m
\nupspoon#m
\nupuparrows#m
\nupVdash#m
\nupvdash#m
\nVDash#m
\nVdash#m
\nvDash#m
\nvdash#m
\Nwarrow#m
\nwarrowtail#m
\nwfilledspoon#m
\nwfootline#m
\nwfree#m
\nwharpoonccw#m
\nwharpooncw#m
\nwlsquigarrow#m
\nwmapsto#m
\nwModels#m
\nwmodels#m
\nwnwarrows#m
\nwpitchfork#m
\nwrsquigarrow#m
\Nwsearrow#m
\nwsearrow#m
\nwsearrows#m
\nwsebipropto#m
\nwsecrossing#m
\nwseharpoonnesw#m
\nwseharpoons#m
\nwseharpoonswne#m
\Nwseline#m
\nwseline#m
\nwspoon#m
\nwVdash#m
\nwvdash#m
\oast#m
\obackslash#m
\ocirc#m
\oiint#m
\ointop$#m
\ostar#m
\otriangle#m
\overgroup{arg}#m
\overleftharpoon{arg}#m
\overlinesegment{arg}#m
\overrightharpoon{arg}#m
\overt#m
\partialvardint#*m
\partialvardlanddownint#*m
\partialvardlandupint#*m
\partialvardlcircleleftint#*m
\partialvardlcirclerightint#*m
\partialvardoiint#*m
\partialvardoint#*m
\partialvardrcircleleftint#*m
\partialvardrcirclerightint#*m
\partialvardstrokedint#*m
\partialvardsumint#*m
\partialvartint#*m
\partialvartlanddownint#*m
\partialvartlandupint#*m
\partialvartlcircleleftint#*m
\partialvartlcirclerightint#*m
\partialvartoiint#*m
\partialvartoint#*m
\partialvartrcircleleftint#*m
\partialvartrcirclerightint#*m
\partialvartstrokedint#*m
\partialvartsumint#*m
\pentagram#m
\pitchfork#m
\powerset#m
\precapprox#m
\preccurlyeq#m
\precnapprox#m
\precnsim#m
\precsim#m
\ranglebar#m
\rcirclearrowdown#m
\rcirclearrowleft#m
\rcirclearrowright#m
\rcirclearrowup#m
\rcircleleftint#m
\rcirclerightint#m
\rcurvearrowdown#m
\rcurvearrowleft#m
\rcurvearrowne#m
\rcurvearrownw#m
\rcurvearrowright#m
\rcurvearrowse#m
\rcurvearrowsw#m
\rcurvearrowup#m
\Relbar#m
\relbar#m
\restriction#m
\rhd#m
\rhookdownarrow#m
\rhookleftarrow#m
\rhooknearrow#m
\rhooknwarrow#m
\rhookrightarrow#m
\rhooksearrow#m
\rhookswarrow#m
\rhookuparrow#m
\rightarrowtail#m
\rightfilledspoon#m
\rightfootline#m
\rightfree#m
\righthalfcap#m
\righthalfcup#m
\rightharpoonccw#m
\rightharpooncw#m
\rightleftarrows#m
\rightlsquigarrow#m
\rightmapsto#m
\rightModels#m
\rightmodels#m
\rightpitchfork#m
\rightpropto#m
\rightrightarrows#m
\rightrsquigarrow#m
\rightslice#m
\rightspoon#m
\rightsquigarrow#m
\righttherefore#m
\rightthreetimes#m
\rightVdash#m
\rightvdash#m
\rightY#m
\risingdotseq#m
\rrangle#m
\Rrightarrow#m
\rsem#m
\Rsh#m
\rtimes#m
\rWavy#m
\rwavy#m
\Searrow#m
\searrowtail#m
\sefilledspoon#m
\sefootline#m
\sefree#m
\seharpoonccw#m
\seharpooncw#m
\selsquigarrow#m
\semapsto#m
\seModels#m
\semodels#m
\senwarrows#m
\senwharpoons#m
\separated#m
\sepitchfork#m
\sersquigarrow#m
\sesearrows#m
\sespoon#m
\seVdash#m
\sevdash#m
\shortmid#m
\shortparallel#m
\slashdiv#m
\smalldiamond#m
\smallfrown#m
\smalllozenge#m
\smallprod#m
\smallsetminus#m
\smallsmile#m
\smallsquare#m
\smallstar#m
\smalltriangledown#m
\smalltriangleleft#m
\smalltriangleright#m
\smalltriangleup#m
\smileeq#m
\smileeqfrown#m
\smilefrown#m
\smilefrowneq#m
\sphericalangle#m
\sqcapdot#m
\sqcapplus#m
\sqcupdot#m
\sqcupplus#m
\sqdoublefrown#m
\sqdoublefrowneq#m
\sqdoublesmile#m
\sqdoublesmileeq#m
\sqeqfrown#m
\sqeqsmile#m
\sqfrown#m
\sqfrowneq#m
\sqfrowneqsmile#m
\sqfrownsmile#m
\sqsmile#m
\sqsmileeq#m
\sqsmileeqfrown#m
\sqsmilefrown#m
\Sqsubset#m
\sqsubset#m
\sqsubseteq#m
\sqsubseteqq#m
\sqsubsetneq#m
\sqsubsetneqq#m
\Sqsupset#m
\sqsupset#m
\sqsupseteq#m
\sqsupseteqq#m
\sqsupsetneq#m
\sqsupsetneqq#m
\sqtriplefrown#m
\sqtriplesmile#m
\square#m
\squaredots#m
\squigarrowdownup#m
\squigarrowleftright#m
\squigarrownesw#m
\squigarrownwse#m
\squigarrowrightleft#m
\squigarrowsenw#m
\squigarrowswne#m
\squigarrowupdown#m
\strokedint#m
\strokethrough{arg}#m
\Subset#m
\subseteqq#m
\subsetneq#m
\subsetneqq#m
\succapprox#m
\succcurlyeq#m
\succnapprox#m
\succnsim#m
\succsim#m
\sumint#m
\Supset#m
\supseteqq#m
\supsetneq#m
\supsetneqq#m
\Swarrow#m
\swarrowtail#m
\swfilledspoon#m
\swfootline#m
\swfree#m
\swharpoonccw#m
\swharpooncw#m
\swlsquigarrow#m
\swmapsto#m
\swModels#m
\swmodels#m
\swnearrows#m
\swneharpoons#m
\swpitchfork#m
\swrsquigarrow#m
\swspoon#m
\swswarrows#m
\swVdash#m
\swvdash#m
\tbigcap#m
\tbigcapdot#m
\tbigcapplus#m
\tbigcircle#m
\tbigcup#m
\tbigcupdot#m
\tbigcupplus#m
\tbigcurlyvee#m
\tbigcurlyveedot#m
\tbigcurlywedge#m
\tbigcurlywedgedot#m
\tbigdoublecurlyvee#m
\tbigdoublecurlywedge#m
\tbigdoublevee#m
\tbigdoublewedge#m
\tbigoast#m
\tbigobackslash#m
\tbigocirc#m
\tbigodot#m
\tbigominus#m
\tbigoplus#m
\tbigoslash#m
\tbigostar#m
\tbigotimes#m
\tbigotriangle#m
\tbigovert#m
\tbigplus#m
\tbigsqcap#m
\tbigsqcapdot#m
\tbigsqcapplus#m
\tbigsqcup#m
\tbigsqcupdot#m
\tbigsqcupplus#m
\tbigtimes#m
\tbigvee#m
\tbigveedot#m
\tbigwedge#m
\tbigwedgedot#m
\tcomplement#m
\tcoprod#m
\therefore#m
\thickapprox#m
\thicksim#m
\thinstar#m
\tidotsint#m
\tiiiint#m
\tiiint#m
\tiint#m
\tint#m
\tlanddownint#m
\tlandupint#m
\tlcircleleftint#m
\tlcirclerightint#m
\toiint#m
\toint#m
\tprod#m
\trcircleleftint#m
\trcirclerightint#m
\triangledown#m
\triangleeq#m
\trianglelefteq#m
\triangleq#m
\trianglerighteq#m
\triplefrown#m
\triplesim#m
\triplesmile#m
\tstrokedint#m
\tsum#m
\tsumint#m
\twoheaddownarrow#m
\twoheadleftarrow#m
\twoheadnearrow#m
\twoheadnwarrow#m
\twoheadrightarrow#m
\twoheadsearrow#m
\twoheadswarrow#m
\twoheaduparrow#m
\udotdot#m
\udots#m
\ulcorner#m
\ullcorner#m
\ulrcorner#m
\undergroup{arg}#m
\underlinesegment{arg}#m
\unlhd#m
\unrhd#m
\uparrowtail#m
\upbrace#m
\upbraceg#*m
\upbracegg#*m
\upbraceggg#*m
\upbracegggg#*m
\updownarrows#m
\updownharpoonleftright#m
\updownharpoonrightleft#m
\updownharpoons#m
\Updownline#m
\updownline#m
\upfilledspoon#m
\upfootline#m
\upfree#m
\upharpoonccw#m
\upharpooncw#m
\upharpoonleft#m
\upharpoonright#m
\uplsquigarrow#m
\upmapsto#m
\upModels#m
\upmodels#m
\uppitchfork#m
\uppropto#m
\uprsquigarrow#m
\upslice#m
\upspoon#m
\uptherefore#m
\upuparrows#m
\upVdash#m
\upvdash#m
\upY#m
\urcorner#m
\utimes#m
\varnothing#m
\varpropto#m
\varsubsetneq#m
\varsubsetneqq#m
\varsupsetneq#m
\varsupsetneqq#m
\vartriangle#m
\vartriangleleft#m
\vartriangleright#m
\vbipropto#m
\vcrossing#m
\VDash#m
\vDash#m
\Vdash#m
\vdotdot#m
\veebar#m
\veedot#m
\vertbowtie#m
\vertdiv#m
\Vvdash#m
\wedgedot#m
\wideparen{arg}#m
\wreath#m

\circledR
\circledS
\yen

\Finv#*m
\Game#*m
\Bbbk#*m
\backepsilon#*m
\digamma#*m
\eth#*m
\mho#*m
\lhook#*m
\rhook#*m
\varkappa#*m
