# musixtex package
# Matthew Bertucci 2023/01/13 for v1.36

# from musixltx.tex
\begin{music}
\end{music}

# from musixtex.tex
\absoluteaccid
\accshift#L
\addspace{length}
\afterruleskip#L
\akkoladen{%<{lower1}{upper1}{lower2}{upper2}{lower3}{upper3}%>}
\alaligne
\alapage
\allabreve
\altitude#*
\alto
\altoclef
\altplancher#*
\altportee#*
\arithmeticskipscale
\arpeggio{pitch}{interlignes}
\atnextbar
\atnextline#*
\backturn{pitch}
\bar
\barno
\barnoadd#*
\barnumbers
\barre
\bass
\bassclef
\basslowoct
\bassoct
\beforeruleskip#L
\bhsk
\bigaccid
\bigdfl{pitch}
\bigdsh{pitch}
\bigfl{pitch}
\bigna{pitch}
\bigsh{pitch}
\bigtype
\Bigtype
\BIgtype
\BIGtype
\blppz{pitch}
\blpz{pitch}
\blsf{pitch}
\blsfz{pitch}
\blst{pitch}
\bltext{n}
\boxit{text}
\boxitsep#*
\bqsk
\bracket{pitch}{internotes}
\breakslur{n}{pitch}
\breve{pitch}
\bsk
\btsk
\buppz{pitch}
\bupz{pitch}
\busf{pitch}
\busfz{pitch}
\bust{pitch}
\butext{n}
\ca{pitch}
\caesura
\catcodesmusic
\cbreath
\cca{pitch}
\ccca{pitch}
\cccca{pitch}
\ccccca{pitch}
\cccccl{pitch}
\cccccu{pitch}
\ccccl{pitch}
\ccccu{pitch}
\cccl{pitch}
\cccu{pitch}
\cchar{pitch-num}{text}
\ccharnote{pitch}{text}
\ccl{pitch}
\cclp
\ccn{pitch}{text}
\ccu{pitch}
\ccup
\cdfl{pitch}
\cdsh{pitch}
\centerbar{symbol}
\centerhpause
\centerHpause
\centerpause
\centerPAuse
\centerPAUSe
\cfl{pitch}
\changeclefs
\Changeclefs
\changecontext
\Changecontext
\changesignature
\chpause
\cHpause{n}
\circleit{text}
\cl{pitch}
\clp{pitch}
\clpp{pitch}
\cmidstaff{text}
\cna{pitch}
\coda %<<pitch>%>
\Coda %<<pitch>%>
\contpiece
\Contpiece
\cPAUSe
\cPAuse
\cpause
\crescendo{length}
\csh{pitch}
\csong{text}
\cu{pitch}
\cup{pitch}
\cupp{pitch}
\curlybrackets{%<{lower1}{upper1}{lower2}{upper2}...%>}
\curve{h}{i}{j}
\decrescendo{length}
\DefaultStemlength
\DEP
\Dep
\dfl{pitch}
\dhsong{text}
\dotted
\doublebar
\doublethumb{pitch}
\downbow
\downtrio{pitch}{noteskips}{slope}
\downtuplet{pitch}{noteskips}{slope}
\Dqbbl
\Dqbbu
\Dqbl
\Dqbu
\ds
\dsh{pitch}
\dsp
\dspp
\duevolte
\eightbf#S
\eightit#S
\eightrm#S
\elemskip#L
\en
\endcatcodesmusic
\endextract
\endmuflex
\Endpiece
\endpiece
\endvolta
\endvoltabox
\enotes#*
\everystaff#*
\extractline#*
\f
\fermatadown{pitch}
\Fermatadown{pitch}
\Fermataup{pitch}
\fermataup{pitch}
\fetafont#S
\fetalargefont#S
\fetaLargefont#S
\fetanorfont#S
\fetasmallfont#S
\fetatinyfont#S
\ff
\fff
\ffff
\fl{pitch}
\flageolett{pitch}
\fontbarno#*
\fp
\frtbf#S
\generalmeter{meter}
\generalsignature{sharps}
\geometricskipscale
\grcl{pitch}
\grcu{pitch}
\groupbottom{g}{m}
\grouptop{g}{n}
\ha{pitch}
\hap{pitch}
\happ{pitch}
\hardlyrics{text}
\hardspace{length}
\hb{n}{pitch}
\hbp{n}{pitch}
\hbpp{n}{pitch}
\hbsk
\hidebarrule{n}
\Hidebarrule{n}
\hl{pitch}
\hloff{notes}
\hlp{pitch}
\hlpp{pitch}
\hp
\hpause
\Hpause{pitch}{noteskips}
\hpausep
\hpausepp
\hpp
\hppp
\hqsk
\hroff{notes}
\hs
\hsk
\hsong{text}
\hsp
\hspp
\hu{pitch}
\hup{pitch}
\hupp{pitch}
\ibbbbbl{n}{pitch}{slope}
\Ibbbbbl{n}{pitch1}{pitch2}{noteskip}
\ibbbbbu{n}{pitch}{slope}
\Ibbbbbu{n}{pitch1}{pitch2}{noteskip}
\ibbbbl{n}{pitch}{slope}
\Ibbbbl{n}{pitch1}{pitch2}{noteskip}
\ibbbbu{n}{pitch}{slope}
\Ibbbbu{n}{pitch1}{pitch2}{noteskip}
\ibbbl{n}{pitch}{slope}
\Ibbbl{n}{pitch1}{pitch2}{noteskip}
\ibbbu{n}{pitch}{slope}
\Ibbbu{n}{pitch1}{pitch2}{noteskip}
\ibbl{n}{pitch}{slope}
\Ibbl{n}{pitch1}{pitch2}{noteskip}
\ibbu{n}{pitch}{slope}
\Ibbu{n}{pitch1}{pitch2}{noteskip}
\ibl{n}{pitch}{slope}
\Ibl{n}{pitch1}{pitch2}{noteskip}
\ibslurd{n}{pitch}
\ibsluru{n}{pitch}
\ibu{n}{pitch}{slope}
\Ibu{n}{pitch1}{pitch2}{noteskip}
\icresc
\ifactiveinstrument
\iftabstylespace#*
\ignorenats
\instrumentnumber{n}
\interbeam#L
\interfacteur#*
\interinstrument#L
\Interligne#L
\internote#L
\Internote#L
\interportee#L
\interstaff{factor}
\invertslur{n}
\Ioctfindown{n}{pitch}
\ioctfindown{pitch}
\Ioctfinup{n}{pitch}
\ioctfinup{pitch}
\islurd{n}{pitch}
\Islurdbreak{n}{pitch}
\isluru{n}{pitch}
\Islurubreak{n}{pitch}
\isslurd{n}{pitch}
\issluru{n}{pitch}
\itenl{n}{pitch}
\Itenl{n}{pitch}#S
\itenu{n}{pitch}
\Itenu{n}{pitch}#S
\itied{n}{pitch}
\itieu{n}{pitch}
\Itrille{n}{pitch}
\ITrille{n}{pitch}
\kernm#*
\largemusicsize
\Largemusicsize
\largenotesize
\Largenotesize
\Largevalue
\largevalue
\larpeggio{pitch}{interlignes}
\lchar{pitch-num}{text}
\lcharnote{pitch}{text}
\lcl{pitch}
\lcn{pitch}{text}
\lcu{pitch}
\ldfl{pitch}
\ldsh{pitch}
\leftrepeat
\leftrightrepeat
\lfl{pitch}
\lh{pitch}
\lhl{pitch}
\lhp{pitch}
\lhu{pitch}
\lifthpause{n}
\lifthpausep{n}
\Liftoctline
\liftpause{n}
\liftpausep{n}
\Liftslur{n}{h}
\linegoal
\lmidstaff{text}
\lna{pitch}
\loff{notes}
\loffset{num}{notes}
\longa{pitch}
\longaa{pitch}
\lpar{pitch}
\lpppt{pitch}
\lppt{pitch}
\lppz{pitch}
\lpt{pitch}
\lpz{pitch}
\lpzst{pitch}
\lql{pitch}
\lqp{pitch}
\lqu{pitch}
\lrlap{text}
\lsf{pitch}
\lsfz{pitch}
\lsh{pitch}
\lsong{text}
\lst{pitch}
\ltab{n}{pitch}
\lw{pitch}
\maxima{pitch}
\meddyn
\medtype
\meterC
\meterfont#*
\meterfrac{numerator}{denominator}
\meterlargefont#*
\meterLargefont#*
\meterN
\meterplus
\meterskip%<<dimen>%>
\metron{note}{tempo}
\metronequiv{note1}{note2}
\mf
\midslur{h}
\mordent{pitch}
\Mordent{pitch}
\mp
\mulooseness
\multnoteskip{num}
\musicparskip
\musixtex
\na{pitch}
\nbbbbbl{n}
\nbbbbbu{n}
\nbbbbl{n}
\nbbbbu{n}
\nbbbl{n}
\nbbbl{n}
\nbbbu{n}
\nbbl{n}
\nbbu{n}
\nbinstruments#*
\nextinstrument
\nextstaff
\nh{pitch}
\ninebf#S
\nineit#S
\ninerm#S
\nnnotes
\nnotes
\nobarnumbers
\normalmusicsize
\normalnotesize
\normaltranspose
\normalvalue
\normdyn
\normtype
\nostartrule
\nostemcut
\Notes
\notes
\NOtes
\NOTes
\NOTEs
\NOTES#*
\noteskip#L
\notesp
\Notesp
\NOtesp
\NOTesp
\NOTEsp#*
\nq{pitch}
\nqqb{n}{pitch}
\nqqh{n}{pitch}
\nqql{n}{pitch}
\nqqqb{n}{pitch}
\nqqqh{n}{pitch}
\nqqql{n}{pitch}
\nqqqu{n}{pitch}
\nqqu{n}{pitch}
\nspace
\octfindown{staff-level}{noteskips}
\octfinup{staff-level}{noteskips}
\octnumberdown#*
\octnumberup#*
\off{length}
\ovbkt{pitch}{noteskips}{slope}
\p
\pause
\PAuse
\PAUSe
\pausep
\pausepp
\pdld
\pdlu
\pdlud
\PED
\Ped
\pp
\ppff
\ppffsixteen
\ppfftwelve
\ppfftwenty
\ppfftwentyfour
\ppfftwentynine
\ppp
\pppp
\pppt{pitch}
\ppt{pitch}
\prevstaff
\pt{pitch}
\ptr{pitch}
\qa{pitch}
\qap{pitch}
\qapp{pitch}
\qb{n}{pitch}
\qbp{pitch}
\qbpp{pitch}
\ql{pitch}
\qlp{pitch}
\qlpp{pitch}
\qp
\qpp
\qppp
\Qqbbl
\Qqbbu
\Qqbl
\Qqbu
\qqs
\qqsk
\qqsp
\qqspp
\qs
\qsk
\qsp
\qspace
\qspp
\qu{pitch}
\qup{pitch}
\qupp{pitch}
\raggedstoppiece
\raisebarno#*
\raiseped#*
\raisevolta#L
\rcl{pitch}
\rcu{pitch}
\relativeaccid
\resetclefsymbols
\resetlayout
\reverseallabreve
\reverseC
\rh{pitch}
\rhl{pitch}
\rhp{pitch}
\rhu{pitch}
\rightrepeat
\roff{notes}
\roffset{num}{notes}
\rpar{pitch}
\rql{pitch}
\rqp{pitch}
\rqu{pitch}
\rtab{n}{pitch}
\rw{pitch}
\scale{factor}
\sDEP
\sDep
\Segno
\segno %<<pitch>%>
\selectinstrument{n}
\selectstaff{n}
\sepbarrules
\setaltoclefsymbol{n}{symbol}
\setbassclefsymbol{n}{symbol}
\setclef{n}{digit-or-clef}
\setclefsymbol{n}{symbol}
\setdoublebar
\setdoubleBAR
\setemptybar
\setendvolta
\setendvoltabox
\setinterinstrument{n}{length}
\setinterstaff{n}{factor}
\setleftrepeat
\setleftrightrepeat
\setlines{n}{lines}
\setmaxcclvibeams{m}
\setmaxcxxviiibeams{m}
\setmaxgroups{m}
\setmaxinstruments{m}
\setmaxoctlines{m}
\setmaxslurs{m}
\setmaxtrills{m}
\setmeter{%<n%>}{%<{m1}{m2}...%>}
\setname{n}{instrument-name}
\setrightrepeat
\setsign{n}{sharps}
\setsize{n}{factor}
\setsongraise{n}{length}
\setstaffs{n}{staves}
\settrebleclefsymbol{n}{symbol}
\Setvolta{text}
\setvolta{text}
\setvoltabox{text}
\sevenbf#S
\sevenit#S
\sevenrm#S
\sF
\sfz
\sfzp
\sh{pitch}
\shake{pitch}
\Shake{pitch}
\Shakel{pitch}
\Shakene{pitch}
\Shakenw{pitch}
\Shakesw{pitch}
\shiftbarno#*
\showallbarrules
\showbarrule{n}
\Showbarrule{n}
\sk
\slide{pitch}{internotes}{slope}
\slur{pitch1}{pitch2}{u|d}{noteskips}
\smallaccid
\smallaltoclef
\smallbassclef
\smallbasslowoct
\smallbassoct
\smalldfl{pitch}
\smalldsh{pitch}
\smalldyn
\smallfl{pitch}
\smallmusicsize
\smallna{pitch}
\smallnotesize
\smallsh{pitch}
\smalltrebleclef
\smalltreblelowoct
\smalltrebleoct
\smalltype
\Smalltype
\smallvalue
\softlyrics{text}
\songbottom{m}
\songtop{n}
\soupir
\sPED
\sPed
\sslur{pitch1}{pitch2}{u|d}{noteskips}
\staffbotmarg#L
\stafftopmarg#L
\startbarno
\startextract
\startmuflex
\startpiece
\startrule
\stdbarrules
\stdstemfalse
\stemcut
\stemfactor#*
\stemlength{number}
\stie{pitch}{u|d}{noteskips}
\stoppiece
\Stoppiece
\svtbf#S
\systemheight#L
\systemnumbers
\tab{n}{pitch}
\tabclef
\tabfnt#*
\tabstringfnt#*
\tabstylespacefalse#*
\tabstylespacetrue
\tbbbbbl{n}
\tbbbbbu{n}
\tbbbbl{n}
\tbbbbu{n}
\tbbbl{n}
\tbbbu{n}
\tbbl{n}
\tbbu{n}
\tbl{n}
\tbslurd{n}{pitch}
\tbsluru{n}{pitch}
\tbu{n}
\tcresc
\tdbslur{n}{pitch}#*
\tdecresc
\tenbf#S
\tenbi#S
\tenit#S
\tenrm#S
\tensc#S
\thelyrics
\thsong{text}
\tie{pitch}{u|d}{noteskips}
\tinydyn
\tinynotesize
\tinytype
\tinyvalue
\Toctfin{n}
\tqb{n}{pitch}
\Tqbbl
\Tqbbu
\Tqbl
\Tqbu
\tqh{n}{pitch}
\tql{n}{pitch}
\tqqb{n}{pitch}
\tqqh{n}{pitch}
\tqql{n}{pitch}
\tqqqb{n}{pitch}
\tqqqh{n}{pitch}
\tqqql{n}{pitch}
\tqqqu{n}{pitch}
\tqqu{n}{pitch}
\tqsk
\tqu{n}{pitch}
\tr{pitch}
\transpose
\treble
\trebleclef
\treblelowoct
\trebleoct
\trille{pitch}{noteskips}
\Trille{pitch}{noteskips}
\triolet{pitch}
\trml{pitch}
\Trml{pitch}
\trmu{pitch}
\Trmu{pitch}
\trrml{pitch}
\Trrml{pitch}
\trrmu{pitch}
\Trrmu{pitch}
\trrrml{pitch}
\Trrrml{pitch}
\trrrmu{pitch}
\Trrrmu{pitch}
\trt{pitch}
\tslur{n}{pitch}
\Tslurbreak{n}{pitch}
\tsslur{n}{pitch}
\tten{n}
\Tten{n}#S
\ttie{n}
\TTrille#S
\Ttrille{n}
\tubslur{n}{pitch}#*
\tuplettxt#*
\turn{pitch}
\twelvebf#S
\twelvebi#S
\twelveit#S
\twelverm#S
\twelvesc#S
\twfvbf#S
\twtybf#S
\txt#*
\txtfont#*
\tzccu
\tzcu
\tzcup
\tzhu
\tzhup
\tzqu
\tzqup
\tzwh
\tzwhp
\unbkt{pitch}{noteskips}{slope}
\upbow
\upperfl{pitch}
\upperna{pitch}
\uppersh{pitch}
\uppz{pitch}
\uptext{text}
\Uptext{text}
\uptrio{pitch}{noteskips}{slope}
\uptuplet{pitch}{noteskips}{slope}
\upz{pitch}
\upzst{pitch}
\usf{pitch}
\usfz{pitch}
\ust{pitch}
\varaccid
\varline{height}{length}{slope}
\vnotes{num}
\voltadot#*
\wh{pitch}
\wholeshift{macro}
\whp{pitch}
\whpp{pitch}
\wq{pitch}
\wqq{pitch}
\writebarno#*
\writethebarno#*
\writezbarno#*
\xbar
\xtr{pitch}
\xtuplet{k}{pitch}
\xxtuplet%<<a>%>:%<<b><pitch>%>
\zalaligne
\zalapage
\zbar
\zbreath
\zbreve{pitch}
\zcccccl{pitch}
\zcccccu{pitch}
\zccccl{pitch}
\zccccu{pitch}
\zcccl{pitch}
\zcccu{pitch}
\zccl{pitch}
\zcclp
\zccu{pitch}
\zccup
\zchangeclefs
\zchangecontext
\zchar{pitch-num}{text}
\zcharnote{pitch}{text}
\zcl{pitch}
\zclp{pitch}
\zclpp
\zcn{pitch}{text}
\zcu{pitch}
\zcup{pitch}
\zcupp
\zdoublebar
\zendextract
\zendpiece
\zh{pitch}
\zhl{pitch}
\zhlp{pitch}
\zhlpp
\zhp{pitch}
\zhpp{pitch}
\zhu{pitch}
\zhup{pitch}
\zhupp
\zleftrepeat
\zleftrightrepeat
\zlonga{pitch}
\zltab{n}{pitch}
\zmaxima{pitch}
\zmidstaff{text}
\znh{pitch}
\znotes
\znq{pitch}
\zq{pitch}
\zqb{n}{pitch}
\zqbp{pitch}
\zqbpp
\zql{pitch}
\zqlp{pitch}
\zqlpp
\zqp{pitch}
\zqpp{pitch}
\zqu{pitch}
\zqup{pitch}
\zqupp
\zrightrepeat
\zrtab{n}{pitch}
\zsong{text}
\zstoppiece
\ztab{n}{pitch}
\ztqb{n}{pitch}
\ztqh{n}{pitch}
\ztql{n}{pitch}
\ztqu{n}{pitch}
\zw{pitch}
\zwh{pitch}#*
\zwp{pitch}
\zwpp{pitch}
\zwq{pitch}
\zwqq{pitch}
\zzbar
\zzdoublebar
\zzleftrepeat
\zzleftrightrepeat
\zzrightrepeat

# not documented
\advancefalse#S
\advancetrue#S
\begininstrument#S
\beginstaff#S
\BIGfont#S
\BIgfont#S
\Bigfont#S
\bigfont#S
\bigwedgebox#S
\catcodeat#S
\catcodesmusicfalse#S
\catcodesmusictrue#S
\charnote{arg1}{arg2}#S
\dppz#S
\dpz#S
\dpzst#S
\dsf#S
\dsfz#S
\dst#S
\eightbi#S
\eightdc#S
\eightsc#S
\eightsl#S
\eightss#S
\eighttt#S
\elevenbf#S
\elevenbi#S
\elevendc#S
\elevenit#S
\elevenrm#S
\elevensc#S
\elevenss#S
\fivedc#S
\fontid#S
\fourdc#S
\freqbarno#S
\frtbi#S
\frtdc#S
\frtit#S
\frtrm#S
\frtsc#S
\frtsl#S
\frtss#S
\frttt#S
\getcurpos#S
\halfwidthbigwedge#S
\hardnotes{arg1}#S
\hchar{arg1}{arg2}#S
\hcharnote#S
\hlthick#*
\hslurd#S
\hslurdd#S
\hslurdeleven#S
\hslurdelevend#S
\hslurdsixteen#S
\hslurdsixteend#S
\hslurdthirteen#S
\hslurdthirteend#S
\hslurdtwenty#S
\hslurdtwentyd#S
\hslurdtwentyfour#S
\hslurdtwentyfourd#S
\hslurdtwentynine#S
\hslurdtwentynined#S
\hsluru#S
\hslurud#S
\hslurueleven#S
\hsluruelevend#S
\hslurusixteen#S
\hslurusixteend#S
\hsluruthirteen#S
\hsluruthirteend#S
\hslurutwenty#S
\hslurutwentyd#S
\hslurutwentyfour#S
\hslurutwentyfourd#S
\hslurutwentynine#S
\hslurutwentynined#S
\ifadvance#S
\ifcatcodesmusic#S
\iflongDCfontnames#S
\iflongECfontnames#S
\ihslurd#S
\ihsluru#S
\inmux#S
\IslurdbreakPrevBar{arg1}{arg2}#S
\IslurubreakPrevBar{arg1}{arg2}e#S
\istied#S
\istieu#S
\itrille#S
\keychar#S
\lastbarno#S
\lastbarpos#S
\lhpp{arg1}#S
\lineset{arg1}{arg2}{arg3}{arg4}{arg5}#S
\longDCfontnamesfalse#S
\longDCfontnamestrue#S
\longECfontnamesfalse#S
\longECfontnamestrue#S
\lowersonginstrum#S
\lqpp{arg1}#S
\ltabbox{arg1}{arg2}#S
\lthick#S
\lwp{arg1}#S
\lwpp{arg1}#S
\maxtrilles#S
\medppff#S
\meterbigfont#S
\meternorfont#S
\metersmallfont#S
\mezzopiano#S
\musiceleven#S
\musickeyfont#S
\musicLargefont#S
\musiclargefont#S
\musicnorfont#S
\musicsixteen#S
\musicsize#S
\musicsmallfont#S
\musicthirteen#S
\musictinyfont#S
\musictwenty#S
\musictwentyfour#S
\musictwentynine#S
\musixchar#S
\musixfont#S
\mxdate#S
\mxmajorvernumber#S
\mxminorvernumber#S
\mxsps#S
\mxvernumber#S
\mxversion#S
\mxversuffix#S
\nblines#S
\ninebi#S
\ninedc#S
\ninesc#S
\ninesl#S
\niness#S
\ninett#S
\nobarmessages#S
\nolinemessages#S
\normppff#S
\nslashes#S
\numslashes#S
\octnumber#S
\octnumberdefault#S
\outmux#S
\pChangecontext#S
\pchangecontext#S
\qlrlap{arg1}#S
\rhpp{arg1}#S
\rqpp{arg1}#S
\rtabbox{arg1}{arg2}#S
\rwp{arg1}#S
\rwpp{arg1}#S
\scalenoteskip#S
\setclefs#S
\sevenbi#S
\sevendc#S
\sevensc#S
\sevenss#S
\sixdc#S
\sld#S
\sldd#S
\slu#S
\slud#S
\slurd#S
\slurdd#S
\slurdeleven#S
\slurdelevend#S
\slurdsixteen#S
\slurdsixteend#S
\slurdthirteen#S
\slurdthirteend#S
\slurdtwenty#S
\slurdtwentyd#S
\slurdtwentyfour#S
\slurdtwentyfourd#S
\slurdtwentynine#S
\slurdtwentynined#S
\sluru#S
\slurud#S
\slurueleven#S
\sluruelevend#S
\slurusixteen#S
\slurusixteend#S
\sluruthirteen#S
\sluruthirteend#S
\slurutwenty#S
\slurutwentyd#S
\slurutwentyfour#S
\slurutwentyfourd#S
\slurutwentynine#S
\slurutwentynined#S
\slurz#S
\slurzd#S
\slz#S
\slzd#S
\smallppff#S
\stringnum#S
\stringraise#S
\svtbi#S
\svtdc#S
\svtit#S
\svtrm#S
\svtsc#S
\svtsl#S
\svttt#S
\tabbox{arg1}{arg2}#S
\tabcleffnt#S
\tabfntsixteen#S
\tabfntthirteen#S
\tabfnttwenty#S
\tabfnttwentyfour#S
\tabfnttwentynine#S
\tabLargecleffnt#S
\tablargecleffnt#S
\tabLargefnt#S
\tablargefnt#S
\tabnorcleffnt#S
\tabnorfnt#S
\tabsmallcleffnt#S
\tabsmallfnt#S
\tendc#S
\tensl#S
\tenss#S
\tentt#S
\threedc#S
\tinyppff#S
\Tleg#S
\tleg{arg1}#S
\toctfin#S
\TrilleX#S
\trilleX#S
\TslurbreakNextBar{arg1}{arg2}#S
\tTrille#S
\ttrille#S
\twelvedc#S
\twelvesl#S
\twelvess#S
\twelvett#S
\twfvbf#S
\twfvbi#S
\twfvit#S
\twfvrm#S
\twfvsc#S
\twfvsl#S
\twfvtt#S
\twtybi#S
\twtydc#S
\twtyit#S
\twtyrm#S
\twtysc#S
\twtysl#S
\twtytt#S
\tzcccu#S
\tzcccup#S
\tzccup#S
\uplap{arg1}#S
\uppersonginstrum#S
\xgregfont#S
\xgregLargefont#S
\xgreglargefont#S
\xgregnorfont#S
\xgregsmallfont#S
\xgregtinyfont#S
\xtie#S
\xtied#S
