# natbib package
# author: Jan Sundermeyer 12/2009
\citet{keylist}#c
\citet[postfix]{keylist}
\citep{keylist}#c
\citep[postfix]{keylist}
\citep[prefix][postfix]{keylist}
\cite[prefix][postfix]{keylist}
\citet*{keylist}#c
\citep*{keylist}#c
\citealt{keylist}#c
\citealt*{keylist}#c
\citealp{keylist}#c
\citealp*{keylist}#c
\citealp[postfix]{keylist}
\citenum{keylist}#c
\citetext{text}
\citeauthor{keylist}#c
\citeauthor*{keylist}#c
\citefullauthor{keylist}#c
\citeyear{keylist}#c
\citeyearpar{keylist}#c
\Citet{keylist}#c
\Citet[postfix]{keylist}
\Citep{keylist}#c
\Citep[postfix]{keylist}
\Citep[prefix][postfix]{keylist}
\Citet*{keylist}#c
\Citep*{keylist}#c
\Citealt{keylist}#c
\Citealt*{keylist}#c
\Citealp{keylist}#c
\Citealp*{keylist}#c
\Citealp[postfix]{keylist}
\Citeauthor{keylist}#c
\Citeauthor*{keylist}#c
\defcitealias{keylist}{alias}
\citetalias{keylist}
\citepalias{keylist}
