# newcomputermodern package
# Matthew Bertucci 12/11/2021 for v4.0

#include:fontspec
#include:unicode-math

\textprosgegrammeni{text%plain}
\prosgegrammeni
\textivbce{text%plain}
\ivbce
\textvibce{text%plain}
\vibce
\textivbcealt{text%plain}
\ivbcealt
\ipatext
\ipatextsans
\textipa{text%plain}
\textsansipa{text%plain}
\uncial
\textuncial{text}

\atticonequarter#*
\hermionianfifty#*
\atticonehalf#*
\thespianfifty#*
\atticonedrachma#*
\thespianonehundred#*
\atticfive#*
\thespianthreehundred#*
\atticfifty#*
\epidaurianfivehundred#*
\atticfivehundred#*
\troezenianfivehundred#*
\atticfivethousand#*
\thespianfivehundred#*
\atticfiftythousand#*
\carystianfivehundred#*
\atticfivetalents#*
\naxianfivehundred#*
\attictentalents#*
\thespianonethousand#*
\atticfiftytalents#*
\thespianfivethousand#*
\atticonehundredtalents#*
\delphicfivemnas#*
\atticfivehundredtalents#*
\stratianfiftymnas#*
\atticonethousandtalents#*
\greekonehalfsign#*
\atticfivethousandtalents#*
\greekonehalfsignalt#*
\atticfivestaters#*
\greektwothirdssign#*
\attictenstaters#*
\greekthreequarterssign#*
\atticfiftystaters#*
\greekyearsign#*
\atticonehundredstaters#*
\greektalentsign#*
\atticfivehundredstaters#*
\greekdrachmasign#*
\atticonethousandstaters#*
\greekobolsign#*
\attictenthousandstaters#*
\greektwoobolssign#*
\atticfiftythousandstaters#*
\greekthreeobolssign#*
\attictenmnas#*
\greekfourobolssign#*
\heraleumoneplethron#*
\greekfiveobolssign#*
\thespianone#*
\greekmetretessign#*
\ermionianone#*
\greekkyathosbasesign#*
\epidauriantwo#*
\greeklytrasign#*
\thespiantwo#*
\greekounkiasign#*
\cyrenaictwodrachmas#*
\greekxestessign#*
\epidauriantwodrachmas#*
\greekartabesign#*
\troezenianfive#*
\greekarourasign#*
\troezenianten#*
\greekgrammasign#*
\troezeniantenalt#*
\greektryblionbasesign#*
\hermionianten#*
\greekzerosign#*
\messenianten#*
\greekonequartersign#*
\thespianten#*
\greeksinusoidsign#*
\thespianthirty#*
\greekindictionsign#*
\troezenianfifty#*
\nomismasign#*
\troezenianfiftyalt#*

\chemalpha
\chembeta
\chemgamma
\chemdelta
\chemepsilon
\chemzeta
\chemeta
\chemtheta
\chemiota
\chemkappa
\chemlambda
\chemmu
\chemnu
\chemxi
\chemomicron
\chempi
\chemrho
\chemrhoalt
\chemsigma
\chemsigmaalt
\chemtau
\chemupsilon
\chemphi
\chemchi
\chempsi
\chemomega
\chemAlpha
\chemBeta
\chemGamma
\chemDelta
\chemEpsilon
\chemZeta
\chemEta
\chemTheta
\chemIota
\chemKappa
\chemLambda
\chemMu
\chemNu
\chemXi
\chemOmicron
\chemPi
\chemRho
\chemSigma
\chemTau
\chemUpsilon
\chemPhi
\chemChi
\chemPsi
\chemOmega

\accurrent#m
\acidfree#m
\acwcirclearrow#m
\acwgapcirclearrow#m
\acwleftarcarrow#m
\acwopencirclearrow#m
\acwoverarcarrow#m
\acwunderarcarrow#m
\adots#m
\angdnr#m
\angles#m
\angleubar#m
\Angstrom#m
\annuity{arg}#m
\APLboxquestion#m
\APLboxupcaret#m
\APLnotbackslash#m
\APLnotslash#m
\approxeqq#m
\approxident#m
\arabichad#m
\arabicmaj#m
\arceq#m
\assert#m
\asteq#m
\asteraccent{arg}#m
\astrosun#m
\awint#m
\backcong#m
\backdprime#m
\backtrprime#m
\bagmember#m
\barcap#m
\barcup#m
\bardownharpoonleft#m
\bardownharpoonright#m
\barleftarrow#m
\barleftarrowrightarrowbar#m
\barleftharpoondown#m
\barleftharpoonup#m
\barovernorthwestarrow#m
\barrightarrowdiamond#m
\barrightharpoondown#m
\barrightharpoonup#m
\baruparrow#m
\barupharpoonleft#m
\barupharpoonright#m
\Barv#m
\barV#m
\barvee#m
\Bbbeight#*m
\Bbbfive#*m
\Bbbfour#*m
\Bbbgamma#*m
\BbbGamma#*m
\Bbbnine#*m
\Bbbone#*m
\Bbbpi#*m
\BbbPi#*m
\Bbbseven#*m
\Bbbsix#*m
\Bbbsum#*m
\Bbbthree#*m
\Bbbtwo#*m
\Bbbzero#*m
\bbrktbrk#m
\bdtriplevdash#m
\benzenr#m
\bigblacktriangledown#m
\bigblacktriangleup#m
\bigbot#m
\bigcupdot#m
\biginterleave#m
\bigslopedvee#m
\bigslopedwedge#m
\bigsqcap#m
\bigtalloblong#m
\bigtimes#m
\bigtop#m
\bigtriangleleft#m
\bigwhitestar#m
\blackcircledownarrow#m
\blackcircledrightdot#m
\blackcircledtwodots#m
\blackcircleulquadwhite#m
\blackdiamonddownarrow#m
\blackhourglass#m
\blackinwhitediamond#m
\blackinwhitesquare#m
\blacklefthalfcircle#m
\blackpointerleft#m
\blackpointerright#m
\blackrighthalfcircle#m
\blacksmiley#m
\blanksymbol#m
\blkhorzoval#m
\blkvertoval#m
\blockfull#m
\blockhalfshaded#m
\blocklefthalf#m
\blocklowhalf#m
\blockqtrshaded#m
\blockrighthalf#m
\blockthreeqtrshaded#m
\blockuphalf#m
\bNot#m
\botsemicircle#m
\boxast#m
\boxbar#m
\boxbox#m
\boxbslash#m
\boxcircle#m
\boxdiag#m
\boxonbox#m
\bsimilarleftarrow#m
\bsimilarrightarrow#m
\bsolhsub#m
\btimes#m
\bullseye#m
\bumpeqq#m
\candra{arg}#m
\capbarcup#m
\capdot#m
\capovercup#m
\capwedge#m
\caretinsert#m
\carriagereturn#m
\ccwundercurvearrow#m
\cirbot#m
\circlebottomhalfblack#m
\circledbullet#m
\circledequal#m
\circledownarrow#m
\circledparallel#m
\circledrightdot#m
\circledstar#m
\circledtwodots#m
\circledvert#m
\circledwhitebullet#m
\circlehbar#m
\circlelefthalfblack#m
\circlellquad#m
\circlelrquad#m
\circleonleftarrow#m
\circleonrightarrow#m
\circlerighthalfblack#m
\circletophalfblack#m
\circleulquad#m
\circleurquad#m
\circleurquadblack#m
\circlevertfill#m
\cirE#m
\cirfnint#m
\cirmid#m
\cirscir#m
\closedvarcap#m
\closedvarcup#m
\closedvarcupsmashprod#m
\closure#m
\Colon#m
\coloneq#m
\Coloneq#m
\commaminus#m
\concavediamond#m
\concavediamondtickleft#m
\concavediamondtickright#m
\congdot#m
\conictaper#m
\conjquant#m
\csub#m
\csube#m
\csup#m
\csupe#m
\cuberoot{arg}#m
\cupbarcap#m
\cupdot#m
\cupleftarrow#m
\cupovercap#m
\cupvee#m
\curvearrowleftplus#m
\curvearrowrightminus#m
\cwcirclearrow#m
\cwgapcirclearrow#m
\cwopencirclearrow#m
\cwrightarcarrow#m
\cwundercurvearrow#m
\danger#m
\dashcolon#m
\dashleftharpoondown#m
\dashrightharpoondown#m
\dashV#m
\Dashv#m
\DashV#m
\DashVDash#m
\dashVdash#m
\dbkarrow#m
\ddotseq#m
\DDownarrow#m
\Ddownarrow#m
\diameter#m
\diamondbotblack#m
\diamondcdot#m
\diamondleftarrow#m
\diamondleftarrowbar#m
\diamondleftblack#m
\diamondrightblack#m
\diamondtopblack#m
\dicei#m
\diceii#m
\diceiii#m
\diceiv#m
\dicev#m
\dicevi#m
\dingasterisk#m
\disin#m
\disjquant#m
\divslash#m
\Doteq#m
\dotequiv#m
\dotminus#m
\dotsim#m
\dotsminusdots#m
\dottedcircle#m
\dottedsquare#m
\dottimes#m
\doublebarvee#m
\doubleplus#m
\downarrowbar#m
\downarrowbarred#m
\downdasharrow#m
\downfishtail#m
\downharpoonleftbar#m
\downharpoonrightbar#m
\downharpoonsleftright#m
\downrightcurvedarrow#m
\downtriangleleftblack#m
\downtrianglerightblack#m
\downuparrows#m
\downupharpoonsleftright#m
\downwhitearrow#m
\downzigzagarrow#m
\dprime#m
\draftingarrow#m
\drbkarrow#m
\droang{arg}#m
\dsol#m
\dsub#m
\dualmap#m
\egsdot#m
\eighthnote#m
\elinters#m
\elsdot#m
\emptysetoarr#m
\emptysetoarrl#m
\emptysetobar#m
\emptysetocirc#m
\enclosecircle#m
\enclosediamond#m
\enclosesquare#m
\enclosetriangle#m
\enleadertwodots#m
\eparsl#m
\eqcolon#m
\eqdef#m
\eqdot#m
\eqeq#m
\eqeqeq#m
\eqgtr#m
\eqless#m
\eqqgtr#m
\eqqless#m
\eqqplus#m
\eqqsim#m
\eqqslantgtr#m
\eqqslantless#m
\equal#m
\equalleftarrow#m
\equalparallel#m
\equalrightarrow#m
\Equiv#m
\equivDD#m
\equivVert#m
\equivVvert#m
\eqvparsl#m
\errbarblackcircle#m
\errbarblackdiamond#m
\errbarblacksquare#m
\errbarcircle#m
\errbardiamond#m
\errbarsquare#m
\Eulerconst#m
\euro#m
\Exclam#m
\fbowtie#m
\fcmp#m
\fdiagovnearrow#m
\fdiagovrdiag#m
\female#m
\fint#m
\fisheye#m
\fltns#m
\forks#m
\forksnot#m
\forkv#m
\fourthroot{arg}#m
\fourvdots#m
\fracslash#m
\fullouterjoin#m
\geqqslant#m
\gescc#m
\gesdot#m
\gesdoto#m
\gesdotol#m
\gesles#m
\gggnest#m
\gla#m
\glE#m
\gleichstark#m
\glj#m
\greater#m
\gsime#m
\gsiml#m
\Gt#m
\gtcc#m
\gtcir#m
\gtlpar#m
\gtquest#m
\gtrarr#m
\harrowextender#*m
\hatapprox#m
\Hermaphrodite#m
\hermitmatrix#m
\hexagon#m
\hexagonblack#m
\hknearrow#m
\hknwarrow#m
\hksearrow#m
\hkswarrow#m
\horizbar#m
\hourglass#m
\house#m
\hrectangle#m
\hrectangleblack#m
\hyphenbullet#m
\hzigzag#m
\iinfin#m
\imageof#m
\increment#m
\intbar#m
\intBar#m
\intbottom#m
\intcap#m
\intclockwise#m
\intcup#m
\interleave#m
\intextender#*m
\intlarhk#m
\intprod#m
\intprodr#m
\inttop#*m
\intx#m
\inversebullet#m
\inversewhitecircle#m
\invlazys#m
\invnot#m
\invwhitelowerhalfcircle#m
\invwhiteupperhalfcircle#m
\isindot#m
\isinE#m
\isinobar#m
\isins#m
\isinvb#m
\Join#m
\kernelcontraction#m
\lAngle#m
\langledot#m
\laplac#m
\lat#m
\late#m
\lbag#m
\lblkbrbrak#m
\lBrace#m
\lbracelend#*m
\lbracemid#m
\lbraceuend#*m
\lBrack#m
\lbrackextender#*m
\lbracklend#*m
\lbracklltick#m
\lbrackubar#m
\lbrackuend#*m
\lbrackultick#m
\lbrbrak#m
\Lbrbrak#m
\lcurvyangle#m
\Ldsh#m
\leftarrowapprox#m
\leftarrowbackapprox#m
\leftarrowbsimilar#m
\leftarrowless#m
\leftarrowonoplus#m
\leftarrowplus#m
\leftarrowshortrightarrow#m
\leftarrowsimilar#m
\leftarrowsubset#m
\leftarrowtriangle#m
\leftarrowx#m
\leftbkarrow#m
\leftcurvedarrow#m
\leftdasharrow#m
\leftdbkarrow#m
\leftdbltail#m
\leftdotarrow#m
\leftdowncurvedarrow#m
\leftfishtail#m
\leftharpoonaccent{arg}#m
\leftharpoondownbar#m
\leftharpoonsupdown#m
\leftharpoonupbar#m
\leftharpoonupdash#m
\leftmoon#m
\leftouterjoin#m
\leftrightarrowcircle#m
\leftrightarrowtriangle#m
\leftrightharpoondowndown#m
\leftrightharpoondownup#m
\leftrightharpoonsdown#m
\leftrightharpoonsup#m
\leftrightharpoonupdown#m
\leftrightharpoonupup#m
\leftsquigarrow#m
\lefttail#m
\leftthreearrows#m
\leftwavearrow#m
\leftwhitearrow#m
\leqqslant#m
\lescc#m
\lesdot#m
\lesdoto#m
\lesdotor#m
\lesges#m
\less#m
\lfbowtie#m
\lftimes#m
\lgblkcircle#m
\lgblksquare#m
\lgE#m
\lgwhtcircle#m
\lgwhtsquare#m
\linefeed#m
\llangle#m
\llarc#m
\llblacktriangle#m
\LLeftarrow#m
\lllnest#m
\llparenthesis#m
\lltriangle#m
\longdashv#m
\longdivision{arg}#m
\longleftsquigarrow#m
\longmapsfrom#m
\Longmapsfrom#m
\Longmapsto#m
\longrightsquigarrow#m
\lowint#m
\lozengeminus#m
\lparen#m
\lParen#m
\lparenextender#*m
\Lparengtr#m
\lparenlend#*m
\lparenless#m
\lparenuend#*m
\lrarc#m
\lrblacktriangle#m
\lrtriangle#m
\lrtriangleeq#m
\lsime#m
\lsimg#m
\lsqhook#m
\Lt#m
\ltcc#m
\ltcir#m
\ltlarr#m
\ltquest#m
\ltrivb#m
\lvboxline#m
\lvzigzag#m
\Lvzigzag#m
\male#m
\mapsdown#m
\mapsfrom#m
\Mapsfrom#m
\Mapsto#m
\mapsup#m
\mathampersand#m
\mathatsign#m
\mathcolon#m
\mathcomma#m
\matheth#m
\mathexclam#m
\mathhyphen#m
\mathoctothorpe#m
\mathpercent#m
\mathperiod#m
\mathplus#m
\mathquestion#m
\mathratio#m
\mathsemicolon#m
\mathslash#m
\mathunderbar{arg}#m
\mathvisiblespace#m
\mathyen#m
\mbfDigamma#*m
\mbfdigamma#*m
\mbffrakA#*m
\mbffraka#*m
\mbffrakB#*m
\mbffrakb#*m
\mbffrakC#*m
\mbffrakc#*m
\mbffrakD#*m
\mbffrakd#*m
\mbffrakE#*m
\mbffrake#*m
\mbffrakF#*m
\mbffrakf#*m
\mbffrakG#*m
\mbffrakg#*m
\mbffrakH#*m
\mbffrakh#*m
\mbffrakI#*m
\mbffraki#*m
\mbffrakJ#*m
\mbffrakj#*m
\mbffrakK#*m
\mbffrakk#*m
\mbffrakL#*m
\mbffrakl#*m
\mbffrakM#*m
\mbffrakm#*m
\mbffrakN#*m
\mbffrakn#*m
\mbffrakO#*m
\mbffrako#*m
\mbffrakP#*m
\mbffrakp#*m
\mbffrakQ#*m
\mbffrakq#*m
\mbffrakR#*m
\mbffrakr#*m
\mbffrakS#*m
\mbffraks#*m
\mbffrakT#*m
\mbffrakt#*m
\mbffrakU#*m
\mbffraku#*m
\mbffrakV#*m
\mbffrakv#*m
\mbffrakW#*m
\mbffrakw#*m
\mbffrakX#*m
\mbffrakx#*m
\mbffrakY#*m
\mbffraky#*m
\mbffrakZ#*m
\mbffrakz#*m
\mbfitsansA#*m
\mbfitsansa#*m
\mbfitsansAlpha#*m
\mbfitsansalpha#*m
\mbfitsansB#*m
\mbfitsansb#*m
\mbfitsansBeta#*m
\mbfitsansbeta#*m
\mbfitsansC#*m
\mbfitsansc#*m
\mbfitsansChi#*m
\mbfitsanschi#*m
\mbfitsansD#*m
\mbfitsansd#*m
\mbfitsansDelta#*m
\mbfitsansdelta#*m
\mbfitsansE#*m
\mbfitsanse#*m
\mbfitsansEpsilon#*m
\mbfitsansepsilon#*m
\mbfitsansEta#*m
\mbfitsanseta#*m
\mbfitsansF#*m
\mbfitsansf#*m
\mbfitsansG#*m
\mbfitsansg#*m
\mbfitsansGamma#*m
\mbfitsansgamma#*m
\mbfitsansH#*m
\mbfitsansh#*m
\mbfitsansI#*m
\mbfitsansi#*m
\mbfitsansIota#*m
\mbfitsansiota#*m
\mbfitsansJ#*m
\mbfitsansj#*m
\mbfitsansK#*m
\mbfitsansk#*m
\mbfitsansKappa#*m
\mbfitsanskappa#*m
\mbfitsansL#*m
\mbfitsansl#*m
\mbfitsansLambda#*m
\mbfitsanslambda#*m
\mbfitsansM#*m
\mbfitsansm#*m
\mbfitsansMu#*m
\mbfitsansmu#*m
\mbfitsansN#*m
\mbfitsansn#*m
\mbfitsansnabla#*m
\mbfitsansNu#*m
\mbfitsansnu#*m
\mbfitsansO#*m
\mbfitsanso#*m
\mbfitsansOmega#*m
\mbfitsansomega#*m
\mbfitsansOmicron#*m
\mbfitsansomicron#*m
\mbfitsansP#*m
\mbfitsansp#*m
\mbfitsanspartial#*m
\mbfitsansPhi#*m
\mbfitsansphi#*m
\mbfitsansPi#*m
\mbfitsanspi#*m
\mbfitsansPsi#*m
\mbfitsanspsi#*m
\mbfitsansQ#*m
\mbfitsansq#*m
\mbfitsansR#*m
\mbfitsansr#*m
\mbfitsansRho#*m
\mbfitsansrho#*m
\mbfitsansS#*m
\mbfitsanss#*m
\mbfitsansSigma#*m
\mbfitsanssigma#*m
\mbfitsansT#*m
\mbfitsanst#*m
\mbfitsansTau#*m
\mbfitsanstau#*m
\mbfitsansTheta#*m
\mbfitsanstheta#*m
\mbfitsansU#*m
\mbfitsansu#*m
\mbfitsansUpsilon#*m
\mbfitsansupsilon#*m
\mbfitsansV#*m
\mbfitsansv#*m
\mbfitsansvarepsilon#*m
\mbfitsansvarkappa#*m
\mbfitsansvarphi#*m
\mbfitsansvarpi#*m
\mbfitsansvarrho#*m
\mbfitsansvarsigma#*m
\mbfitsansvarTheta#*m
\mbfitsansvartheta#*m
\mbfitsansW#*m
\mbfitsansw#*m
\mbfitsansX#*m
\mbfitsansx#*m
\mbfitsansXi#*m
\mbfitsansxi#*m
\mbfitsansY#*m
\mbfitsansy#*m
\mbfitsansZ#*m
\mbfitsansz#*m
\mbfitsansZeta#*m
\mbfitsanszeta#*m
\mbfsansA#*m
\mbfsansa#*m
\mbfsansAlpha#*m
\mbfsansalpha#*m
\mbfsansB#*m
\mbfsansb#*m
\mbfsansBeta#*m
\mbfsansbeta#*m
\mbfsansC#*m
\mbfsansc#*m
\mbfsansChi#*m
\mbfsanschi#*m
\mbfsansD#*m
\mbfsansd#*m
\mbfsansDelta#*m
\mbfsansdelta#*m
\mbfsansE#*m
\mbfsanse#*m
\mbfsanseight#*m
\mbfsansEpsilon#*m
\mbfsansepsilon#*m
\mbfsansEta#*m
\mbfsanseta#*m
\mbfsansF#*m
\mbfsansf#*m
\mbfsansfive#*m
\mbfsansfour#*m
\mbfsansG#*m
\mbfsansg#*m
\mbfsansGamma#*m
\mbfsansgamma#*m
\mbfsansH#*m
\mbfsansh#*m
\mbfsansI#*m
\mbfsansi#*m
\mbfsansIota#*m
\mbfsansiota#*m
\mbfsansJ#*m
\mbfsansj#*m
\mbfsansK#*m
\mbfsansk#*m
\mbfsansKappa#*m
\mbfsanskappa#*m
\mbfsansL#*m
\mbfsansl#*m
\mbfsansLambda#*m
\mbfsanslambda#*m
\mbfsansM#*m
\mbfsansm#*m
\mbfsansMu#*m
\mbfsansmu#*m
\mbfsansN#*m
\mbfsansn#*m
\mbfsansnabla#*m
\mbfsansnine#*m
\mbfsansNu#*m
\mbfsansnu#*m
\mbfsansO#*m
\mbfsanso#*m
\mbfsansOmega#*m
\mbfsansomega#*m
\mbfsansOmicron#*m
\mbfsansomicron#*m
\mbfsansone#*m
\mbfsansP#*m
\mbfsansp#*m
\mbfsanspartial#*m
\mbfsansPhi#*m
\mbfsansphi#*m
\mbfsansPi#*m
\mbfsanspi#*m
\mbfsansPsi#*m
\mbfsanspsi#*m
\mbfsansQ#*m
\mbfsansq#*m
\mbfsansR#*m
\mbfsansr#*m
\mbfsansRho#*m
\mbfsansrho#*m
\mbfsansS#*m
\mbfsanss#*m
\mbfsansseven#*m
\mbfsansSigma#*m
\mbfsanssigma#*m
\mbfsanssix#*m
\mbfsansT#*m
\mbfsanst#*m
\mbfsansTau#*m
\mbfsanstau#*m
\mbfsansTheta#*m
\mbfsanstheta#*m
\mbfsansthree#*m
\mbfsanstwo#*m
\mbfsansU#*m
\mbfsansu#*m
\mbfsansUpsilon#*m
\mbfsansupsilon#*m
\mbfsansV#*m
\mbfsansv#*m
\mbfsansvarepsilon#*m
\mbfsansvarkappa#*m
\mbfsansvarphi#*m
\mbfsansvarpi#*m
\mbfsansvarrho#*m
\mbfsansvarsigma#*m
\mbfsansvarTheta#*m
\mbfsansvartheta#*m
\mbfsansW#*m
\mbfsansw#*m
\mbfsansX#*m
\mbfsansx#*m
\mbfsansXi#*m
\mbfsansxi#*m
\mbfsansY#*m
\mbfsansy#*m
\mbfsansZ#*m
\mbfsansz#*m
\mbfsanszero#*m
\mbfsansZeta#*m
\mbfsanszeta#*m
\mbfscrA#*m
\mbfscra#*m
\mbfscrB#*m
\mbfscrb#*m
\mbfscrC#*m
\mbfscrc#*m
\mbfscrD#*m
\mbfscrd#*m
\mbfscrE#*m
\mbfscre#*m
\mbfscrF#*m
\mbfscrf#*m
\mbfscrG#*m
\mbfscrg#*m
\mbfscrH#*m
\mbfscrh#*m
\mbfscrI#*m
\mbfscri#*m
\mbfscrJ#*m
\mbfscrj#*m
\mbfscrK#*m
\mbfscrk#*m
\mbfscrL#*m
\mbfscrl#*m
\mbfscrM#*m
\mbfscrm#*m
\mbfscrN#*m
\mbfscrn#*m
\mbfscrO#*m
\mbfscro#*m
\mbfscrP#*m
\mbfscrp#*m
\mbfscrQ#*m
\mbfscrq#*m
\mbfscrR#*m
\mbfscrr#*m
\mbfscrS#*m
\mbfscrs#*m
\mbfscrT#*m
\mbfscrt#*m
\mbfscrU#*m
\mbfscru#*m
\mbfscrV#*m
\mbfscrv#*m
\mbfscrW#*m
\mbfscrw#*m
\mbfscrX#*m
\mbfscrx#*m
\mbfscrY#*m
\mbfscry#*m
\mbfscrZ#*m
\mbfscrz#*m
\mdblkcircle#m
\mdblkdiamond#m
\mdblklozenge#m
\mdblksquare#m
\mdlgblkcircle#m
\mdlgblkdiamond#m
\mdlgblklozenge#m
\mdlgblksquare#m
\mdlgwhtcircle#m
\mdlgwhtdiamond#m
\mdlgwhtlozenge#m
\mdlgwhtsquare#m
\mdsmblkcircle#m
\mdsmblksquare#m
\mdsmwhtcircle#m
\mdsmwhtsquare#m
\mdwhtcircle#m
\mdwhtdiamond#m
\mdwhtlozenge#m
\mdwhtsquare#m
\measangledltosw#m
\measangledrtose#m
\measangleldtosw#m
\measanglelutonw#m
\measanglerdtose#m
\measanglerutone#m
\measangleultonw#m
\measangleurtone#m
\measeq#m
\measuredangleleft#m
\measuredrightangle#m
\medblackstar#m
\medwhitestar#m
\mfrakA#*m
\mfraka#*m
\mfrakB#*m
\mfrakb#*m
\mfrakC#*m
\mfrakc#*m
\mfrakD#*m
\mfrakd#*m
\mfrakE#*m
\mfrake#*m
\mfrakF#*m
\mfrakf#*m
\mfrakG#*m
\mfrakg#*m
\mfrakh#*m
\mfrakH#*m
\mfraki#*m
\mfrakJ#*m
\mfrakj#*m
\mfrakK#*m
\mfrakk#*m
\mfrakL#*m
\mfrakl#*m
\mfrakM#*m
\mfrakm#*m
\mfrakN#*m
\mfrakn#*m
\mfrakO#*m
\mfrako#*m
\mfrakP#*m
\mfrakp#*m
\mfrakQ#*m
\mfrakq#*m
\mfrakr#*m
\mfrakS#*m
\mfraks#*m
\mfrakT#*m
\mfrakt#*m
\mfrakU#*m
\mfraku#*m
\mfrakV#*m
\mfrakv#*m
\mfrakW#*m
\mfrakw#*m
\mfrakX#*m
\mfrakx#*m
\mfrakY#*m
\mfraky#*m
\mfrakZ#*m
\mfrakz#*m
\midbarvee#m
\midbarwedge#m
\midcir#m
\minus#m
\minusdot#m
\minusfdots#m
\minusrdots#m
\mitBbbD#*m
\mitBbbd#*m
\mitBbbe#*m
\mitBbbi#*m
\mitBbbj#*m
\mitsansA#*m
\mitsansa#*m
\mitsansAlpha#*m
\mitsansalpha#*m
\mitsansB#*m
\mitsansb#*m
\mitsansBeta#*m
\mitsansbeta#*m
\mitsansC#*m
\mitsansc#*m
\mitsansChi#*m
\mitsanschi#*m
\mitsansD#*m
\mitsansd#*m
\mitsansDelta#*m
\mitsansdelta#*m
\mitsansE#*m
\mitsanse#*m
\mitsansEpsilon#*m
\mitsansepsilon#*m
\mitsansEta#*m
\mitsanseta#*m
\mitsansF#*m
\mitsansf#*m
\mitsansG#*m
\mitsansg#*m
\mitsansGamma#*m
\mitsansgamma#*m
\mitsansH#*m
\mitsansh#*m
\mitsansI#*m
\mitsansi#*m
\mitsansIota#*m
\mitsansiota#*m
\mitsansJ#*m
\mitsansj#*m
\mitsansK#*m
\mitsansk#*m
\mitsansKappa#*m
\mitsanskappa#*m
\mitsansL#*m
\mitsansl#*m
\mitsansLambda#*m
\mitsanslambda#*m
\mitsansM#*m
\mitsansm#*m
\mitsansMu#*m
\mitsansmu#*m
\mitsansN#*m
\mitsansn#*m
\mitsansNu#*m
\mitsansnu#*m
\mitsansO#*m
\mitsanso#*m
\mitsansOmega#*m
\mitsansomega#*m
\mitsansOmicron#*m
\mitsansomicron#*m
\mitsansP#*m
\mitsansp#*m
\mitsansPhi#*m
\mitsansphi#*m
\mitsansPi#*m
\mitsanspi#*m
\mitsansPsi#*m
\mitsanspsi#*m
\mitsansQ#*m
\mitsansq#*m
\mitsansR#*m
\mitsansr#*m
\mitsansRho#*m
\mitsansrho#*m
\mitsansS#*m
\mitsanss#*m
\mitsansSigma#*m
\mitsanssigma#*m
\mitsansT#*m
\mitsanst#*m
\mitsansTau#*m
\mitsanstau#*m
\mitsansTheta#*m
\mitsanstheta#*m
\mitsansU#*m
\mitsansu#*m
\mitsansUpsilon#*m
\mitsansupsilon#*m
\mitsansV#*m
\mitsansv#*m
\mitsansvarepsilon#*m
\mitsansvarsigma#*m
\mitsansW#*m
\mitsansw#*m
\mitsansX#*m
\mitsansx#*m
\mitsansXi#*m
\mitsansxi#*m
\mitsansY#*m
\mitsansy#*m
\mitsansZ#*m
\mitsansz#*m
\mitsansZeta#*m
\mitsanszeta#*m
\mlcp#m
\modtwosum#m
\msansA#*m
\msansa#*m
\msansAlpha#*m
\msansalpha#*m
\msansB#*m
\msansb#*m
\msansBeta#*m
\msansbeta#*m
\msansC#*m
\msansc#*m
\msansChi#*m
\msanschi#*m
\msansD#*m
\msansd#*m
\msansDelta#*m
\msansdelta#*m
\msansE#*m
\msanse#*m
\msanseight#*m
\msansEpsilon#*m
\msansepsilon#*m
\msansEta#*m
\msanseta#*m
\msansF#*m
\msansf#*m
\msansfive#*m
\msansfour#*m
\msansG#*m
\msansg#*m
\msansGamma#*m
\msansgamma#*m
\msansH#*m
\msansh#*m
\msansI#*m
\msansi#*m
\msansIota#*m
\msansiota#*m
\msansJ#*m
\msansj#*m
\msansK#*m
\msansk#*m
\msansKappa#*m
\msanskappa#*m
\msansL#*m
\msansl#*m
\msansLambda#*m
\msanslambda#*m
\msansM#*m
\msansm#*m
\msansMu#*m
\msansmu#*m
\msansN#*m
\msansn#*m
\msansnine#*m
\msansNu#*m
\msansnu#*m
\msansO#*m
\msanso#*m
\msansOmega#*m
\msansomega#*m
\msansOmicron#*m
\msansomicron#*m
\msansone#*m
\msansP#*m
\msansp#*m
\msansPhi#*m
\msansphi#*m
\msansPi#*m
\msanspi#*m
\msansPsi#*m
\msanspsi#*m
\msansQ#*m
\msansq#*m
\msansR#*m
\msansr#*m
\msansRho#*m
\msansrho#*m
\msansS#*m
\msanss#*m
\msansseven#*m
\msansSigma#*m
\msanssigma#*m
\msanssix#*m
\msansT#*m
\msanst#*m
\msansTau#*m
\msanstau#*m
\msansTheta#*m
\msanstheta#*m
\msansthree#*m
\msanstwo#*m
\msansU#*m
\msansu#*m
\msansUpsilon#*m
\msansupsilon#*m
\msansV#*m
\msansv#*m
\msansvarepsilon#*m
\msansvarsigma#*m
\msansW#*m
\msansw#*m
\msansX#*m
\msansx#*m
\msansXi#*m
\msansxi#*m
\msansY#*m
\msansy#*m
\msansZ#*m
\msansz#*m
\msanszero#*m
\msansZeta#*m
\msanszeta#*m
\mscrA#*m
\mscra#*m
\mscrb#*m
\mscrB#*m
\mscrC#*m
\mscrc#*m
\mscrD#*m
\mscrd#*m
\mscre#*m
\mscrE#*m
\mscrf#*m
\mscrF#*m
\mscrG#*m
\mscrg#*m
\mscrh#*m
\mscrH#*m
\mscri#*m
\mscrI#*m
\mscrJ#*m
\mscrj#*m
\mscrK#*m
\mscrk#*m
\mscrl#*m
\mscrL#*m
\mscrm#*m
\mscrM#*m
\mscrN#*m
\mscrn#*m
\mscrO#*m
\mscro#*m
\mscrP#*m
\mscrp#*m
\mscrQ#*m
\mscrq#*m
\mscrr#*m
\mscrR#*m
\mscrS#*m
\mscrs#*m
\mscrT#*m
\mscrt#*m
\mscrU#*m
\mscru#*m
\mscrV#*m
\mscrv#*m
\mscrW#*m
\mscrw#*m
\mscrX#*m
\mscrx#*m
\mscrY#*m
\mscry#*m
\mscrZ#*m
\mscrz#*m
\mtteight#*m
\mttfive#*m
\mttfour#*m
\mttnine#*m
\mttone#*m
\mttseven#*m
\mttsix#*m
\mttthree#*m
\mtttwo#*m
\mttzero#*m
\multimapinv#m
\napprox#m
\nasymp#m
\Nearrow#m
\neovnwarrow#m
\neovsearrow#m
\nequiv#m
\neswarrow#m
\neuter#m
\ngtrless#m
\ngtrsim#m
\nHdownarrow#m
\nhpar#m
\nHuparrow#m
\nhVvert#m
\niobar#m
\nis#m
\nisd#m
\nleftleftarrows#m
\nlessgtr#m
\nlesssim#m
\nni#m
\Not#m
\npolint#m
\npreccurlyeq#m
\nrightrightarrows#m
\nsime#m
\nsimeq#m
\nsqsubseteq#m
\nsqsupseteq#m
\nsubset#m
\nsucccurlyeq#m
\nsupset#m
\nvartriangleleft#m
\nvartriangleright#m
\nvinfty#m
\nvleftarrow#m
\nVleftarrow#m
\nvLeftarrow#m
\nvleftarrowtail#m
\nVleftarrowtail#m
\nvleftrightarrow#m
\nVleftrightarrow#m
\nvLeftrightarrow#m
\nvrightarrow#m
\nVrightarrow#m
\nvRightarrow#m
\nvrightarrowtail#m
\nVrightarrowtail#m
\nvtwoheadleftarrow#m
\nVtwoheadleftarrow#m
\nvtwoheadleftarrowtail#m
\nVtwoheadleftarrowtail#m
\nvtwoheadrightarrow#m
\nVtwoheadrightarrow#m
\nvtwoheadrightarrowtail#m
\nVtwoheadrightarrowtail#m
\Nwarrow#m
\nwovnearrow#m
\nwsearrow#m
\obar#m
\obot#m
\obrbrak#m
\obslash#m
\ocirc{arg}#m
\ocommatopright{arg}#m
\odiv#m
\odotslashdot#m
\ogreaterthan#m
\oiiint#m
\oiint#m
\ointctrclockwise#m
\olcross#m
\olessthan#m
\operp#m
\opluslhrim#m
\oplusrhrim#m
\origof#m
\Otimes#m
\otimeshat#m
\otimeslhrim#m
\otimesrhrim#m
\oturnedcomma{arg}#m
\overbar{arg}#m
\overbracket{arg}#m
\overparen{arg}#m
\ovhook{arg}#m
\parallelogram#m
\parallelogramblack#m
\parsim#m
\partialmeetcontraction#m
\pentagon#m
\pentagonblack#m
\perps#m
\Planckconst#m
\plusdot#m
\pluseqq#m
\plushat#m
\plussim#m
\plussubtwo#m
\plustrif#m
\pointint#m
\postalmark#m
\Prec#m
\preceqq#m
\precneq#m
\profline#m
\profsurf#m
\PropertyLine#m
\prurel#m
\pullback#m
\pushout#m
\QED#m
\qprime#m
\quarternote#m
\questeq#m
\Question#m
\rAngle#m
\rangledot#m
\rangledownzigzagarrow#m
\rbag#m
\rblkbrbrak#m
\rBrace#m
\rbracelend#*m
\rbracemid#*m
\rbraceuend#*m
\rBrack#m
\rbrackextender#*m
\rbracklend#*m
\rbracklrtick#m
\rbrackubar#m
\rbrackuend#*m
\rbrackurtick#m
\rbrbrak#m
\Rbrbrak#m
\rcurvyangle#m
\rdiagovfdiag#m
\rdiagovsearrow#m
\Rdsh#m
\revangle#m
\revangleubar#m
\revemptyset#m
\revnmid#m
\rfbowtie#m
\rftimes#m
\rightangle#m
\rightanglemdot#m
\rightanglesqr#m
\rightarrowapprox#m
\rightarrowbackapprox#m
\rightarrowbar#m
\rightarrowbsimilar#m
\rightarrowdiamond#m
\rightarrowgtr#m
\rightarrowonoplus#m
\rightarrowplus#m
\rightarrowshortleftarrow#m
\rightarrowsimilar#m
\rightarrowsupset#m
\rightarrowtriangle#m
\rightarrowx#m
\rightbkarrow#m
\rightcurvedarrow#m
\rightdasharrow#m
\rightdbltail#m
\rightdotarrow#m
\rightdowncurvedarrow#m
\rightfishtail#m
\rightharpoonaccent{arg}#m
\rightharpoondownbar#m
\rightharpoonsupdown#m
\rightharpoonupbar#m
\rightharpoonupdash#m
\rightimply#m
\rightleftharpoonsdown#m
\rightleftharpoonsup#m
\rightmoon#m
\rightouterjoin#m
\rightpentagon#m
\rightpentagonblack#m
\righttail#m
\rightthreearrows#m
\rightwavearrow#m
\rightwhitearrow#m
\ringplus#m
\rparen#m
\rParen#m
\rparenextender#*m
\rparengtr#m
\rparenlend#*m
\Rparenless#m
\rparenuend#*m
\rppolint#m
\rrangle#m
\RRightarrow#m
\rrparenthesis#m
\rsolbar#m
\rsqhook#m
\rsub#m
\rtriltri#m
\ruledelayed#m
\rvboxline#m
\rvzigzag#m
\Rvzigzag#m
\sansLmirrored#m
\sansLturned#m
\scpolint#m
\scurel#m
\Searrow#m
\seovnearrow#m
\shortdowntack#m
\shortlefttack#m
\shortrightarrowleftarrow#m
\shortuptack#m
\shuffle#m
\sime#m
\simgE#m
\simgtr#m
\similarleftarrow#m
\similarrightarrow#m
\simlE#m
\simless#m
\simminussim#m
\simneqq#m
\simplus#m
\simrdots#m
\sinewave#m
\smallblacktriangleleft#m
\smallblacktriangleright#m
\smallin#m
\smallni#m
\smalltriangleleft#m
\smalltriangleright#m
\smashtimes#m
\smblkcircle#m
\smblkdiamond#m
\smblklozenge#m
\smblksquare#m
\smeparsl#m
\smt#m
\smte#m
\smwhitestar#m
\smwhtcircle#m
\smwhtdiamond#m
\smwhtlozenge#m
\smwhtsquare#m
\sphericalangleup#m
\Sqcap#m
\Sqcup#m
\sqint#m
\sqlozenge#m
\sqrtbottom#m
\sqsubsetneq#m
\sqsupsetneq#m
\squarebotblack#m
\squarecrossfill#m
\squarehfill#m
\squarehvfill#m
\squareleftblack#m
\squarellblack#m
\squarellquad#m
\squarelrblack#m
\squarelrquad#m
\squareneswfill#m
\squarenwsefill#m
\squarerightblack#m
\squaretopblack#m
\squareulblack#m
\squareulquad#m
\squareurblack#m
\squareurquad#m
\squarevfill#m
\squoval#m
\sslash#m
\stareq#m
\strns#m
\subedot#m
\submult#m
\subrarr#m
\subsetapprox#m
\subsetcirc#m
\subsetdot#m
\subsetplus#m
\subsim#m
\subsub#m
\subsup#m
\Succ#m
\succeqq#m
\succneq#m
\sumbottom#m
\sumint#m
\sumtop#*m
\sun#m
\supdsub#m
\supedot#m
\suphsol#m
\suphsub#m
\suplarr#m
\supmult#m
\supsetapprox#m
\supsetcirc#m
\supsetdot#m
\supsetplus#m
\supsim#m
\supsub#m
\supsup#m
\Swarrow#m
\talloblong#m
\thermod#m
\threedangle#m
\threedotcolon#m
\threeunderdot{arg}#m
\tieconcat#m
\tieinfty#m
\timesbar#m
\tminus#m
\toea#m
\tona#m
\topbot#m
\topcir#m
\topfork#m
\topsemicircle#m
\tosa#m
\towa#m
\tplus#m
\trapezium#m
\trianglecdot#m
\triangleleftblack#m
\triangleminus#m
\triangleodot#m
\triangleplus#m
\trianglerightblack#m
\triangles#m
\triangleserifs#m
\triangletimes#m
\triangleubar#m
\tripleplus#m
\trprime#m
\trslash#m
\turnangle#m
\turnediota#m
\turnednot#m
\twocaps#m
\twocups#m
\twoheaddownarrow#m
\twoheadleftarrowtail#m
\twoheadleftdbkarrow#m
\twoheadmapsfrom#m
\twoheadmapsto#m
\twoheadrightarrowtail#m
\twoheaduparrow#m
\twoheaduparrowcircle#m
\twolowline#m
\twonotes#m
\typecolon#m
\ubrbrak#m
\ularc#m
\ulblacktriangle#m
\ultriangle#m
\uminus#m
\underbracket{arg}#m
\underleftharpoondown{arg}#m
\underparen{arg}#m
\underrightharpoondown{arg}#m
\unicodecdots#m
\unicodeellipsis#m
\upand#m
\uparrowbarred#m
\uparrowoncircle#m
\upbackepsilon#m
\updasharrow#m
\upDigamma#m
\updigamma#m
\updownarrowbar#m
\updownarrows#m
\updownharpoonleftleft#m
\updownharpoonleftright#m
\updownharpoonrightleft#m
\updownharpoonrightright#m
\updownharpoonsleftright#m
\upfishtail#m
\upharpoonleftbar#m
\upharpoonrightbar#m
\upharpoonsleftright#m
\upin#m
\upint#m
\uprightcurvearrow#m
\upwhitearrow#m
\urarc#m
\urblacktriangle#m
\urtriangle#m
\UUparrow#m
\Uuparrow#m
\varbarwedge#m
\varcarriagereturn#m
\varclubsuit#m
\vardiamondsuit#m
\vardoublebarwedge#m
\varheartsuit#m
\varhexagon#m
\varhexagonblack#m
\varhexagonlrbonds#m
\varisinobar#m
\varisins#m
\varlrtriangle#m
\varniobar#m
\varnis#m
\varointclockwise#m
\varspadesuit#m
\varstar#m
\varVdash#m
\varveebar#m
\vBar#m
\Vbar#m
\vBarv#m
\vbraceextender#*m
\vbrtri#m
\VDash#m
\vDdash#m
\vectimes#m
\Vee#m
\veedot#m
\veedoublebar#m
\veeeq#m
\veemidvert#m
\veeodot#m
\veeonvee#m
\veeonwedge#m
\vertoverlay{arg}#m
\viewdata#m
\vlongdash#m
\vrectangle#m
\vrectangleblack#m
\Vvert#m
\vysmblkcircle#m
\vysmblksquare#m
\vysmwhtcircle#m
\vysmwhtsquare#m
\vzigzag#m
\Wedge#m
\wedgebar#m
\wedgedot#m
\wedgedoublebar#m
\wedgemidvert#m
\wedgeodot#m
\wedgeonwedge#m
\wedgeq#m
\whitearrowupfrombar#m
\whiteinwhitetriangle#m
\whitepointerleft#m
\whitepointerright#m
\whitesquaretickleft#m
\whitesquaretickright#m
\whthorzoval#m
\whtvertoval#m
\wideangledown#m
\wideangleup#m
\widebridgeabove{arg}#m
\wideutilde{arg}#m
\xbsol#m
\xsol#m
\Yup#m
\Zbar#m
\zcmp#m
\zpipe#m
\zproject#m
