# newcomputermodern package
# Matthew Bertucci 2026/06/06 for v8.1.0

#include:fontspec
#include:unicode-math

#keyvals:\usepackage/newcomputermodern#c
regular
sansdefault
#endkeyvals

\textprosgegrammeni{text%plain}
\prosgegrammeni
\textivbce{text%plain}
\ivbce
\textvibce{text%plain}
\vibce
\textivbcealt{text%plain}
\ivbcealt
\textipa{text%plain}
\ipatext
\textoldipa{text%plain}#*
\oldipatext#*
\textuncial{text}
\uncial

\atticonequarter#*
\hermionianfifty#*
\atticonehalf#*
\thespianfifty#*
\atticonedrachma#*
\thespianonehundred#*
\atticfive#*
\thespianthreehundred#*
\atticfifty#*
\epidaurianfivehundred#*
\atticfivehundred#*
\troezenianfivehundred#*
\atticfivethousand#*
\thespianfivehundred#*
\atticfiftythousand#*
\carystianfivehundred#*
\atticfivetalents#*
\naxianfivehundred#*
\attictentalents#*
\thespianonethousand#*
\atticfiftytalents#*
\thespianfivethousand#*
\atticonehundredtalents#*
\delphicfivemnas#*
\atticfivehundredtalents#*
\stratianfiftymnas#*
\atticonethousandtalents#*
\greekonehalfsign#*
\atticfivethousandtalents#*
\greekonehalfsignalt#*
\atticfivestaters#*
\greektwothirdssign#*
\attictenstaters#*
\greekthreequarterssign#*
\atticfiftystaters#*
\greekyearsign#*
\atticonehundredstaters#*
\greektalentsign#*
\atticfivehundredstaters#*
\greekdrachmasign#*
\atticonethousandstaters#*
\greekobolsign#*
\attictenthousandstaters#*
\greektwoobolssign#*
\atticfiftythousandstaters#*
\greekthreeobolssign#*
\attictenmnas#*
\greekfourobolssign#*
\heraleumoneplethron#*
\greekfiveobolssign#*
\thespianone#*
\greekmetretessign#*
\ermionianone#*
\greekkyathosbasesign#*
\epidauriantwo#*
\greeklytrasign#*
\thespiantwo#*
\greekounkiasign#*
\cyrenaictwodrachmas#*
\greekxestessign#*
\epidauriantwodrachmas#*
\greekartabesign#*
\troezenianfive#*
\greekarourasign#*
\troezenianten#*
\greekgrammasign#*
\troezeniantenalt#*
\greektryblionbasesign#*
\hermionianten#*
\greekzerosign#*
\messenianten#*
\greekonequartersign#*
\thespianten#*
\greeksinusoidsign#*
\thespianthirty#*
\greekindictionsign#*
\troezenianfifty#*
\nomismasign#*
\troezenianfiftyalt#*

\chemalpha
\chembeta
\chemgamma
\chemdelta
\chemepsilon
\chemzeta
\chemeta
\chemtheta
\chemiota
\chemkappa
\chemlambda
\chemmu
\chemnu
\chemxi
\chemomicron
\chempi
\chemrho
\chemrhoalt
\chemsigma
\chemsigmaalt
\chemtau
\chemupsilon
\chemphi
\chemchi
\chempsi
\chemomega
\chemAlpha
\chemBeta
\chemGamma
\chemDelta
\chemEpsilon
\chemZeta
\chemEta
\chemTheta
\chemIota
\chemKappa
\chemLambda
\chemMu
\chemNu
\chemXi
\chemOmicron
\chemPi
\chemRho
\chemSigma
\chemTau
\chemUpsilon
\chemPhi
\chemChi
\chemPsi
\chemOmega

\aegeanseparator#*
\aegeanseparatordot#*
\aegeancheckmark#*
\aegeanone#*
\aegeantwo#*
\aegeanthree#*
\aegeanfour#*
\aegeanfive#*
\aegeansix#*
\aegeanseven#*
\aegeaneight#*
\aegeanine#*
\aegeanten#*
\aegeantwenty#*
\aegeanthirty#*
\aegeanfourty#*
\aegeanfifty#*
\aegeansixty#*
\aegeanseventy#*
\aegeaneighty#*
\aegeanninety#*
\aegeanonehundred#*
\aegeantwohundred#*
\aegeanthreehundred#*
\aegeanfourhundred#*
\aegeanfivehundred#*
\aegeansixhundred#*
\aegeansevenhundred#*
\aegeaneighthundred#*
\aegeanninehundred#*
\aegeanonethousand#*
\aegeantwothousand#*
\aegeanthreethousand#*
\aegeanfourthousand#*
\aegeanfivethousand#*
\aegeansixthousand#*
\aegeanseventhousand#*
\aegeaneightthousand#*
\aegeanninethousand#*
\aegeantenthousand#*
\aegeantwentythousand#*
\aegeanthirtythousand#*
\aegeanfourtythousand#*
\aegeanfiftythousand#*
\aegeansixtythousand#*
\aegeanseventythousand#*
\aegeaneightythousand#*
\aegeanninetythousand#*
\aegeanweightbaseunit#*
\aegeanweightfirstsubunit#*
\aegeanweightsecondsubunit#*
\aegeanweightthirdsubunit#*
\aegeanweightfourthsubunit#*
\aegeandrymeasurefirstsubunit#*
\aegeanliquidmeasurefirstsubunit#*
\aegeansecondsubunit#*
\aegeanthirdsubunit#*

\mathchancery{text%plain}#m
\mathbfchancery{text%plain}#m
\symchancery{text%plain}#m

\titlo{text}

\circledA
\circledB
\circledC
\circledD
\circledE
\circledF
\circledG
\circledH
\circledI
\circledJ
\circledK
\circledL
\circledM
\circledN
\circledO
\circledP
\circledQ
\circledR
\circledS
\circledT
\circledU
\circledV
\circledW
\circledX
\circledY
\circledZ
\circleda
\circledb
\circledc
\circledd
\circlede
\circledeight
\circledeightteen
\circledeleven
\circledf
\circledfifteen
\circledfive
\circledfour
\circledfourteen
\circledg
\circledh
\circledi
\circledj
\circledk
\circledl
\circledm
\circledn
\circlednine
\circlednineteen
\circledo
\circledone
\circledp
\circledq
\circledr
\circleds
\circledseven
\circledseventeen
\circledsix
\circledsixteen
\circledt
\circledten
\circledthirteen
\circledthree
\circledtwelve
\circledtwenty
\circledtwo
\circledu
\circledv
\circledw
\circledx
\circledy
\circledz
\circledzero
\doublecircledeight
\doublecircledfive
\doublecircledfour
\doublecirclednine
\doublecircledone
\doublecircledseven
\doublecircledsix
\doublecircledten
\doublecircledthree
\doublecircledtwo
\negativecircledeightteen
\negativecircledeleven
\negativecircledfifteen
\negativecircledfourteen
\negativecirclednineteen
\negativecircledseventeen
\negativecircledsixteen
\negativecircledthirteen
\negativecircledtwelve
\negativecircledtwenty
\negativecircledzero

# non-default unicode-math symbols
\accurrent#m
\acidfree#m
\acwcirclearrow#m
\acwgapcirclearrow#m
\acwleftarcarrow#m
\acwoverarcarrow#m
\acwunderarcarrow#m
\angdnr#m
\angles#m
\angleubar#m
\annuity{arg}#m
\APLboxquestion#m
\APLboxupcaret#m
\APLnotbackslash#m
\APLnotslash#m
\approxeqq#m
\arabichad#m
\arabicmaj#m
\asteq#m
\astrosun#m
\backepsilon#m
\bagmember#m
\barcap#m
\barcup#m
\bardownharpoonleft#m
\bardownharpoonright#m
\barleftarrow#m
\barleftarrowrightarrowbar#m
\barleftharpoondown#m
\barleftharpoonup#m
\barovernorthwestarrow#m
\barrightarrowdiamond#m
\barrightharpoondown#m
\barrightharpoonup#m
\baruparrow#m
\barupharpoonleft#m
\barupharpoonright#m
\Barv#m
\barV#m
\bbrktbrk#m
\bdtriplevdash#m
\benzenr#m
\biginterleave#m
\bigslopedvee#m
\bigslopedwedge#m
\bigstar#m
\bigtalloblong#m
\bigtriangleleft#m
\bigwhitestar#m
\blackcircledownarrow#m
\blackcircledrightdot#m
\blackcircledtwodots#m
\blackcircleulquadwhite#m
\blackdiamonddownarrow#m
\blackhourglass#m
\blackinwhitediamond#m
\blackinwhitesquare#m
\blacklefthalfcircle#m
\blackpointerleft#m
\blackpointerright#m
\blackrighthalfcircle#m
\blacksmiley#m
\blacktriangle#m
\blacktriangledown#m
\blkhorzoval#m
\blkvertoval#m
\blocklefthalf#m
\blocklowhalf#m
\blockrighthalf#m
\blockuphalf#m
\bNot#m
\botsemicircle#m
\boxast#m
\boxbar#m
\boxbox#m
\boxbslash#m
\boxcircle#m
\boxdiag#m
\boxonbox#m
\bsimilarleftarrow#m
\bsimilarrightarrow#m
\bsolhsub#m
\btimes#m
\bullseye#m
\bumpeqq#m
\candra{arg}#m
\capbarcup#m
\capdot#m
\capovercup#m
\capwedge#m
\caretinsert#m
\ccwundercurvearrow#m
\cirbot#m
\circlebottomhalfblack#m
\circledbullet#m
\circledownarrow#m
\circledparallel#m
\circledrightdot#m
\circledstar#m
\circledtwodots#m
\circledvert#m
\circledwhitebullet#m
\circlehbar#m
\circlelefthalfblack#m
\circlellquad#m
\circlelrquad#m
\circleonleftarrow#m
\circleonrightarrow#m
\circlerighthalfblack#m
\circletophalfblack#m
\circleulquad#m
\circleurquad#m
\circleurquadblack#m
\circlevertfill#m
\cirE#m
\cirfnint#m
\cirmid#m
\cirscir#m
\closedvarcap#m
\closedvarcup#m
\closedvarcupsmashprod#m
\closure#m
\Coloneq#m
\commaminus#m
\congdot#m
\conictaper#m
\conjquant#m
\convolution#m
\csub#m
\csube#m
\csup#m
\csupe#m
\cuberoot{arg}#m
\cuberootsign{arg}#*m
\cupbarcap#m
\cupovercap#m
\cupvee#m
\curvearrowleftplus#m
\curvearrowrightminus#m
\cwcirclearrow#m
\cwgapcirclearrow#m
\cwrightarcarrow#m
\cwundercurvearrow#m
\danger#m
\dashleftharpoondown#m
\dashrightharpoondown#m
\DashV#m
\Dashv#m
\dashV#m
\dbkarow#m
\dbkarrow#m
\ddotseq#m
\DDownarrow#m
\Ddownarrow#m
\diamondbotblack#m
\diamondcdot#m
\diamondleftarrow#m
\diamondleftarrowbar#m
\diamondleftblack#m
\diamondrightblack#m
\diamondtopblack#m
\dicei#m
\diceii#m
\diceiii#m
\diceiv#m
\dicev#m
\dicevi#m
\Digamma#m
\digamma#m
\dingasterisk#m
\disin#m
\disjquant#m
\dotequiv#m
\dotsim#m
\dottedcircle#m
\dottimes#m
\doublebarvee#m
\doublebarwedge#m
\doubleplus#m
\downarrowbar#m
\downarrowbarred#m
\downdasharrow#m
\downfishtail#m
\downharpoonleftbar#m
\downharpoonrightbar#m
\downharpoonsleftright#m
\downrightcurvedarrow#m
\downtriangleleftblack#m
\downtrianglerightblack#m
\downupharpoonsleftright#m
\downzigzagarrow#m
\draftingarrow#m
\drbkarow#m
\drbkarrow#m
\droang{arg}#m
\dsol#m
\dsub#m
\dualmap#m
\egsdot#m
\elinters#m
\elsdot#m
\emptysetoarr#m
\emptysetoarrl#m
\emptysetobar#m
\emptysetocirc#m
\enleadertwodots#m
\eparsl#m
\eqdot#m
\eqeq#m
\eqeqeq#m
\eqqgtr#m
\eqqless#m
\eqqplus#m
\eqqsim#m
\eqqslantgtr#m
\eqqslantless#m
\equalleftarrow#m
\equalrightarrow#m
\equivDD#m
\equivVert#m
\equivVvert#m
\eqvparsl#m
\errbarblackcircle#m
\errbarblackdiamond#m
\errbarblacksquare#m
\errbarcircle#m
\errbardiamond#m
\errbarsquare#m
\Exclam#m
\fbowtie#m
\fcmp#m
\fdiagovnearrow#m
\fdiagovrdiag#m
\female#m
\fint#m
\Finv#m
\fisheye#m
\fltns#m
\forks#m
\forksnot#m
\forkv#m
\fourthroot{arg}#m
\fourthrootsign{arg}#*m
\fourvdots#m
\fullouterjoin#m
\Game#m
\geqqslant#m
\gescc#m
\gesdot#m
\gesdoto#m
\gesdotol#m
\gesles#m
\gggnest#m
\gla#m
\glE#m
\gleichstark#m
\glj#m
\gsime#m
\gsiml#m
\Gt#m
\gtcc#m
\gtcir#m
\gtlpar#m
\gtquest#m
\gtrarr#m
\harrowextender#*m
\hatapprox#m
\Hermaphrodite#m
\hexagon#m
\hexagonblack#m
\hknearrow#m
\hknwarrow#m
\hksearow#m
\hksearrow#m
\hkswarow#m
\hkswarrow#m
\hourglass#m
\house#m
\hyphenbullet#m
\hzigzag#m
\iinfin#m
\intBar#m
\intbar#m
\intcap#m
\intcup#m
\interleave#m
\intextender#*m
\intlarhk#m
\intprod#m
\intprodr#m
\intx#m
\inversebullet#m
\inversewhitecircle#m
\invwhitelowerhalfcircle#m
\invwhiteupperhalfcircle#m
\isindot#m
\isinE#m
\isinobar#m
\isins#m
\isinvb#m
\Join#m
\langledot#m
\laplac#m
\lat#m
\late#m
\lbag#m
\lblkbrbrak#m
\lBrace#m
\lbracklltick#m
\lbrackubar#m
\lbrackultick#m
\Lbrbrak#m
\lbrbrak#m
\lcurvyangle#m
\leftarrowapprox#m
\leftarrowbackapprox#m
\leftarrowbsimilar#m
\leftarrowless#m
\leftarrowonoplus#m
\leftarrowplus#m
\leftarrowshortrightarrow#m
\leftarrowsimilar#m
\leftarrowsubset#m
\leftarrowtriangle#m
\leftarrowx#m
\leftbkarrow#m
\leftcurvedarrow#m
\leftdasharrow#m
\leftdbkarrow#m
\leftdbltail#m
\leftdotarrow#m
\leftdowncurvedarrow#m
\leftfishtail#m
\leftharpoondownbar#m
\leftharpoonsupdown#m
\leftharpoonupbar#m
\leftharpoonupdash#m
\leftmoon#m
\leftouterjoin#m
\leftrightarrowcircle#m
\leftrightarrowtriangle#m
\leftrightharpoondowndown#m
\leftrightharpoondownup#m
\leftrightharpoonsdown#m
\leftrightharpoonsup#m
\leftrightharpoonupdown#m
\leftrightharpoonupup#m
\lefttail#m
\leftwavearrow#m
\leqqslant#m
\lescc#m
\lesdot#m
\lesdoto#m
\lesdotor#m
\lesges#m
\lfbowtie#m
\lftimes#m
\lgblkcircle#m
\lgblksquare#m
\lgE#m
\lgwhtsquare#m
\llangle#m
\llarc#m
\llblacktriangle#m
\LLeftarrow#m
\lllnest#m
\llparenthesis#m
\lltriangle#m
\longdivision{arg}#m
\longdivisionsign{arg}#*m
\lowint#m
\lParen#m
\Lparengtr#m
\lparenless#m
\lrarc#m
\lrblacktriangle#m
\lrtriangle#m
\lrtriangleeq#m
\lsime#m
\lsimg#m
\lsqhook#m
\Lt#m
\ltcc#m
\ltcir#m
\ltlarr#m
\ltquest#m
\ltrivb#m
\lvboxline#m
\Lvzigzag#m
\lvzigzag#m
\male#m
\mbfDigamma#*m
\mbfdigamma#*m
\mbfscra#*m
\mbfscrb#*m
\mbfscrc#*m
\mbfscrd#*m
\mbfscre#*m
\mbfscrf#*m
\mbfscrg#*m
\mbfscrh#*m
\mbfscri#*m
\mbfscrj#*m
\mbfscrk#*m
\mbfscrl#*m
\mbfscrm#*m
\mbfscrn#*m
\mbfscro#*m
\mbfscrp#*m
\mbfscrq#*m
\mbfscrr#*m
\mbfscrs#*m
\mbfscrt#*m
\mbfscru#*m
\mbfscrv#*m
\mbfscrw#*m
\mbfscrx#*m
\mbfscry#*m
\mbfscrz#*m
\mdblkcircle#m
\mdblkdiamond#m
\mdblklozenge#m
\mdblksquare#m
\mdlgblkdiamond#m
\mdlgblklozenge#m
\mdlgwhtdiamond#m
\mdsmblkcircle#m
\mdsmblksquare#m
\mdsmwhtcircle#m
\mdsmwhtsquare#m
\mdwhtcircle#m
\mdwhtdiamond#m
\mdwhtlozenge#m
\mdwhtsquare#m
\measangledltosw#m
\measangledrtose#m
\measangleldtosw#m
\measanglelutonw#m
\measanglerdtose#m
\measanglerutone#m
\measangleultonw#m
\measangleurtone#m
\measuredangleleft#m
\medblackstar#m
\medwhitestar#m
\midbarvee#m
\midbarwedge#m
\midcir#m
\minusdot#m
\minusfdots#m
\minusrdots#m
\mitsansAlpha#*m
\mitsansalpha#*m
\mitsansBeta#*m
\mitsansbeta#*m
\mitsansChi#*m
\mitsanschi#*m
\mitsansDelta#*m
\mitsansdelta#*m
\mitsansEpsilon#*m
\mitsansepsilon#*m
\mitsansEta#*m
\mitsanseta#*m
\mitsansGamma#*m
\mitsansgamma#*m
\mitsansIota#*m
\mitsansiota#*m
\mitsansKappa#*m
\mitsanskappa#*m
\mitsansLambda#*m
\mitsanslambda#*m
\mitsansMu#*m
\mitsansmu#*m
\mitsansNu#*m
\mitsansnu#*m
\mitsansOmega#*m
\mitsansomega#*m
\mitsansOmicron#*m
\mitsansomicron#*m
\mitsansPhi#*m
\mitsansphi#*m
\mitsansPi#*m
\mitsanspi#*m
\mitsansPsi#*m
\mitsanspsi#*m
\mitsansRho#*m
\mitsansrho#*m
\mitsansSigma#*m
\mitsanssigma#*m
\mitsansTau#*m
\mitsanstau#*m
\mitsansTheta#*m
\mitsanstheta#*m
\mitsansUpsilon#*m
\mitsansupsilon#*m
\mitsansvarepsilon#*m
\mitsansvarsigma#*m
\mitsansXi#*m
\mitsansxi#*m
\mitsansZeta#*m
\mitsanszeta#*m
\mlcp#m
\modtwosum#m
\msansAlpha#*m
\msansalpha#*m
\msansBeta#*m
\msansbeta#*m
\msansChi#*m
\msanschi#*m
\msansDelta#*m
\msansdelta#*m
\msansEpsilon#*m
\msansepsilon#*m
\msansEta#*m
\msanseta#*m
\msansGamma#*m
\msansgamma#*m
\msansIota#*m
\msansiota#*m
\msansKappa#*m
\msanskappa#*m
\msansLambda#*m
\msanslambda#*m
\msansMu#*m
\msansmu#*m
\msansNu#*m
\msansnu#*m
\msansOmega#*m
\msansomega#*m
\msansOmicron#*m
\msansomicron#*m
\msansPhi#*m
\msansphi#*m
\msansPi#*m
\msanspi#*m
\msansPsi#*m
\msanspsi#*m
\msansRho#*m
\msansrho#*m
\msansSigma#*m
\msanssigma#*m
\msansTau#*m
\msanstau#*m
\msansTheta#*m
\msanstheta#*m
\msansUpsilon#*m
\msansupsilon#*m
\msansvarepsilon#*m
\msansvarsigma#*m
\msansXi#*m
\msansxi#*m
\msansZeta#*m
\msanszeta#*m
\mscra#*m
\mscrb#*m
\mscrc#*m
\mscrd#*m
\mscre#*m
\mscrf#*m
\mscrg#*m
\mscrh#*m
\mscri#*m
\mscrj#*m
\mscrk#*m
\mscrl#*m
\mscrm#*m
\mscrn#*m
\mscro#*m
\mscrp#*m
\mscrq#*m
\mscrr#*m
\mscrs#*m
\mscrt#*m
\mscru#*m
\mscrv#*m
\mscrw#*m
\mscrx#*m
\mscry#*m
\mscrz#*m
\neovnwarrow#m
\neovsearrow#m
\neswarrow#m
\neuter#m
\nHdownarrow#m
\nhpar#m
\nHuparrow#m
\nhVvert#m
\niobar#m
\nis#m
\nisd#m
\nleftleftarrows#m
\Not#m
\npolint#m
\nrightrightarrows#m
\nvinfty#m
\nVleftarrow#m
\nvLeftarrow#m
\nvleftarrow#m
\nVleftarrowtail#m
\nvleftarrowtail#m
\nVleftrightarrow#m
\nvLeftrightarrow#m
\nvleftrightarrow#m
\nVrightarrow#m
\nvRightarrow#m
\nvrightarrow#m
\nVrightarrowtail#m
\nvrightarrowtail#m
\nVtwoheadleftarrow#m
\nvtwoheadleftarrow#m
\nVtwoheadleftarrowtail#m
\nvtwoheadleftarrowtail#m
\nVtwoheadrightarrow#m
\nvtwoheadrightarrow#m
\nVtwoheadrightarrowtail#m
\nvtwoheadrightarrowtail#m
\nwovnearrow#m
\nwsearrow#m
\obar#m
\obot#m
\obslash#m
\ocommatopright{arg}#m
\odiv#m
\odotslashdot#m
\ogreaterthan#m
\olcross#m
\olessthan#m
\operp#m
\opluslhrim#m
\oplusrhrim#m
\Otimes#m
\otimeshat#m
\otimeslhrim#m
\otimesrhrim#m
\oturnedcomma{arg}#m
\parallelogram#m
\parallelogramblack#m
\parsim#m
\partialmeetcontraction#m
\pentagon#m
\pentagonblack#m
\perps#m
\pitchfork#m
\plusdot#m
\pluseqq#m
\plushat#m
\plussim#m
\plussubtwo#m
\plustrif#m
\pointint#m
\postalmark#m
\Prec#m
\precapprox#m
\preceqq#m
\precnapprox#m
\precneq#m
\precneqq#m
\profline#m
\profsurf#m
\PropertyLine#m
\prurel#m
\pullback#m
\pushout#m
\quarternote#m
\Question#m
\rangledot#m
\rangledownzigzagarrow#m
\rbag#m
\rblkbrbrak#m
\rBrace#m
\rbracklrtick#m
\rbrackubar#m
\rbrackurtick#m
\Rbrbrak#m
\rbrbrak#m
\rcurvyangle#m
\rdiagovfdiag#m
\rdiagovsearrow#m
\revangle#m
\revangleubar#m
\revemptyset#m
\revnmid#m
\rfbowtie#m
\rftimes#m
\rightanglemdot#m
\rightanglesqr#m
\rightarrowapprox#m
\rightarrowbackapprox#m
\rightarrowbar#m
\rightarrowbsimilar#m
\rightarrowdiamond#m
\rightarrowgtr#m
\rightarrowplus#m
\rightarrowshortleftarrow#m
\rightarrowsimilar#m
\rightarrowsupset#m
\rightarrowtriangle#m
\rightarrowx#m
\rightbkarrow#m
\rightcurvedarrow#m
\rightdasharrow#m
\rightdbltail#m
\rightdotarrow#m
\rightdowncurvedarrow#m
\rightfishtail#m
\rightharpoondownbar#m
\rightharpoonsupdown#m
\rightharpoonupbar#m
\rightharpoonupdash#m
\rightimply#m
\rightleftharpoonsdown#m
\rightleftharpoonsup#m
\rightmoon#m
\rightouterjoin#m
\rightpentagon#m
\rightpentagonblack#m
\righttail#m
\rightwavearrow#m
\ringplus#m
\rParen#m
\rparengtr#m
\Rparenless#m
\rppolint#m
\rrangle#m
\RRightarrow#m
\rrparenthesis#m
\rsolbar#m
\rsqhook#m
\rsub#m
\rtriltri#m
\ruledelayed#m
\rvboxline#m
\Rvzigzag#m
\rvzigzag#m
\sansLmirrored#m
\sansLturned#m
\scpolint#m
\scurel#m
\seovnearrow#m
\shortdowntack#m
\shortlefttack#m
\shortrightarrowleftarrow#m
\shortuptack#m
\shuffle#m
\simgE#m
\simgtr#m
\similarleftarrow#m
\similarrightarrow#m
\simlE#m
\simless#m
\simminussim#m
\simplus#m
\simrdots#m
\smallblacktriangleleft#m
\smallblacktriangleright#m
\smalltriangleleft#m
\smalltriangleright#m
\smashtimes#m
\smblkdiamond#m
\smblklozenge#m
\smeparsl#m
\smt#m
\smte#m
\smwhitestar#m
\smwhtlozenge#m
\sphericalangleup#m
\Sqcap#m
\Sqcup#m
\sqint#m
\sqlozenge#m
\squarebotblack#m
\squarecrossfill#m
\squarehfill#m
\squarehvfill#m
\squareleftblack#m
\squarellblack#m
\squarellquad#m
\squarelrblack#m
\squarelrquad#m
\squareneswfill#m
\squarenwsefill#m
\squarerightblack#m
\squaretopblack#m
\squareulblack#m
\squareulquad#m
\squareurblack#m
\squareurquad#m
\squarevfill#m
\squoval#m
\sslash#m
\strns#m
\subedot#m
\submult#m
\subrarr#m
\subsetapprox#m
\subsetcirc#m
\subsetdot#m
\subseteqq#m
\subsetneqq#m
\subsetplus#m
\subsim#m
\subsub#m
\subsup#m
\Succ#m
\succapprox#m
\succeqq#m
\succnapprox#m
\succneq#m
\succneqq#m
\sumint#m
\sun#m
\supdsub#m
\supedot#m
\suphsol#m
\suphsub#m
\suplarr#m
\supmult#m
\supsetapprox#m
\supsetcirc#m
\supsetdot#m
\supseteqq#m
\supsetneqq#m
\supsetplus#m
\supsim#m
\supsub#m
\supsup#m
\talloblong#m
\thermod#m
\threedangle#m
\threedotcolon#m
\tieconcat#m
\tieinfty#m
\timesbar#m
\tminus#m
\toea#m
\tona#m
\topbot#m
\topcir#m
\topfork#m
\topsemicircle#m
\tosa#m
\towa#m
\tplus#m
\trapezium#m
\trianglecdot#m
\triangledown#m
\triangleleftblack#m
\triangleminus#m
\triangleodot#m
\triangleplus#m
\trianglerightblack#m
\triangles#m
\triangleserifs#m
\triangletimes#m
\triangleubar#m
\tripleplus#m
\trslash#m
\turnangle#m
\turnediota#m
\twocaps#m
\twocups#m
\twoheadhookleftarrow#m
\twoheadhookrightarrow#m
\twoheadleftarrowtail#m
\twoheadleftdbkarrow#m
\twoheadmapsfrom#m
\twoheadmapsto#m
\twoheadrightarrowtail#m
\twoheaduparrowcircle#m
\twonotes#m
\typecolon#m
\ularc#m
\ulblacktriangle#m
\ultriangle#m
\uminus#m
\upand#m
\uparrowbarred#m
\uparrowoncircle#m
\upbackepsilon#m
\updasharrow#m
\upDigamma#m
\updigamma#m
\updownarrowbar#m
\updownharpoonleftleft#m
\updownharpoonleftright#m
\updownharpoonrightleft#m
\updownharpoonrightright#m
\updownharpoonsleftright#m
\upfishtail#m
\upharpoonleftbar#m
\upharpoonrightbar#m
\upharpoonsleftright#m
\upin#m
\upint#m
\uprightcurvearrow#m
\urarc#m
\urblacktriangle#m
\urtriangle#m
\UUparrow#m
\Uuparrow#m
\varcarriagereturn#m
\varhexagon#m
\varhexagonblack#m
\varhexagonlrbonds#m
\varisinobar#m
\varisins#m
\varniobar#m
\varnis#m
\varstar#m
\vartriangle#m
\varVdash#m
\varveebar#m
\Vbar#m
\vBar#m
\vBarv#m
\vbrtri#m
\vDdash#m
\Vee#m
\veedot#m
\veedoublebar#m
\veemidvert#m
\veeodot#m
\veeonvee#m
\veeonwedge#m
\viewdata#m
\vrectangle#m
\vrectangleblack#m
\Vvert#m
\vysmblksquare#m
\vysmwhtsquare#m
\vzigzag#m
\Wedge#m
\wedgebar#m
\wedgedot#m
\wedgedoublebar#m
\wedgemidvert#m
\wedgeodot#m
\wedgeonwedge#m
\whitearrowupfrombar#m
\whiteinwhitetriangle#m
\whitepointerleft#m
\whitepointerright#m
\whitesquaretickleft#m
\whitesquaretickright#m
\whthorzoval#m
\whtvertoval#m
\wideangledown#m
\wideangleup#m
\xbsol#m
\xsol#m
\Yup#m
\Zbar#m
\zcmp#m
\zpipe#m
\zproject#m
\increasingconcave#m
\increasingconvex#m
\decreasingconcave#m
\increasingconvex#m

# non-unicode math symbols
\acwtrhbuarrow#m
\acwtrhluarrow#m
\acwtrhruarrow#m
\acwtrhtuarrow#m
\acwtriangleheadopencirclearrow#m
\cwtriangleheadopencirclearrow#m
\downblackarrow#m
\downtrharrowdowntrharrow#m
\downtrharrowuptrharrow#m
\downtriangleheadarrow#m
\downtriangleheadarrowbar#m
\downtriangleheaddasharrow#m
\fourcornerarrowsacw#m
\htabkey#m
\leftarrowdown#m
\leftarrowup#m
\leftblackarrow#m
\leftrightblackarrow#m
\leftrighttriangleheadarrow#m
\leftrightwhitearrow#m
\lefttriangleheadarrow#m
\lefttriangleheadarrowbar#m
\lefttriangleheaddasharrow#m
\ltrharrorltrharrow#m
\ltrharrowrtrharrow#m
\nacwcirclearrow#m
\nacwgapcirclearrow#m
\nacwleftarcarrow#m
\nacwopencirclearrow#m
\nacwoverarcarrow#m
\nacwtrhbuarrow#m
\nacwtrhluarrow#m
\nacwtrhruarrow#m
\nacwtrhtuarrow#m
\nacwtriangleheadopencirclearrow#m
\nacwunderarcarrow#m
\napproxeq#m
\napproxeqq#m
\napproxident#m
\narceq#m
\nassert#m
\nasteq#m
\nbackcong#m
\nbacksim#m
\nbacksimeq#m
\nbagmember#m
\nbardownharpoonleft#m
\nbardownharpoonright#m
\nbarleftarrow#m
\nbarleftarrowrightarrowbar#m
\nbarleftharpoondown#m
\nbarleftharpoonup#m
\nbarovernorthwestarrow#m
\nbarrightarrowdiamond#m
\nbarrightharpoondown#m
\nbarrightharpoonup#m
\nbaruparrow#m
\nbarupharpoonleft#m
\nbarupharpoonright#m
\nBarv#m
\nbarV#m
\nbetween#m
\nbNot#m
\nbsimilarleftarrow#m
\nbsimilarrightarrow#m
\nbumpeq#m
\nBumpeq#m
\nbumpeqq#m
\nCap#m
\ncarriagereturn#m
\nccwundercurvearrow#m
\ncirbot#m
\ncirceq#m
\ncircleonleftarrow#m
\ncircleonrightarrow#m
\ncirmid#m
\nclosure#m
\ncoloneq#m
\nColoneq#m
\nconcavediamond#m
\nconcavediamondtickleft#m
\nconcavediamondtickright#m
\ncongdot#m
\ncsub#m
\ncsube#m
\ncsup#m
\ncsupe#m
\nCup#m
\ncurlyeqprec#m
\ncurlyeqsucc#m
\ncurlyvee#m
\ncurlywedge#m
\ncurvearrowleft#m
\ncurvearrowleftplus#m
\ncurvearrowright#m
\ncurvearrowrightminus#m
\ncwcirclearrow#m
\ncwgapcirclearrow#m
\ncwopencirclearrow#m
\ncwrightarcarrow#m
\ncwtriangleheadopencirclearrow#m
\ncwundercurvearrow#m
\ndashcolon#m
\ndashleftharpoondown#m
\ndashrightharpoondown#m
\ndashv#m
\nDashv#m
\nDashV#m
\ndashV#m
\nDashVDash#m
\ndashVdash#m
\ndbkarrow#m
\nddotseq#m
\nDDownarrow#m
\nDdownarrow#m
\ndiamondleftarrow#m
\ndiamondleftarrowbar#m
\ndisin#m
\nDoteq#m
\ndoteq#m
\ndotequiv#m
\ndotsminusdots#m
\ndownarrow#m
\nDownarrow#m
\ndownarrowbar#m
\ndownarrowbarred#m
\ndownblackarrow#m
\ndowndasharrow#m
\ndowndownarrows#m
\ndownfishtail#m
\ndownharpoonleft#m
\ndownharpoonleftbar#m
\ndownharpoonright#m
\ndownharpoonrightbar#m
\ndownharpoonsleftright#m
\ndownrightcurvedarrow#m
\ndowntrharrowdowntrharrow#m
\ndowntrharrowuptrharrow#m
\ndowntriangleheadarrow#m
\ndowntriangleheadarrowbar#m
\ndowntriangleheaddasharrow#m
\ndownuparrows#m
\ndownupharpoonsleftright#m
\ndownwhitearrow#m
\ndownzigzagarrow#m
\ndrbkarrow#m
\ndsub#m
\ndualmap#m
\neblackarrow#m
\negsdot#m
\nelsdot#m
\neqcirc#m
\neqcolon#m
\neqdef#m
\neqdot#m
\neqeq#m
\neqeqeq#m
\neqgtr#m
\neqless#m
\neqqgtr#m
\neqqless#m
\neqqsim#m
\neqqslantgtr#m
\neqqslantless#m
\neqsim#m
\neqslantgtr#m
\neqslantless#m
\nequalleftarrow#m
\nequalrightarrow#m
\nEquiv#m
\nequivDD#m
\netriangleheadarrow#m
\netriangleheadarrowbar#m
\newhitearrow#m
\newlineleft#m
\newlineright#m
\nfallingdotseq#m
\nforkv#m
\nfourcornerarrowsacw#m
\nfrown#m
\ngeqq#m
\ngeqqslant#m
\ngeqslant#m
\ngescc#m
\ngesdot#m
\ngesdoto#m
\ngesdotol#m
\ngesles#m
\ngg#m
\nggg#m
\ngggnest#m
\ngla#m
\nglE#m
\ngleichstark#m
\nglj#m
\ngsime#m
\ngsiml#m
\nGt#m
\ngtcc#m
\ngtcir#m
\ngtquest#m
\ngtrapprox#m
\ngtrarr#m
\ngtrdot#m
\ngtreqless#m
\ngtreqqless#m
\nhatapprox#m
\nhknearrow#m
\nhknwarrow#m
\nhksearrow#m
\nhkswarrow#m
\nhookleftarrow#m
\nhookrightarrow#m
\nhtabkey#m
\nimageof#m
\nisindot#m
\nisinE#m
\nisinobar#m
\nisins#m
\nisinvb#m
\nkernelcontraction#m
\nlat#m
\nlate#m
\nLdsh#m
\nleftarrowapprox#m
\nleftarrowbackapprox#m
\nleftarrowbsimilar#m
\nleftarrowdown#m
\nleftarrowless#m
\nleftarrowonoplus#m
\nleftarrowplus#m
\nleftarrowshortrightarrow#m
\nleftarrowsimilar#m
\nleftarrowsubset#m
\nleftarrowtriangle#m
\nleftarrowup#m
\nleftarrowx#m
\nleftbkarrow#m
\nleftblackarrow#m
\nleftcurvedarrow#m
\nleftdasharrow#m
\nleftdbkarrow#m
\nleftdbltail#m
\nleftdotarrow#m
\nleftdowncurvedarrow#m
\nleftfishtail#m
\nleftharpoondown#m
\nleftharpoondownbar#m
\nleftharpoonsupdown#m
\nleftharpoonup#m
\nleftharpoonupbar#m
\nleftharpoonupdash#m
\nleftrightarrowcircle#m
\nleftrightarrows#m
\nleftrightarrowtriangle#m
\nleftrightblackarrow#m
\nleftrightharpoondowndown#m
\nleftrightharpoondownup#m
\nleftrightharpoons#m
\nleftrightharpoonsdown#m
\nleftrightharpoonsup#m
\nleftrightharpoonupdown#m
\nleftrightharpoonupup#m
\nleftrightsquigarrow#m
\nleftrighttriangleheadarrow#m
\nleftrightwhitearrow#m
\nleftsquigarrow#m
\nlefttail#m
\nleftthreearrows#m
\nlefttriangleheadarrow#m
\nlefttriangleheadarrowbar#m
\nlefttriangleheaddasharrow#m
\nleftwavearrow#m
\nleftwhitearrow#m
\nleqq#m
\nleqqslant#m
\nleqslant#m
\nlescc#m
\nlesdot#m
\nlesdoto#m
\nlesdotor#m
\nlesges#m
\nlessapprox#m
\nlessdot#m
\nlesseqgtr#m
\nlesseqqgtr#m
\nlgE#m
\nlinefeed#m
\nll#m
\nLleftarrow#m
\nLLeftarrow#m
\nlll#m
\nlllnest#m
\nlongdashv#m
\nLongleftarrow#m
\nlongleftarrow#m
\nLongleftrightarrow#m
\nlongleftrightarrow#m
\nlongleftsquigarrow#m
\nlongmapsfrom#m
\nLongmapsfrom#m
\nLongmapsto#m
\nlongmapsto#m
\nLongrightarrow#m
\nlongrightarrow#m
\nlongrightsquigarrow#m
\nlooparrowleft#m
\nlooparrowright#m
\nlozengeminus#m
\nLparengtr#m
\nlparenless#m
\nlrtriangleeq#m
\nLsh#m
\nlsime#m
\nlsimg#m
\nlsqhook#m
\nLt#m
\nltcc#m
\nltcir#m
\nltlarr#m
\nltquest#m
\nltrharrorltrharrow#m
\nltrharrowrtrharrow#m
\nltrivb#m
\nmapsdown#m
\nmapsfrom#m
\nMapsfrom#m
\nMapsto#m
\nmapsto#m
\nmapsup#m
\nmeaseq#m
\nmidcir#m
\nmlcp#m
\nmultimap#m
\nmultimapinv#m
\nNearrow#m
\nneblackarrow#m
\nneswarrow#m
\nnetriangleheadarrow#m
\nnetriangleheadarrowbar#m
\nnewhitearrow#m
\nnewlineleft#m
\nnewlineright#m
\nnHdownarrow#m
\nnHuparrow#m
\nniobar#m
\nnis#m
\nnisd#m
\nNot#m
\nnVrightarrowtail#m
\nnvrightarrowtail#m
\nnvtwoheadrightarrowtail#m
\nnVtwoheadrightarrowtail#m
\nNwarrow#m
\nnwarrowcorner#m
\nnwblackarrow#m
\nnwsearrow#m
\nnwtriangleheadarrow#m
\nnwtriangleheadarrowbar#m
\nnwwhitearrow#m
\norigof#m
\npartialmeetcontraction#m
\nperp#m
\nperps#m
\npitchfork#m
\nPrec#m
\nprecapprox#m
\npreceq#m
\npreceqq#m
\nprecsim#m
\npropto#m
\nprurel#m
\nquesteq#m
\nRdsh#m
\nreturnleft#m
\nreturnright#m
\nrightarrowapprox#m
\nrightarrowbackapprox#m
\nrightarrowbar#m
\nrightarrowbsimilar#m
\nrightarrowdiamond#m
\nrightarrowdown#m
\nrightarrowgtr#m
\nrightarrowplus#m
\nrightarrowshortleftarrow#m
\nrightarrowsimilar#m
\nrightarrowsupset#m
\nrightarrowtriangle#m
\nrightarrowup#m
\nrightarrowx#m
\nrightbkarrow#m
\nrightcurvedarrow#m
\nrightdasharrow#m
\nrightdbltail#m
\nrightdotarrow#m
\nrightdowncurvedarrow#m
\nrightfishtail#m
\nrightharpoondown#m
\nrightharpoondownbar#m
\nrightharpoonsupdown#m
\nrightharpoonup#m
\nrightharpoonupbar#m
\nrightharpoonupdash#m
\nrightimply#m
\nrightleftarrows#m
\nrightleftharpoons#m
\nrightleftharpoonsdown#m
\nrightleftharpoonsup#m
\nrightsquigarrow#m
\nrighttail#m
\nrightthreearrows#m
\nrighttriangleheadarrow#m
\nrighttriangleheadarrowbar#m
\nrighttriangleheaddasharrow#m
\nrightwardsblackarrow#m
\nrightwavearrow#m
\nrightwhitearrow#m
\nrisingdotseq#m
\nrparengtr#m
\nRparenless#m
\nRrightarrow#m
\nRRightarrow#m
\nRsh#m
\nrsqhook#m
\nrsub#m
\nrtrharrowltrharrow#m
\nrtrharrowrtrharrow#m
\nrtriltri#m
\nruledelayed#m
\nscurel#m
\nSearrow#m
\nsearrowcorner#m
\nseblackarrow#m
\nsetriangleheadarrow#m
\nsetriangleheadarrowbar#m
\nsewhitearrow#m
\nshortdowntack#m
\nshortlefttack#m
\nshortrightarrowleftarrow#m
\nshortuptack#m
\nshuffle#m
\nsimgE#m
\nsimgtr#m
\nsimilarleftarrow#m
\nsimilarrightarrow#m
\nsimlE#m
\nsimless#m
\nsimminussim#m
\nsmallin#m
\nsmallni#m
\nsmile#m
\nsmt#m
\nsmte#m
\nsqsubset#m
\nsqsupset#m
\nstareq#m
\nsubedot#m
\nsubmult#m
\nsubrarr#m
\nSubset#m
\nsubsetapprox#m
\nsubsetcirc#m
\nsubsetdot#m
\nsubseteqq#m
\nsubsetplus#m
\nsubsim#m
\nsubsub#m
\nsubsup#m
\nSucc#m
\nsuccapprox#m
\nsucceq#m
\nsucceqq#m
\nsuccsim#m
\nsupdsub#m
\nsupedot#m
\nsuphsub#m
\nsuplarr#m
\nsupmult#m
\nSupset#m
\nsupsetapprox#m
\nsupsetcirc#m
\nsupsetdot#m
\nsupseteqq#m
\nsupsetplus#m
\nsupsim#m
\nsupsub#m
\nsupsup#m
\nSwarrow#m
\nswblackarrow#m
\nswtriangleheadarrow#m
\nswtriangleheadarrowbar#m
\nswwhitearrow#m
\ntopcir#m
\ntopfork#m
\ntriangleq#m
\ntwoheaddownarrow#m
\ntwoheadleftarrowtail#m
\ntwoheadleftdbkarrow#m
\ntwoheadmapsfrom#m
\ntwoheadmapsto#m
\ntwoheadrightarrowtail#m
\ntwoheaduparrow#m
\ntwoheaduparrowcircle#m
\nUparrow#m
\nuparrow#m
\nuparrowbarred#m
\nupblackarrow#m
\nupdasharrow#m
\nupdownarrow#m
\nUpdownarrow#m
\nupdownarrowbar#m
\nupdownarrows#m
\nupdownblackarrow#m
\nupdownharpoonleftleft#m
\nupdownharpoonleftright#m
\nupdownharpoonrightleft#m
\nupdownharpoonrightright#m
\nupdownharpoonsleftright#m
\nupdowntriangleheadarrow#m
\nupfishtail#m
\nupharpoonleft#m
\nupharpoonleftbar#m
\nupharpoonright#m
\nupharpoonrightbar#m
\nupharpoonsleftright#m
\nupin#m
\nuprightcurvearrow#m
\nuptrharrowdowntrharrow#m
\nuptrharrowuptrharrow#m
\nuptriangleheadarrow#m
\nuptriangleheadarrowbar#m
\nuptriangleheaddasharrow#m
\nupuparrows#m
\nupwhitearrow#m
\nUUparrow#m
\nUuparrow#m
\nvarisinobar#m
\nvarisins#m
\nvarniobar#m
\nvarnis#m
\nvartriangle#m
\nvarVdash#m
\nvBar#m
\nVbar#m
\nvBarv#m
\nvbrtri#m
\nvDash#m
\nvDdash#m
\nveedot#m
\nveeeq#m
\nvlongdash#m
\nvtabkey#m
\nVvert#m
\nwblackarrow#m
\nwedgedot#m
\nwedgeq#m
\nwhitearrowupfrombar#m
\nwhitemapsto#m
\nwhitemapsup#m
\nwhitemapsupbar#m
\nwhitemapsupvbar#m
\nwhitetwoheadmapsup#m
\nwhitetwoheaduparrow#m
\nwhiteupdownarrow#m
\nwtriangleheadarrow#m
\nwtriangleheadarrowbar#m
\nwwhitearrow#m
\returnleft#m
\returnright#m
\rightarrowdown#m
\rightarrowup#m
\righttriangleheadarrow#m
\righttriangleheadarrowbar#m
\righttriangleheaddasharrow#m
\rightwardsblackarrow#m
\rtrharrowltrharrow#m
\rtrharrowrtrharrow#m
\seblackarrow#m
\setriangleheadarrow#m
\setriangleheadarrowbar#m
\sewhitearrow#m
\swblackarrow#m
\swtriangleheadarrow#m
\swtriangleheadarrowbar#m
\swwhitearrow#m
\upblackarrow#m
\updownblackarrow#m
\updowntriangleheadarrow#m
\uptrharrowdowntrharrow#m
\uptrharrowuptrharrow#m
\uptriangleheadarrow#m
\uptriangleheadarrowbar#m
\uptriangleheaddasharrow#m
\vtabkey#m