# newtx package
# Matthew Bertucci 3/8/2022 for v1.71

#include:newtxtext
#include:newtxmath

#keyvals:\usepackage/newtx#c
# options specific to the bundled package
otfmath#true,false
textscaled=%<factor%>
mathscaled=%<factor%>
libertine#true,false
libertinus#true,false
etbb#true,false
ebgaramond#true,false
minion#true,false
cochineal#true,false
garamondx#true,false
baskerville#true,false
baskervaldx#true,false
heuristica#true,false
erewhon#true,false
xcharter#true,false
stix2#true,false
nc#true,false
ncf#true,false
sfracvcenter=##L
sfracvspacing=##L
sfracbarthick=##L
sfracscaling=%<factor%>
# options from newtxtext
type1#true,false
type1text#true,false
otfmath#true,false
nofontspec#true,false
defaultfeatures={%<fontspec options%>}
lining#true,false
lf#true,false
oldstyle#true,false
osf#true,false
tabular#true,false
t#true,false
proportional#true,false
p#true,false
scaled=%<factor%>
defaultsups#true,false
largesc#true,false
nohelv#true,false
nott#true,false
helvratio=%<factor%>
spcfactor=%<factor%>
spacing=##L
stretch=##L
shrink=##L
oldSS
slashedzero
theoremfont
thmslshape
thmlining
trueslanted
scosf
tighter
looser
# options from newtxmath
subscriptcorrectionfile=%<file%>
nosubscriptcorrection
subscriptcorrection
timesmathacc
varbb
vvarbb
nosymbolsc
noamssymbols
amssymbols
uprightscript
uprightGreek
slantedGreek
altnu
largelibfigs
liby
frenchmath
nonewtxmathopt
upint
smallerops
useBImacros
varg
varvw
noOT1
amsthm
vecsep=##L
#endkeyvals

#ifOption:libertine
#include:libertinus
#endif
#ifOption:libertine=true
#include:libertinus
#endif
#ifOption:libertinus
#include:libertinus
#endif
#ifOption:libertinus=true
#include:libertinus
#endif

#ifOption:etbb
#include:ETbb
#endif
#ifOption:etbb=true
#include:ETbb
#endif

#ifOption:ebgaramond
#include:ebgaramond
#endif
#ifOption:ebgaramond=true
#include:ebgaramond
#endif

#ifOption:MinionPro
#include:MinionPro
#endif
#ifOption:MinionPro=true
#include:MinionPro
#endif
#ifOption:minion
#include:MinionPro
#endif
#ifOption:minion=true
#include:MinionPro
#endif

#ifOption:cochineal
#include:cochineal
#endif
#ifOption:cochineal=true
#include:cochineal
#endif

#ifOption:garamondx
#include:garamondx
#endif
#ifOption:garamondx=true
#include:garamondx
#endif

#ifOption:baskerville
#include:baskervillef
#endif
#ifOption:baskerville=true
#include:baskervillef
#endif
#ifOption:Baskerville
#include:baskervillef
#endif
#ifOption:Baskerville=true
#include:baskervillef
#endif
#ifOption:baskervillef
#include:baskervillef
#endif
#ifOption:baskervillef=true
#include:baskervillef
#endif
#ifOption:BaskervilleF
#include:baskervillef
#endif
#ifOption:BaskervilleF=true
#include:baskervillef
#endif

#ifOption:baskervaldx
#include:baskervaldx
#endif
#ifOption:baskervaldx=true
#include:baskervaldx
#endif
#ifOption:Baskervaldx
#include:baskervaldx
#endif
#ifOption:Baskervaldx=true
#include:baskervaldx
#endif

#ifOption:heuristica
#include:heuristica
#endif
#ifOption:heuristica=true
#include:heuristica
#endif
#ifOption:Heuristica
#include:heuristica
#endif
#ifOption:Heuristica=true
#include:heuristica
#endif

#ifOption:erewhon
#include:erewhon
#endif
#ifOption:erewhon=true
#include:erewhon
#endif
#ifOption:Erewhon
#include:erewhon
#endif
#ifOption:Erewhon=true
#include:erewhon
#endif

#ifOption:xcharter
#include:XCharter
#endif
#ifOption:xcharter=true
#include:XCharter
#endif
#ifOption:XCharter
#include:XCharter
#endif
#ifOption:XCharter=true
#include:XCharter
#endif

#ifOption:stickstoo
#include:stickstootext
#endif
#ifOption:stickstoo=true
#include:stickstootext
#endif
#ifOption:Stickstoo
#include:stickstootext
#endif
#ifOption:Stickstoo=true
#include:stickstootext
#endif
#ifOption:stix2
#include:stickstootext
#endif
#ifOption:stix2=true
#include:stickstootext
#endif

#ifOption:scholax
#include:scholax
#endif
#ifOption:scholax=true
#include:scholax
#endif
#ifOption:nc
#include:scholax
#endif
#ifOption:nc=true
#include:scholax
#endif
#ifOption:scholaxf
#include:scholax
#endif
#ifOption:scholaxf=true
#include:scholax
#endif
#ifOption:ncf
#include:scholax
#endif
#ifOption:ncf=true
#include:scholax
#endif

#ifOption:amsthm
#include:amsthm
#endif

#ifOption:useBImacros
\BIA#m
\BIB#m
\BIC#m
\BID#m
\BIE#m
\BIF#m
\BIG#m
\BIH#m
\BII#m
\BIJ#m
\BIK#m
\BIL#m
\BIM#m
\BIN#m
\BIO#m
\BIP#m
\BIQ#m
\BIR#m
\BIS#m
\BIT#m
\BIU#m
\BIV#m
\BIW#m
\BIX#m
\BIY#m
\BIZ#m
\BIa#m
\BIb#m
\BIc#m
\BId#m
\BIe#m
\BIf#m
\BIg#m
\BIh#m
\BIi#m
\BIj#m
\BIk#m
\BIl#m
\BIm#m
\BIn#m
\BIo#m
\BIp#m
\BIq#m
\BIr#m
\BIs#m
\BIt#m
\BIu#m
\BIv#m
\BIw#m
\BIx#m
\BIy#m
\BIz#m
#endif

\PassMathScale#*
\PassMatchingScale{factor}#*
\textsfrac[whole part]{numerator}{denominator}
\textsfrac{numerator}{denominator}
\pliningnums#*
