# newtxsf package
# Matthew Bertucci 6/21/2021

#include:amsmath
#include:amssymb
#include:amsfonts
#include:xkeyval

\alphaup#*m
\barbar{arg}#m
\barhat{arg}#m
\bartilde{arg}#m
\betaup#*m
\bigcapop#*m
\bigcapplus#m
\bigcapplusop#*m
\bigcupdot#m
\bigcupdotop#*m
\bigcupop#*m
\bigcupplus#m
\bignplus#m
\bigodotop#*m
\bigoplusop#*m
\bigotimesop#*m
\bigsqcap#m
\bigsqcapop#*m
\bigsqcapplus#m
\bigsqcapplusop#*m
\bigsqcupop#*m
\bigsqcupplus#m
\bigsqcupplusop#*m
\bigtimes#m
\bigtimesop#*m
\biguplusop#*m
\bigveeop#*m
\bigwedgeop#*m
\Bot#m
\boxast#m
\boxbar#m
\boxbslash#m
\boxdotleft#m
\boxdotLeft#m
\boxdotright#m
\boxdotRight#m
\boxleft#m
\boxLeft#m
\boxright#m
\boxRight#m
\boxslash#m
\bulletS#m
\bulletSS#m
\bulletSSS#m
\cdotB#m
\cdotBB#m
\chiup#*m
\circledbar#m
\circledbslash#m
\circleddot#m
\circleddotleft#m
\circleddotright#m
\circledgtr#m
\circledless#m
\circledminus#m
\circledotleft#m
\circledotright#m
\circledplus#m
\circledR#m
\circledslash#m
\circledtimes#m
\circledvee#m
\circledwedge#m
\circleleft#m
\circleright#m
\circS#m
\colonapprox#m
\Colonapprox#m
\Coloneq#m
\coloneq#m
\coloneqq#m
\Coloneqq#m
\colonsim#m
\Colonsim#m
\coprodop#*m
\dasharrow#m
\dashleftarrow#m
\dashleftrightarrow#m
\Deltaup#*m
\deltaup#*m
\Diamond#m
\Diamondblack#m
\Diamonddot#m
\Diamonddotleft#m
\DiamonddotLeft#m
\Diamonddotright#m
\DiamonddotRight#m
\Diamondleft#m
\DiamondLeft#m
\Diamondright#m
\DiamondRight#m
\dlb#m
\Doteq#m
\doublecap#m
\doublecup#m
\downgroupfill#*
\downgroupfillla#*
\downgroupfillra#*
\drb#m
\emptysetAlt#m
\epsilonup#*m
\Eqcolon#m
\eqcolon#m
\Eqqcolon#m
\eqqcolon#m
\equalht{arg}#*
\etaup#*m
\existsAlt#m
\fint#m
\fintop#*m
\fintsl#*m
\fintslop#*m
\fintup#*m
\fintupop#*m
\forallAlt#m
\Gammaup#*m
\gammaup#*m
\gggtr#m
\groupld#*m
\grouplda#*m
\grouplu#*m
\grouplua#*m
\grouprd#*m
\grouprda#*m
\groupru#*m
\grouprua#*m
\harpoonacc{arg}#m
\hatbar{arg}#m
\hathat{arg}#m
\hattilde{arg}#m
\hermtransp#m
\htransp#m
\iiiintop#*m
\iiiintsl#*m
\iiiintslop#*m
\iiiintup#*m
\iiiintupop#*m
\iiintop#*m
\iiintsl#*m
\iiintslop#*m
\iiintup#*m
\iiintupop#*m
\iintop#*m
\iintsl#*m
\iintslop#*m
\iintup#*m
\iintupop#*m
\intop#*m
\intsl#*m
\intslop#*m
\intup#*m
\intupop#*m
\invamp#m
\iotaup#*m
\Join#m
\kappaup#*m
\lambdabar#m
\lambdaslash#m
\Lambdaup#*m
\lambdaup#*m
\lbag#m
\Lbag#m
\lBrack#m
\leadsto#m
\leadstoext#m
\leftsquigarrow#m
\lharpoonacc{arg}#m
\lJoin#m
\llbracket#m
\llless#m
\Longmappedfrom#m
\longmappedfrom#m
\Longmapsto#m
\Longmmappedfrom#m
\longmmappedfrom#m
\Longmmapsto#m
\longmmapsto#m
\lrharpoonacc{arg}#m
\lrJoin#m
\lrtimes#m
\lrvec{arg}#m
\lvec{arg}#m
\Mappedfrom#m
\mappedfrom#m
\mappedfromchar#*m
\Mappedfromchar#*m
\Mapsfrom#m
\mapsfrom#m
\Mapsto#m
\Mapstochar#*m
\medbullet#m
\medcirc#m
\Mmappedfrom#m
\mmappedfrom#m
\mmappedfromchar#*m
\Mmappedfromchar#*m
\Mmapsto#m
\mmapsto#m
\mmapstochar#*m
\Mmapstochar#*m
\multimapboth#m
\multimapbothvert#m
\multimapbothvert#m
\multimapdot#m
\multimapdotboth#m
\multimapdotbothA#m
\multimapdotbothAvert#m
\multimapdotbothB#m
\multimapdotbothBvert#m
\multimapdotbothvert#m
\multimapdotinv#m
\multimapinv#m
\muup#*m
\nablaup#*m
\napprox#m
\napproxeq#m
\nasymp#m
\nbacksim#m
\nbacksimeq#m
\nBumpeq#m
\nbumpeq#m
\Nearrow#m
\nequiv#m
\nexists#m
\nexistsAlt#m
\ngg#m
\ngtrapprox#m
\ngtrless#m
\ngtrsim#m
\nlessapprox#m
\nlessgtr#m
\nlesssim#m
\nll#m
\nni#*m
\notni#m
\notowns#m
\nPerp#m
\nplus#m
\nprecapprox#m
\npreccurlyeq#m
\npreceqq#m
\nprecsim#m
\nsimeq#m
\nsqsubset#m
\nsqsubseteq#m
\nsqsupset#m
\nsqsupseteq#m
\nsubset#m
\nSubset#m
\nsuccapprox#m
\nsucccurlyeq#m
\nsucceqq#m
\nsuccsim#m
\nsupset#m
\nSupset#m
\nthickapprox#m
\ntwoheadleftarrow#m
\ntwoheadrightarrow#m
\nuup#*m
\nvarparallel#m
\nvarparallelinv#m
\Nwarrow#m
\oiiint#m
\oiiintop#*m
\oiiintsl#*m
\oiiintslop#*m
\oiiintup#*m
\oiiintupop#*m
\oiint#m
\oiintop#*m
\oiintsl#*m
\oiintslop#*m
\oiintup#*m
\oiintupop#*m
\ointctrclockwise#m
\ointctrclockwiseop#*m
\ointctrclockwisesl#*m
\ointctrclockwiseslop#*m
\ointctrclockwiseup#*m
\ointctrclockwiseupop#*m
\ointop#*m
\ointsl#*m
\ointslop#*m
\ointup#*m
\ointupop#*m
\Omegaup#*m
\omegaup#*m
\openbox#m
\openJoin#m
\openJoin#m
\opentimes#m
\overgroup{arg}#m
\overgroupla{arg}#m
\overgroupra{arg}#m
\Perp#m
\Phiup#*m
\phiup#*m
\Piup#*m
\piup#*m
\preceqq#m
\primeS#m
\prodop#*m
\Psiup#*m
\psiup#*m
\rbag#m
\Rbag#m
\rBrack#m
\restriction#m
\rhoup#*m
\rJoin#m
\rrbracket#m
\Searrow#m
\Sigmaup#*m
\sigmaup#*m
\smallcoprod#m
\smallfint#m
\smallfintsl#*m
\smallfintup#*m
\smalliiiint#m
\smalliiiintsl#*m
\smalliiiintup#*m
\smalliiint#m
\smalliiintsl#*m
\smalliiintup#*m
\smalliint#m
\smalliintsl#*m
\smalliintup#*m
\smallintsl#*m
\smallintup#*m
\smalloiiint#m
\smalloiiintsl#*m
\smalloiiintup#*m
\smalloiint#m
\smalloiintsl#*m
\smalloiintup#*m
\smalloint#m
\smallointctrclockwise#m
\smallointctrclockwisesl#*m
\smallointctrclockwiseup#*m
\smallointsl#*m
\smallointup#*m
\smallprod#m
\smallsqint#m
\smallsqintsl#*m
\smallsqintup#*m
\smallsum#m
\smallsumint#m
\smallsumintsl#*m
\smallsumintup#*m
\smallvarointclockwise#m
\smallvarointclockwisesl#*m
\smallvarointclockwiseup#*m
\sqcapplus#m
\sqcupplus#m
\sqint#m
\sqintop#*m
\sqintsl#*m
\sqintslop#*m
\sqintup#*m
\sqintupop#*m
\strictfi#m
\strictif#m
\strictiff#m
\succeqq#m
\sumint#m
\sumintop#*m
\sumintsl#*m
\sumintslop#*m
\sumintup#*m
\sumintupop#*m
\sumop#*m
\Swarrow#m
\tauup#*m
\textsquare#m
\Thetaup#*m
\thetaup#*m
\tildebar{a}#m
\tildehat{a}#m
\tildetilde{a}#m
\Top#m
\transp#m
\txvec{arg}#*m
\undergroup{arg}#m
\undergroupla{arg}#m
\undergroupra{arg}#m
\upalpha#m
\upbeta#m
\upchi#m
\upDelta#m
\updelta#m
\upepsilon#m
\upeta#m
\upGamma#m
\upgamma#m
\upgroupfill#*
\upgroupfillla#*
\upgroupfillra#*
\upimath#m
\upiota#m
\upjmath#m
\upkappa#m
\upLambda#m
\uplambda#m
\upmu#m
\upnu#m
\upOmega#m
\upomega#m
\uppartial#m
\upPhi#m
\upphi#m
\upPi#m
\uppi#m
\upPsi#m
\uppsi#m
\uprho#m
\upSigma#m
\upsigma#m
\Upsilonup#*m
\upsilonup#*m
\uptau#m
\upTheta#m
\uptheta#m
\upUpsilon#m
\upupsilon#m
\upvarepsilon#m
\upvarkappa#m
\upvarphi#m
\upvarpi#m
\upvarrho#m
\upvarsigma#m
\upvartheta#m
\upXi#m
\upxi#m
\upzeta#m
\varclubsuit#m
\vardiamondsuit#m
\varepsilonup#*m
\varheartsuit#m
\varkappaup#*m
\varmathbb{letter}#m
\varointclockwise#m
\varointclockwiseop#*m
\varointclockwisesl#*m
\varointclockwiseslop#*m
\varointclockwiseup#*m
\varointclockwiseupop#*m
\varparallel#m
\varparallelinv#m
\varphiup#*m
\varpiup#*m
\varprod#m
\varrhoup#*m
\varsigmaup#*m
\varspadesuit#m
\varthetaup#*m
\VDash#m
\vv*{arg}{sub}#m
\vv{arg}#m
\VvDash#m
\vvstar{arg}{sub}#*m
\widearc{arg}#m
\wideOarc{arg}#m
\widering{arg}#m
\Wr#m
\Xiup#*m
\xiup#*m
\zetaup#*m

\DoFutureLet#*
\ShowMathFonts#*
