# principia package
# Matthew Bertucci 1/9/2021 for v1.3

#include:amssymb
#include:amsmath
#include:graphicx
#include:pifont

\pmthm#m
\pmast
\pmcdot
\pmpp
\pmiddf#m
\pmdf
\pmdem
\pmdot#m
\pmdott#m
\pmdottt#m
\pmdotttt#m
\pmdottttt#m
\pmdotttttt#m
\pmdotttttt#m
\pmand#m
\pmandd#m
\pmanddd#m
\pmandddd#m
\pmanddddd#m
\pmandddddd#m
\pmsub{top}{bot}#m
\pmsubb{top1}{bot1}{top2}{bot2}#m
\pmsubbb{top1}{bot1}{top2}{bot2}{top3}{bot3}#m
\pmsubbbb{top1}{bot1}{top2}{bot2}{top3}{bot3}{top4}{bot4}#m
\pmSub{name}{top}{bot}#m
\pmSubb{name}{top1}{bot1}{top2}{bot2}#m
\pmSubbb{name}{top1}{bot1}{top2}{bot2}{top3}{bot3}#m
\pmSubbbb{name}{top1}{bot1}{top2}{bot2}{top3}{bot3}{top4}{bot4}#m
\pmor#m
\pmnot#m
\pmimp#m
\pmiff#m
\pmhat{x}#m
\pmpf{func}{arg}
\pmpff{func}{arg1}{arg2}
\pmpfff{func}{arg1}{arg2}{arg3}
\pmall{arg}
\pmsome{arg}
\pmSome
\pmshr
\pmpred{pred}{arg}
\pmpredd{pred}{arg1}{arg2}
\pmpreddd{pred}{arg1}{arg2}{arg3}
\pmnid#m
\pmdsc{arg}
\pmexists

# not documented
\pmDsc#*
\pmSUb{name}{top}{bot}#*m
\pmSUbb{name}{top1}{bot1}{top2}{bot2}#*m
\pmSUbbb{name}{top1}{bot1}{top2}{bot2}{top3}{bot3}#*m
\pmSUbbbb{name}{top1}{bot1}{top2}{bot2}{top3}{bot3}{top4}{bot4}#*m
\pmbreve{arg}#*m
\pmbr{arg}#*
\pmcirc{arg}#*m
\pmdemi#*
\pmfd#*
\pmhp#*
\pmiota#*
\pmithm#*m
\pmprod#*m
\pmprop#*
\pmsUb{top}{bot}#*m
\pmsUbb{top1}{bot1}{top2}{bot2}#*m
\pmsUbbb{top1}{bot1}{top2}{bot2}{top3}{bot3}#*m
\pmsUbbbb{top1}{bot1}{top2}{bot2}{top3}{bot3}{top4}{bot4}#*m