# projlib-theorem package
# Matthew Bertucci 2022/06/17 for 2022/06/15 release

#include:l3keys2e
#include:projlib-language
#include:amsthm
#include:create-theorem

#keyvals:\usepackage/projlib-theorem#c
nothms#true,false
nothmnum#true,false
thmnum
thmnum=%<counter%>
theorem style=%<style%>
complex name#true,false
simple name#true,false
no preset names#true,false
#endkeyvals

\begin{application}
\begin{application}[heading%text]
\end{application}
\begin{application*}
\begin{application*}[heading%text]
\end{application*}
\begin{assertion}
\begin{assertion}[heading%text]
\end{assertion}
\begin{assertion*}
\begin{assertion*}[heading%text]
\end{assertion*}
\begin{assumption}
\begin{assumption}[heading%text]
\end{assumption}
\begin{assumption*}
\begin{assumption*}[heading%text]
\end{assumption*}
\begin{axiom}
\begin{axiom}[heading%text]
\end{axiom}
\begin{axiom*}
\begin{axiom*}[heading%text]
\end{axiom*}
\begin{claim}
\begin{claim}[heading%text]
\end{claim}
\begin{claim*}
\begin{claim*}[heading%text]
\end{claim*}
\begin{conclusion}
\begin{conclusion}[heading%text]
\end{conclusion}
\begin{conclusion*}
\begin{conclusion*}[heading%text]
\end{conclusion*}
\begin{conjecture}
\begin{conjecture}[heading%text]
\end{conjecture}
\begin{conjecture*}
\begin{conjecture*}[heading%text]
\end{conjecture*}
\begin{construction}
\begin{construction}[heading%text]
\end{construction}
\begin{construction*}
\begin{construction*}[heading%text]
\end{construction*}
\begin{convention}
\begin{convention}[heading%text]
\end{convention}
\begin{convention*}
\begin{convention*}[heading%text]
\end{convention*}
\begin{corollary}
\begin{corollary}[heading%text]
\end{corollary}
\begin{corollary*}
\begin{corollary*}[heading%text]
\end{corollary*}
\begin{definition}
\begin{definition}[heading%text]
\end{definition}
\begin{definition*}
\begin{definition*}[heading%text]
\end{definition*}
\begin{example}
\begin{example}[heading%text]
\end{example}
\begin{example*}
\begin{example*}[heading%text]
\end{example*}
\begin{exercise}
\begin{exercise}[heading%text]
\end{exercise}
\begin{exercise*}
\begin{exercise*}[heading%text]
\end{exercise*}
\begin{fact}
\begin{fact}[heading%text]
\end{fact}
\begin{fact*}
\begin{fact*}[heading%text]
\end{fact*}
\begin{hypothesis}
\begin{hypothesis}[heading%text]
\end{hypothesis}
\begin{hypothesis*}
\begin{hypothesis*}[heading%text]
\end{hypothesis*}
\begin{lemma}
\begin{lemma}[heading%text]
\end{lemma}
\begin{lemma*}
\begin{lemma*}[heading%text]
\end{lemma*}
\begin{notation}
\begin{notation}[heading%text]
\end{notation}
\begin{notation*}
\begin{notation*}[heading%text]
\end{notation*}
\begin{observation}
\begin{observation}[heading%text]
\end{observation}
\begin{observation*}
\begin{observation*}[heading%text]
\end{observation*}
\begin{postulate}
\begin{postulate}[heading%text]
\end{postulate}
\begin{postulate*}
\begin{postulate*}[heading%text]
\end{postulate*}
\begin{problem}
\begin{problem}[heading%text]
\end{problem}
\begin{problem*}
\begin{problem*}[heading%text]
\end{problem*}
\begin{property}
\begin{property}[heading%text]
\end{property}
\begin{property*}
\begin{property*}[heading%text]
\end{property*}
\begin{proposition}
\begin{proposition}[heading%text]
\end{proposition}
\begin{proposition*}
\begin{proposition*}[heading%text]
\end{proposition*}
\begin{question}
\begin{question}[heading%text]
\end{question}
\begin{question*}
\begin{question*}[heading%text]
\end{question*}
\begin{recall}
\begin{recall}[heading%text]
\end{recall}
\begin{recall*}
\begin{recall*}[heading%text]
\end{recall*}
\begin{remark}
\begin{remark}[heading%text]
\end{remark}
\begin{remark*}
\begin{remark*}[heading%text]
\end{remark*}
\begin{theorem}
\begin{theorem}[heading%text]
\end{theorem}
\begin{theorem*}
\begin{theorem*}[heading%text]
\end{theorem*}
\begin{definition-proposition}
\begin{definition-proposition}[heading%text]
\end{definition-proposition}
\begin{definition-proposition*}
\begin{definition-proposition*}[heading%text]
\end{definition-proposition*}
\begin{definition-theorem}
\begin{definition-theorem}[heading%text]
\end{definition-theorem}
\begin{definition-theorem*}
\begin{definition-theorem*}[heading%text]
\end{definition-theorem*}
\begin{proposition-definition}
\begin{proposition-definition}[heading%text]
\end{proposition-definition}
\begin{proposition-definition*}
\begin{proposition-definition*}[heading%text]
\end{proposition-definition*}
\begin{theorem-definition}
\begin{theorem-definition}[heading%text]
\end{theorem-definition}
\begin{theorem-definition*}
\begin{theorem-definition*}[heading%text]
\end{theorem-definition*}

\begin{theorem-with-name}{arg}
\begin{theorem-with-name}{arg}[opt]
\end{theorem-with-name}
\begin{theorem-with-name*}{arg}
\begin{theorem-with-name*}{arg}[opt]
\end{theorem-with-name*}

\begin{proof*}
\begin{proof*}[heading%text]
\end{proof*}
\theproof#*

\DisableTheoremNumbering{envname}
\SwitchTheoremNumbering{envname}
