# pst-fractal package
# Matthew Bertucci 2022/10/14 for v0.12

#include:pstricks
#include:pst-func
#include:pstricks-add
#include:pst-xkey

\psCantor
\psCantor[options%keyvals]
\psSier(x0,y0)(x1,y1)(x2,y2)
\psSier(x0,y0){base}{recursion}
\psSier[options%keyvals]
\psSier[options%keyvals](x0,y0)(x1,y1)(x2,y2)
\psSier[options%keyvals](x0,y0){base}{recursion}
\psSierCarpet
\psSierCarpet(x,y)
\psSierCarpet[options%keyvals]
\psSierCarpet[options%keyvals](x,y)
\psfractal
\psfractal[options%keyvals]
\psfractal(x0,y0)(x1,y1)
\psfractal[options%keyvals](x0,y0)(x1,y1)
\psPhyllotaxis
\psPhyllotaxis[options%keyvals]
\psPhyllotaxis(x,y)
\psPhyllotaxis[options%keyvals](x,y)
\psFern
\psFern[options%keyvals]
\psFern(x,y)
\psFern[options%keyvals](x,y)
\psKochflake
\psKochflake[options%keyvals]
\psKochflake(x,y)
\psKochflake[options%keyvals](x,y)
\psAppolonius
\psAppolonius[options%keyvals]
\psAppolonius(x,y)
\psAppolonius[options%keyvals](x,y)
\psPTree
\psPTree[options%keyvals]
\psPTree(x,y)
\psPTree[options%keyvals](x,y)
\psFArrow{fraction}
\psFArrow[options%keyvals]{fraction}
\psFArrow(x,y){fraction}
\psFArrow[options%keyvals](x,y){fraction}
\psFibonacciWord(x,y)
\psFibonacciWord[options%keyvals](x,y)
\psFibonacci
\psFibonacci[options%keyvals]
\psNewFibonacci
\psNewFibonacci[options%keyvals]
\psiFibonacci
\psiFibonacci[options%keyvals]
\pskFibonacci[options%keyvals]
\pskFibonacci[options%keyvals](x,y)
\psBiperiodicFibonacci[options%keyvals]
\psBiperiodicFibonacci[options%keyvals](x,y)
\psFibonacciPolyominoes[options%keyvals]
\psFibonacciPolyominoes[options%keyvals](x,y)
\psHilbert
\psHilbert[options%keyvals]
\psHenon
\psHenon[options%keyvals]
\psHugo
\psHugo[options%keyvals]
\psHugo(x,y)
\psHugo[options%keyvals](x,y)
\psdotcolor#S
\pscolorF#S
\PSTfractalLoaded#S
