# roboto package
# Matthew Bertucci 2022/05/10 for release 2019/12/11

#include:ifxetex
#include:ifluatex
#include:textcomp
#include:xkeyval
#include:fontenc
#include:fontaxes
#include:mweights

#keyvals:\usepackage/roboto#c
scale=%<factor%>
default
sfdefault
type1
medium
bold
black
thin
light
regular
condensed
slab
lining
oldstyle
tabular
proportional
#endkeyvals

\robotoLF{text}
\robotoTLF{text}
\robotoOsF{text}
\robotoTOsF{text}
\robotoThin{text}
\robotoLight{text}
\robotoRegular{text}
\robotoMedium{text}
\robotoBold{text}
\robotoBlack{text}
\roboto#*
\robotocondensed#*
\robotoboldcondensed#*
\robotoslab#*
\robotoregular#*
\robotolight#*
\robotobold#*
\robotoosf#*
\robotolf#*
\robototlf#*
\robototosf#*
\robotothin#*
\robotomedium#*
\robotoblack#*
\robotoosf#*
\robotolgr#*
\robotoslablgr#*
\robotofamily#*
\robotoslabfamily#*
