# rubikcube package
# Matthew Bertucci 1/22/2022 for v5.0

#include:forarray
#include:ifthen
#include:tikz

# note: several commands repeated with args changed to
# "color" and #S added to get color completion

\Blb#*
\Blm#*
\Blt#*
\Cubiedx{number}
\Cubiedy{number}
\Dlb#*
\Dlm#*
\Dlt#*
\DrawCubieLD{color}{color}{color}#S
\DrawCubieLD{Xcolor}{Ycolor}{Zcolor}
\DrawCubieLU{color}{color}{color}#S
\DrawCubieLU{Xcolor}{Ycolor}{Zcolor}
\DrawCubieRD{color}{color}{color}#S
\DrawCubieRD{Xcolor}{Ycolor}{Zcolor}
\DrawCubieRU{color}{color}{color}#S
\DrawCubieRU{Xcolor}{Ycolor}{Zcolor}
\DrawNCubeAll{integer}{color}{color}{color}#S
\DrawNCubeAll{integer}{Xcolor}{Ycolor}{Zcolor}
\DrawNotationBox#*
\DrawRubikCube
\DrawRubikCubeF
\DrawRubikCubeFrontFace#*
\DrawRubikCubeLD
\DrawRubikCubeLU
\DrawRubikCubeRD
\DrawRubikCubeRU
\DrawRubikCubeSF
\DrawRubikCubeSidebarBD{view direction}
\DrawRubikCubeSidebarBDLD#*
\DrawRubikCubeSidebarBDRD#*
\DrawRubikCubeSidebarBL{view direction}
\DrawRubikCubeSidebarBLLD#*
\DrawRubikCubeSidebarBLLU#*
\DrawRubikCubeSidebarBR{view direction}
\DrawRubikCubeSidebarBRRD#*
\DrawRubikCubeSidebarBRRU#*
\DrawRubikCubeSidebarBU{view direction}
\DrawRubikCubeSidebarBULU#*
\DrawRubikCubeSidebarBURU#*
\DrawRubikCubeSidebarDB{view direction}
\DrawRubikCubeSidebarDBLD#*
\DrawRubikCubeSidebarDBRD#*
\DrawRubikCubeSidebarDF{view direction}
\DrawRubikCubeSidebarDFLU#*
\DrawRubikCubeSidebarDFRU#*
\DrawRubikCubeSidebarFD{view direction}
\DrawRubikCubeSidebarFDLU#*
\DrawRubikCubeSidebarFDRU#*
\DrawRubikCubeSidebarFL{view direction}
\DrawRubikCubeSidebarFLRD#*
\DrawRubikCubeSidebarFLRU#*
\DrawRubikCubeSidebarFR{view direction}
\DrawRubikCubeSidebarFRLD#*
\DrawRubikCubeSidebarFRLU#*
\DrawRubikCubeSidebarFU{view direction}
\DrawRubikCubeSidebarFULD#*
\DrawRubikCubeSidebarFURD#*
\DrawRubikCubeSidebarLB{view direction}
\DrawRubikCubeSidebarLBLD#*
\DrawRubikCubeSidebarLBLU#*
\DrawRubikCubeSidebarLF{view direction}
\DrawRubikCubeSidebarLFRD#*
\DrawRubikCubeSidebarLFRU#*
\DrawRubikCubeSidebarRB{view direction}
\DrawRubikCubeSidebarRBRD#*
\DrawRubikCubeSidebarRBRU#*
\DrawRubikCubeSidebarRF{view direction}
\DrawRubikCubeSidebarRFLD#*
\DrawRubikCubeSidebarRFLU#*
\DrawRubikCubeSidebarUB{view direction}
\DrawRubikCubeSidebarUBLU#*
\DrawRubikCubeSidebarUBRU#*
\DrawRubikCubeSidebarUF{view direction}
\DrawRubikCubeSidebarUFLD#*
\DrawRubikCubeSidebarUFRD#*
\DrawRubikFaceB#*
\DrawRubikFaceBack
\DrawRubikFaceBackSide
\DrawRubikFaceBS#*
\DrawRubikFaceD#*
\DrawRubikFaceDown
\DrawRubikFaceDownSide
\DrawRubikFaceDS#*
\DrawRubikFaceF#*
\DrawRubikFaceFront
\DrawRubikFaceFrontSide
\DrawRubikFaceFS#*
\DrawRubikFaceL#*
\DrawRubikFaceLeft
\DrawRubikFaceLeftSide
\DrawRubikFaceLS#*
\DrawRubikFaceR#*
\DrawRubikFaceRight
\DrawRubikFaceRightSide
\DrawRubikFaceRS#*
\DrawRubikFaceU#*
\DrawRubikFaceUp
\DrawRubikFaceUpSide
\DrawRubikFaceUS#*
\DrawRubikFlatBack{x}{y}
\DrawRubikFlatDown{x}{y}
\DrawRubikFlatFront
\DrawRubikFlatLeft{x}{y}
\DrawRubikFlatRight{x}{y}
\DrawRubikFlatUp{x}{y}
\Flb#*
\Flm#*
\Flt#*
\Llb#*
\Llm#*
\Llt#*
\NoSidebar{color-code}
\RCfiledate#S
\RCfileversion#S
\Rlb#*
\Rlm#*
\Rlt#*
\rr{rotation code}
\rrB#*
\rrb#*
\rrBa#*
\rrBap#*
\rrBc#*
\rrBcp#*
\rrBm#*
\rrBmp#*
\rrBp#*
\rrbp#*
\rrBs#*
\rrBsp#*
\rrBw#*
\rrBwp#*
\rrCB#*
\rrCBp#*
\rrCD#*
\rrCDp#*
\rrCF#*
\rrCFp#*
\rrCL#*
\rrCLp#*
\rrCR#*
\rrCRp#*
\rrCU#*
\rrCUp#*
\rrD#*
\rrd#*
\rrDa#*
\rrDap#*
\rrDc#*
\rrDcp#*
\rrDm#*
\rrDmp#*
\rrDp#*
\rrdp#*
\rrDs#*
\rrDsp#*
\rrDw#*
\rrDwp#*
\rrE#*
\rrEp#*
\rrF#*
\rrf#*
\rrFa#*
\rrFap#*
\rrFc#*
\rrFcp#*
\rrFm#*
\rrFmp#*
\rrFp#*
\rrfp#*
\rrFs#*
\rrFsp#*
\rrFw#*
\rrFwp#*
\rrh{rotation code}
\rrhB#*
\rrhb#*
\rrhBa#*
\rrhBap#*
\rrhBc#*
\rrhBcp#*
\rrhBm#*
\rrhBmp#*
\rrhBp#*
\rrhbp#*
\rrhBs#*
\rrhBsp#*
\rrhBw#*
\rrhBwp#*
\rrhCB#*
\rrhCBp#*
\rrhCD#*
\rrhCDp#*
\rrhCF#*
\rrhCFp#*
\rrhCL#*
\rrhCLp#*
\rrhCR#*
\rrhCRp#*
\rrhCU#*
\rrhCUp#*
\rrhD#*
\rrhd#*
\rrhDa#*
\rrhDap#*
\rrhDc#*
\rrhDcp#*
\rrhDm#*
\rrhDmp#*
\rrhDp#*
\rrhdp#*
\rrhDs#*
\rrhDsp#*
\rrhDw#*
\rrhDwp#*
\rrhE#*
\rrhEp#*
\rrhF#*
\rrhf#*
\rrhFa#*
\rrhFap#*
\rrhFc#*
\rrhFcp#*
\rrhFm#*
\rrhFmp#*
\rrhFp#*
\rrhfp#*
\rrhFs#*
\rrhFsp#*
\rrhFw#*
\rrhFwp#*
\rrhL#*
\rrhl#*
\rrhLa#*
\rrhLap#*
\rrhLc#*
\rrhLcp#*
\rrhLm#*
\rrhLmp#*
\rrhLp#*
\rrhlp#*
\rrhLs#*
\rrhLsp#*
\rrhLw#*
\rrhLwp#*
\rrhM#*
\rrhMB#*
\rrhMBp#*
\rrhMD#*
\rrhMDp#*
\rrhMF#*
\rrhMFp#*
\rrhML#*
\rrhMLp#*
\rrhMp#*
\rrhMR#*
\rrhMRp#*
\rrhMU#*
\rrhMUp#*
\rrhR#*
\rrhr#*
\rrhRa#*
\rrhRap#*
\rrhRc#*
\rrhRcp#*
\rrhRm#*
\rrhRmp#*
\rrhRp#*
\rrhrp#*
\rrhRs#*
\rrhRsp#*
\rrhRw#*
\rrhRwp#*
\rrhS#*
\rrhSB#*
\rrhSb#*
\rrhSBp#*
\rrhSbp#*
\rrhSD#*
\rrhSd#*
\rrhSDp#*
\rrhSdp#*
\rrhSF#*
\rrhSf#*
\rrhSFp#*
\rrhSfp#*
\rrhSL#*
\rrhSl#*
\rrhSLp#*
\rrhSlp#*
\rrhSp#*
\rrhSR#*
\rrhSr#*
\rrhSRp#*
\rrhSrp#*
\rrhSU#*
\rrhSu#*
\rrhSUp#*
\rrhSup#*
\rrhTB#*
\rrhTBp#*
\rrhTD#*
\rrhTDp#*
\rrhTF#*
\rrhTFp#*
\rrhTL#*
\rrhTLp#*
\rrhTR#*
\rrhTRp#*
\rrhTU#*
\rrhTUp#*
\rrhU#*
\rrhu#*
\rrhUa#*
\rrhUap#*
\rrhUc#*
\rrhUcp#*
\rrhUm#*
\rrhUmp#*
\rrhUp#*
\rrhup#*
\rrhUs#*
\rrhUsp#*
\rrhUw#*
\rrhUwp#*
\rrhx#*
\rrhxp#*
\rrhy#*
\rrhyp#*
\rrhz#*
\rrhzp#*
\rrL#*
\rrl#*
\rrLa#*
\rrLap#*
\rrLc#*
\rrLcp#*
\rrLm#*
\rrLmp#*
\rrLp#*
\rrlp#*
\rrLs#*
\rrLsp#*
\rrLw#*
\rrLwp#*
\rrM#*
\rrMB#*
\rrMBp#*
\rrMD#*
\rrMDp#*
\rrMF#*
\rrMFp#*
\rrML#*
\rrMLp#*
\rrMp#*
\rrMR#*
\rrMRp#*
\rrMU#*
\rrMUp#*
\rrR#*
\rrr#*
\rrRa#*
\rrRap#*
\rrRc#*
\rrRcp#*
\rrRm#*
\rrRmp#*
\rrRp#*
\rrrp#*
\rrRs#*
\rrRsp#*
\rrRw#*
\rrRwp#*
\rrS#*
\rrSB#*
\rrSb#*
\rrSBp#*
\rrSbp#*
\rrSD#*
\rrSd#*
\rrSDp#*
\rrSdp#*
\rrSF#*
\rrSf#*
\rrSFp#*
\rrSfp#*
\rrSL#*
\rrSl#*
\rrSLp#*
\rrSlp#*
\rrSp#*
\rrSR#*
\rrSr#*
\rrSRp#*
\rrSrp#*
\rrSU#*
\rrSu#*
\rrSUp#*
\rrSup#*
\rrTB#*
\rrTBp#*
\rrTD#*
\rrTDp#*
\rrTF#*
\rrTFp#*
\rrTL#*
\rrTLp#*
\rrTR#*
\rrTRp#*
\rrTU#*
\rrTUp#*
\rrU#*
\rru#*
\rrUa#*
\rrUap#*
\rrUc#*
\rrUcp#*
\rrUm#*
\rrUmp#*
\rrUp#*
\rrup#*
\rrUs#*
\rrUsp#*
\rrUw#*
\rrUwp#*
\rrx#*
\rrxp#*
\rry#*
\rryp#*
\rrz#*
\rrzp#*
\Rubik{rotation code}
\RubikB#*
\Rubikb#*
\RubikBa#*
\RubikBap#*
\RubikBc#*
\RubikBcp#*
\RubikBm#*
\RubikBmp#*
\RubikBp#*
\Rubikbp#*
\RubikBs#*
\RubikBsp#*
\RubikBw#*
\RubikBwp#*
\RubikCB#*
\RubikCBp#*
\RubikCD#*
\RubikCDp#*
\RubikCF#*
\RubikCFp#*
\RubikCL#*
\RubikCLp#*
\RubikCR#*
\RubikCRp#*
\RubikCU#*
\Rubikcube#*
\rubikcube#*
\RubikCubeGray#S
\RubikCubeGrayAll#S
\RubikCubeGrayWB#S
\RubikCubeGrayWY#S
\RubikCubeGrey#*
\RubikCubeGreyAll
\RubikCubeGreyWB
\RubikCubeGreyWY
\RubikCubeSolved
\RubikCubeSolvedWB
\RubikCubeSolvedWY
\RubikCUp#*
\RubikD#*
\Rubikd#*
\RubikDa#*
\RubikDap#*
\RubikDc#*
\RubikDcp#*
\RubikDm#*
\RubikDmp#*
\RubikDp#*
\Rubikdp#*
\RubikDs#*
\RubikDsp#*
\RubikDw#*
\RubikDwp#*
\RubikE#*
\RubikEp#*
\RubikF#*
\Rubikf#*
\RubikFa#*
\RubikFaceBack{clr1}{clr2}{clr3}{clr4}{clr5}{clr6}{clr7}{clr8}{clr9}
\RubikFaceBack{color}{color}{color}{color}{color}{color}{color}{color}{color}#S
\RubikFaceBackAll{color}
\RubikFaceDown{clr1}{clr2}{clr3}{clr4}{clr5}{clr6}{clr7}{clr8}{clr9}
\RubikFaceDown{color}{color}{color}{color}{color}{color}{color}{color}{color}#S
\RubikFaceDownAll{color}
\RubikFaceFront{clr1}{clr2}{clr3}{clr4}{clr5}{clr6}{clr7}{clr8}{clr9}
\RubikFaceFront{color}{color}{color}{color}{color}{color}{color}{color}{color}#S
\RubikFaceFrontAll{color}
\RubikFaceLeft{clr1}{clr2}{clr3}{clr4}{clr5}{clr6}{clr7}{clr8}{clr9}
\RubikFaceLeft{color}{color}{color}{color}{color}{color}{color}{color}{color}#S
\RubikFaceLeftAll{color}
\RubikFaceRight{clr1}{clr2}{clr3}{clr4}{clr5}{clr6}{clr7}{clr8}{clr9}
\RubikFaceRight{color}{color}{color}{color}{color}{color}{color}{color}{color}#S
\RubikFaceRightAll{color}
\RubikFaceUp{clr1}{clr2}{clr3}{clr4}{clr5}{clr6}{clr7}{clr8}{clr9}
\RubikFaceUp{color}{color}{color}{color}{color}{color}{color}{color}{color}#S
\RubikFaceUpAll{color}
\RubikFap#*
\RubikFc#*
\RubikFcp#*
\RubikFm#*
\RubikFmp#*
\RubikFp#*
\Rubikfp#*
\RubikFs#*
\RubikFsp#*
\RubikFw#*
\RubikFwp#*
\RubikL#*
\Rubikl#*
\RubikLa#*
\RubikLap#*
\RubikLc#*
\RubikLcp#*
\RubikLm#*
\RubikLmp#*
\RubikLp#*
\Rubiklp#*
\RubikLs#*
\RubikLsp#*
\RubikLw#*
\RubikLwp#*
\RubikM#*
\RubikMB#*
\RubikMBp#*
\RubikMD#*
\RubikMDp#*
\RubikMF#*
\RubikMFp#*
\RubikML#*
\RubikMLp#*
\RubikMp#*
\RubikMR#*
\RubikMRp#*
\RubikMU#*
\RubikMUp#*
\RubikR#*
\Rubikr#*
\RubikRa#*
\RubikRap#*
\RubikRc#*
\RubikRcp#*
\RubikRm#*
\RubikRmp#*
\RubikRp#*
\Rubikrp#*
\RubikRs#*
\RubikRsp#*
\RubikRw#*
\RubikRwp#*
\RubikS#*
\RubikSB#*
\RubikSb#*
\RubikSBp#*
\RubikSbp#*
\RubikSD#*
\RubikSd#*
\RubikSDp#*
\RubikSdp#*
\RubikSF#*
\RubikSf#*
\RubikSFp#*
\RubikSfp#*
\RubikSidebarLength{number}
\RubikSideBarLength{number}#S
\RubikSidebarSep{number}
\RubikSideBarSep{number}#S
\RubikSidebarWidth{number}
\RubikSideBarWidth{number}#S
\RubikSL#*
\RubikSl#*
\RubikSliceBottomL{color}{color}{color}{color}{color}{color}#S
\RubikSliceBottomL{color1}{color2}{color3}{color4}{color5}{color6}
\RubikSliceBottomR{color}{color}{color}{color}{color}{color}#S
\RubikSliceBottomR{color1}{color2}{color3}{color4}{color5}{color6}
\RubikSliceEquatorL{color}{color}{color}{color}{color}{color}#S
\RubikSliceEquatorL{color1}{color2}{color3}{color4}{color5}{color6}#*
\RubikSliceEquatorR{color}{color}{color}{color}{color}{color}#S
\RubikSliceEquatorR{color1}{color2}{color3}{color4}{color5}{color6}#*
\RubikSliceMiddleL{color}{color}{color}{color}{color}{color}#S
\RubikSliceMiddleL{color1}{color2}{color3}{color4}{color5}{color6}
\RubikSliceMiddleR{color}{color}{color}{color}{color}{color}#S
\RubikSliceMiddleR{color1}{color2}{color3}{color4}{color5}{color6}
\RubikSliceTopL{color}{color}{color}{color}{color}{color}#S
\RubikSliceTopL{color1}{color2}{color3}{color4}{color5}{color6}
\RubikSliceTopR{color}{color}{color}{color}{color}{color}#S
\RubikSliceTopR{color1}{color2}{color3}{color4}{color5}{color6}
\RubikSLp#*
\RubikSlp#*
\RubikSolvedConfig{color}{color}{color}{color}{color}{color}#S
\RubikSolvedConfig{X+color}{X-color}{Y+color}{Y-color}{Z+color}{Z-color}
\RubikSp#*
\RubikSR#*
\RubikSr#*
\RubikSRp#*
\RubikSrp#*
\RubikSU#*
\RubikSu#*
\RubikSUp#*
\RubikSup#*
\RubikTB#*
\RubikTBp#*
\RubikTD#*
\RubikTDp#*
\RubikTF#*
\RubikTFp#*
\RubikTL#*
\RubikTLp#*
\RubikTR#*
\RubikTRp#*
\RubikTU#*
\RubikTUp#*
\RubikU#*
\Rubiku#*
\RubikUa#*
\RubikUap#*
\RubikUc#*
\RubikUcp#*
\RubikUm#*
\RubikUmp#*
\RubikUp#*
\Rubikup#*
\RubikUs#*
\RubikUsp#*
\RubikUw#*
\RubikUwp#*
\Rubikx#*
\Rubikxp#*
\Rubiky#*
\Rubikyp#*
\Rubikz#*
\Rubikzp#*
\SequenceBraceA{name}{sequence}
\SequenceBraceAF{name}{sequence}
\SequenceBraceB{name}{sequence}
\SequenceBraceBF{name}{sequence}
\SequenceInfo
\SequenceLong
\SequenceName
\SequenceShort
\ShowCube{width}{scale}{commands}
\ShowCubeF{width}{scale}{commands}
\ShowSequence{separator}{font code}{sequence}
\ShowSequenceF{separator}{font code}{sequence}
\ShowSequencef{separator}{font code}{sequence}
\SquareB#*
\SquareBa#*
\SquareBap#*
\SquareBm#*
\SquareBmp#*
\SquareBp#*
\SquareBs#*
\SquareBsp#*
\SquareBw#*
\SquareBwp#*
\SquareD#*
\SquareDa#*
\SquareDap#*
\SquareDp#*
\SquareDs#*
\SquareDsp#*
\SquareDw#*
\SquareDwp#*
\SquareE#*
\SquareEp#*
\SquareF#*
\SquareFa#*
\SquareFap#*
\SquareFm#*
\SquareFmp#*
\SquareFp#*
\SquareFs#*
\SquareFsp#*
\SquareFw#*
\SquareFwp#*
\SquareL#*
\SquareLa#*
\SquareLap#*
\SquareLp#*
\SquareLs#*
\SquareLsp#*
\SquareLw#*
\SquareLwp#*
\SquareM#*
\SquareMB#*
\SquareMBp#*
\SquareMF#*
\SquareMFp#*
\SquareMp#*
\SquareR#*
\SquareRa#*
\SquareRap#*
\SquareRp#*
\SquareRs#*
\SquareRsp#*
\SquareRw#*
\SquareRwp#*
\SquareS#*
\SquareSB#*
\SquareSb#*
\SquareSBp#*
\SquareSbp#*
\SquareSF#*
\SquareSf#*
\SquareSFp#*
\SquareSfp#*
\SquareSp#*
\SquareTB#*
\SquareTBp#*
\SquareU#*
\SquareUa#*
\SquareUap#*
\SquareUp#*
\SquareUs#*
\SquareUsp#*
\SquareUw#*
\SquareUwp#*
\textCubieLD{color}{color}{color}#S
\textCubieLD{color1}{color2}{color3}
\textCubieLU{color}{color}{color}#S
\textCubieLU{color1}{color2}{color3}
\textCubieRD{color}{color}{color}#S
\textCubieRD{color1}{color2}{color3}
\textCubieRU{color}{color}{color}#S
\textCubieRU{color1}{color2}{color3}
\textRubik{rotation code}#*
\textRubikB#*
\textRubikb#*
\textRubikBa#*
\textRubikBap#*
\textRubikBc#*
\textRubikBcp#*
\textRubikBm#*
\textRubikBmp#*
\textRubikBp#*
\textRubikbp#*
\textRubikBs#*
\textRubikBsp#*
\textRubikBw#*
\textRubikBwp#*
\textRubikCB#*
\textRubikCBp#*
\textRubikCD#*
\textRubikCDp#*
\textRubikCF#*
\textRubikCFp#*
\textRubikCL#*
\textRubikCLp#*
\textRubikCR#*
\textRubikCRp#*
\textRubikCU#*
\textRubikCUp#*
\textRubikD#*
\textRubikd#*
\textRubikDa#*
\textRubikDap#*
\textRubikDc#*
\textRubikDcp#*
\textRubikDm#*
\textRubikDmp#*
\textRubikDp#*
\textRubikdp#*
\textRubikDs#*
\textRubikDsp#*
\textRubikDw#*
\textRubikDwp#*
\textRubikE#*
\textRubikEp#*
\textRubikF#*
\textRubikf#*
\textRubikFa#*
\textRubikFap#*
\textRubikFc#*
\textRubikFcp#*
\textRubikFm#*
\textRubikFmp#*
\textRubikFp#*
\textRubikfp#*
\textRubikFs#*
\textRubikFsp#*
\textRubikFw#*
\textRubikFwp#*
\textRubikL#*
\textRubikl#*
\textRubikLa#*
\textRubikLap#*
\textRubikLc#*
\textRubikLcp#*
\textRubikLm#*
\textRubikLmp#*
\textRubikLp#*
\textRubiklp#*
\textRubikLs#*
\textRubikLsp#*
\textRubikLw#*
\textRubikLwp#*
\textRubikM#*
\textRubikMB#*
\textRubikMBp#*
\textRubikMD#*
\textRubikMDp#*
\textRubikMF#*
\textRubikMFp#*
\textRubikML#*
\textRubikMLp#*
\textRubikMp#*
\textRubikMR#*
\textRubikMRp#*
\textRubikMU#*
\textRubikMUp#*
\textRubikR#*
\textRubikr#*
\textRubikRa#*
\textRubikRap#*
\textRubikRc#*
\textRubikRcp#*
\textRubikRm#*
\textRubikRmp#*
\textRubikRp#*
\textRubikrp#*
\textRubikRs#*
\textRubikRsp#*
\textRubikRw#*
\textRubikRwp#*
\textRubikS#*
\textRubikSB#*
\textRubikSb#*
\textRubikSBp#*
\textRubikSbp#*
\textRubikSD#*
\textRubikSd#*
\textRubikSDp#*
\textRubikSdp#*
\textRubikSF#*
\textRubikSf#*
\textRubikSFp#*
\textRubikSfp#*
\textRubikSL#*
\textRubikSl#*
\textRubikSLp#*
\textRubikSlp#*
\textRubikSp#*
\textRubikSR#*
\textRubikSr#*
\textRubikSRp#*
\textRubikSrp#*
\textRubikSU#*
\textRubikSu#*
\textRubikSUp#*
\textRubikSup#*
\textRubikTB#*
\textRubikTBp#*
\textRubikTD#*
\textRubikTDp#*
\textRubikTF#*
\textRubikTFp#*
\textRubikTL#*
\textRubikTLp#*
\textRubikTR#*
\textRubikTRp#*
\textRubikTU#*
\textRubikTUp#*
\textRubikU#*
\textRubiku#*
\textRubikUa#*
\textRubikUap#*
\textRubikUc#*
\textRubikUcp#*
\textRubikUm#*
\textRubikUmp#*
\textRubikUp#*
\textRubikup#*
\textRubikUs#*
\textRubikUsp#*
\textRubikUw#*
\textRubikUwp#*
\textRubikx#*
\textRubikxp#*
\textRubiky#*
\textRubikyp#*
\textRubikz#*
\textRubikzp#*
\Ulb#*
\Ulm#*
\Ult#*
\x#*
\xcount#*

R#B
G#B
B#B
Y#B
O#B
W#B
X#B