# dbitouze/2015-03-20 for siunitx v2.6e
\A#*
\ampere
\amu#*
\ang[%<options%>]{%<degrees%>}
\ang[%<options%>]{%<decimal number%>}
\ang{%<degrees%>}
\ang{%<decimal number%>}
#keyvals:\ang
add-arc-degree-zero
add-arc-minute-zero
add-arc-second-zero
angle-symbol-over-decimal
arc-separator=
number-angle-product=
#endkeyvals
\angstrom
\arcminute
\arcsecond
\as#*
\astronomicalunit
\atomicmassunit
\atto#*
\bar
\barn
\becquerel
\bel
\bit
\bohr
\byte
\cancel
\candela
\celsius
\centi
\clight
\cmclight
\color
\coulomb
\cubed
\cubic
\dalton
\day
\dB#*
\deca
\deci
\decibel
\DeclareBinaryPrefix{%<prefix%>}{%<symbol%>}{%<power of 2%>}#d
\DeclareSIPostPower{%<power macro%>}{%<number%>}#d
\DeclareSIPrefix{%<prefix%>}{%<symbol%>}{%<power of 10%>}#d
\DeclareSIPrePower{%<power macro%>}{%<number%>}#d
\DeclareSIQualifier{%<qualifier%>}{%<symbol%>}#d
\DeclareSIUnit[%<options%>]{%<unit%>}{%<definition%>}#d
\DeclareSIUnit{%<unit%>}{%<definition%>}#d
\degreeCelsius
\deka
\dm#*
\electronmass
\electronvolt
\elementarycharge
\ensuremath
\eV#*
\exa
\exbi
\F#*
\farad
\femto
\fF#*
\fg#*
\fmol#*
\fs#*
\g#*
\GeV#*
\GHz#*
\gibi
\giga
\GPa#*
\gray
\GW#*
\hartree
\hectare
\hecto
\henry
\hertz
\highlight
\hL#*
\hl#*
\hour
\Hz#*
\J#*
\joule
\K#*
\kA#*
\katal
\kelvin
\keV#*
\kg#*
\kHz#*
\kibi
\kilo
\kilogram
\kJ#*
\km#*
\kmol#*
\kN#*
\knot
\kohm#*
\kPa#*
\kV#*
\kW#*
\kWh#*
\m#*
\mA#*
\mebi
\mega
\meter
\metre
\MeV#*
\meV#*
\mg#*
\MHz#*
\mHz#*
\micro
\milli
\minute
\mL#*
\ml#*
\mm#*
\mmHg
\mmol#*
\MN#*
\mN#*
\Mohm#*
\mohm#*
\mol#*
\mole
\mp#*
\MPa#*
\ms#*
\mV#*
\MW#*
\mW#*
\N#*
\nA#*
\nano
\nauticalmile
\neper
\newton
\ng#*
\nm#*
\nmol#*
\ns#*
\num[%<options%>]{%<number%>}
#keyvals:\num
add-decimal-zero#true,false
add-integer-zero#true,false
explicit-sign=
fixed-exponent=
minimum-integer-digits=
omit-uncertainty#true,false
retain-explicit-plus#true,false
retain-unity-mantissa#true,false
retain-zero-exponent#true,false
round-half=#up,even
round-integer-to-decimal#true,false
round-minimum=
round-mode=#off,figures,places
round-precision=
scientific-notation=#true,false,fixed,engineering
zero-decimal-to-integer#true,false
bracket-negative-numbers#true,false
bracket-numbers#true,false
close-bracket=
complex-root-position=#after-number,before-number
copy-complex-root=
copy-decimal-marker=
exponent-base=
exponent-product=
group-digits=#true,false,decimal,integer
group-minimum-digits=
group-separator=
negative-color=
open-bracket=
output-close-uncertainty=
output-complex-root=
output-decimal-marker=
output-exponent-marker=
output-open-uncertainty=
separate-uncertainty#true,false
tight-spacing#true,false
uncertainty-separator=
fraction-function=
input-product=
input-quotient=
output-product=
output-quotient=
quotient-mode=#symbol,fraction
#endkeyvals
\num{%<number%>}
\numlist[%<options%>]{%<numbers%>}
\numlist{%<numbers%>}
#keyvals:\numlist
list-final-separator=
list-pair-separator=
list-separator=
range-phrase=
#endkeyvals
\numrange[%<options%>]{%<number1%>}{%<number2%>}
\numrange{%<number2%>}{%<number2%>}
\nV#*
\of
\ohm
\Pa#*
\pA#*
\pascal
\pebi
\per
\percent
\peta
\pF#*
\pg#*
\pico
\planckbar
\pmol#*
\ps#*
\pV#*
\radian
\raiseto{%<power%>}
\s#*
\second
\SendSettingsToPgf
\SI[%<options%>]{%<value%>}[%<pre-unit%>]{%<unit commands%>}
\SI[%<options%>]{%<value%>}{%<unit commands%>}
\si{%<unit%>}
\SI{%<value%>}[%<pre-unit%>]{%<unit commands%>}
\SI{%<value%>}{%<unit commands%>}
#keyvals:\SI
mode=#math,text
math-rm=
math-sf=
math-tt=
text-rm=
text-sf=
text-tt=
color=
number-color=
unit-color=
locale=#DE,UK,US,ZA,FR
allow-number-unit-breaks#true,false
exponent-to-prefix#true,false
list-units=#brackets,repeat,single
multi-part-units=#brackets,repeat,single
number-unit-product=
product-units=#brackets,brackets-power,power,repeat,single
range-units=#brackets,repeat,single
parse-units#true,false
#endkeyvals
\si[%<options%>]{%<unit%>}
#keyvals:\si
bracket-unit-denominator#true,false
forbid-literal-units#true,false
literal-superscript-as-power#true,false
inter-unit-product=
parse-units#true,false
per-mode=#fraction,reciprocal,reciprocal-positive-first,symbol,symbol-or-fraction,repeated-symbol
per-symbol=
power-font=
prefixes-as-symbols#true,false
qualifier-mode=#subscript,space,text,brackets
sticky-per#true,false
#endkeyvals
\siemens
\sievert
\SIlist{%<values%>}{%<unit commands%>}
\SIlist[%<options%>]{%<values%>}{%<unit commands%>}
\SIrange{%<value1%>}{%<value2%>}{%<unit commands%>}
\SIrange[%<options%>]{%<value1%>}{%<value2%>}{%<unit commands%>}
\sisetup{%<options%>}
\SIUnitSymbolAngstrom
\SIUnitSymbolArcminute
\SIUnitSymbolArcsecond
\SIUnitSymbolCelsius
\SIUnitSymbolDegree
\SIUnitSymbolMicro
\SIUnitSymbolOhm
\square
\squared
\steradian
\tablenum
\tebi
\tera
\tesla
\TeV#*
\THz#*
\tonne
\tothe{%<power%>}
\uA#*
\ug#*
\uL#*
\ul#*
\um#*
\umol#*
\us#*
\uV#*
\uW#*
\V#*
\volt
\W#*
\watt
\weber
\yobi
\yocto
\yotta
\zebi
\zepto
\zetta
