# stix2 package
# Matthew Bertucci 6/21/2021

#include:textcomp

\Gamma#m
\Delta#m
\Theta#m
\Lambda#m
\Xi#m
\Pi#m
\Sigma#m
\Upsilon#m
\Phi#m
\Psi#m
\Omega#m
\alpha#m
\beta#m
\gamma#m
\delta#m
\epsilon#m
\zeta#m
\eta#m
\theta#m
\iota#m
\kappa#m
\lambda#m
\mu#m
\nu#m
\xi#m
\pi#m
\rho#m
\sigma#m
\tau#m
\upsilon#m
\phi#m
\chi#m
\psi#m
\omega#m
\varepsilon#m
\vartheta#m
\varpi#m
\varrho#m
\varsigma#m
\varphi#m
\nabla#m
\partial#m
\imath#m
\jmath#m
\mathdollar#m
\backslash#m
\mathsterling#m
\mathsection#m
\neg#m
\lnot#m
\mathparagraph#m
\eth#m
\Zbar#m
\digamma#m
\varkappa#m
\backepsilon#m
\upbackepsilon#m
\enleadertwodots#m
\mathellipsis#m
\prime#m
\dprime#m
\trprime#m
\backprime#m
\backdprime#m
\backtrprime#m
\caretinsert#m
\Exclam#m
\hyphenbullet#m
\Question#m
\qprime#m
\enclosecircle#m
\enclosesquare#m
\enclosediamond#m
\enclosetriangle#m
\Eulerconst#m
\hbar#m
\hslash#m
\Im#m
\ell#m
\wp#m
\Re#m
\mho#m
\turnediota#m
\Angstrom#m
\Finv#m
\aleph#m
\beth#m
\gimel#m
\daleth#m
\Game#m
\sansLturned#m
\sansLmirrored#m
\Yup#m
\PropertyLine#m
\updownarrowbar#m
\linefeed#m
\carriagereturn#m
\barovernorthwestarrow#m
\barleftarrowrightarrowbar#m
\acwopencirclearrow#m
\cwopencirclearrow#m
\nHuparrow#m
\nHdownarrow#m
\leftdasharrow#m
\updasharrow#m
\rightdasharrow#m
\downdasharrow#m
\leftwhitearrow#m
\upwhitearrow#m
\rightwhitearrow#m
\downwhitearrow#m
\whitearrowupfrombar#m
\forall#m
\complement#m
\exists#m
\nexists#m
\varnothing#m
\emptyset#m
\increment#m
\QED#m
\infty#m
\rightangle#m
\angle#m
\measuredangle#m
\sphericalangle#m
\therefore#m
\because#m
\sinewave#m
\top#m
\bot#m
\hermitmatrix#m
\measuredrightangle#m
\varlrtriangle#m
\cdots#m
\diameter#m
\house#m
\invnot#m
\sqlozenge#m
\profline#m
\profsurf#m
\viewdata#m
\turnednot#m
\varhexagonlrbonds#m
\conictaper#m
\topbot#m
\APLnotbackslash#m
\APLboxupcaret#m
\APLboxquestion#m
\rangledownzigzagarrow#m
\hexagon#m
\bbrktbrk#m
\varcarriagereturn#m
\obrbrak#m
\ubrbrak#m
\trapezium#m
\benzenr#m
\strns#m
\fltns#m
\accurrent#m
\elinters#m
\mathvisiblespace#m
\circledS#m
\mdlgblksquare#m
\blacksquare#m
\mdlgwhtsquare#m
\square#m
\Box#m
\squoval#m
\blackinwhitesquare#m
\squarehfill#m
\squarevfill#m
\squarehvfill#m
\squarenwsefill#m
\squareneswfill#m
\squarecrossfill#m
\smblksquare#m
\smwhtsquare#m
\hrectangleblack#m
\hrectangle#m
\vrectangleblack#m
\vrectangle#m
\parallelogramblack#m
\parallelogram#m
\bigblacktriangleup#m
\blacktriangle#m
\blacktriangleright#m
\smallblacktriangleright#m
\smalltriangleright#m
\blackpointerright#m
\whitepointerright#m
\bigblacktriangledown#m
\bigtriangledown#m
\blacktriangledown#m
\triangledown#m
\blacktriangleleft#m
\smallblacktriangleleft#m
\smalltriangleleft#m
\blackpointerleft#m
\whitepointerleft#m
\mdlgblkdiamond#m
\mdlgwhtdiamond#m
\blackinwhitediamond#m
\fisheye#m
\mdlgwhtlozenge#m
\lozenge#m
\Diamond#m
\dottedcircle#m
\circlevertfill#m
\bullseye#m
\mdlgblkcircle#m
\circlelefthalfblack#m
\circlerighthalfblack#m
\circlebottomhalfblack#m
\circletophalfblack#m
\circleurquadblack#m
\blackcircleulquadwhite#m
\blacklefthalfcircle#m
\blackrighthalfcircle#m
\inversebullet#m
\inversewhitecircle#m
\invwhiteupperhalfcircle#m
\invwhitelowerhalfcircle#m
\ularc#m
\urarc#m
\lrarc#m
\llarc#m
\topsemicircle#m
\botsemicircle#m
\lrblacktriangle#m
\llblacktriangle#m
\ulblacktriangle#m
\urblacktriangle#m
\smwhtcircle#m
\squareleftblack#m
\squarerightblack#m
\squareulblack#m
\squarelrblack#m
\trianglecdot#m
\triangleleftblack#m
\trianglerightblack#m
\lgwhtcircle#m
\squareulquad#m
\squarellquad#m
\squarelrquad#m
\squareurquad#m
\circleulquad#m
\circlellquad#m
\circlelrquad#m
\circleurquad#m
\ultriangle#m
\urtriangle#m
\lltriangle#m
\mdwhtsquare#m
\mdblksquare#m
\mdsmwhtsquare#m
\mdsmblksquare#m
\lrtriangle#m
\bigstar#m
\bigwhitestar#m
\astrosun#m
\danger#m
\blacksmiley#m
\sun#m
\rightmoon#m
\leftmoon#m
\female#m
\male#m
\spadesuit#m
\heartsuit#m
\diamondsuit#m
\clubsuit#m
\varspadesuit#m
\varheartsuit#m
\vardiamondsuit#m
\varclubsuit#m
\quarternote#m
\eighthnote#m
\twonotes#m
\flat#m
\natural#m
\sharp#m
\acidfree#m
\dicei#m
\diceii#m
\diceiii#m
\diceiv#m
\dicev#m
\dicevi#m
\circledrightdot#m
\circledtwodots#m
\blackcircledrightdot#m
\blackcircledtwodots#m
\Hermaphrodite#m
\mdwhtcircle#m
\mdblkcircle#m
\mdsmwhtcircle#m
\neuter#m
\circledstar#m
\varstar#m
\dingasterisk#m
\draftingarrow#m
\threedangle#m
\whiteinwhitetriangle#m
\subsetcirc#m
\supsetcirc#m
\diagup#m
\diagdown#m
\diamondcdot#m
\rdiagovfdiag#m
\fdiagovrdiag#m
\seovnearrow#m
\neovsearrow#m
\fdiagovnearrow#m
\rdiagovsearrow#m
\neovnwarrow#m
\nwovnearrow#m
\uprightcurvearrow#m
\downrightcurvedarrow#m
\mdsmblkcircle#m
\fourvdots#m
\vzigzag#m
\measuredangleleft#m
\rightanglesqr#m
\rightanglemdot#m
\angles#m
\angdnr#m
\gtlpar#m
\sphericalangleup#m
\turnangle#m
\revangle#m
\angleubar#m
\revangleubar#m
\wideangledown#m
\wideangleup#m
\measanglerutone#m
\measanglelutonw#m
\measanglerdtose#m
\measangleldtosw#m
\measangleurtone#m
\measangleultonw#m
\measangledrtose#m
\measangledltosw#m
\revemptyset#m
\emptysetobar#m
\emptysetocirc#m
\emptysetoarr#m
\emptysetoarrl#m
\obot#m
\olcross#m
\odotslashdot#m
\uparrowoncircle#m
\circledwhitebullet#m
\circledbullet#m
\cirscir#m
\cirE#m
\boxonbox#m
\triangleodot#m
\triangleubar#m
\triangles#m
\iinfin#m
\tieinfty#m
\nvinfty#m
\laplac#m
\thermod#m
\downtriangleleftblack#m
\downtrianglerightblack#m
\blackdiamonddownarrow#m
\blacklozenge#m
\circledownarrow#m
\blackcircledownarrow#m
\errbarsquare#m
\errbarblacksquare#m
\errbardiamond#m
\errbarblackdiamond#m
\errbarcircle#m
\errbarblackcircle#m
\perps#m
\topcir#m
\squaretopblack#m
\squarebotblack#m
\squareurblack#m
\squarellblack#m
\diamondleftblack#m
\diamondrightblack#m
\diamondtopblack#m
\diamondbotblack#m
\dottedsquare#m
\lgblksquare#m
\lgwhtsquare#m
\vysmblksquare#m
\vysmwhtsquare#m
\pentagonblack#m
\pentagon#m
\varhexagon#m
\varhexagonblack#m
\hexagonblack#m
\lgblkcircle#m
\mdblkdiamond#m
\mdwhtdiamond#m
\mdblklozenge#m
\mdwhtlozenge#m
\smblkdiamond#m
\smblklozenge#m
\smwhtlozenge#m
\blkhorzoval#m
\whthorzoval#m
\blkvertoval#m
\whtvertoval#m
\medwhitestar#m
\medblackstar#m
\smwhitestar#m
\rightpentagonblack#m
\rightpentagon#m
\postalmark#m
\hzigzag#m
\Bbbk#m
\bracevert#m
\pm#m
\cdotp#m
\centerdot#m
\times#m
\div#m
\dagger#m
\ddagger#m
\smblkcircle#m
\fracslash#m
\upand#m
\mp#m
\dotplus#m
\smallsetminus#m
\ast#m
\vysmwhtcircle#m
\bullet#m
\land#m
\lor#m
\cap#m
\cup#m
\dotminus#m
\invlazys#m
\wr#m
\cupleftarrow#m
\cupdot#m
\uplus#m
\sqcap#m
\sqcup#m
\oplus#m
\ominus#m
\otimes#m
\oslash#m
\odot#m
\circledcirc#m
\circledast#m
\circledequal#m
\circleddash#m
\boxplus#m
\boxminus#m
\boxtimes#m
\boxdot#m
\intercal#m
\veebar#m
\barwedge#m
\barvee#m
\diamond#m
\smwhtdiamond#m
\cdot#m
\star#m
\divideontimes#m
\ltimes#m
\rtimes#m
\leftthreetimes#m
\rightthreetimes#m
\curlyvee#m
\curlywedge#m
\doublecap#m
\doublecup#m
\varbarwedge#m
\vardoublebarwedge#m
\obar#m
\triangle#m
\bigtriangleup#m
\lhd#m
\rhd#m
\unlhd#m
\unrhd#m
\mdlgwhtcircle#m
\boxbar#m
\veedot#m
\wedgedot#m
\lozengeminus#m
\concavediamond#m
\concavediamondtickleft#m
\concavediamondtickright#m
\whitesquaretickleft#m
\whitesquaretickright#m
\typecolon#m
\circlehbar#m
\circledvert#m
\circledparallel#m
\obslash#m
\operp#m
\olessthan#m
\ogreaterthan#m
\boxdiag#m
\boxbslash#m
\boxast#m
\boxcircle#m
\boxbox#m
\triangleserifs#m
\hourglass#m
\blackhourglass#m
\shuffle#m
\mdlgblklozenge#m
\setminus#m
\dsol#m
\rsolbar#m
\doubleplus#m
\tripleplus#m
\tplus#m
\tminus#m
\ringplus#m
\plushat#m
\simplus#m
\plusdot#m
\plussim#m
\plussubtwo#m
\plustrif#m
\commaminus#m
\minusdot#m
\minusfdots#m
\minusrdots#m
\opluslhrim#m
\oplusrhrim#m
\vectimes#m
\dottimes#m
\timesbar#m
\btimes#m
\smashtimes#m
\otimeslhrim#m
\otimesrhrim#m
\otimeshat#m
\Otimes#m
\odiv#m
\triangleplus#m
\triangleminus#m
\triangletimes#m
\intprod#m
\intprodr#m
\fcmp#m
\amalg#m
\capdot#m
\uminus#m
\barcup#m
\barcap#m
\capwedge#m
\cupvee#m
\cupovercap#m
\capovercup#m
\cupbarcap#m
\capbarcup#m
\twocups#m
\twocaps#m
\closedvarcup#m
\closedvarcap#m
\Sqcap#m
\Sqcup#m
\closedvarcupsmashprod#m
\wedgeodot#m
\veeodot#m
\Wedge#m
\Vee#m
\wedgeonwedge#m
\veeonvee#m
\bigslopedvee#m
\bigslopedwedge#m
\wedgemidvert#m
\veemidvert#m
\midbarwedge#m
\midbarvee#m
\doublebarwedge#m
\wedgebar#m
\wedgedoublebar#m
\varveebar#m
\doublebarvee#m
\veedoublebar#m
\dsub#m
\rsub#m
\eqqplus#m
\pluseqq#m
\interleave#m
\nhVvert#m
\threedotcolon#m
\trslash#m
\sslash#m
\talloblong#m
\ast#m
\closure#m
\vertoverlay#m
\leftarrow#m
\gets#m
\uparrow#m
\rightarrow#m
\to#m
\downarrow#m
\leftrightarrow#m
\updownarrow#m
\nwarrow#m
\nearrow#m
\searrow#m
\swarrow#m
\nleftarrow#m
\nrightarrow#m
\leftwavearrow#m
\rightwavearrow#m
\twoheadleftarrow#m
\twoheaduparrow#m
\twoheadrightarrow#m
\twoheaddownarrow#m
\leftarrowtail#m
\rightarrowtail#m
\mapsfrom#m
\mapsup#m
\mapsto#m
\mapsdown#m
\hookleftarrow#m
\hookrightarrow#m
\looparrowleft#m
\looparrowright#m
\leftrightsquigarrow#m
\nleftrightarrow#m
\downzigzagarrow#m
\Lsh#m
\Rsh#m
\Ldsh#m
\Rdsh#m
\curvearrowleft#m
\curvearrowright#m
\circlearrowleft#m
\circlearrowright#m
\leftharpoonup#m
\leftharpoondown#m
\upharpoonright#m
\restriction#m
\upharpoonleft#m
\rightharpoonup#m
\rightharpoondown#m
\downharpoonright#m
\downharpoonleft#m
\rightleftarrows#m
\updownarrows#m
\leftrightarrows#m
\leftleftarrows#m
\upuparrows#m
\rightrightarrows#m
\downdownarrows#m
\leftrightharpoons#m
\rightleftharpoons#m
\nLeftarrow#m
\nLeftrightarrow#m
\nRightarrow#m
\Leftarrow#m
\Uparrow#m
\Rightarrow#m
\Downarrow#m
\Leftrightarrow#m
\Updownarrow#m
\Nwarrow#m
\Nearrow#m
\Searrow#m
\Swarrow#m
\Lleftarrow#m
\Rrightarrow#m
\leftsquigarrow#m
\rightsquigarrow#m
\leadsto#m
\barleftarrow#m
\rightarrowbar#m
\circleonrightarrow#m
\downuparrows#m
\rightthreearrows#m
\nvleftarrow#m
\nvrightarrow#m
\nvleftrightarrow#m
\nVleftarrow#m
\nVrightarrow#m
\nVleftrightarrow#m
\leftarrowtriangle#m
\rightarrowtriangle#m
\leftrightarrowtriangle#m
\in#m
\notin#m
\smallin#m
\ni#m
\owns#m
\nni#m
\smallni#m
\propto#m
\varpropto#m
\mid#m
\shortmid#m
\nmid#m
\nshortmid#m
\parallel#m
\shortparallel#m
\nparallel#m
\nshortparallel#m
\Colon#m
\dashcolon#m
\dotsminusdots#m
\kernelcontraction#m
\sim#m
\thicksim#m
\backsim#m
\nsim#m
\eqsim#m
\simeq#m
\nsime#m
\cong#m
\simneqq#m
\ncong#m
\approx#m
\thickapprox#m
\napprox#m
\approxeq#m
\approxident#m
\backcong#m
\asymp#m
\Bumpeq#m
\bumpeq#m
\doteq#m
\Doteq#m
\doteqdot#m
\fallingdotseq#m
\risingdotseq#m
\coloneq#m
\eqcolon#m
\eqcirc#m
\circeq#m
\arceq#m
\wedgeq#m
\veeeq#m
\stareq#m
\triangleq#m
\eqdef#m
\measeq#m
\questeq#m
\ne#m
\neq#m
\equiv#m
\nequiv#m
\Equiv#m
\leq#m
\le#m
\geq#m
\ge#m
\leqq#m
\geqq#m
\lneqq#m
\lvertneqq#m
\gneqq#m
\gvertneqq#m
\ll#m
\gg#m
\between#m
\nasymp#m
\nless#m
\ngtr#m
\nleq#m
\ngeq#m
\lesssim#m
\gtrsim#m
\nlesssim#m
\ngtrsim#m
\lessgtr#m
\gtrless#m
\nlessgtr#m
\ngtrless#m
\prec#m
\succ#m
\preccurlyeq#m
\succcurlyeq#m
\precsim#m
\succsim#m
\nprec#m
\nsucc#m
\subset#m
\supset#m
\nsubset#m
\nsupset#m
\subseteq#m
\supseteq#m
\nsubseteq#m
\nsupseteq#m
\subsetneq#m
\varsubsetneq#m
\supsetneq#m
\varsupsetneq#m
\sqsubset#m
\sqsupset#m
\sqsubseteq#m
\sqsupseteq#m
\vdash#m
\dashv#m
\assert#m
\models#m
\vDash#m
\Vdash#m
\Vvdash#m
\VDash#m
\nvdash#m
\nvDash#m
\nVdash#m
\nVDash#m
\prurel#m
\scurel#m
\vartriangleleft#m
\vartriangleright#m
\trianglelefteq#m
\trianglerighteq#m
\origof#m
\imageof#m
\multimap#m
\bowtie#m
\backsimeq#m
\Subset#m
\Supset#m
\pitchfork#m
\equalparallel#m
\lessdot#m
\gtrdot#m
\lll#m
\llless#m
\ggg#m
\gggtr#m
\lesseqgtr#m
\gtreqless#m
\eqless#m
\eqgtr#m
\curlyeqprec#m
\curlyeqsucc#m
\npreccurlyeq#m
\nsucccurlyeq#m
\nsqsubseteq#m
\nsqsupseteq#m
\sqsubsetneq#m
\sqsupsetneq#m
\lnsim#m
\gnsim#m
\precnsim#m
\succnsim#m
\nvartriangleleft#m
\nvartriangleright#m
\ntrianglelefteq#m
\ntrianglerighteq#m
\vdots#m
\adots#m
\ddots#m
\disin#m
\varisins#m
\isins#m
\isindot#m
\varisinobar#m
\isinobar#m
\isinvb#m
\isinE#m
\nisd#m
\varnis#m
\nis#m
\varniobar#m
\niobar#m
\bagmember#m
\frown#m
\smallfrown#m
\smile#m
\smallsmile#m
\APLnotslash#m
\vartriangle#m
\perp#m
\bsolhsub#m
\suphsol#m
\upin#m
\pullback#m
\pushout#m
\DashVDash#m
\dashVdash#m
\multimapinv#m
\vlongdash#m
\longdashv#m
\cirbot#m
\UUparrow#m
\DDownarrow#m
\acwgapcirclearrow#m
\cwgapcirclearrow#m
\rightarrowonoplus#m
\longleftarrow#m
\longrightarrow#m
\longleftrightarrow#m
\Longleftarrow#m
\Longrightarrow#m
\Longleftrightarrow#m
\longmapsfrom#m
\longmapsto#m
\Longmapsfrom#m
\Longmapsto#m
\longrightsquigarrow#m
\nvtwoheadrightarrow#m
\nVtwoheadrightarrow#m
\nvLeftarrow#m
\nvRightarrow#m
\nvLeftrightarrow#m
\twoheadmapsto#m
\Mapsfrom#m
\Mapsto#m
\downarrowbarred#m
\uparrowbarred#m
\Uuparrow#m
\Ddownarrow#m
\leftbkarrow#m
\rightbkarrow#m
\leftdbkarrow#m
\dashleftarrow#m
\dbkarow#m
\dashrightarrow#m
\drbkarow#m
\rightdotarrow#m
\baruparrow#m
\downarrowbar#m
\nvrightarrowtail#m
\nVrightarrowtail#m
\twoheadrightarrowtail#m
\nvtwoheadrightarrowtail#m
\nVtwoheadrightarrowtail#m
\lefttail#m
\righttail#m
\leftdbltail#m
\rightdbltail#m
\diamondleftarrow#m
\rightarrowdiamond#m
\diamondleftarrowbar#m
\barrightarrowdiamond#m
\nwsearrow#m
\neswarrow#m
\hknwarrow#m
\hknearrow#m
\hksearow#m
\hkswarow#m
\tona#m
\toea#m
\tosa#m
\towa#m
\rightcurvedarrow#m
\leftdowncurvedarrow#m
\rightdowncurvedarrow#m
\cwrightarcarrow#m
\acwleftarcarrow#m
\acwoverarcarrow#m
\acwunderarcarrow#m
\curvearrowrightminus#m
\curvearrowleftplus#m
\cwundercurvearrow#m
\ccwundercurvearrow#m
\acwcirclearrow#m
\cwcirclearrow#m
\rightarrowshortleftarrow#m
\leftarrowshortrightarrow#m
\shortrightarrowleftarrow#m
\rightarrowplus#m
\leftarrowplus#m
\rightarrowx#m
\leftrightarrowcircle#m
\twoheaduparrowcircle#m
\leftrightharpoonupdown#m
\leftrightharpoondownup#m
\updownharpoonrightleft#m
\updownharpoonleftright#m
\leftrightharpoonupup#m
\updownharpoonrightright#m
\leftrightharpoondowndown#m
\updownharpoonleftleft#m
\barleftharpoonup#m
\rightharpoonupbar#m
\barupharpoonright#m
\downharpoonrightbar#m
\barleftharpoondown#m
\rightharpoondownbar#m
\barupharpoonleft#m
\downharpoonleftbar#m
\leftharpoonupbar#m
\barrightharpoonup#m
\upharpoonrightbar#m
\bardownharpoonright#m
\leftharpoondownbar#m
\barrightharpoondown#m
\upharpoonleftbar#m
\bardownharpoonleft#m
\leftharpoonsupdown#m
\upharpoonsleftright#m
\rightharpoonsupdown#m
\downharpoonsleftright#m
\leftrightharpoonsup#m
\leftrightharpoonsdown#m
\rightleftharpoonsup#m
\rightleftharpoonsdown#m
\leftharpoonupdash#m
\dashleftharpoondown#m
\rightharpoonupdash#m
\dashrightharpoondown#m
\updownharpoonsleftright#m
\downupharpoonsleftright#m
\rightimply#m
\equalrightarrow#m
\similarrightarrow#m
\leftarrowsimilar#m
\rightarrowsimilar#m
\rightarrowapprox#m
\ltlarr#m
\leftarrowless#m
\gtrarr#m
\subrarr#m
\leftarrowsubset#m
\suplarr#m
\leftfishtail#m
\rightfishtail#m
\upfishtail#m
\downfishtail#m
\rtriltri#m
\ltrivb#m
\vbrtri#m
\lfbowtie#m
\rfbowtie#m
\fbowtie#m
\lftimes#m
\rftimes#m
\dualmap#m
\lrtriangleeq#m
\eparsl#m
\smeparsl#m
\eqvparsl#m
\gleichstark#m
\ruledelayed#m
\veeonwedge#m
\eqdot#m
\dotequiv#m
\equivVert#m
\equivVvert#m
\dotsim#m
\simrdots#m
\simminussim#m
\congdot#m
\asteq#m
\hatapprox#m
\approxeqq#m
\eqqsim#m
\Coloneq#m
\eqeq#m
\eqeqeq#m
\ddotseq#m
\equivDD#m
\ltcir#m
\gtcir#m
\ltquest#m
\gtquest#m
\leqslant#m
\geqslant#m
\lesdot#m
\gesdot#m
\lesdoto#m
\gesdoto#m
\lesdotor#m
\gesdotol#m
\lessapprox#m
\gtrapprox#m
\lneq#m
\gneq#m
\lnapprox#m
\gnapprox#m
\lesseqqgtr#m
\gtreqqless#m
\lsime#m
\gsime#m
\lsimg#m
\gsiml#m
\lgE#m
\glE#m
\lesges#m
\gesles#m
\eqslantless#m
\eqslantgtr#m
\elsdot#m
\egsdot#m
\eqqless#m
\eqqgtr#m
\eqqslantless#m
\eqqslantgtr#m
\simless#m
\simgtr#m
\simlE#m
\simgE#m
\Lt#m
\Gt#m
\partialmeetcontraction#m
\glj#m
\gla#m
\ltcc#m
\gtcc#m
\lescc#m
\gescc#m
\smt#m
\lat#m
\smte#m
\late#m
\bumpeqq#m
\preceq#m
\npreceq#m
\succeq#m
\nsucceq#m
\precneq#m
\succneq#m
\preceqq#m
\succeqq#m
\precneqq#m
\succneqq#m
\precapprox#m
\succapprox#m
\precnapprox#m
\succnapprox#m
\Prec#m
\Succ#m
\subsetdot#m
\supsetdot#m
\subsetplus#m
\supsetplus#m
\submult#m
\supmult#m
\subedot#m
\supedot#m
\subseteqq#m
\nsubseteqq#m
\supseteqq#m
\nsupseteqq#m
\subsim#m
\supsim#m
\subsetapprox#m
\supsetapprox#m
\subsetneqq#m
\varsubsetneqq#m
\supsetneqq#m
\varsupsetneqq#m
\lsqhook#m
\rsqhook#m
\csub#m
\csup#m
\csube#m
\csupe#m
\subsup#m
\supsub#m
\subsub#m
\supsup#m
\suphsub#m
\supdsub#m
\forkv#m
\topfork#m
\mlcp#m
\forks#m
\forksnot#m
\shortlefttack#m
\shortdowntack#m
\shortuptack#m
\vDdash#m
\dashV#m
\Dashv#m
\DashV#m
\varVdash#m
\Barv#m
\vBar#m
\vBarv#m
\barV#m
\Vbar#m
\Not#m
\bNot#m
\revnmid#m
\cirmid#m
\midcir#m
\nhpar#m
\parsim#m
\lllnest#m
\gggnest#m
\leqqslant#m
\geqqslant#m
\circleonleftarrow#m
\leftthreearrows#m
\leftarrowonoplus#m
\longleftsquigarrow#m
\nvtwoheadleftarrow#m
\nVtwoheadleftarrow#m
\twoheadmapsfrom#m
\twoheadleftdbkarrow#m
\leftdotarrow#m
\nvleftarrowtail#m
\nVleftarrowtail#m
\twoheadleftarrowtail#m
\nvtwoheadleftarrowtail#m
\nVtwoheadleftarrowtail#m
\leftarrowx#m
\leftcurvedarrow#m
\equalleftarrow#m
\bsimilarleftarrow#m
\leftarrowbackapprox#m
\rightarrowgtr#m
\rightarrowsupset#m
\LLeftarrow#m
\RRightarrow#m
\bsimilarrightarrow#m
\rightarrowbackapprox#m
\similarleftarrow#m
\leftarrowapprox#m
\leftarrowbsimilar#m
\rightarrowbsimilar#m
\ngeqq#m
\ngeqslant#m
\nleqslant#m
\nleqq#m
\ncongdot#m
\napproxeqq#m
\nll#m
\ngg#m
\nsqsubset#m
\nsqsupset#m
\nBumpeq#m
\nbumpeq#m
\neqsim#m
\nvarisinobar#m
\nvarniobar#m
\neqslantless#m
\neqslantgtr#m
\lhook#m
\rhook#m
\relbar#m
\Relbar#m
\Rrelbar#m
\RRelbar#m
\mapsfromchar#m
\mapstochar#m
\ldotp#m
\colon#m
\smallint#m
\smalliint#m
\smalliiint#m
\smalloint#m
\smalloiint#m
\smalloiiint#m
\smallintclockwise#m
\smallvarointclockwise#m
\smallointctrclockwise#m
\smallsumint#m
\smalliiiint#m
\smallintbar#m
\smallintBar#m
\smallfint#m
\smallcirfnint#m
\smallawint#m
\smallrppolint#m
\smallscpolint#m
\smallnpolint#m
\smallpointint#m
\smallsqint#m
\smallintlarhk#m
\smallintx#m
\smallintcap#m
\smallintcup#m
\smallupint#m
\smalllowint#m
\int#m
\iint#m
\iiint#m
\oint#m
\oiint#m
\oiiint#m
\intclockwise#m
\varointclockwise#m
\ointctrclockwise#m
\sumint#m
\iiiint#m
\intbar#m
\intBar#m
\fint#m
\cirfnint#m
\awint#m
\rppolint#m
\scpolint#m
\npolint#m
\pointint#m
\sqint#m
\intlarhk#m
\intx#m
\intcap#m
\intcup#m
\upint#m
\lowint#m
\Bbbsum#m
\prod#m
\coprod#m
\sum#m
\bigwedge#m
\bigvee#m
\bigcap#m
\bigcup#m
\leftouterjoin#m
\rightouterjoin#m
\fullouterjoin#m
\bigbot#m
\bigtop#m
\xsol#m
\xbsol#m
\bigodot#m
\bigoplus#m
\bigotimes#m
\bigcupdot#m
\biguplus#m
\bigsqcap#m
\bigsqcup#m
\conjquant#m
\disjquant#m
\bigtimes#m
\modtwosum#m
\Join#m
\bigtriangleleft#m
\zcmp#m
\zpipe#m
\zproject#m
\biginterleave#m
\bigtalloblong#m
\lbrace#m
\rbrace#m
\lceil#m
\rceil#m
\lfloor#m
\rfloor#m
\lmoustache#m
\rmoustache#m
\lbrbrak#m
\rbrbrak#m
\lBrack#m
\rBrack#m
\langle#m
\rangle#m
\lAngle#m
\rAngle#m
\lgroup#m
\rgroup#m
\lBrace#m
\rBrace#m
\lParen#m
\rParen#m
\backslash#m
\vert#m
\Vert#m
\Vvert#m
\uparrow#m
\downarrow#m
\updownarrow#m
\Uparrow#m
\Downarrow#m
\Updownarrow#m
\Uuparrow#m
\Ddownarrow#m
\UUparrow#m
\DDownarrow#m
\arrowvert#m
\Arrowvert#m
\bracevert#m
\ulcorner#m
\urcorner#m
\llcorner#m
\lrcorner#m
\Lbrbrak#m
\Rbrbrak#m
\llparenthesis#m
\rrparenthesis#m
\llangle#m
\rrangle#m
\lbrackubar#m
\rbrackubar#m
\lbrackultick#m
\rbracklrtick#m
\lbracklltick#m
\rbrackurtick#m
\langledot#m
\rangledot#m
\lparenless#m
\rparengtr#m
\Lparengtr#m
\Rparenless#m
\lblkbrbrak#m
\rblkbrbrak#m
\lvzigzag#m
\rvzigzag#m
\Lvzigzag#m
\Rvzigzag#m
\lcurvyangle#m
\rcurvyangle#m
\lbrbrak#m
\rbrbrak#m
\lbag#m
\rbag#m
\Lbrbrak#m
\Rbrbrak#m
\grave{arg}#m
\acute{arg}#m
\hat{arg}#m
\tilde{arg}#m
\bar{arg}#m
\breve{arg}#m
\dot{arg}#m
\ddot{arg}#m
\ovhook{arg}#m
\mathring{arg}#m
\check{arg}#m
\candra{arg}#m
\oturnedcomma{arg}#m
\ocommatopright{arg}#m
\droang{arg}#m
\leftharpoonaccent{arg}#m
\rightharpoonaccent{arg}#m
\leftarrowaccent{arg}#m
\rightarrowaccent{arg}#m
\leftrightarrowaccent{arg}#m
\dddot{arg}#m
\ddddot{arg}#m
\annuity{arg}#m
\widebridgeabove{arg}#m
\asteraccent{arg}#m
\widehat{arg}#m
\widetilde{arg}#m
\widecheck{arg}#m
\overleftarrow{arg}#m
\overrightarrow{arg}#m
\underrightarrow{arg}#m
\underleftarrow{arg}#m
\overleftrightarrow{arg}#m
\underleftrightarrow{arg}#m
\overleftharpoon{arg}#m
\overrightharpoon{arg}#m
\underleftharpoon{arg}#m
\underrightharpoon{arg}#m
\overbracket{arg}#m
\overparen{arg}#m
\overbrace{arg}#m
\underbracket{arg}#m
\underparen{arg}#m
\underbrace{arg}#m
\sqrt{arg}#m
\longdivision{arg}#m
\mathrm{arg}#m
\mathbf{arg}#m
\mathit{arg}#m
\mathbfit{arg}#m
\mathcal{letter}#m
\mathscr{letter}#m
\mathbfscr{letter}#m
\mathsf{arg}#m
\mathbfsf{arg}#m
\mathsfit{arg}#m
\mathbfsfit{arg}#m
\mathbb{letter}#m
\mathfrak{letter}#m
\mathbffrak{letter}#m
\mathtt{arg}#m

\yen
\circledR
\checkmark
\maltese