# autogenerated by txs
# edited by t_hoffmann 2013-05-15
\Subref{label}#r
\listsubcaptions#S
\subcapfont#S
\subcaplabelfont#S
\subcapsize#S
\subfigure#S
\subref{label}#r
\theHsubfigure#S
\theHsubtable#S
\thelofdepth
\thelotdepth
\thesubfigure
\thesubfigure#S
\thesubtable
\thesubtable#S
