# autogenerated by txs
# edited by t_hoffmann 2013-05-15
\Subref{label}#r
\listsubcaptions#*
\subcapfont#*
\subcaplabelfont#*
\subcapsize#*
\subfigure[listentry][caption]{file}
\subfigure[caption]{file}
\subfigure{file}
\subref{label}#r
\theHsubfigure#*
\theHsubtable#*
\thelofdepth#*
\thelotdepth#*
\thesubfigure#*
\thesubtable#*
\subfigtopskip#*
\subfigcapskip#*
\subfigcaptopadj#*
\subfigbottomskip#*
\subfigcapmargin#*
\subfiglabelskip#*
 
