# subfigure package
# edited by t_hoffmann 2013-05-15
# edited by Matthew Bertucci 2022/05/03 for v2.1.4

#keyvals:\usepackage/subfigure#c
normal
hang
center
centerlast
nooneline
raggedright
isu
anne
scriptsize
footnotesize
small
normalsize
large
Large
rm
sf
tt
md
bf
up
it
sl
sc
RM
SF
TT
MD
BF
IT
SL
SC
UP
figbotcap
figtopcap
tabbotcap
tabtopcap
FIGBOTCAP
FIGTOPCAP
TABBOTCAP
TABTOPCAP
loose
tight
#endkeyvals

\subfigure{figure%text}
\subfigure[caption%text]{figure%text}
\subfigure[listentry%text][caption%text]{figure%text}
\subtable{figure%text}
\subtable[caption%text]{figure%text}
\subtable[listentry%text][caption%text]{figure%text}
\thesubfigure#*
\thesubtable#*
\theHsubfigure#S
\theHsubtable#S
\subfigtopskip#*
\subfigcapskip#*
\subfigcaptopadj#*
\subfigbottomskip#*
\subfigcapmargin#*
\subfiglabelskip#*
\subref{label}#r
\Subref{label}#r
\listsubcaptions
\ifsubfiguretopcap#*
\subfiguretopcaptrue#*
\subfiguretopcapfalse#*
\ifsubtabletopcap#*
\subtabletopcaptrue#*
\subtabletopcapfalse#*
\iffiguretopcap#*
\figuretopcaptrue#*
\figuretopcapfalse#*
\figureotopcapfalse#*
\iftabletopcap#*
\tabletopcaptrue#*
\tabletopcapfalse#*
\label(bookmark){key%labeldef}#l
\subcapfont#*
\subcaplabelfont#*
\subcapsize#*
\thelofdepth#*
\thelotdepth#*
\ifhyperrefloaded#S
\hyperrefloadedtrue#S
\hyperrefloadedfalse#S
\ifsubcaphang#S
\subcaphangtrue#S
\subcaphangfalse#S
\ifsubcapcenter#S
\subcapcentertrue#S
\subcapcenterfalse#S
\ifsubcapcenterlast#S
\subcapcenterlasttrue#S
\subcapcenterlastfalse#S
\ifsubcapnooneline#S
\subcapnoonelinetrue#S
\subcapnoonelinefalse#S
\ifsubcapraggedright#S
\subcapraggedrighttrue#S
\subcapraggedrightfalse#S
