# tablvars package
# Matthew Bertucci 1/25/2022 for v1.2

#include:array
#include:colortbl
#include:ifthen
#include:multido
#include:pst-node

#keyvals:\usepackage/tablvars#c
pstricks
tikz
#endkeyvals

#ifOption:tikz
#include:tikz
#include:tikzlibrarypatterns
#endif

\begin{tablvar}{nombre}#m\array
\begin{tablvar}[largeur%l]{nombre}#m\array
\end{tablvar}#m
\begin{tablvar*}{nombre}#m\array
\begin{tablvar*}[largeur%l]{nombre}#m\array
\end{tablvar*}#m
\haut{label}#t
\bas{label}#t
\mil{label}#t
\pos{ligne}{valeur}#t
\pos[align%keyvals]{ligne}{valeur}#t
\pos*{ligne}{valeur}#t
#keyvals:\pos
c
b
t
#endkeyvals
\variations{nodes}
\variations[nblignes]{nodes}
\fleche{node1}{node2}#*
\barre#t
\barre[label]#t
\bb#t
\discont#t
\bblim{ligne1}{label1}{ligne2}{label2}#t
\tablvarinit#*
\vr{label}
\vr[ligne]{label}
\tablvarstretch#*
\vdecal{decal%l}{contenu}
\noeud{name}{label}
\vrconnect{node1}{node2}
\ZIc#t
\zbox{contenu}
\zbox[pos%keyvals]{contenu}
#keyvals:\zbox
c
l
r
#endkeyvals
\ZIh#t
\ZIh[hauteur%l]#t
\ZIh*#t
\ZIinit
\ZIinit[width]
\hachure{llx,lly}{urx,ury}

\intervalwidth#*
\bordercolsep#*
\innercolsep#*
\themaxdiscont#*
\tvbarrewidth#*
tvbarrecolor#B
\theligne#*
\thenoeud#*
\thenumvr#*
\thenumdiscont#*
\ZIheight#*
\ZIdepth#*
\ZIwidth#*
\theZI#*
\theZIstar#*
\theZIvarlignes#*
\varloop{iter}{code}#*
