# texdimens package
# Matthew Bertucci 11/11/2021 for v1.0

\texdimenpt{dim-expr}#*
\texdimenbp{dim-expr}#*
\texdimenbpdown{dim-expr}#*
\texdimenbpup{dim-expr}#*
\texdimennd{dim-expr}#*
\texdimennddown{dim-expr}#*
\texdimenndup{dim-expr}#*
\texdimendd{dim-expr}#*
\texdimendddown{dim-expr}#*
\texdimenddup{dim-expr}#*
\texdimenmm{dim-expr}#*
\texdimenmmdown{dim-expr}#*
\texdimenmmup{dim-expr}#*
\texdimenpc{dim-expr}#*
\texdimenpcdown{dim-expr}#*
\texdimenpcup{dim-expr}#*
\texdimennc{dim-expr}#*
\texdimenncdown{dim-expr}#*
\texdimenncup{dim-expr}#*
\texdimencc{dim-expr}#*
\texdimenccdown{dim-expr}#*
\texdimenccup{dim-expr}#*
\texdimencm{dim-expr}#*
\texdimencmdown{dim-expr}#*
\texdimencmup{dim-expr}#*
\texdimenin{dim-expr}#*
\texdimenindown{dim-expr}#*
\texdimeninup{dim-expr}#*
\texdimenbothcmin{dim-expr}#*
\texdimenbothincm{dim-expr}#*
\texdimenbothcminpt{dim-expr}#*
\texdimenbothincmpt{dim-expr}#*
\texdimenbothcminsp{dim-expr}#*
\texdimenbothincmsp{dim-expr}#*
\texdimenbothmmbp{dim-expr}#*
\texdimenbothbpmm{dim-expr}#*
\texdimenbothbpmmpt{dim-expr}#*
\texdimenbothmmbppt{dim-expr}#*
\texdimenbothbpmmsp{dim-expr}#*
\texdimenbothmmbpsp{dim-expr}#*
\texdimenwithunit{dim-expr1}{dim-expr2}#*

\texdimenfirstofone{arg}#S
\texdimenstrippt#S
\texdimendown#S
\texdimenup#S
\texdimenboth#S
\texdimenbothsp#S
