# texlinks package
# Matthew Bertucci 2022/05/31 for v0.83

#include:domore
#include:langcode

#keyvals:\usepackage/texlinks#c
blog
#endkeyvals

\newlet#*
\newlet{cmd}#Sd
\htm
\html
\pdf
\DoubleArg{cmd}{arg}
\urlfmt{text%plain}#*
\filenamefmt{text%plain}#*
\pkgnamefmt{text%plain}#*
\httpref{URL}{text%plain}#U
\httpsref{URL}{text%plain}#U
\NormalHTTPref{URL}{text%plain}#*U
\ithttpref{URL}{text%plain}#U
\httpprefix#*
\theHTTPprefix#*
\urlhttpsref{URL}#U
\urlhttpref{URL}#U
\domainref{domain%URL}{path%URL}#U
\prefixref{prefix%URL}{suffix%URL}#U
\foothttpurlref{URL}#U
\urlfoot{short}{id}
\urlpkgfoot{package-id}
\httpbaseref{base%URL}{rest%URL}{text%plain}#U
\httpsbaseref{base%URL}{rest%URL}{text%plain}#U
\MakeBasedHref{cmd}{base%URL}#d
\MakeBasedHref[prefix]{cmd}{base%URL}#d
\googlecom#*
\googleref{keywords}{text%plain}
\googlemapsref{keywords}{text%plain}
\wikilangref{lang-code}{lemma}{text%plain}
\Wikilangdisambref{lang-code}{term}{tag}
\Wikilangref{lang-code}{lemma|text}
\wikideref{lemma}{text%plain}
\wikienref{lemma}{text%plain}
\Wikideref{lemma}
\Wikienref{lemma}
\Wikidedisambref{lemma}{tag}
\Wikiendisambref{lemma}{tag}
\langcode#*
\wikiref{lemma}{text%plain}
\Wikiref{lemma}
\Wikidisambref{term}{tag}
\ancuml{char}
\nullctanorg#*
\ctanorg#*
\wwwctanorg#*
\wwwctanorgbaseref{path%URL}{text%plain}
\nullctanorgbaseref{path%URL}{text%plain}
\ctanorgbaseref{path%URL}{text%plain}
\texarchive#*
\ltxcontrib#*
\wwwctanref{path%URL}{text%plain}
\nullctanref{path%URL}{text%plain}
\tugctanref{path%URL}{text%plain}
\dantectanref{path%URL}{text%plain}
\sciservref{path%URL}{text%plain}
\mirrorctanref{path%URL}{text%plain}
\ctanref{path%URL}{text%plain}
\usemirrorctan
\usewwwctan
\usenullctan
\usetugctan
\usedantectani
\usesciservctan
\CTANfileref{cmd}{path%URL}{file name%file}#*
\mirrorctanfileref{path%URL}{file name%file}
\ctanfileref{path%URL}{file name%file}
\dirctanref{path%URL}{text%plain}#*
\catalogueref{path%URL}{text%plain}
\cataloguestartref{text%plain}
\bytopicref{anchor}{text%plain}
\catpkgref{package}
\CatPkgRef{name}{Name}
\catpkggenref{package}{text%plain}
\wwwctanpkggenref{package}{text%plain}
\nullctanpkggenref{package}{text%plain}
\wwwctanpkgref{package}
\WwwCtanPkgRef{name}{Name}
\wwwctanpkgstyref{package}
\nullctanpkgstyref{package}
\nullctanpkgref{package}
\NullCtanPkgRef{name}{Name}
\ctanpkgstyref{package}
\ctanpkgref{package}
\CtanPkgRef{package}
\ctanpkggenref{package}
\useWWWpkgpages
\useOpkgpages
\useCATpkgpages
\AllPkgRefs{name}{Name}
\allpkgrefs{name}
\useALLpkgpages
\wwwctanpkgauref{id}{description%text}
\nullctanpkgauref{id}{description%text}
\ctanpkgauref{id}{description%text}
\wwwctanpkgtopicref{topic-id}{text%plain}
\nullctanpkgtopicref{topic-id}{text%plain}
\nullctanpkgsearchref{text%plain}
\wwwctanpkgsearchref{text%plain}
\ctanpkgtopicref{text%plain}
\ctanpkgsearchref{text%plain}
\texlistyearmonthref{listref}{2digits-monthno}
\texlanglistmonthref{monthcmd}{listref}{2digits-monthno}
\detexlistmonthref{listref}{2digits-monthno}
\entexlistmonthref{listref}{2digits-monthno}
\texlistmonthref{listref}{2digits-monthno}
\ctanannref{id}{text%plain}
\ctanannpref{id}{text%plain}
\ctanannyearmonthref{2digits-monthno}
\ctanannmonthref{2digits-monthno}
\stackexref{id}{text%plain}
\stackquestionref{URL base%URL}{id}{text%plain}#*
\stackoverref{id}{text%plain}
\tugref{path%URL}{text%plain}
\texhaxref{id}{text%plain}
\THref{id}
\texhaxpref{id}{text%plain}
\THpref{id}
\texhaxyearmonthref{2digits-monthno}
\texhaxmonthref{2digits-monthno}
\tugbartref{tb%<<vol>%>-%<<issue>%>/%<<filename-base>%>}{%<text%>}
\tugbArtref{%<<vol>%>-%<<issue>%>/%<<filename-base>%>}{%<text%>}
\tugiref{anchor}{text%plain}
\TUGIref{anchor}{text%plain}#S
\ukfaqref{label}{text%plain}
\wikilangbooksref{lang-code}{book/subject}{text%plain}
\latexwikibookref{subject}{text%plain}
\texwikibookref{subject}{text%plain}
