# textalpha package
# Matthew Bertucci 9/22/2021

\ensuregreek{text}
\greekscript
\textAlpha#n
\textBeta#n
\textGamma#n
\textDelta#n
\textEpsilon#n
\textZeta#n
\textEta#n
\textTheta#n
\textIota#n
\textKappa#n
\textLambda#n
\textMu#n
\textNu#n
\textXi#n
\textOmicron#n
\textPi#n
\textRho#n
\textSigma#n
\textTau#n
\textUpsilon#n
\textPhi#n
\textChi#n
\textPsi#n
\textOmega#n
\textalpha#n
\textbeta#n
\textgamma#n
\textdelta#n
\textepsilon#n
\textzeta#n
\texteta#n
\texttheta#n
\textiota#n
\textkappa#n
\textlambda#n
\textmu#n
\textnu#n
\textxi#n
\textomicron#n
\textpi#n
\textrho#n
\textsigma#n
\textfinalsigma#n
\textautosigma#n
\texttau#n
\textupsilon#n
\textphi#n
\textchi#n
\textpsi#n
\textomega#n
\textpentedeka#n
\textpentehekaton#n
\textpenteqilioi#n
\textstigma#n
\textvarstigma#n
\textKoppa#n
\textkoppa#n
\textqoppa#n
\textQoppa#n
\textStigma#n
\textSampi#n
\textsampi#n
\textanoteleia#n
\texterotimatiko#n
\textdigamma#n
\textDigamma#n
\textdexiakeraia#n
\textaristerikeraia#n
\textvarsigma#*n
\textstigmagreek#*n
\textkoppagreek#*n
\textStigmagreek#*n
\textSampigreek#*n
\textsampigreek#*n
\textdigammagreek#*n
\textDigammagreek#*n
\textnumeralsigngreek#*n
\textnumeralsignlowergreek#*n
\accdialytika{arg}#n
\acctonos{arg}#n
\accdasia{arg}#n
\accpsili{arg}#n
\accvaria{arg}#n
\accperispomeni{arg}#n
\prosgegrammeni#n
\ypogegrammeni#n
\accdialytikaperispomeni{arg}#n
\accdialytikatonos{arg}#n
\accdialytikavaria{arg}#n
\accdasiaperispomeni{arg}#n
\accdasiavaria{arg}#n
\accdasiaoxia{a}#n
\accpsiliperispomeni{a}#n
\accpsilioxia{arg}#n
\accpsilivaria{arg}#n
\accinvertedbrevebelow{arg}#n
\textsubarch{arg}#n
\accbrevebelow{arg}#n
\accvaria{arg}#n
\accdasia{arg}#n
\accpsili{arg}#n
\accdasiavaria{arg}#n
\acctonos{arg}#n
\accdasiaoxia{arg}#n
\accpsilioxia{arg}#n
\accpsilivaria{arg}#n
\accperispomeni{arg}#n
\accdasiaperispomeni{arg}#n
\accpsiliperispomeni{arg}#n
\accvaria{arg}#n
\accdasia{arg}#n
\accpsili{arg}#n
\textsemicolon#n
\<#*
\>#*
\textbetasymbol#*
\textthetasymbol#*
\textphisymbol#*
\textpisymbol#*
\textkappasymbol#*
\textrhosymbol#*
\textThetasymbol#*
\textepsilonsymbol#*