# textcomp package
# tbraun 04/27/2006

\capitalgrave{text}
\capitalacute{text}
\capitalcircumflex{text}
\capitaltilde{text}
\capitaldieresis{text}
\capitalhungarumlaut{text}
\capitalring{text}
\capitalcaron{text}
\capitalbreve{text}
\capitaldotaccent{text}
\capitalcedilla{text}
\capitalogonek{text}
\t{text}
\capitaltie{text}
\newtie{text}
\capitalnewtie{text}
\textcapitalcompwordmark
\textascendercompwordmark
\oldstylenums{number}
\textzerooldstyle
\textoneoldstyle
\texttwooldstyle
\textthreeoldstyle
\textfouroldstyle
\textfiveoldstyle
\textsixoldstyle
\textsevenoldstyle
\texteightoldstyle
\textnineoldstyle
\textquotestraightbase
\textquotestraightdblbase
\texttwelveudash
\textthreequartersemdash
\textleftarrow
\textrightarrow
\textblank
\textdollar
\textquotesingle
\textasteriskcentered
\textdblhyphen
\textfractionsolidus
\textlangle
\textminus
\textrangle
\textmho
\textbigcircle
\textohm
\textlbrackdbl
\textrbrackdbl
\textuparrow
\textdownarrow
\textasciigrave
\textborn
\textdivorced
\textdied
\textleaf
\textmarried
\textmusicalnote
\texttildelow
\textdblhyphenchar
\textasciibreve
\textasciicaron
\textacutedbl
\textgravedbl
\textdagger
\textdaggerdbl
\textbardbl
\textperthousand
\textbullet
\textcelsius
\textdollaroldstyle
\textcent
\textflorin
\textcolonmonetary
\textwon
\textnaira
\textguarani
\textpeso
\textlira
\textrecipe
\textinterrobang
\textinterrobangdown
\textdong
\texttrademark
\textpertenthousand
\textpilcrow
\textbaht
\textnumero
\textdiscount
\textestimated
\textopenbullet
\textservicemark
\textlquill
\textrquill
\textcent
\textsterling
\textcurrency
\textyen
\textbrokenbar
\textsection
\textasciidieresis
\textcopyright
\textordfeminine
\textcopyleft
\textlnot
\textcircled
\textregistered
\textasciimacron
\textdegree
\textpm
\texttwosuperior
\textthreesuperior
\textasciiacute
\textmu
\textparagraph
\textperiodcentered
\textreferencemark
\textonesuperior
\textordmasculine
\textsurd
\textonequarter
\textonehalf
\textthreequarters
\texteuro
\texttimes
\textdiv
