# textcomp package
# tbraun 04/27/2006
# muzimuzhi 13 Mar 2020

\capitalacute{A}
\capitalbreve{A}
\capitalcaron{A}
\capitalcedilla{A}
\capitalcircumflex{A}
\capitaldieresis{A}
\capitaldotaccent{A}
\capitalgrave{A}
\capitalhungarumlaut{A}
\capitalmacron{A}
\capitalnewtie{A}
\capitalogonek{A}
\capitalring{A}
\capitaltie{A}
\capitaltilde{A}
\newtie{A}
\oldstylenums{number}
\textacutedbl
\textascendercompwordmark
\textasciiacute
\textasciibreve
\textasciicaron
\textasciidieresis
\textasciigrave
\textasciimacron
\textasteriskcentered
\textbaht
\textbardbl
\textbigcircle
\textblank
\textborn
\textbrokenbar
\textbullet
\textcapitalcompwordmark
\textcelsius
\textcent
\textcentoldstyle
\textcircled
\textcircledP
\textcolonmonetary
\textcopyleft
\textcopyright
\textcurrency
\textdagger
\textdaggerdbl
\textdblhyphen
\textdblhyphenchar
\textdegree
\textdied
\textdiscount
\textdiv
\textdivorced
\textdollar
\textdollaroldstyle
\textdong
\textdownarrow
\texteightoldstyle
\textestimated
\texteuro
\textfiveoldstyle
\textflorin
\textfouroldstyle
\textfractionsolidus
\textgravedbl
\textguarani
\textinterrobang
\textinterrobangdown
\textlangle
\textlbrackdbl
\textleaf
\textleftarrow
\textlegacyasteriskcentered
\textlegacybardbl
\textlegacybullet
\textlegacydagger
\textlegacydaggerdbl
\textlegacyparagraph
\textlegacyperiodcentered
\textlegacysection
\textlira
\textlnot
\textlquill
\textmarried
\textmho
\textminus
\textmu
\textmusicalnote
\textnaira
\textnineoldstyle
\textnumero
\textohm
\textonehalf
\textoneoldstyle
\textonequarter
\textonesuperior
\textopenbullet
\textordfeminine
\textordmasculine
\textparagraph
\textperiodcentered
\textpertenthousand
\textperthousand
\textpeso
\textpilcrow
\textpm
\textquotesingle
\textquotestraightbase
\textquotestraightdblbase
\textrangle
\textrbrackdbl
\textrecipe
\textreferencemark
\textregistered
\textrightarrow
\textrquill
\textsection
\textservicemark
\textsevenoldstyle
\textsixoldstyle
\textsterling
\textsurd
\textthreeoldstyle
\textthreequarters
\textthreequartersemdash
\textthreesuperior
\texttildelow
\texttimes
\texttrademark
\texttwelveudash
\texttwooldstyle
\texttwosuperior
\textuparrow
\textwon
\textyen
\textzerooldstyle
\t{A}
