# tikzlings package
# Matthew Bertucci 8/12/2021

#include:tikzlings-anteaters
#include:tikzlings-bats
#include:tikzlings-bears
#include:tikzlings-bees
#include:tikzlings-bugs
#include:tikzlings-cats
#include:tikzlings-chickens
#include:tikzlings-coatis	
#include:tikzlings-elephants
#include:tikzlings-hippos	
#include:tikzlings-koalas
#include:tikzlings-marmots
#include:tikzlings-mice
#include:tikzlings-moles
#include:tikzlings-owls
#include:tikzlings-pandas	
#include:tikzlings-penguins
#include:tikzlings-pigs
#include:tikzlings-rhinos
#include:tikzlings-sheep
#include:tikzlings-sloths
#include:tikzlings-snowmen	
#include:tikzlings-squirrels

\tikzling
\tikzling[options%keyvals]

#keyvals:\tikzling#c
body=#%color
back
3D
contour
contour=#%color
#endkeyvals

\thing[options%keyvals]

#keyvals:\tikzling#c,\thing#c
hat
hat=#%color
tophat
tophat=#%color
beret
beret=#%color
strawhat
strawhat=#%color
ribbon
ribbon=#%color
harlequin
harlequin=#%color
niuqelrah
niuqelrah=#%color
witch
witch=#%color
magichat
magichat=#%color
magicstars
magicstars=#%color
crown
crown=#%color
queencrown
queencrown=#%color
kingcrown
kingcrown=#%color
santa
santa=#%color
chef
chef=#%color
graduate
graduate=#%color
tassel
tassel=#%color
alien
alien=#%color
book
book=
bookcolour=#%color
signpost
signpost=
signcolour=#%color
signback=#%color
speech
speech=
bubblecolour=#%color
think
think=
pizza
cheese
cheese=#%color
baguette
baguette=#%color
cake
cake=#%color
icecream
icecream=#%color
flavoura=#%color
flavourb=#%color
flavourc=#%color
milkshake
milkshake=#%color
wine
wine=#%color
cricket
cricket=#%color
hockey
hockey=#%color
football
football=#%color
crystalball
crystalball=#%color
magicwand
rollingpin
rollingpin=#%color
lightsaber
lightsaber=#%color
torch
torch=#%color
basket
basket=#%color
easter
easter=#%color
egga=#%color
eggb=#%color
eggc=#%color
crozier
crozier=#%color
shovel
shovel=#%color
pickaxe
pickaxe=#%color
strawbroom
strawbroom=#%color
strawbroomstick
strawbroomstick=#%color
strawbroomribbon
strawbroomribbon=#%color
broom
broom=#%color
broomstick
broomstick=#%color
umbrella
umbrella=#%color
umbrellaclosed
umbrellaclosed=#%color
handbag
handbag=#%color
cocktail
#endkeyvals