# tipx package
# Matthew Bertucci 7/29/2021

#include:tipa

\textaolig#n
\textbenttailyogh#n
\textbktailgamma#n
\textctinvglotstop#n
\textctjvar#n
\textctstretchc#n
\textctstretchcvar#n
\textctturnt#n
\textdblig#n
\textdoublebarpipevar#n
\textdoublepipevar#n
\textdownfullarrow#n
\textfemale#n
\textfrbarn#n
\textfrhookd#n
\textfrhookdvar#n
\textfrhookt#n
\textfrtailgamma#n
\textglotstopvari#n
\textglotstopvarii#n
\textglotstopvariii#n
\textgrgamma#n
\textheng#n
\texthmlig#n
\texthtbardotlessjvar#n
\textinvomega#n
\textinvsca#n
\textinvscripta#n
\textlfishhookrlig#n
\textlhookfour#n
\textlhookp#n
\textlhti#n
\textlooptoprevesh#n
\textnrleg#n
\textObullseye#n
\textpalhooklong#n
\textpalhookvar#n
\textpipevar#n
\textqplig#n
\textrectangle#n
\textretractingvar#n
\textrevpolhook{arg1}#n
\textrevscl#n
\textrevscr#n
\textrhooka#n
\textrhooke#n
\textrhookepsilon#n
\textrhookopeno#n
\textrtailhth#n
\textrthooklong#n
\textscaolig#n
\textscdelta#n
\textscf#n
\textsck#n
\textscm#n
\textscp#n
\textscq#n
\textspleftarrow#n
\textstretchcvar#n
\textsubdoublearrow#n
\textsubrightarrow#n
\textthornvari#n
\textthornvarii#n
\textthornvariii#n
\textthornvariv#n
\textturnglotstop#n
\textturnsck#n
\textturnscu#n
\textturnthree#n
\textturntwo#n
\textuncrfemale#n
\textupfullarrow#n