# tiscreen package
# Matthew Bertucci 3/14/2022

#include:lcd
#include:tikz
#include:tcolorbox
#include:array
#include:xcolor
#include:tipa
#include:textgreek
#include:wasysym

#keyvals:\usepackage/tiscreen#c
color
#endkeyvals

\tiscreenX
\tiscreenY

tiscreenfg#B
tiscreenbg#B
tibtngray#B
tibtnyellow#B
tibtngreen#B
tibtnwhite#B
tibtnblue#B
tibtncaseblack#B

\tiscreen|%<line1%>|%< ... |lineN|%>
\tibtn{bgcolor}{text}
\tibtn[textcolor]{bgcolor}{text}
\tibtn[color]{color}{text}#S
\tibtnextra{content%text}{text1%text}{text2%text}
\tibtnalpha
\tibtnsecond
\tibtnenter
\tibtnextraalpha
\tibtnextrasecond
\tibtnextraenter
\tibtndiv
\tibtntimes
\tibtnminus
\tibtnplus
\tibtnextradiv
\tibtnextratimes
\tibtnextraminus
\tibtnextraplus
\tibtnzero
\tibtnone
\tibtntwo
\tibtnthree
\tibtnfour
\tibtnfive
\tibtnsix
\tibtnseven
\tibtneight
\tibtnnine
\tibtnextrazero
\tibtnextraone
\tibtnextratwo
\tibtnextrathree
\tibtnextrafour
\tibtnextrafive
\tibtnextrasix
\tibtnextraseven
\tibtnextraeight
\tibtnextranine
\tibtnmode
\tibtndel
\tibtnxton
\tibtnstat
\tibtnmath
\tibtnmatrix
\tibtnprgm
\tibtnvars
\tibtnclear
\tibtnxnone
\tibtnsin
\tibtncos
\tibtntan
\tibtnpower
\tibtnxtwo
\tibtncomma
\tibtnleftparen
\tibtnrightparen
\tibtnlog
\tibtnln
\tibtnsto
\tibtnon
\tibtndot
\tibtnneg
\tibtnextramode
\tibtnextradel
\tibtnextraxton
\tibtnextrastat
\tibtnextramath
\tibtnextramatrix
\tibtnextraprgm
\tibtnextravars
\tibtnextraclear
\tibtnextraxnone
\tibtnextrasin
\tibtnextracos
\tibtnextratan
\tibtnextrapower
\tibtnextraxtwo
\tibtnextracomma
\tibtnextraleftparen
\tibtnextrarightparen
\tibtnextralog
\tibtnextraln
\tibtnextrasto
\tibtnextraon
\tibtnextradot
\tibtnextraneg
